### ISSUE TITLE
Keyboard: Formatter is not invoked with proper value argument

### ISSUE THREAD

**Issue by steliyan** [leongersen/noUiSlider#1000]
Hey,

I've found an issue where the `format: { from }` is not invoked with the proper value argument when the keyboard is used.

Here is a reproduction of the issue: https://codesandbox.io/s/nouislider-documentelement-i32vf

You can observe the behavior if you remove the following code:
```js
if (index === -1) {
    return Number(v);
}
```

This happens only when using the keyboard keys, if the mouse is used to slide, everything is working as expected.

Greetings, Steliyan.

**Comment by leongersen** [comment]
Thanks for the reproducer. Keyboard interaction doesn't need to pass through the formatter at all. I'll have a look.

**Comment by leongersen** [comment]
I've fixed this in noUiSlider 14.0.2. Thanks for reporting!

**Comment by steliyan** [comment]
Thanks for the quick response!

Keep up the good work! ;)
