### ISSUE TITLE
After upgrade to "version": "14.0.2", While using connect: true, the Position of the first connecter is not display because the translate ( 1000%,0px) instead of translate(100%,0px)

### ISSUE THREAD

**Issue by GayathriRamasamy** [leongersen/noUiSlider#1003]

**Comment by martyspain** [comment]
I'm experiencing this too. It appears that the calculation for the `translate` style is out by a factor of 100.

**Comment by leongersen** [comment]
You'll need to update the CSS that came with the update too.

**Comment by martyspain** [comment]
@leongersen Brilliant, thanks for the swift reply. Updating my CSS to account for the JS code change resolved the issue.
