### ISSUE TITLE
Range Slider from Select

### ISSUE THREAD

**Issue by ProdesignerAgency** [leongersen/noUiSlider#1007]
Hello,
I have two selects and they are the same class and name (different option values):

`<select name="price_range[]" class="price_select"> <option value="">Price range</option><option value="0">0</option><option value="2000">2000</option><option value="5000">5000</option><option value="10000">10000</option></select>`

Is possible to make them range sliders?

Best

**Comment by leongersen** [comment]
Yes, you can. Have a look at the [range documentation](https://refreshless.com/nouislider/slider-values/#section-non-linear).
