### ISSUE TITLE
Doesn't have "p" tags on div tooltips

### ISSUE THREAD

**Issue by tiagoevanp** [leongersen/noUiSlider#1008]
I love noUiSlider, but i did find one simple issue that can be solved. The tooltips of sliders doesn't have a "p" tag that, for me, is really useful to make more stylizations. A good example about what I am saying is the alignment of the text into the handles.

**Comment by leongersen** [comment]
The content in a tooltip isn't semantically a paragraph, so it doesn't be marked up as such. You can use a [formatter](https://refreshless.com/nouislider/number-formatting/#section-tooltips) if you want to change the rendering of a tooltip.

**Comment by tiagoevanp** [comment]
Thanks for the fast feedback. I found a way to fix the problem without modifications in the main code. That issue may be closed to me. Thanks again.
