### ISSUE TITLE
aria-valuetext - value vs aria-valuenow value

### ISSUE THREAD

**Issue by ProdesignerAgency** [leongersen/noUiSlider#1011]
I set
`   format: wNumb({
     decimals: 0
   })`
and its working :)

aria-valuenow show full numbers like  1,2,3,4 etc.

but
aria-valuetext somtimes show value like this "1.00000000000006" etc.

please help

**Comment by leongersen** [comment]
Could you provide a full example?

**Comment by leongersen** [comment]
I'll close this as there's been no further response.
