### ISSUE TITLE
Tooltip overlap.

### ISSUE THREAD

**Issue by d8dev** [leongersen/noUiSlider#1012]
While I drag the second point closer to the first, the tooltip of the first point overlaps the second (active).
How can I fix that?
Thank you in advance.
![image](https://user-images.githubusercontent.com/38289023/61707593-83678080-ad53-11e9-8ae4-1ad3017a2b8b.png)

https://refreshless.com/nouislider/number-formatting/#section-tooltips

**Comment by leongersen** [comment]
Merging this with #1032.

**Comment by arlangalvez** [comment]
Hello all, is this really fixed? my sliders are getting overlapped yet. How to manage this issue @leongersen?
![image](https://user-images.githubusercontent.com/55986072/72086603-2ea1cd00-32d5-11ea-95ca-6ff0c740e449.png)
