### ISSUE TITLE
Update method broken after dynamically adding handles with destroy method 

### ISSUE THREAD

**Issue by psycheluke** [leongersen/noUiSlider#1013]
Hello leongersen, 

I have been using your slider in a project of mine. The code below synchronizes handle values with HTML inputs. A button is used to call slider.noUiSlider.destroy() in order to add handles dynamically. After calling destory(), slider.noUiSlider.on Update no longer works and inputs become unsynchronized with slider handles.
Any help would be appreciated.

var sliderUp = document.getElementById('sliderid');

		function createSlider ( sliderUp ) {
            noUiSlider.create(sliderUp, options);
        }

        Sliderbox = function(options) {
            this.options = options;
            this.init();
        };

        Sliderbox.prototype.init = function() {
            var box = document.querySelectorAll(this.options.target),
                len = box.length,
                i = 0;

            for (; i < len; i++) {
                this.handler(box[i]);
            }
        };

        var options = {
            target: '.sliderbox',
            start: [ 47, 97], // Handle start position
            step: 10, // Slider moves in increments of '10'
            margin: 50, // Handles must be more than '20' apart
            connect: true, // Display a colored bar between the handles
            orientation: 'vertical',
            direction: 'rtl',
            behaviour: 'tap-drag', // Move handle on tap, bar is draggable
            tooltips: true,
            animate: true,
            animationDuration: 300,
            range: { // Slider can select '0' to '100'
                'min': 47,
                'max': 1000
            },
            // Show a scale with the slider
            pips: {
                mode: 'values',
                values: [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000],
                density: 1,
                format: {
                    to: function ( value ) {
                if(value==0) return 0;
                return (value + " mm");
                },
                from: function ( value ) {
                return value;
                }
            },
            }
        };
        Sliderbox.prototype.handler = function(target) {
        // Assigning variables to html inputs
            slider = target.querySelector('.sliderbox-slider'),
            inp0 = target.querySelector('.sliderbox-input0'),
            inp1 = target.querySelector('.sliderbox-input1'),
            inp2 = target.querySelector('.sliderbox-input2'),
            inp3 = target.querySelector('.sliderbox-input3'),
            inp4 = target.querySelector('.sliderbox-input4'),
            inp5 = target.querySelector('.sliderbox-input5'),

            diff0 = target.querySelector('.sliderbox-input-diff0'),
            diff1 = target.querySelector('.sliderbox-input-diff1'),
            diff2 = target.querySelector('.sliderbox-input-diff2'),
            diff3 = target.querySelector('.sliderbox-input-diff3'),
            diff4 = target.querySelector('.sliderbox-input-diff4'),
            diff5 = target.querySelector('.sliderbox-input-diff5');

        // Moving Slider handles updates HTML Inputs
        slider.noUiSlider.on('update', function( values, handle ) {

                switch ( handle ) {
                    case 0:
                    inp0.value = values[handle];
                    diff0.value = values[1] - values[0];
                    break;
                    case 1:
                    diff0.value = values[1] - values[0];
                    inp1.value = values[handle];
                    diff1.value = values[2] - values[1];
                    break;
                    case 2:
                    diff1.value = values[2] - values[1];
                    inp2.value = values[handle];
                    diff2.value = values[3] - values[2];
                    break;
                    case 3:
                    diff2.value = values[3] - values[2];
                    inp3.value = values[handle];
                    diff3.value = values[4] - values[3];
                    break;
                    case 4:
                    diff3.value = values[4] - values[3];
                    inp4.value = values[handle];
                    diff4.value = values[5] - values[4];
                    break;
                    case 5:
                    diff4.value = values[5] - values[4];
                    inp5.value = values[handle];
                    diff5.value = values[6] - values[5];
                    break;
                }      
            });

function addHandle ( ) {
        highestHandle();
        var values = sliderUp.noUiSlider.get();
        values.push(highestNum +50); // Your new handle start value
        slider.noUiSlider.destroy();
        options.start = values;
        noUiSlider.create(sliderUp, options);
    }
};

slider = document.querySelectorAll('.sliderbox-slider');

        Array.prototype.forEach.call(slider, createSlider);
    
    
        Sliderbox = new Sliderbox({
            target: '.sliderbox',
            
            start: true, // Handle start position
            step: 10, // Slider moves in increments of '10'
            margin: 50, // Handles must be more than '50' apart
            connect: true, // Display a colored bar between the handles
            orientation: 'vertical',
            direction: 'rtl',
            behaviour: 'tap-drag', // Move handle on tap, bar is draggable
            tooltips: true,
            animate: true,
            range: {
                'min': 47,
                'max': 1000
            },
            // Show a scale with the slider
            pips: {
                mode: 'values',
                values: [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000],
                density: 1
            }
        });

**Comment by leongersen** [comment]
After calling `destroy`, you need to re-add your `.on('update')` event listener.

**Comment by psycheluke** [comment]
I have it working now. Thank you, I appreciate you helping me.
