### ISSUE TITLE
Unable to preventDefault inside passive event listener

### ISSUE THREAD

**Issue by jan-vanicek** [leongersen/noUiSlider#1015]
Hi, when I'm moving a slider, the slider stays focused and cannot be "unfocused" to interact with other page elements (buttons, etc.), console is writing this (more in attached image below). Any suggestions or fixes? Thanks.

![err](https://user-images.githubusercontent.com/53607722/62363872-73ecf200-b520-11e9-8481-5d25ce37dcc5.png)

**Comment by leongersen** [comment]
Can you show me the code you're trying to use? The event listeners in noUiSlider are passive (meaning they "promise" not to call preventDefault) as an important performance optimization.

**Comment by jan-vanicek** [comment]
I'm using this code.

    var slider = document.getElementById('SwitchSlider');

    noUiSlider.create(slider, {
        start: '65',
        step: 1,
        connect: [true, false],
        range: {
            'min': 40,
            'max': 80
        },
        format: wNumb({
            decimals: 0
        })
    });

    slider.noUiSlider.on('change', function (values) {
        var message = '' + values;
        sendMessage(message,'/volume');
    });

**Comment by leongersen** [comment]
I can't reproduce this. What are you doing to trigger this error?

**Comment by jan-vanicek** [comment]
Watch the video below, I've attached an image too.

[https://youtu.be/b5b10hLRpe0](https://youtu.be/b5b10hLRpe0)

![scree](https://user-images.githubusercontent.com/53607722/62468563-a9027a00-b796-11e9-9ffc-8203aa51d7bd.png)

**Comment by leongersen** [comment]
Do you have any other `focus`/`touchstart` event listeners? noUiSlider itself doesn't call `preventDefault` when it adds a passive listener.

**Comment by jan-vanicek** [comment]
No, I think not. Did you mean some custom function in `on` change event function, which could call `preventDefault`?

**Comment by leongersen** [comment]
Something like that, yes. Can you reproduces this on the documentation website?

**Comment by jan-vanicek** [comment]
No, unfortunately, I can't reproduce on documentation website, and I still don't have any ideas how to solve this problem. Any ideas?

**Comment by leongersen** [comment]
With the current code in this issue, I can't really provide any new insights here.

**Comment by jan-vanicek** [comment]
Sorry but I didn't know that the library what I use uses really old version of noUiSlider which used `preventDefault`. Thank you for your suggestions and patience. Now it's everything OK.
