### ISSUE TITLE
With two handles overlapping, only one can be moved

### ISSUE THREAD

**Issue by My6UoT9** [leongersen/noUiSlider#1017]
When the right handle is moved to the left, so that it overlaps, one can only move the handle to the right again, and only then the other handle can be moved to the left. 
Its obvious why, since the second handler is above the first; but from user experience its not good.

**Comment by leongersen** [comment]
You can set the [`unconstrained` behaviour](https://refreshless.com/nouislider/behaviour-option/#section-unconstrained) to change how this works.

**Comment by My6UoT9** [comment]
That is very nice!
For reference https://jsfiddle.net/zjxwbch1/
