### ISSUE TITLE
Need play, forward and backward buttons

### ISSUE THREAD

**Issue by Giswin** [leongersen/noUiSlider#1021]
Under one input value scenario, can you add paly and forward buttons on the left side and a backward button on the left?
something looks like this:

![image](https://user-images.githubusercontent.com/2694092/65849132-e9e1bf80-e2fd-11e9-82da-f6bd9d1f73f5.png)

when 'Play' is clicked, the slider will go forward step by step, when forward or backward is clicked it moves by one step.

**Comment by leongersen** [comment]
For general questions like this, I'll direct you to [StackOverflow](https://stackoverflow.com/questions/tagged/nouislider). There, some more information and a sample of how you've attempted to implement this will be required.
