### ISSUE TITLE
You Shouldn't Need to DOM Manipulate a Library's Elements To Use It

### ISSUE THREAD

**Issue by machineghost** [leongersen/noUiSlider#1022]
jQuery, and DOM manipulation in general, is yester-year's way of making web sites.  Countless developers use React, and other libraries that rely on abstraction layers like virtual DOMs, which make doing direct DOM manipulation a bad idea.

(In fact, this library is used to power React libraries like Shards: https://designrevision.com/docs/shards-react/component/slider).

Given all that, it really seems like there should be a way to tell the tool "I want *you* to render the notches on my slider are low medium high, not 1 2 3" ... without having to use jQuery or raw DOM manipulation to accomplish it.

**Comment by leongersen** [comment]
Formatting pips is a [build in feature](https://refreshless.com/nouislider/number-formatting/#section-pips).

**Comment by machineghost** [comment]
I don't know what that means: "build in feature"?

It's an _undocumented_ feature, or at least and _under-documented_ one.  There's no explanation of what any of the object's properties are.
