### ISSUE TITLE
Uncaught SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by a007mr** [leongersen/noUiSlider#1027]
Hi, please help me to figure out how to use noUiSlider. It doesn't work on my website.

Right now I have the error in console:
```
Uncaught SyntaxError: Cannot use import statement outside a module   at scripts.js:76
```

I've run the command `npm install nouislider` and added the code in my `script.js`:
```
import noUiSlider from "nouislider";
var slider = document.getElementById('slider');
var snapSlider = document.getElementById('slider-snap');

noUiSlider.create(slider, {
    start: [20, 80],
    connect: true,
    range: {
        'min': 0,
        'max': 100
    }
});

noUiSlider.create(snapSlider, {
    start: [0, 500],
    snap: true,
    connect: true,
    range: {
        'min': 0,
        '10%': 50,
        '20%': 100,
        '30%': 150,
        '40%': 500,
        '50%': 800,
        'max': 1000
    }
});
```
What's wrong?

**Comment by leongersen** [comment]
Well, your `script.js` isn't a module, so you can't import other sources in it. The simplest solution is to add a separate `<script>` tag to your page that includes `nouislider.js`. If you want to use imports, you'll need a bundler like [webpack](https://webpack.js.org/).
