### ISSUE TITLE
Padding on a scaled slider

### ISSUE THREAD

**Issue by Macro-Jackson** [leongersen/noUiSlider#1030]
I'd like to have limits on my slider where you can't go lower then the lower limit and not higher then the higher limit.

Example:
Range: 0 - 1000
Lower limit: 200
Higher limit: 800

In this case the handles shouldn't be able to go below 200 or above 800...
As my range is sometimes highly none linear, I am using the ranges (Non-linear sliders) where I set the 40% and 70% mark.

Is it possible to apply padding? As I can see this is the feature I need. But I am getting an error: Uncaught Error: noUiSlider (12.0.0): 'padding' option is only supported on linear sliders.

**Comment by leongersen** [comment]
Yes, your use case indeed calls for the `padding` option, but as you mention this option isn't yet supported on non-linear sliders.

**Comment by Macro-Jackson** [comment]
Thanks for the response! Is supporting padding for none linear sliders on the near future roadmap?

**Comment by leongersen** [comment]
I've just released noUiSlider 14.5.0, which includes this feature. Thanks, @Macro-Jackson!
