### ISSUE TITLE
Prevent handles from over-lapping on non-linear slider

### ISSUE THREAD

**Issue by psycheluke** [leongersen/noUiSlider#1031]
I have a non linear slider and cannot use the Margin option. How would I go about preventing overlap of handles?

**Comment by Rablin92** [comment]
Hey, i run into the same Porblem until we get a Feature, i did build my own but its defently dirty. I guess you should use it as an Idea and refactor it.
Also it wont work with `behaviour: 'unconstrained-tap',` cuz handles can't cross themselfs(they dont have to in my case).

> The start event sets a data attribute to save where its startet moving(to reset it here, try again logic)

> The update event checks for "collision"


    `range.noUiSlider.on('start', function (values, handle) {
        $('#rangeSlide div[data-handle=' + handle + ']').data("oldVal", values[handle]);
    });

    range.noUiSlider.on('update', function (values, handle) {
        //slice to get off the decimal
        let sliderObj = {
            'min': $('#rangeSlide div[data-handle=' + handle + ']').attr('aria-valuemin').slice(0, -2),
            'max': $('#rangeSlide div[data-handle=' + handle + ']').attr('aria-valuemax').slice(0, -2),
            'old': $('#rangeSlide div[data-handle=' + handle + ']').data('oldVal'),
        };
        //dont let 2 sliders be on one value && dont let slider be 0 
        if (values[handle] == sliderObj.min || values[handle] == sliderObj.max || values[handle] < 0.1) {
            //&& let the highest handle get to max
            if (values.length - 1 == handle && values[handle] == sliderObj.max) {
            } else {
                range.noUiSlider.setHandle(handle, sliderObj.old, false);
                values[handle] = sliderObj.old;
            }
        }
    });`

**Comment by leongersen** [comment]
noUiSlider 14.5.0 allows margin on non-linear sliders. Many thanks to @Macro-Jackson for this implementation, and to everyone else for contributing!
