### ISSUE TITLE
Joining overlapping tooltips

### ISSUE THREAD

**Issue by omuryildirim** [leongersen/noUiSlider#1032]
Goal: join and display single tooltip whenever two tooltips overlaps.

Solution: Catch overlapping tooltips by calculating their start and end points in x coordinate. Then add a new tooltip to the handle on the right side. Add a margin-left to adjust it to middle of two handles. Finally, make overlapping tooltips invisible.

Hope this fix helps everyone in need of it. Thanks for your contributions with noUiSlider.

**Comment by jasongrout** [comment]
FYI, [ion slider](http://ionden.com/a/plugins/ion.rangeSlider/demo.html) (used by R shiny) has a nice polished UX for this. If the tooltips would overlap, they join into a single tooltip: 
<img width="139" alt="Screen Shot 2020-01-07 at 11 38 31 AM" src="https://user-images.githubusercontent.com/192614/71889377-4bf26200-3142-11ea-8e92-0299f8b304b6.png">

**Comment by jbarradas** [comment]
Is anyone working on this? Just ran into this issue.
![Screenshot from 2020-02-21 10-17-57](https://user-images.githubusercontent.com/8421826/75025699-8f572480-5493-11ea-9763-8ebd7c52af32.png)

**Comment by leongersen** [comment]
The documentation now has an [example for merging overlapping tooltips](https://refreshless.com/nouislider/examples/#section-merging-tooltips). Thanks for contributing, everyone!

**Comment by bjarnef** [comment]
@leongersen thanks, it seems to work great! 👍 

When e.g. the two handles have same value, would it be possible to merge these to a single tooltip value?

![image](https://user-images.githubusercontent.com/2919859/81280254-7d2f6000-9058-11ea-8168-59e345d51531.png)

Examples from [Ion.RangeSlider](http://ionden.com/a/plugins/ion.rangeSlider/demo_advanced.html)

**Handles with different values**
![image](https://user-images.githubusercontent.com/2919859/81280433-c089ce80-9058-11ea-8782-a9c5d677e0cc.png)

**Handles with same value**
![image](https://user-images.githubusercontent.com/2919859/81280573-f929a800-9058-11ea-983b-0b546e5e50c0.png)

**Comment by jasongrout** [comment]
Thanks! This example goes a long ways to making the slider more user friendly. It does seem to have some glitches in some cases, for example when I set the sliders to have 47.85, 50, 65.43, 73.60, and 73.60: 
<img width="387" alt="Screen Shot 2020-05-07 at 3 03 36 AM" src="https://user-images.githubusercontent.com/192614/81282045-8516e200-900f-11ea-888b-c7ffd5ba6157.png">

**Comment by leongersen** [comment]
@bjarnef Yes, you could extend the line `poolValues[poolIndex].join(separator);` in the example by [filtering it for unique values](https://stackoverflow.com/questions/1960473/get-all-unique-values-in-a-javascript-array-remove-duplicates).

@jasongrout You could slightly increase the threshold passed to the `mergeTooltips` function in the example,. e.g. to `20`.

**Comment by bjarnef** [comment]
@leongersen thanks, it seems to work perfect!

I modfied these lines.

```
var tooltipValues = poolValues[poolIndex].filter((v, i, a) => a.indexOf(v) === i); 

// Center this tooltip over the affected handles
tooltips[handleNumber].innerHTML = tooltipValues.join(separator);
```

![image](https://user-images.githubusercontent.com/2919859/81289663-15ccdc80-9067-11ea-9f37-8d0fd46621c3.png)
