### ISSUE TITLE
Postback issue

### ISSUE THREAD

**Issue by Tabassumsiddiqui** [leongersen/noUiSlider#1037]
I have used the step slider which has price min and price max values.
 When I reinitialize the slider using post back. The values reset to its start value.
 But i want the slider should take the updated value ( whatever the user has given the min and max input value).

I have used these code for reinitializing,

 function fireRangeSlider() {
    
       //Price Range Slider
    var stepsSlider = document.getElementById('steps-slider');
    var input0 = document.getElementById('pricemin');
    var input1 = document.getElementById('pricemax');
    var inputs = [input0, input1];
       
noUiSlider.create(stepsSlider, {
        start: [0, 10000],
    connect: true,
    behaviour: 'drag',
    
    range: {
        'min': 0,  
        'max': 50000
    },
    format: wNumb({
        decimals: 0
    })
});

     stepsSlider.noUiSlider.on('slide', function (values, handle) {
    inputs[handle].value = values[handle];
});

**Comment by leongersen** [comment]
You'll need to pass the values for your slider to the `start` parameter, or call `set`.

**Comment by Tabassumsiddiqui** [comment]
I have tried but the slider goes away after onclick. I want the updated values (whatever the user type ) should come after submission. I have used these slider for product filtering which is based on price.

Live website : https://sooperbuy.com/productListing.aspx

**Comment by leongersen** [comment]
Sorry, but I can't debug your code for you.
