### ISSUE TITLE
Invalid LTR classes generated

### ISSUE THREAD

**Issue by bazineta** [leongersen/noUiSlider#1038]
I'm having an issue with the 14.1.0 release that to date has not been present with any release, up to and including 14.0.3.

In the case of a horizontal slider, the handles don't match the direction; the slider is getting mismatched classes, e.g.,
```
<div id="input-alarm-slider" class="noUi-target noUi-ltr noUi-horizontal noUi-txt-dir-rtl">
    ...omitted for brevity...
</div>
```
Note the mismatch of LTR and RTL there.

I've traced this to the following in `addSlider`:
```
var textDirection = getComputedStyle(addTarget).direction;

if (textDirection === "ltr") {
  addClass(addTarget, options.cssClasses.textDirectionLtr);
} else {
  addClass(addTarget, options.cssClasses.textDirectionRtl);
}
```
The issue is that textDirection is null. In that `CSSStyleDeclaration` objects are live and thus a bit  difficult to debug, I'm having a terrible time figuring out why it's null at that point, but I suspect it's due to the fact that we use Marionette, and the slider is being rendered into a fragment at that point.

That's never been a problem to date, but neither has the slider attempted this type of dynamic determination before, I think.

As a grody hack, we can work around the problem via the following, which arguably more closely matches the defaults, but it's obviously not a real solution.
```
if (textDirection === "rtl") {
  addClass(addTarget, options.cssClasses.textDirectionRtl);
} else {
  addClass(addTarget, options.cssClasses.textDirectionLtr);
}
```

**Comment by leongersen** [comment]
Thanks for your report, this is definitely a bug. Your proposed solution seems fine to me, as LTR is the default text direction, so inverting the check seems sensible. I'd be happy to accept a PR, if you're so inclined.

**Comment by bazineta** [comment]
PR submitted. As mentioned, I think that this is at best a workaround, but it's at least one that will return to the previous behavior for what I suspect will be the majority of those affected.

**Comment by leongersen** [comment]
I've just pushed noUiSlider 14.1.1 with this fix. Thanks for the PR, @bazineta!

**Comment by CGamesPlay** [comment]
Hey, this appears to cause problems in RTL languages. As you can see from this image, in RTL layouts the slider is shifted to the right. The behavior is actually that the slider on the left controls the left axis (so the orientation is correct), but it's graphically translated.

![image](https://user-images.githubusercontent.com/1216626/75323253-18f95e80-58a7-11ea-806f-533205cfd85d.png)

**Comment by leongersen** [comment]
@CGamesPlay What is the `direction` of your document?

**Comment by CGamesPlay** [comment]
The root element has `<html lang="he" dir="rtl">` and the component is in a container element with `<div style="direction: ltr">`.

For reference, the actual slider has `class="noUi-target noUi-ltr noUi-horizontal noUi-txt-dir-ltr"`.

**Comment by leongersen** [comment]
Is your slider element taken out of the DOM when you initialize it? As a workaround, could you try adding a `.noUi-target { direction: "rtl" }` style declaration?

**Comment by CGamesPlay** [comment]
That makes it seem more consistent, but still wrong. Now the slider handles begin exactly on the right edge of the slider bar.

![image](https://user-images.githubusercontent.com/1216626/75326470-42b58400-58ad-11ea-86da-7c8a142d7917.png)

No I don't think there's any delayed action going on. We are using a [react wrapper](https://gist.github.com/CGamesPlay/ef5464a0b43ed02bf3a9b62954944f93) around the component, but it's created post-mount, so the DOM node is already attached.

**Comment by leongersen** [comment]
With that style declaration added, do the generated classes change?

**Comment by CGamesPlay** [comment]
I think I had some caching issue. Setting `.noUi-target { direction: rtl }` does actually resolve the issue for me. It seems like it should be auto detected, but I can manually set it using something like `html[dir="rtl"] .noUi-target { direction: rtl }`.
