### ISSUE TITLE
nouislider.js:922 Uncaught TypeError: Cannot read property 'format' of undefined

### ISSUE THREAD

**Issue by SergeyGuns** [leongersen/noUiSlider#1040]
Hi, I use it for a long time, but not often. If option = undefined, trow this err : nouislider.js:922 Uncaught TypeError: Cannot read property 'format' of undefined.
In the minified version, it’s hard to understand what’s wrong.

**Comment by leongersen** [comment]
Could you show me the code you're using?

**Comment by SergeyGuns** [comment]
this works fine now, but if options are not declared. It turns out this error.
```js
function hasSlider(sliderElem, noUiSlider) {
	let sliderValue = 0;
	if (sliderElem && noUiSlider) {
		noUiSlider.create(slider, {
			tooltips: true,
			start: 0,
			format: {
				to: function(value) {
					sliderValue = value;
					const parseValue = parseInt(sliderValue);
					console.log(sliderValue);
					return `<div 
						class="noUi-tooltip__inner-block noUi-tooltip__inner-block_${parseValue}">
					</div>
					<div class="noUi-tooltip__message">${getMessage(parseValue)}</div>`;
				},
				from: () => sliderValue
			},
			range: {
				min: 0,
				max: 10
			}
		});
	}
}
````

**Comment by leongersen** [comment]
Sorry, I don't understand what you mean by your last comment.

**Comment by SergeyGuns** [comment]
`noUiSlider.create(slider, options)`  for options, need to do a check of undefined

**Comment by leongersen** [comment]
There's checks for the validity of the slider. I've added some extra tests to reflect this.
