### ISSUE TITLE
Not able to use as readonly slider.

### ISSUE THREAD

**Issue by Navin-vis** [leongersen/noUiSlider#1041]
I want to use the slider for only read the value. Can't find anything in the documentation to make the slider readonly.
Please will you help me out this. 
Thanks.

**Comment by leongersen** [comment]
You can [disable the slider](https://refreshless.com/nouislider/more/#section-disable) to make it readonly.

**Comment by Navin-vis** [comment]
Yup i did, but i had to make some changes in css as well.
