### ISSUE TITLE
Allow slider handle to pass another handle

### ISSUE THREAD

**Issue by jeremyroelfs** [leongersen/noUiSlider#1044]
I have a interest rate selector. When the value is past a certain point, the zero interest rate kicks in.
![image](https://user-images.githubusercontent.com/15094842/72179870-1a2c0600-33a3-11ea-834a-309db8f83de5.png)

The problem is, the user needs to slide the first handle past the zero percent handle to select a higher payment. Is there a setting or way to do this? If not, can I make this a feature request?

Edit... and it's more of a marker. Sort of like an overlay with a value that matches a certain point on the range.

Thanks!

**Comment by leongersen** [comment]
Yes, you can set the `behaviour` option to [unconstrained](https://refreshless.com/nouislider/behaviour-option/#section-unconstrained). That will allow handles to move past each other.

**Comment by jeremyroelfs** [comment]
Thanks Leon! I missed that in the docs.

**Comment by leongersen** [comment]
Glad I could help!
