### ISSUE TITLE
not working on(update)

### ISSUE THREAD

**Issue by GamerSK** [leongersen/noUiSlider#1046]
Hi,
I have newest version. 14.1.1. Problem is in function .on('update')

`document.noUiSlider.on("update", function(values, handle) {
            $("#price-from").text(values[handle] + "€");
            $("#price-to").text(values[handle] + "€");
        });`

error Cannot read property 'on' of undefined

**Comment by leongersen** [comment]
I'm not sure what you are trying to do. `noUiSlider` isn't a property on your `document`, it is on `window` (as a global), or after initializing a slider, on the element (e.g. `slider.noUiSlider.on`).

**Comment by GamerSK** [comment]
I don't get how it works.

Here is working example:

var slider1 = noUiSlider.create($("#slider-range")[0], {
    start: [1, 5000],
    connect: true,
    step: 100,
    range: {
        min: 0,
        max: 5000
    }
});

slider1.on("update", function(values) {
    $("#price-from").text(values[0] + "€");
    $("#price-to").text(values[1] + "€");
});

You have store slider in variable....

**Comment by leongersen** [comment]
Sorry, I don't get what you are asking. The example you are showing is the way it works.

**Comment by leongersen** [comment]
Closing this for lack of further feedback.
