### ISSUE TITLE
js .activeElement is not reported correctly for the noui-dragable class divs

### ISSUE THREAD

**Issue by hillct** [leongersen/noUiSlider#1047]
It appears that when (options object) behavior is set to drag-tap, and the user selects a draggable area between handles, .actieElement is reported to be the document.body tag, rather than the DIV having class 'noui-dragable'.

In this scenario, the expected behavior would be that the .activeElement would be the element the the user has clicked upon, ie: a DIV having the class noui-draggable.

Having not yet done an extensive code analysis, it would seem to me that this behavior is the result of the call to set document.body.style.cursor to "ew-resize" shortly before the 'slide' event is triggered. As such, the solution may be to slightly adjust the internal order of operation in this section of the code.

With this in mind, the workaround, for detecting the condition of user dragging a draggable range between handles, is to test for document.activeElement.style.cursor == "ew-resize" OR document.body.style.cursor == "ew-resize", although this is undesirable for what hould be obvious reasons - namely in the case where the cursor style is being reset outside of the noUI-Slider libraary, this workaround would be rendered ineffectual.

**Comment by leongersen** [comment]
What are you trying to do? I image the element isn't "active" as it cannot receive focus.

**Comment by leongersen** [comment]
Closing because there was no further response.
