### ISSUE TITLE
Way to color background in chunks

### ISSUE THREAD

**Issue by jmaurier** [leongersen/noUiSlider#1048]
I was wondering if there's a way to color the background between specified points in order to highlight interesting points on a timeline.

Example of what I'm working on creating:
![2020_01_24_11_31_05_noUiSlider_Examples_and_hints_Refreshless com_Brave](https://user-images.githubusercontent.com/13860561/73086106-f6d28200-3e9d-11ea-9722-97e4a5eb2458.png)

**Comment by leongersen** [comment]
Yes, you can use a `linear-gradient` with color stops for this purpose.

See [this answer](https://stackoverflow.com/questions/35561800/nouislider-set-a-background-color-for-the-limited-area) for an example.
