### ISSUE TITLE
Integers steps not working with every range

### ISSUE THREAD

**Issue by ZeCarlosCoutinho** [leongersen/noUiSlider#1049]
**PROBLEM**: The slider shows some values with a lot of decimal zeros, even if the step and the ranges are integers.
For example, instead of showing "14", it shows "14.00000001".
Why is it getting messed up with floats if all the parameters passed are integers?

**CURRENT SETUP**: The options for the slider are the following:
```
start: [0,90],
connect: true,
behaviour: 'drag-snap-tap',
step: 1 ,
orientation: 'horizontal',
range: {
    min: 0,
    max: 99
},
format: {
    to: function (value) {
        console.log(value) // This is here for explanation reasons
        return(value)
    },
    from: function (value) {
        return(value)
    }
}
```

The value logged by `console.log()`, in the initial rendering, is
> 0
> 90.00000000000001

(This should be just "90" since that is what I wrote in the arguments)

**Comment by leongersen** [comment]
The `format` option allows you to format your output the way you prefer. Floats are used internally, the logic is generic for any numeric input.

What do you need help with?

**Comment by ZeCarlosCoutinho** [comment]
I've already come up with a workaround by using the format option.

However, the bug still remains.
If define `step` option as 1 and the range as 0-90, I would expect to get numbers like [0, 1, 2, 3, 4,...] and not something like 14.000000000001.
Why would this operation between "integers" give a result with decimals?

**Comment by leongersen** [comment]
> Why would this operation between "integers" give a result with decimals?

The result of any division will be a float.
