### ISSUE TITLE
Keyboard input does not call .on('end')

### ISSUE THREAD

**Issue by jeremyroelfs** [leongersen/noUiSlider#1050]
Doing some ADA compliance and I realized that when a user tabs to the handle and moves it using the keyboard, that slider.noUiSlider.on('end', function(){ }); is not invoked.

"Update" does fire when using the keyboard arrows, however I am making a call to an endpoint and I do not want the endpoint hit consecutively on mouse/finger movement as it has nasty effects.

I added `fireEvent("end", handleNumber);` at line 1878 to fire on end also. It doesn't seem to have any negative effects but I do not want it breaking later. Is there a reason that wasn't added there?

**Comment by leongersen** [comment]
The `start` and `end` events are for mouse/pointer/touch interactions with the handles. For your use case, you probably want the `change` event.
