### ISSUE TITLE
When is the format.from called?

### ISSUE THREAD

**Issue by ZeCarlosCoutinho** [leongersen/noUiSlider#1051]
The `format` option requires the functions `to` and `from`.

I'm using the `to` function to encode a number of seconds in an 'mm:ss' format,
and the `from` function to decode that format.
```javascript
{
to: function(seconds) { 
    let duration = moment.duration(seconds, 'seconds')
    let formattedMin = Math.floor(duration.asMinutes())
    let formattedSec = ('0' + duration.seconds().toString()).slice(-2)
    return(`${formattedMin}:${formattedSec}`) //mm:ss
},
from: function(timeString) {
    let splittedTimeString = timeString.split(':')
    let duration = moment.duration({
        minutes: splittedTimeString[0],
        seconds: splittedTimeString[1]
    })
    return(duration)
}
}
```
```javascript
myfunction(value) {
    console.log(value)
}
```
```javascript
myslider.noUiSlider.on('set', myfunction)
```
WHAT I WOULD EXPECT:
When dragging the slider, the value selected would be decoded by `from` and returned by my handler function.

WHAT IS HAPPENING:
However, when the user drags the slider and `myfunction` is called, the value passed to `myfunction` is the output of `to`, not the output of `from`.
Shouldn't the `from` function be decoding the values picked by the user in the slider?

**Comment by leongersen** [comment]
The `format` option sets the formatting used to interact with the slider api. The `from` method is called when you initialize a slider, or when you call `noUiSlider.set`.
