### ISSUE TITLE
Missing documentation on `distribute/nouislider.css`

### ISSUE THREAD

**Issue by CamilleBC** [leongersen/noUiSlider#1052]
I don't know if this is the case in pure JavaScript, as I am using MeteorJS (not by choice ^^).

When importing `noUiSlider` with es6 syntax, the `distribute/nouislider.css` file is not imported. This causes the slider to *not* display. 
```javascript
import noUiSlider from 'nouislider';
```

I had to add `import 'nouislider/distribute/nouislider.css'` after the first import to get it working.
```javascript
import noUiSlider from 'nouislider';
import 'nouislider/distribute/nouislider.css';
```

Could it be added to the documentation somewhere in the installation instructions?
I hope I am not violating the guidelines here (I've read them, but I might still be wrong).

**Comment by leongersen** [comment]
It really depends on your build system, and whether you are using any kind of bundler. I'll add a note to the docs about this.

**Comment by leongersen** [comment]
I've added this now. Thanks for the suggestion!
