### ISSUE TITLE
Setting the start value with ranges spanning negative and positive numbers has odd behaviour

### ISSUE THREAD

**Issue by DanLew** [leongersen/noUiSlider#1059]
I have run into an issue while using a range which spans from negative to positive numbers, and trying to set the start parameter of a handle.

With a slider with a minimum of -25, and a maximum of 25, the start parameter seems to work like an offset from the lowest number. For instance, if I set the start value to 5, instead of the handle starting at the number 5 on the slider, it instead starts at -20. This works fine up until setting start to 25, which we would expect to set the start to 0 on the slider. However, I have found that it sets the handles start position to the integer 25 on the slider, making it impossible to set the start to any other positive number.

I have managed to work around this using the below, allowing me to set the start value to 0, but there I cannot set it to the positive numbers.

    noUiSlider.create(slider, {

            start: [24.99],
            connect: 'lower',
            range: {
                'min' : -25,
                'max' : 25
            },
            step: 0.25,
            tooltips: true,
            format: {
                // Return formatting
            }

        });

**Comment by leongersen** [comment]
What are you doing in your `// Return formatting`?

**Comment by DanLew** [comment]
Ok, yeah. It's an issue the return formatting.

We needed to make sure the + sign was included on positive numbers, so we added it to the beginning of the number in those cases.

    format: {
                to: function (value) {

                    if(value === 0){
                        return value;
                    }

                    if(value <= 0){
                        return Number(value).toFixed(2);
                    }

                    return '+'+Number(value).toFixed(2);
                },
                from: function (value) {
                    
                    if(value === 0){
                        return value;
                    }

                    if(value <= 0){
                        return Number(value).toFixed(2);
                    }
                    return Number(value.replace('+', '')).toFixed(2);
                }
            }

The start property works correctly without this.

**Comment by leongersen** [comment]
Happy to help!
