### ISSUE TITLE
Pip value does not get drawn if the only pip to be drawn equals the slider max value

### ISSUE THREAD

**Issue by rollila** [leongersen/noUiSlider#1062]
As per the title: given a slider with a single displayed pip value, if the pip value equals the maximum range value, the value does not get drawn. If there is more than one pip value shown, they will be displayed even if one of them equals the range maximum value. 

The use case here is to use the pip value to show the currently selected value. When the slider is moved to the end, the displayed value disappears. 

Code to replicate: 

```javascript
noUiSlider.create(el, {
  start: [0],
  step: 1,
  range: {
    in: 0,
    max: 20
  },
  connect: [true, false],
  pips: {
  	mode: 'values',
        values: [20]
  }
});

el.noUiSlider.on('update', valueStrings => {
	var values = valueStrings.map(value => parseInt(value, 10));
	el.noUiSlider.pips({
  	   mode: 'values',
           values: values
      })
})
```

**Comment by leongersen** [comment]
I've merged your fix, and released it in noUiSlider 14.2.0. Thanks for contributing!
