### ISSUE TITLE
noUiSlider.on('change', function () { }) event not working on some devices

### ISSUE THREAD

**Issue by ErlashTheOne** [leongersen/noUiSlider#1064]
Hi,
Im working with this library and Chart.js-RangeSlider in one web project, but i have issues on some mobile devices like iPhone 11, iPhone 11 pro and iPhone X. Nevertheless, in iPhone 11 pro max and all desktop works perfectly.

I have a function that is:
this.rangeSliderChart.sliderElement[0].noUiSlider.on('change', () => {
/* do something*/
}

This function do something everytime that the slide handle is moved. I prove with another noUiSlider events but this is not working in more devices that have worked with 'change' event.

Do you know if this is a bug of this library, is it Chart.js-RangeSlider bug or is it a conflict between devices?

Thanks in advance.

**Comment by leongersen** [comment]
This isn't something that sounds familiar to me. Is there perhaps an element overlapping your slider on these smaller devices?

**Comment by leongersen** [comment]
Closing this as there was no further response.
