### ISSUE TITLE
Pips aren't hitting same value of slider

### ISSUE THREAD

**Issue by terryaney** [leongersen/noUiSlider#1065]
I can't figure out how to get pips to hit 'integer' values.  For small scale, I'd like a pip (large and/or small) for every step/value.  For large ranges, I'd like pips to hit multiples of 5.  My min isn't always 0 as well, so that might be an issue.

You can see how the value is slightly shifted from the pip:

![image](https://user-images.githubusercontent.com/6237247/78301958-854b2b80-74ff-11ea-8095-ccca46e544ca.png)

You can view the problem displayed here: https://jsfiddle.net/v5xepmj0/9/ (note that our app doesn't use default tooltips)

Any guidance would be greatly appreciated.

**Comment by terryaney** [comment]
I was battling this while waiting for any comments, turns out the above fiddle is on bootstrap 4 and latest noUiSlider.  Our site uses bootstrap 3, jquery 1.12, and noUiSlider 10.0 and it seems to actually hit exactly what I want here: https://jsfiddle.net/oy3ktma1/.  But if I change noUiSlider to latest (leaving it at older bootstrap and jquery versions), it behaves as I originally asked - https://jsfiddle.net/oy3ktma1/1/.

**Comment by leongersen** [comment]
Since you are changing the `width` of the `.noUi-handle`s, you'll also need to correct the `right` value to half of the width (in your case that would be `-10px` instead of the current `-17px`).

**Comment by terryaney** [comment]
Thanks.  The 'styling' was given to me from designer no longer avail for support and css/html is not a 'strength' of mine :)  So, the style needed is obviously because of changes to later versions of the library? (and yes, applying a right style with same specificity as libary css fixed issue)

**Comment by leongersen** [comment]
Yes, starting from noUiSlider 11 all handles are positioned using transforms, thus affecting existing stylesheets.
