### ISSUE TITLE
defer noUiSlider problem

### ISSUE THREAD

**Issue by Macro-Jackson** [leongersen/noUiSlider#1067]
I have the following problem. My slider on my page is not the most important element on the page. So I'd like to defer my noUiSlider script.

But that does not work because the initialization is done by Javascript itself and it is dynamic so generated by PHP (for example the range values). So I need to put the JS inline in my HTML page. Therefor I can't defer my script. Now there are ways around that but....

Can't I give these parameters via HTML properties? Then I can initialize in my general deferred javascript (which is static).

Or do it like they add configuration settings to Lazysizes: https://github.com/aFarkas/lazysizes#js-api---options

**Comment by leongersen** [comment]
You can wrap your php-generated JS in a `function`, and call it when you need to.
