### ISSUE TITLE
Can not remove classes properly if entries of cssClasses contains multiple classes

### ISSUE THREAD

**Issue by nightire** [leongersen/noUiSlider#1069]
The PR https://github.com/leongersen/noUiSlider/pull/1055 introduces a nice feature to allow users to provide multiple class names in the `cssClasses` option, but this PR is not complete because it only covers the initialize phase.

With v14.2.0, if users called `.destroy()`, below codes will throw an error because `HTMLElement.classList.remove()` can not remove the class name contains spaces:

https://github.com/leongersen/noUiSlider/blob/f8090f1e59506ad5a2260ee5e6164c5d56175918/src/nouislider.js#L110-L119

I'll send a patch PR later to help with the release of a new patch version ASAP.

**Comment by leongersen** [comment]
I've added a test in 159ff1164ae34619a7418183073e3410566e7965. I've exposed the default `cssClasses` object as well, and released this as noUiSlider 14.3.0. Thanks for reporting this, @nightire!
