### ISSUE TITLE
Trojan:Win32/Sprisky.U!cl

### ISSUE THREAD

**Issue by Cocomat** [leongersen/noUiSlider#1072]
Windows Security blocked me from downloading the Zip from Github. Is this threat real or is it a bug in Windows Security? 

![image](https://user-images.githubusercontent.com/7515232/81387486-10c76600-9117-11ea-8dbd-2784f6b16d7a.png)

**Comment by leongersen** [comment]
The zip is just a download of the whole repository. I just ran defender on one myself, and I'm not getting any hits. My guess is there is either something else on your system causing this, or you are running into a false positive.

**Comment by Cocomat** [comment]
Ok, thank you. Thats weird. I will recheck my system.
