### ISSUE TITLE
Problem with nouislider Scale

### ISSUE THREAD

**Issue by AkriFazeer** [leongersen/noUiSlider#1073]
Hi !
I have a little problem with your extension, the slider takes the width of the DIV but the buttons do not go until the end! (pic join: https://ibb.co/jvt3bD2)

`noUiSlider.create(doubleSlider[0], {
            start: [50, 160],
            step: 1,
            behaviour: 'drag',
            tooltips: true,
            connect: true,
            margin: 0,
            padding: 0,
            range: {
                'min': 50,
                'max': 60
            }
        });`
![issuenoui](https://user-images.githubusercontent.com/62928026/81461228-90eadb80-91aa-11ea-85cf-2040be97b60a.PNG)

Here for the blows I do not know if the problem comes from me or the extension.

Thank you for your help

**Comment by leongersen** [comment]
I don't completely understand what your issue is, sorry. Could you elaborate? You do have `160` as your handle `start` value, but `60` as the slider `max`.

**Comment by AkriFazeer** [comment]
Hello ! Sorry I'm using Google Translate.
Indeed I had a small error in the code:
`noUiSlider.create(doubleSlider[0], {
            start: [50, 160],
            step: 1,
            behaviour: 'drag',
            tooltips: true,
            connect: true,
            range: {
                'min': 50,
                'max': 160
            }
        });`

But the result is the same, the maximum cursor does not go until the end of the slider.
The "min" is at 60 and the "max" at 160, but the cursor "max" does not go all the way.

Thanks again !!
![issuenoui](https://user-images.githubusercontent.com/62928026/81473027-3da17900-91fc-11ea-8200-01d56ca88689.PNG)

**Comment by AkriFazeer** [comment]
Hi,

I come back to you because I solved my problem. It was my own css that was involved.
Sorry to have created a question for nothing.

Good continuation

**Comment by leongersen** [comment]
No problem, I'm glad you figured it out!
