### ISSUE TITLE
nouiSlider update on - not on initialization

### ISSUE THREAD

**Issue by Macro-Jackson** [leongersen/noUiSlider#1074]
I have a price slider implemented and for usability I'd like the input fields (min and max) to have a placeholder value (start values). So I've taken care about this in my PHP code to get this done. That works fine.

Now I also like these fields to be updated realtime by the slider moving around. So I've implemented:
```
slider.noUiSlider.on('update', function (values, handle) {
    inputs[handle].value = Math.round(values[handle]);
});
```

But that directly give the input fields a value. So it directly undo's the placeholder idea. And now the user when entering the price field directly needs to delete the numbers in the field to enter a new one even though they never entered a value.
Is there a known way around this (slider.noUiSlider.on('update',) that it is not updated on initialization? Or do I need to make a custom one myself? :-)

**Comment by leongersen** [comment]
You could keep a variable that registers whether the `update` event was called:

```JavaScript
var init = [];

slider.noUiSlider.on('update', function (values, handle) {
    if (init[handle]) {
        inputs[handle].value = Math.round(values[handle]);
    }

    init[handle] = true;
});
```

**Comment by Macro-Jackson** [comment]
I should be able to found that myself....

Thanks!
