### ISSUE TITLE
Move lower handle if upper handle is set to a value bellow it

### ISSUE THREAD

**Issue by smfukaya** [leongersen/noUiSlider#1075]
Hello,

I'm building a 2-handle slider using the 14.5.0 version and following the simple [example](https://refreshless.com/nouislider/slider-values/#section-handles). I added two buttons: one to set the lower handle to 100 and the other sets the upper handle to 50. The first button makes the lower handle move to 100 and the upper handle is "dragged" together (desired outcome). However, the second button makes the upper handle move only to 70 (value of lower handle) instead of 50. I was wondering if there is a way to make both handle behave equally.

`
    setLowerButton.addEventListener('click', function () {
        slider1.noUiSlider.set([100, null]);
	});

    setUpperButton.addEventListener('click', function () {
        slider1.noUiSlider.set([null, 50]);
	});
`

My slider was initialized:
`
noUiSlider.create(slider1, {
	start: [70, 80],
        connect: true,
        animate: false,
		range: {
			min: 10,
			max: 150
		}
	});  
`
Thank you!

**Comment by smfukaya** [comment]
Please also check that behavior using with the modified [locking sliders together](https://refreshless.com/nouislider/examples/#section-lock) with two handles in the attached video
[noUiSlider_v14.5.0.mp4.zip](https://github.com/leongersen/noUiSlider/files/4688555/noUiSlider_v14.5.0.mp4.zip)

**Comment by leongersen** [comment]
You are calling the `set` method with `[null, 50]` meaning the lower handle will not be affected. If you want to change both handles at the same time, you can pass `[50, 50]` (setting the lower handle, too). Does that help?

**Comment by smfukaya** [comment]
Hi Léon, I think it could help (gonna try it), but shouldn't it happen with the upper handle when I call the `set` method with `[100, null]`?

**Comment by leongersen** [comment]
Sorry, I missed your follow-up, @smfukaya. Did you manage to figure out your issue?

**Comment by smfukaya** [comment]
Hi @leongersen! It seems that the lower handle can move the upper handle if you call `set` from the 'slide' event (while the upper handle cannot move the lower handle). After checking the [events docs](https://refreshless.com/nouislider/events-callbacks/) and some trials and errors, I changed my code (it was based on the [Locking sliders together](https://refreshless.com/nouislider/examples/#section-lock)) to call `set` from the 'update' event. Now each handle in same slider cannot move the other further its current position. At least, the behavior is consistent.
