### ISSUE TITLE
Disabling a slider code? [noUiSlider-3.2.1]

### ISSUE THREAD

**Issue by Kowa92** [leongersen/noUiSlider#1078]
Hello,

i have a webpage that uses you noUiSlider version 3.2.1. 
For not change the graphics of these sliders, i would like to avoid using a new version of your software (i.e. https://refreshless.com/nouislider/more/ one). My question is:

- In this version is it possible to disable these sliders or not? If the answer is yes, what code/method/function should i use to do this?

I tried to search around web but i could not find anything (no in your official wiki too).

PS: This is an example of code of noUiSlider i have:

`      $("#brightness_slider").noUiSlider({
          range: [<?php echo $brightness_minimum . ',' . $brightness_maximum ?>]
         ,start: <?php echo $brightness . "\r\n" ?>
         ,step: 1
         ,handles: 1
         ,slide: function(){
            var values = $(this).val();
            $("#brightness").val(values);
         }
      });`

It is a mix of php and jQuety.

Thanks to all.

Greetings

**Comment by leongersen** [comment]
Sorry, I can't support that noUiSlider version any more. I recommend that you upgrade to the latest version, you you can take advantage of all cross-browser (and mobile) support that has since been added.
