### ISSUE TITLE
Connect background gradient affected by scaling

### ISSUE THREAD

**Issue by dresende** [leongersen/noUiSlider#1080]
The connect blocks (`.noUi-connect`) are scaled based on the vales of the slider. This affects defining gradients in CSS for that black since the scale transition will destroy the goal, or at least for some use cases.

I'm using noUiSlider to design a window shutter. I believe 2 images will make my point clear.

<img width="249" alt="Screenshot 2020-06-20 at 19 22 07" src="https://user-images.githubusercontent.com/157494/85208840-5fc60500-b32b-11ea-98ee-e7aaa3cb12be.png">
<img width="233" alt="Screenshot 2020-06-20 at 19 22 15" src="https://user-images.githubusercontent.com/157494/85208842-62285f00-b32b-11ea-9d69-da97f3f019fb.png">

Is there a solution to this background scaling?

**Comment by dresende** [comment]
This is my CSS. I was trying to find an alternative but I'm out of ideas..

```css
background: repeating-linear-gradient(to top, #fff 0, #fff 10px, #aaa 10px, #aaa 11px, #ccc 11px, #ccc 12px);
```

**Comment by leongersen** [comment]
For your example images, you could solve this by setting the connect on the other side, and styling it the dark gray color. You could then use the repeating background on `.noUi-base`.

**Comment by dresende** [comment]
> For your example images, you could solve this by setting the connect on the other side, and styling it the dark gray color. You could then use the repeating background on `.noUi-base`.

Thank you. Good one! It solves my case, but for people with more than one handle, this could be a problem. Thank you anyway for finding a solution!

**Comment by dresende** [comment]
The only thing it won't be perfect, is that if I style the connect area, I could see the shutter going up. In your solution it will be strange for someone expecting to see a shutter going up.
