### ISSUE TITLE
Suggestions with two starting values do not work

### ISSUE THREAD

**Issue by segressio** [leongersen/noUiSlider#1081]
Hello, why do suggestions for work for three sliders, but for two it gives an error?
![image](https://user-images.githubusercontent.com/52033804/85234126-ea822f00-b413-11ea-80c3-a5e91b672323.png) 
![image](https://user-images.githubusercontent.com/52033804/85234144-08e82a80-b414-11ea-9e19-fde8214a35b2.png)

**Comment by leongersen** [comment]
The error message isn't correct there (I'll get that fixed), but the issue here is that the amount of values you pass to `tooltips` needs to match the amount of values you pass to `start` (as it specifies a formatter for each tooltip).
