### ISSUE TITLE
Handles inside container

### ISSUE THREAD

**Issue by amichel86** [leongersen/noUiSlider#1086]
Hi thank you for your plugin, I searched a lot to find a good one and I found a great one with noUiSlider!

I am trying to achieve this layout (see image) but the handles are always overflowing outside of the container (because of the negative _right_ property I guess?). Is there a way to have them like in my screenshot or for functionality purposes they always need to be a little bit overflowed?

![image](https://user-images.githubusercontent.com/5871701/86918157-43301800-c0f4-11ea-81c4-a7c6d8ffb4d2.png)

Thanks!

**Comment by leongersen** [comment]
You can do this by adding some padding the the slider target element. There's some docs here:

https://refreshless.com/nouislider/more/#section-styling

**Comment by amichel86** [comment]
Hey @leongersen thanks a lot, I will look into that! :)
