### ISSUE TITLE
Slider goes from months to years 

### ISSUE THREAD

**Issue by lori698** [leongersen/noUiSlider#1087]
Is it possible to create a slider that goes from months to years i.e. starts at 3 months (0.25) and goes to 60 months (5 years) but the tool tips displays (60 months (5 years)) or 3 months (0.25) etc. 

Also is it possible to have +/- buttons at the side of slider to make it go up/down. 

Any help is much appreciated

**Comment by leongersen** [comment]
Yes, that would all be possible. You'd use the `format` setting and the `set` method.

Please check the [contribution guidelines](https://github.com/leongersen/noUiSlider/blob/master/CONTRIBUTING.md).
