### ISSUE TITLE
Make slider readonly 

### ISSUE THREAD

**Issue by lcor-commits** [leongersen/noUiSlider#1089]
https://jsfiddle.net/leongersen/9hyfv0bw/6/

Is there anyway to make the slider so that the button in the middle doesn't move?  But stays in its initial position?

**Comment by leongersen** [comment]
Yes, you can set either the slider or the handle to `[disabled]`. Have a look at the [documentation on disabling sliders](https://refreshless.com/nouislider/more/#section-disable).
