### ISSUE TITLE
Change events called twice on iOS when tapping on slider

### ISSUE THREAD

**Issue by chickenwing** [leongersen/noUiSlider#1095]
On my iPhone iOS 13.3 the change (and set) events get called twice when I tap on the slider to move the handle there - it does not happen when I drag the handle. Is this by design?

I made a codepen to reproduce: https://codepen.io/bjoernpen/pen/QWNpexY

thx for this library!

**Comment by leongersen** [comment]
I just tested this on Browser stack, and I'm seeing this too. There isn't supposed to be a second change event, and only one fires on iOS 12. The one from the tap is handled first (the `tap` argument to the event is `true`), but a dragging event seems handled, too. I'll investigate.

**Comment by leongersen** [comment]
Possibly related to #1057 and #1079.

**Comment by leongersen** [comment]
I just fixed this issue, and release noUiSlider 14.6.2. Thanks for reporting!
