### ISSUE TITLE
Slider handles layout issue when html direction is rtl.

### ISSUE THREAD

**Issue by Usman08** [leongersen/noUiSlider#1097]
I am facing a layout issue when HTML document direction is rtl. 

```
<html style="direction: rtl;">
	<head>
		<link href="nouislider.css" rel="stylesheet">
		<script src="nouislider.js"></script>
	</head>
	<body>
		<div id="slider" style="width:150px;"></div>
		<script>
			noUiSlider.create(slider, {
				start: [20, 80],
				connect: true,
				direction: 'rtl',
				range: {
					'min': 0,
					'max': 100
				}
			});
		</script>
	</body>
</html>
```

I'm using this code. when I remove the direction style from the HTML tag then it works fine. Please suggest some configurations that can fix it. Thanks!

@leongersen

**Comment by leongersen** [comment]
What issue are you facing? You might want to try changing your document direction using the [dir attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir).

**Comment by Usman08** [comment]
Using dir attribute it is working fine but while using direction of style attribute it causes the issue as you can see in the attached screenshot.
![image](https://user-images.githubusercontent.com/26241703/91970206-bccd3680-ed30-11ea-8c70-c8a8159cca9e.png)

By the way many thanks @leongersen for your quick response.

**Comment by leongersen** [comment]
Any reason not to use the `dir` attribute here? Note that swapping the direction on the `html` element behaves differently to loading a document with it already present.

**Comment by Usman08** [comment]
No special reason, now I'm using `dir` attribute. Thanks again
