### ISSUE TITLE
Vertical slider in flex container fails in Safari

### ISSUE THREAD

**Issue by RickMohr** [leongersen/noUiSlider#1103]
Please see [this pen](https://codepen.io/RickMohr/pen/XWKJPLq), showing a vertical slider in a flexbox container. In Safari the handle can't be moved, but it works fine in other browsers.

It appears that Safari is ignoring the `transform` property (used to position the slider handle) -- here's [another pen showing the same issue without noUiSlider](https://codepen.io/RickMohr/pen/NWNzJvb).

One workaround is to make the slider `position: absolute` and add an extra `div` to contain it (as in [this pen](https://codepen.io/RickMohr/pen/PozwEXw)).

Thank you very much for noUiSlider. I am gratefully using a vertical non-linear slider with unlabeled pips at custom positions (to control an animation).

**Comment by RikuVan** [comment]
I think this is just a quirk of flexbox in safari:
What if you change to this?

```
#slider {
  position: relative;
  flex: 1 0 0px;
}
```

**Comment by RickMohr** [comment]
This appears to have been fixed in Safari. 

Closing.

**Comment by leongersen** [comment]
Ok, great. Thanks for following up. 👍
