### ISSUE TITLE
Ability to add additional ranges (connected pairs of handles) to a slider

### ISSUE THREAD

**Issue by mandclu** [leongersen/noUiSlider#1105]
I'd like to have my slider start as full range, and then a user can narrow down. I can foresee valid uses cases where the required input isn't a single, continuous range, however. I would like to provide a button the user could use to add additional ranges. Is there a method that currently supports this?

It seems like it would be possible to effectively rebuild the entire slider with an additional set of handles, but I wondered if there was a simpler way to achieve it.

**Comment by leongersen** [comment]
You are right, to add and remove handles you'll have to rebuild the slider.
