### ISSUE TITLE
set and change events are fired twice when using snap behaviour

### ISSUE THREAD

**Issue by ofrias** [leongersen/noUiSlider#1106]
Hello.

The 'set' and 'change' events are fired twice when noUiSlider is configured using the 'snap' behaviour.  I am using the last version (14.6.2).

This is the sequence of events fired when I click on the slider bar and it is configured with the 'snap' behaviour:

slide, update, change, set, start, change, set, end

And this is the sequence when not using snap:

slide, update, change, set

It looks as if a spurious mouse drag is being processed, even if you just click in the slider bar without moving the mouse at all.

Could you please check this?

**Comment by leongersen** [comment]
Thanks for reporting this, I'll have a look.

**Comment by leongersen** [comment]
This is fixed in noUiSlider 15.4.0. Thank you for reporting this, @ofrias!
