### ISSUE TITLE
Entering decimals through inputs and not the handles

### ISSUE THREAD

**Issue by lomadejors** [leongersen/noUiSlider#1107]
I have been trying to work this out, but it seems impossible. All I need is to make the slider show decimals in the tooltips without setting step at 0.1 because I still want it to be that way, and I just want to be able to enter decimals through the use of inputs and not by the handles. Is there something I can do?

**Comment by leongersen** [comment]
You can pass a formatter to the tooltips option:
```
tooltips: wNumb({decimals: 1}),
```

https://refreshless.com/nouislider/number-formatting/

**Comment by lomadejors** [comment]
Thanks for replying. The thing is that if I enter 2.5 in my input, the tooltip does not display 2.5, instead it shows 3 since the steps are set at 1.

**Comment by lomadejors** [comment]
I just came across exactinput, thank you so much!

**Comment by leongersen** [comment]
Glad you worked it out! :)
