### ISSUE TITLE
Value of slider is coming in decimals even if min, max and steps are in integer

### ISSUE THREAD

**Issue by sunilpandey** [leongersen/noUiSlider#1108]
I am creating slider with following configuration
 noUiSlider.create(slider, {
      start: 20,
      connect: true,
      
      range: {
          'min': 1000,
          'max': 10000
      },
      connect: [true, false],
      step: 1000,
      tooltips: true,
      format: wNumb({decimal: 0}),
  });

However when I am moving the handle to 4000 slider is returning value 3999.9999..5 instead.
Please find related plunkr https://plnkr.co/edit/WEGWt1edqXGm3aXQ
![value in decimal](https://user-images.githubusercontent.com/3031692/97327182-bc699b80-189a-11eb-863a-7c1c18bb82f7.png)

**Comment by leongersen** [comment]
The `{decimal: 0}` you are using should be `{decimals: 0}` (you are missing the `s`).

**Comment by sunilpandey** [comment]
Issue still persist. It looks like you are formatting and parsing with 2 decimal digits that is why when custom formatter is not applied it is working fine. 
Once custom formatter is applied this becomes a problem and internal value is wrong with fraction. In ideal scenario If all three value min, max and step are numeric then it should never return a fractional value.
