### ISSUE TITLE
Interrupt sliding on update event.

### ISSUE THREAD

**Issue by ansanes** [leongersen/noUiSlider#1111]
I'm trying to implement a dynamic range slider. Initially the slider range is set to min:100, max:200. When the user slides to the max value(200) I change the range of the slider to min:200, max:300 by using the 'update' event and then updateOptions function. 

When the range changes, the slider handle automatically moves to the top left of the slider (200) but immediately goes back to the top right(300) because the slide hasn't finish yet. 

Is there a way to interrupt the sliding when I change the slider range to keep the handle in the correct position?

**Comment by leongersen** [comment]
There're currently no cancelable events in noUiSlider. It's a feature I'd be interested in, but I haven't given it much thought yet.
