### ISSUE TITLE
Feature request: pure JS replacement of HTML inputs, without the need of a div

### ISSUE THREAD

**Issue by int-ua** [leongersen/noUiSlider#1113]
I'm setting up a Drupal site and putting a new div in a correct place is a hassle. Wouldn't it be nice if it was possible to just add noUiSlider without a div and without a need to create the div in JS myself, just by pointing it to an `<input type=number>`? So that any client without JS will just see the original input and anyone with JS will see the slider. Yes, the code may be trivial, but it would make noUiSlider even more useful. Feel free to close this, I'll have to implement it myself if I decide to go with noUiSlider anyway.

**Comment by leongersen** [comment]
For a feature like this, the minimum version would always be missing that "one thing" for a specific situation to make it useful. In this case it is reading settings from an `input`, but that'd rapidly expand to `data-` attributes, etc, etc.

Like you mentioned, the wrapper code to make this happen is minimal, and adaptable to the specific situation, so I'll close this one. Thanks for contributing though, hope you find noUiSlider useful!
