### ISSUE TITLE
Accept user input while animating

### ISSUE THREAD

**Issue by GitFr33** [leongersen/noUiSlider#1115]
Is there a way to make noUiSlider respond to user input while it is being set by javascript? It seems like the default behaviour is to disable user input when noUiSlider.set() is called until animation is finished. If not, is there a way to speed up the animation to reduce the amount of time that the slider is busy animating.

I am using noUiSlider as a seekbar for an html audio player. The noUiSlider is set every second to reflect progress as a song plays. noUiSlider works well for this but my problem is that much of the time it is busy animating, so when the user tries to use the scrubber to rewind of fast-forward if often doesn't respond.

**Comment by leongersen** [comment]
I think for your use the best solution would to to disable the animation. You can set `animate`  to false (which will allow user interaction), and optionally remove the CSS transition. Here's the [documentation on the `animate` option](https://refreshless.com/nouislider/slider-options/#section-animate).

**Comment by GitFr33** [comment]
Thank you @leongersen!
