### ISSUE TITLE
Cannot slide while updating the data 

### ISSUE THREAD

**Issue by mdhsl** [leongersen/noUiSlider#1117]
First of all, Hi everyone and thank you for the great work done on this lib!

I have a problem trying to slide while updating the data.

If you have a loop continuously updating the data to move the handle using the "set" method, and you try to move the slider at the same time, it doesn't work every time. In fact, after investigation, the click on the handle is not always captured because the update execution is running.

Here is an example showing the problem: http://opensensorhub.github.io/osh-js/dev/showcase/range-slider.html

The code of my component: https://github.com/opensensorhub/osh-js/blob/dev/source/osh-ext/ui/view/rangeslider/RangeSliderView.js#L199

**Comment by mdhsl** [comment]
I have found a work around but I don't know if it doesn't cause any other problems. 

My problem comes from this line: https://gist.github.com/mdhsl/01aee2a6ddf5a208e9706c6b5a8fe91e#file-nouislider-js-L1594

The event is not propagated any more because we enter this condition.

My work around is to use the doNotReject value on the 'mousedown' type by forcing it to true:

https://gist.github.com/mdhsl/01aee2a6ddf5a208e9706c6b5a8fe91e#file-nouislider-js-L2041

Can it cause edge effects?

**Comment by leongersen** [comment]
If the condition you've linked causes your issue, I think the fix you have applied probably won't have side effects, other than unexpected reactions when setting the slider value just after the user has tapped the slider to change it. You can also [disable animation](https://refreshless.com/nouislider/slider-options/#section-animate), which probably would also resolve your issue.
