### ISSUE TITLE
At what point is the noUi-target class added to the Element?

### ISSUE THREAD

**Issue by damiantoczek** [leongersen/noUiSlider#1119]
Hello,
I want to make the sliders usable for Form elements and I need to know at what point the `noUi-target` class is added to the root element. I can't find it.

**Comment by leongersen** [comment]
The `noUi-target` class is added when the slider is initialized.

**Comment by damiantoczek** [comment]
Do you have a flowchart or similar for this?
noUiSlider.create -> initialize -> calls scope -> calls setupSlider with no arguments -> calls addSlider -> add slider calls addClass functions that are appended to the root element that was provided when calling the noUiSlider.create function `noUi-target noUi-ltr noUi-horizontal noUi-txt-dir-ltr` -> calls addNodeTo the target element with css classes base.

Correct?

**Comment by leongersen** [comment]
Yes, the slider is initialized on `create` and that's when classes are added.
