### ISSUE TITLE
Add starter

### ISSUE THREAD

**Issue by Belingheri** [leongersen/noUiSlider#1122]
Hi, how can i add new item to the slider?
If i inizialized with strater like `[0,30,90] `how can i add another?
if i do `set([10,34,93,100]) ` it work only on the first 3 
tk

**Comment by leongersen** [comment]
To add a handle to the slider, you can `destroy()` and recreate it.

**Comment by Belingheri** [comment]
Yes i do in this way,  but i suppose there is another way
tk
