### ISSUE TITLE
updateOptions({start: 0}) does not move slider position

### ISSUE THREAD

**Issue by JonathanGawrych** [leongersen/noUiSlider#1127]
When you pass `start: 0` to updateOptions, it does not move the slider, but instead uses the current position. Here's an example of that: https://plnkr.co/edit/JuHqtg7EMQX7QejI

It looks like the issue is https://github.com/leongersen/noUiSlider/blob/14.6.3/src/nouislider.js#L2601. The code assumes a falsey `start` value should use the current value, but 0 is a valid start value. Instead it should only be a undefined (or null) value that uses the current value.

(obviously `set` is the correct function for updating values, but this is a specific case where I need to update various options and restart the slider back to 0)

**Comment by leongersen** [comment]
I'd say you are quite right, looks like a bug.

**Comment by leongersen** [comment]
Fixed in noUiSlider 14.6.4. Thanks for reporting!

**Comment by JonathanGawrych** [comment]
Awesome. Thanks for the amazing (accessible) library!
