### ISSUE TITLE
I integrated wNumb.js to format the number but received the error message

### ISSUE THREAD

**Issue by aboyit** [leongersen/noUiSlider#1131]
I integrated wNumb.js to format the number but received the error message, please give me a way to handle it, thanks a lot.
![image](https://user-images.githubusercontent.com/20743425/114169420-c0c2d600-995b-11eb-9376-ebaa38714b50.png)

**Comment by leongersen** [comment]
You have a syntax error, there is a comma missing after `range`/before `format`.
