### ISSUE TITLE
How do I change the step?

### ISSUE THREAD

**Issue by fisherspoon** [leongersen/noUiSlider#1136]
Hi, I have a slider, the range is from 3000 to 300,000. I can't figure out how to make sure that the step from 3000 to 5000 was equal to 2000, and after five it was equal to 5000. And is it possible to add a separator in the form of a space and a marker in the marker text currency? $ 5,000, $ 50,000, $ 150,000. I would be grateful for your help.

https://codepen.io/fisherspoon/pen/jOBWJQP

**Comment by leongersen** [comment]
I've answered [your StackOverflow question](https://stackoverflow.com/a/67530689/775265).
