### ISSUE TITLE
-50 to 2020

### ISSUE THREAD

**Issue by mprove** [leongersen/noUiSlider#1138]
I remember having an issue with a range from -50 to 2020. But I am too lazy to check again.
The problem was that the value indicators went blank.

I still love your excellent module!  e.g. screenshot: https://twitter.com/chronohh/status/1395239832985743361/photo/1

**Comment by leongersen** [comment]
I'm glad you're liking noUiSlider. You'll need to expand on what you're having issues with, I can't really do anything based on this so far.

**Comment by mprove** [comment]
Oh dear, do you know that moment when you look at your code and say, "how on Earth was this working before?!"
FYI I set a string as a value. That caused the issue. Hence its mine; not yours.
Now I can set this map at 50 B.C. https://mprove.de/chrono?q=46.16711,2.88347&z=4.93&m=AUgavle&t=15&c=m
Press L are open this link to see your slider in action: https://mprove.de/chrono?q=46.16711,2.88347&z=4.93&m=AUgavle&t=15&d=1&c=l
