### ISSUE TITLE
Get the scope_Values

### ISSUE THREAD

**Issue by s-cork** [leongersen/noUiSlider#1139]
Can we have a method to expose the unencoded values?

Maybe just an argument to the get method

```typescript
// Get the slider value.   
function valueGet(unencoded=false): GetResult {
    if (unencoded) {
        return scope_Values.length === 0 ? scope_Values[0] : scope_Values.slice(0);
    }
    ...
}
```

The only api I can see to get these values is as part of the event handlers system.

**Comment by leongersen** [comment]
Yes, this sounds like a good addition. I'd be open to a pull request :)
