### ISSUE TITLE
updateOptions - tooltips can't be set to a single formatter

### ISSUE THREAD

**Issue by s-cork** [leongersen/noUiSlider#1140]
extension of issue #1101 I think.

**Comment by leongersen** [comment]
Could you add an example?

The following works as expected:

```
var format = { to: ..., from: ... };

noUiSlider.create(slider, {
    start: [20, 80],
    range: { 'min': 0, 'max': 100 }
});

slider.noUiSlider.updateOptions({ tooltips: format });
```

**Comment by s-cork** [comment]
right you are - I think i'd done something strange when I was hacking around.

Love the library btw.

**Comment by leongersen** [comment]
Ok good - Glad you find it useful :)

**Comment by s-cork** [comment]
I know what it was - I tried to update a tooltip with just a {'to': ...} as a formatter. Since I figured tooltips didn't need a {'from': ...}.

The following code breaks with the error:
`noUiSlider: must pass a formatter for all handles`

```javascript
var format = { to: ... };

noUiSlider.create(slider, {
    start: [20, 80],
    range: { 'min': 0, 'max': 100 }
});

slider.noUiSlider.updateOptions({ tooltips: format });
```

But the code would have worked fine if i'd passed in the same formatter like `tooltips: [format, format]`
