### ISSUE TITLE
How to use format (from, to) with range slider?

### ISSUE THREAD

**Issue by Venegrad** [leongersen/noUiSlider#1141]
How to use format (from, to) with range slider?
I have 2 caption for 2 fields, from and to, but in docs i see only one value, not array. How to set format for second hander?
```
 format: {
        to: (value) => {
          return value
          //return parseInt(value).toLocaleString("ru-RU") + " " + p_min;
        },
        from: () => {
          console.log(value)

          return value
          // return Number(value.replace(/\s/g, "").replace(p_min, ""));
        },
      },
```

**Comment by leongersen** [comment]
The `format` option applies to all handles. Note that your `from` method is missing it's argument.

**Comment by Venegrad** [comment]
ye, but how i can validate them? to set different caption for 2 handlers?

**Comment by Venegrad** [comment]
if i have an array, i can use value[0] value[1] and use it when validate, but in this case, i cant undestand, cuz i have only 2 string, can someone show me example?

**Comment by Venegrad** [comment]
if first hander (have caption "from") and second (have caption "to"). How i can use format?

**Comment by Venegrad** [comment]
up
