### ISSUE TITLE
noUISlider is not smooth in the touch devices (Android and iOS)

### ISSUE THREAD

**Issue by suhaz** [leongersen/noUiSlider#1142]
Hello,

I am using noUISlider with 2 handles. It works fine when you slide one handle on all platforms (web and mobile). But when I try to use both thumbs for the handles, sometimes the handles jump and it's not smooth.

Below is the link to my slider.

https://www.techcredence.com/slider.php

You can watch the video of the current behavior at the below URL:

https://www.techcredence.com/slider_smoothness.mp4

What could be done to fix it so that I can use both handles at the same time?

Btw, it's an amazing plugin.

Thank you.

Suhas

**Comment by leongersen** [comment]
I won't go digging through production code. Please refer to the [contributing guidelines](https://github.com/leongersen/noUiSlider/blob/master/CONTRIBUTING.md).
