### ISSUE TITLE
Use a template literal type for behaviour option

### ISSUE THREAD

**Issue by RikuVan** [leongersen/noUiSlider#1144]
The Typescript support could be improved a little I think for the behaviour by using a [template literal](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html) type. I am not sure there is a more terse way to do this but at least the Behaviour could be a union type like this:

`type Behaviour = 'tap' | 'drag'...`
 
and then in the interface it could be a union of the potential concatenations:

```
interface Options {
  ...
  behaviour:  Behaviour
        | `${Behaviour}-${Behaviour}`
        | `${Behaviour}-${Behaviour}-${Behaviour}`
        | `${Behaviour}-${Behaviour}-${Behaviour}-${Behaviour}`
        | `${Behaviour}-${Behaviour}-${Behaviour}-${Behaviour}-${Behaviour}`
        | `${Behaviour}-${Behaviour}-${Behaviour}-${Behaviour}-${Behaviour}-${Behaviour}`;
]
```

Admittedly this is kind of ugly and with a mapped type maybe (?) there is a way to do this more elegantly. But I think it would be pretty cool to get some type completion adding this option.

**Comment by leongersen** [comment]
Thanks for your feedback! Admittedly, the `behaviour` option being a string was a mistake (as was using the British spelling). I'm planning to replace it with an object basically matching what is now the (internal) `Behaviour` interface, but I haven gotten around to that yet. I addition to that, and to keep this change (initially) backward compatible, I think your suggestion would be very helpful. I don't think there are more than 3 behaviours to be combined at any one time.

**Comment by RikuVan** [comment]
There doesn't seem to be a script to run the tests with Qunit. What is your setup (or the easiest setup) for running them locally (eg from cli, in IDE...)?

**Comment by RikuVan** [comment]
@leongersen so is it correct there can be a variation of at most 3 of these: `type Behaviour = 'drag' | 'fixed' | 'snap' | 'hover' | 'unconstrained'`?

Would this suffice: 

```
type Behaviour = 'drag' | 'fixed' | 'snap' | 'hover' | 'unconstrained'

const a: BehaviourPermutation<'drag'> = 'drag';
const b: BehaviourPermutation<'drag-fixed'> = 'drag-fixed';
const c: BehaviourPermutation<'drag-fixed-snap'> = 'drag-fixed-snap';

const d: BehaviourPermutation<'drag-fixed-drag'> = 'drag-fixed-drag'; // Error
const e: BehaviourPermutation<'snap-hover-hover'> = 'snap-hover-hover'; // Error
const f: BehaviourPermutation<'unconstrained-unconstrained-unconstrained'> = 'unconstrained-unconstrained-unconstrained'; // Error

type BehaviourPermutation<T> =
    (T extends `${infer A}-${infer B}`
        ? (B extends `${infer BA}-${infer BB}`
            ? (
                `${A}-${Exclude<Behaviour, A>}-${Exclude<Exclude<Behaviour, BA>, A>}`
            )
            : (`${A}-${Exclude<Behaviour, A>}`)
        )
        : T
    );
```
[example](https://www.typescriptlang.org/play?#code/C4TwDgpgBAQhAWBDAbgSwPYFcBOUC8UA5ACbaIDmhUAPkQGaoAeExVthAzgHaJhtHx0yCNn6FMXAMbouHYGVRcWhALAAoddNnAoiAFywEKDDgAKIgLaZgiYBi4AeEmUoA+fEVIVCAbk0y5KAAjAzgkNCxsc2wrGzsZJy9yAFoGZlZ3AmcKVKZlPzUtQMlQowizS2tbe0SXXPTk7l5CTM86tJZGnj4C-20oYlLwkyjKuJrslI7iZKSWj0n6zrmfKAB6NagAUWxsdGw+wIgh40jo2OqEzm7kwWFsW6EReaymsEf7j+fVje3d-cOOjoJ3KoxiVXijnEUgC8kQik6EiKcIRMyRsIUSgyC3R2kxiJhePhWOSuLk+NYP02Oz2Bw0alAkEMwzOY0ujgAKpl1FBeVAABQcqAQRjACBcYgcKAAAwAJABvRR0ERQACCAF9kgqlSqYOrpTy+UaAPwCmDC0XiyUy7VcZW4GAarWKu26vUGtRGr18038w3egM2+VOhVbRiSAA2mGIEAcYVOOAANGrXJrQ+GozGHGHI9HY-HQcnHa5k6rUx7A0aAJT+ysGfly4Np+U5zP5sojUvlmuegM9wMGDm1qs+IA)

**Comment by RikuVan** [comment]
While the above works; I am doubtful it is the best solution since it requires the user to apply the type, via a generic. Also it seems from the issues that now all possible combinations are actually valid. Maybe it would be best to actually list (it a little onerous, all the valid combinations).

**Comment by RikuVan** [comment]
I am closing as I realized that this will be a problem for consumers with older typescript versions.
