### ISSUE TITLE
install noUiSlider without npm/yarn

### ISSUE THREAD

**Issue by tednaaa** [leongersen/noUiSlider#1148]
Hi

My friend trying to use this plugin, but he is a newbie and cannot build the `dist` folder on his own, I think many beginners have the same problem, what do you think of adding a way to install the `dist` folder besides the source code from the site? 

https: //refreshless.com/nouislider/download

**Comment by leongersen** [comment]
To make it easier to download release files, I've committed the `dist` folder to the repository, and added a note about that in the documentation. Thanks for your suggestion!

https://refreshless.com/nouislider/download/
