### ISSUE TITLE
ESM/ES6 module support

### ISSUE THREAD

**Issue by cdalexndr** [leongersen/noUiSlider#1149]
Please provide esm module distribution.

**Comment by leongersen** [comment]
Could you add some details on your use case?

**Comment by ivoevolution** [comment]
we need to
````
import noUiSlider from 'noUiSlider'

//...
````

**Comment by leongersen** [comment]
@ivoevolution You can currently do that:

```
// Either import the default:
import noUiSlider from 'nouislider';
// Or the namespace:
import * as noUiSlider from 'nouislider';
```

**Comment by cdalexndr** [comment]
> @ivoevolution You can currently do that:

Without any javascript bundler, directly in browser:
```
<script type="module">
    import noUiSlider from 'nouislider.js';
</script>
```
For this to work, the distributed javascript must have esm compliant `export` statements.
Other libraries build a separate `.esm.js` & min file, with this specificaiton.

**Comment by leongersen** [comment]
Ah, right. I'm open to a PR adding these distribution files.

**Comment by leongersen** [comment]
As of noUiSlider 15.4.0 the distribution offers `nouislider.mjs` and `nouislider.min.mjs`. You can see the [module import in action here](https://refreshless.com/nouislider/tests/module.html). Thank you for contributing!
