### ISSUE TITLE
Correlation between padding and step options

### ISSUE THREAD

**Issue by YuriKwon** [leongersen/noUiSlider#1150]
### Initial setting
```js
range: {
  min: 0,
  max: 100
},
padding: [20, 20],
start: [20],
step: 10
```
After creating the slider with the above setting, updating the step option to **7** results in the following error:

<img width="893" alt="스크린샷 2021-07-22 오후 3 31 53" src="https://user-images.githubusercontent.com/55318618/126602394-3f0b7371-7325-4f21-ab02-b58af380a245.png">

I don't quite understand this error message. Does the padding value have to be a multiple of steps? If so, please explain why it should be.

**Comment by leongersen** [comment]
> Does the padding value have to be a multiple of steps?

Yes, that is the case. This prevents ambiguity in the options (with a step of 7 and a padding of 20, the padding ends up at either 14 or 21, effectively).
