### ISSUE TITLE
Handle flying away

### ISSUE THREAD

**Issue by wnabil** [leongersen/noUiSlider#1152]
I noticed an issue with the translate value that its multiplied by 10 for some reason and when removing the multiplication it works fine, any idea what is this multiplication for ?
![image](https://user-images.githubusercontent.com/23165327/128642885-f464a25a-f25a-4ca8-b964-e86f7d2e605d.png)

https://github.com/leongersen/noUiSlider/blob/0d3fc23e322d1902c8834cbe9179f9aeaee3b771/src/nouislider.ts#L2567

**Comment by leongersen** [comment]
Did you update from a previous version of noUiSlider? This scaling was introduced (809eb82) in 14.0.0 and fixes #987. If you are using a custom stylesheet you'll need to incorporate this change there as well.

**Comment by leongersen** [comment]
In that case I don't really have enough information in your original question to help you debug this. Could you add a code sample to show the issue?

**Comment by wnabil** [comment]
@leongersen the problem is from the creativetim now ui angular pro kit
https://github.com/creativetimofficial/ct-now-ui-kit-pro-angular
no matter what I do to fix it via the CSS it doesn't work until I remove the 10 multiplication from the library
and sadly cant share it because I'm using a paid plugin
