### ISSUE TITLE
Relative date for noUiSlider

### ISSUE THREAD

**Issue by mmarienko** [leongersen/noUiSlider#1153]
Hello, i faced the issue of implementing a relative date in noUiSlider. I didn't find any suitable examples on the site or anywhere else and started solving the problem myself.

Solution: https://gist.github.com/mmarienko/07de50a6811c4f35c665cbc47a689c44
Demo: https://jsfiddle.net/mmarienko/kvj6h3pw/12/

I will be glad if you add this solution to the site in the tab "Examples".

PS: works with all languages of the world, just replace value in Intl.RelativeTimeFormat('en').

**Comment by leongersen** [comment]
I've update the [dates example](https://refreshless.com/nouislider/examples/#section-dates).
