### ISSUE TITLE
Round number to the nearest multiple

### ISSUE THREAD

**Issue by Meth0d-S** [leongersen/noUiSlider#1156]
I use noUiSlider with the 'step' parameter. Each step is equal to 100,000, 'range' = 1,000,000. When I enter a number in' stepSliderValueElement ' that is not a multiple of 100,000, it rounds the number to the nearest multiple. Is it possible to select a number that is not a multiple of 'step' with the 'step' parameter?

**Comment by leongersen** [comment]
Glad you worked it out 👍
