### ISSUE TITLE
Unable to disable slider by setAttribute

### ISSUE THREAD

**Issue by Alex-Popov** [leongersen/noUiSlider#1158]
I used noUIslider inside LWC component of Salesforce. It doesn't support disable attribute for DIV tag, because it's not a native attribute for div. As a result I'm unable to disable slider.

Need an option or method directly on slider object to disable it

**Comment by leongersen** [comment]
An API to set the slider or handles disabled seems like a good idea. I'm open to API design suggestions and/or a PR.

**Comment by mgibbs189** [comment]
PR #1224 added to address this.
