### ISSUE TITLE
Some styling questions

### ISSUE THREAD

**Issue by zetashift** [leongersen/noUiSlider#1162]
Hiya! You made an awesome library!

I was wondering if it's possible to override the handles styling, so that it's just a simple image(an .svg in my case), I'm not sure how to achieve this tho, do you have any tips?

And I was wondering how to bolden the text of a pip when the handle is set on that value, is this possible?

**Comment by leongersen** [comment]
For the handle image, it is probably easiest to set a `background-image` to `.noUi-handle`.

As for the pips: the behavior you describe isn't built-in, but you can do this with an `update` event, something along these lines:

```
slider.noUiSlider.on('update', function(values, handle) {
    this.target.querySelector('.noUi-value[data-value="' + values[handle] + '"]'); // add a class or set a style
});
```

**Comment by zetashift** [comment]
Ah thank you!
