### ISSUE TITLE
Slider works nice

### ISSUE THREAD

**Issue by ldijkman** [leongersen/noUiSlider#1170]
Hello

took some time for me but figured out most things
far from finished
playing with it
my nouislider in action
        
https://jsfiddle.net/luberth/ow3zceyn/show/     

should become timeline timesetting for wifi relais
https://github.com/ldijkman/ART-ESP32-Touch-TFT-Thermostat/blob/main/test/art_test_1/Remote_WiFi_Sense_Switch/readme.md

![2021-11-02-175711_1360x768_scrot](https://user-images.githubusercontent.com/45427770/140024246-96a0fe6d-1584-41b2-8404-93d0d4336743.png)

**Comment by leongersen** [comment]
Thanks for showing me what you're working on, I'm glad you are finding noUiSlider useful! 😄
