### ISSUE TITLE
Exception on undefined callback

### ISSUE THREAD

**Issue by AAverin** [leongersen/noUiSlider#1175]
Somehow this line fails with `Cannot read property 'call' of undefined`
https://github.com/leongersen/noUiSlider/blob/5344a23d4b46eba6c3bafa43e49a326a611bd620/src/nouislider.ts#L2423

Can `Scoped_events` in any case get an `undefined` value inside? I am rebinding events with `on` and `off` a lot due to state changes in react.

Unfortunately, no code to reproduce the problem exactly. Problem seems to happen mostly with `set` event.

**Comment by leongersen** [comment]
I haven't run into this before, I'll see if I can reproduce this.
