### ISSUE TITLE
Custom Formula With double slider 

### ISSUE THREAD

**Issue by Hamzahsm** [leongersen/noUiSlider#1178]
is there a way to do custom arithmetic on the "type : double" slider? I want to subtract the value in each circle and then multiply it by a certain number.

my page is here : https://mmovigi.com/nouislider-3/ or you can also click here

**Comment by leongersen** [comment]
Sure, all events have the numbers for the handles:

```JavaScript
slider.noUiSlider.on('update', function(values, handle) {
	if (handle === 0) {
		// do something with values[handle]
	}
	if (handle === 1) {
		// do something else with values[handle]
	}
});
```

**Comment by Hamzahsm** [comment]
Hi, Thanks for your answer Leon! 

i've been implemented on my site but it still didn't work. 

I want the slider to be like this : https://boosting-ground.com/new-world/boosting/level-up 

my code is goes like this. 

![code goes like this](https://user-images.githubusercontent.com/70360637/145976731-61c16c08-78a6-427e-b01a-10ea090b3ca3.png)


your help will really help me in solving this problem

**Comment by leongersen** [comment]
Sorry, I can't help you in debugging your production code. Have a look at the [contribution guidelines](https://github.com/leongersen/noUiSlider/blob/master/CONTRIBUTING.md).
