### ISSUE TITLE
Pips container (noUi-pips) DOM placement

### ISSUE THREAD

**Issue by dave0783** [leongersen/noUiSlider#1179]
I have a situation that has arisen where the pips need to be positioned atop of the slider.  Adjusting the positioning to place them atop the slider works as expected; however if you are using the connect option, you cannot get the positioning atop the connect container `noUi-connect`.  Upon inspecting the DOM generated, I have come to the conclusion that this is happening because the container `noUi-pips` is rendered outside of `noUi-base` making the necessary `z-index` changes impossible.  Is there a way to place the `noUi-pips` container inside of `noUi-base`

**Comment by leongersen** [comment]
I don't see issues in moving the `.noUi-pips` element to `.noUi-base` (using, for example, [`appendChild`](https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild). I think this'd be too niche to create an option for this in the library.

**Comment by dave0783** [comment]
Are you suggesting I programmatically move `.noUi-pips` inside of `.noUi-base`? To be clear, I'm suggesting the default markup be changed so that `.noUi-pips` is rendered inside of `.noUi-base`

**Comment by leongersen** [comment]
> Are you suggesting I programmatically move .noUi-pips inside of .noUi-base?

Yep. I don't want to make this the default, though.

**Comment by dave0783** [comment]
It seems rather inefficient to programmatically change this when there is seemingly no reason to not make this to default; I would think the positioning I’m talking about would be a common scenario. If there is a reason you wouldn’t want to make it the default, I would suspect there must be a reason why programmatically moving it would be an issue.

~Dave

**Comment by leongersen** [comment]
> I would suspect there must be a reason why programmatically moving it would be an issue.

I don't think there is one. I'd rather not make this breaking change for implementations depending on the current structure.
