### ISSUE TITLE
Help: Cannot add noUiSlider to Svelte component

### ISSUE THREAD

**Issue by SkepticMystic** [leongersen/noUiSlider#1180]
Hi there!

I'm trying to get your awesome tool working in a Svelte component.
This is my current set up:

```html
<script lang='ts>
let slider: HTMLElement;

onMount(() => {
    noUiSlider.create(slider, {
        start: [20, 80],
	connect: true,
	range: {
	       min: 0,
	       max: 100,
	},
    });
});
</script>

<div class='slider' bind:this={slider} />
```

I'm not sure how familiar you are with Svelte, but a couple of things are happening here:
1. Bind the `div` element to the js variable `slider`
2. This only happens after the component is mounted, so that's why I create the noUiSlider inside `onMount`
3. It seems to insert the html elements into the right place of the dom:
![image](https://user-images.githubusercontent.com/70717676/148213504-66a2967a-29b9-4a27-9fa4-e54fc81da927.png)

But no slider is actually visible on the page.
Can you please advise if I'm doing something wrong here

**Comment by leongersen** [comment]
Your setup looks good. Did you include/load the stylesheet?

**Comment by SkepticMystic** [comment]
@leongersen stylesheet? What stylesheet! Lol, that's probably it. Can you point me to where and how I can do that?

**Comment by leongersen** [comment]
I don't know your build system, but if you are using a bundler like Webpack, you are likely doing something like:

```
import * as noUiSlider from 'nouislider';
```

You'd add:
```
import 'nouislider/dist/nouislider.css';
```

**Comment by SkepticMystic** [comment]
Simply import it? Will it get applied by itself? I guess it's just css, so yeah

**Comment by SkepticMystic** [comment]
Importing it inside the script tag didn't do it.
Using `svelte:head` makes it appear in the element inspector, but the styles still aren't being applied:
```html
<svelte:head>
	<link rel="stylesheet" href="nouislider/dist/nouislider.css" />
</svelte:head>
```

**Comment by SkepticMystic** [comment]
@leongersen I ended up just copy pasting the css into my app's stylesheet, and now it works 😅
