### ISSUE TITLE
Is there anyway to tell the direction of the drag event?

### ISSUE THREAD

**Issue by charlymz** [leongersen/noUiSlider#1182]
Hi i want to be able to tell when dragging left or right, i am connecting 2 sliders, one is a timeframe and the second a zoom, it can go down into 2 month views and then drag the range but need to keep going when reaching the limit of the 2 month slider and update the range for the new dates

**Comment by leongersen** [comment]
The direction is not available as a value in the event. You can capture/store the current value on every `slide` event, then compare the new value to determine the direction.
