### ISSUE TITLE
Is there a way to return the new slider value on mouseover?

### ISSUE THREAD

**Issue by bitowaqr** [leongersen/noUiSlider#1187]
I'd like to programmatically create a new handle when the cursor is moved over the slider, as if it was clicked at that position. Is there a way to get the position of the new handle position?

**Comment by leongersen** [comment]
Yes, you can enable the [`hover` behaviour](https://refreshless.com/nouislider/behaviour-option/#section-hover).

**Comment by bitowaqr** [comment]
Ah, so easy! Can this work with 'dragover' as well?

**Comment by leongersen** [comment]
I'm not sure what you mean, could you elaborate?

**Comment by bitowaqr** [comment]
Sorry, what I would like to do is to put a handle-like element somewhere on the page and the user should then be able to drag the handle-element on to the slider. My idea was to remove the handle-like element once the cursor reaches the slider and create a proper handle on the slider at the cursor position – I hope this makes sense?

I guess the problem is, the cursor is dragging an element, so it doesn't trigger the hover event. Is there an easy fix for this?

**Comment by bitowaqr** [comment]
Never mind, I figured something out myself, and it's probably not a functionality many people would want to use.

https://github.com/bitowaqr/dragon-noUiSlider

Thanks anyway.

**Comment by leongersen** [comment]
That's pretty cool, thanks for sharing the demo!
