### ISSUE TITLE
label for range and calculate between marks 

### ISSUE THREAD

**Issue by devopg** [leongersen/noUiSlider#1188]
how i can show 1 label beetween marks  ? and calculate value  beetween marks? 
![image](https://user-images.githubusercontent.com/61819835/161854194-db4dc9df-301f-45df-868d-efae730f9f89.png)

I read the documentation, I didn't find how to do it. noUiSlider can do this?

**Comment by leongersen** [comment]
You can add a tooltip element to `.noUi-base`, and `translate` it to the right (or set `left`) on the `update` event. This isn't a build in feature, but shouldn't be doable this way.
