### ISSUE TITLE
Issue format

### ISSUE THREAD

**Issue by SylvainBailly** [leongersen/noUiSlider#1189]
Hi,
I got some issue with the number i pass to the slider.
I use it with 2 associated inputs : 
![image](https://user-images.githubusercontent.com/50401053/162222601-fd207396-47f1-44b6-951a-db3c9c9577b8.png)

Some numbers (like 78) are unreacheable end always rounded to former value (77 for 78).
So if i write 78 in my left input the slider go to 77 as min.

Any idea why ? 
![image](https://user-images.githubusercontent.com/50401053/162222306-d7f29c5b-9416-4147-8b16-a427e444576c.png)

**Comment by leongersen** [comment]
Why are you passing `true`, `true` as additional arguments to `set` here?

**Comment by leongersen** [comment]
The slider isn't storing its positions as integers. You are taking the output, and instead of rounding, you truncate (so 77.99999999 to 77 instead of 87). You need to set your `to` formatter to a function that does the rounding you want, so say `to: (value) => Math.round(value)`.

**Comment by SylvainBailly** [comment]
I feel myself dumb.. it work perfectly thanks :)
