### ISSUE TITLE
Question: is it possible to setup an arbitrary range with arbitrary steps/snaps?

### ISSUE THREAD

**Issue by stratboy** [leongersen/noUiSlider#1192]
Hi, thank you for your code.
What I mean is: say I've got non-linear values, like:

100, 150, 300, 475, 500, 630.

Say I want to build a slider which has the above steps, snapped. Is it possible?

Thank you, regards

**Comment by leongersen** [comment]
Yes, you can set the [`snap` option](https://refreshless.com/nouislider/slider-values/#section-snap).
