### ISSUE TITLE
Woo-commerce / Extra Product Options

### ISSUE THREAD

**Issue by smooth1884** [leongersen/noUiSlider#1193]
Has anyone experienced how to integrate this range slider into WordPress? I saw someone else doing so but not sure how they did it...  As you can see here: [Link](https://leprestore.com/wow-us/boost/buy-rbg-rating-carry-service/)

**Comment by smooth1884** [comment]
Then.. where can I ask it?

**Comment by leongersen** [comment]
Try [StackOverflow](https://stackoverflow.com/questions/tagged/nouislider). You'll be expected to provide a code sample showing what you've tried so far.

**Comment by smooth1884** [comment]
Ok, thanks... tbh I have no idea where to start as I've never done smth like that before with wp. Will look for some leads first to learn about it and then I guess go to  StackOverflow if I cannot figure it out myself at some point. I just thought maybe you've got some ideas :) Thanks and sorry for disturbing you  🙏
