### ISSUE TITLE
Question: onchange, is it possible to check the previous values?

### ISSUE THREAD

**Issue by stratboy** [leongersen/noUiSlider#1194]
Hi, for an app I would need to know, onchange, if the user has broadened or restricted the range, so I need to know if passed values are larger or smaller than the previous ones. Is it some way possible?

Thank you

**Comment by leongersen** [comment]
Yeah, you can keep track of the previous values and compare:

```JavaScript
noUiSlider.create(slider, { ... });

// Initial values
var previousValues = slider.noUiSlider.get();

slider.noUiSlider.on('change', function(values, handle) {
    // compare "values" and "previousValues"

    previousValues = values;
});
```
