### ISSUE TITLE
Documentation server documentation incomplete

### ISSUE THREAD

**Issue by xeruf** [leongersen/noUiSlider#1198]
https://github.com/leongersen/noUiSlider/blob/master/documentation/README.md
Running `npm run docs` did not work for me right away.
First, I had to install php, and then it required root permissions to be able to listen on any port below `1024`.

**Comment by xeruf** [comment]
ah, 8080 is already quite overused, fossil webui and some other things use it, maybe you can choose something a little different as default, for example 8040?

**Comment by leongersen** [comment]
You can now set a port: 

```
PORT=8086 npm run docs
```
