### ISSUE TITLE
Evenly spaced range of discrete values

### ISSUE THREAD

**Issue by xeruf** [leongersen/noUiSlider#1199]
Hey, I would like to have a slider with a list of evenly-spaced values. Is there a way to implement that easily now without having to calculate percentages for each?

My feature suggestion here would be to have `range` also accept an array, which would then be evenly spaced automatically.

**Comment by xeruf** [comment]
Wow, thank you!
There is one thing I forgot to mention: What if the values are not numbers but could also be strings - would I have to do a mapping via from-to? This was what I meant with discrete values, actually.

**Comment by leongersen** [comment]
Yes, you'd need to set up `format` to translate between a numeric range and the string values (if they are not numeric).

**Comment by leongersen** [comment]
There is now an example on [using an array of values](https://refreshless.com/nouislider/examples/#section-values) in the documentation.
