### ISSUE TITLE
Double-sided tooltip

### ISSUE THREAD

**Issue by xeruf** [leongersen/noUiSlider#1200]
Hey, I would like a very minimal slider that essentially shows tooltips on two sides rather than pips.
Can this be sensibly implemented by offsetting the existing tooltip, or do you have a suggestion what to do here?

![4f391940-50e4-4913-9fbe-12524a25749a](https://user-images.githubusercontent.com/13354331/168063132-f0185f3f-37f5-49a1-9ba7-434e8d1040f6.jpg)

**Comment by leongersen** [comment]
It's probably easiest to add a html element to the slider handle, and set its values in the `update` event. That's how the build-in tooltips work, too.
