### ISSUE TITLE
format with intergers skips a step

### ISSUE THREAD

**Issue by frenchcdsl44** [leongersen/noUiSlider#1201]
Hi

On this fiddle https://jsfiddle.net/s59j0rof/

I set  `  start: [0, 20, 150],`
but i get [0, 19, 149]

I think it has to do with the format because without the problem does not show

`  format: {
    from: function(value) {
      return parseInt(value);
    },
    to: function(value) {
      return parseInt(value);
    }
  },
`

How do I use integers as input and output?

Thanks for you nice work anyway.

**Comment by leongersen** [comment]
With `parseInt` you are dropping the decimals when formatting. Use `Number()` in `from` instead.

**Comment by frenchcdsl44** [comment]
Hi

Thanks for the quick reply. I had to add  Math.rounding in the `to`. I updated the jsfiddle : 
https://jsfiddle.net/sw4k0egj/1/

with
```
 format: {
    from: function(value) {
      return Number(value);
    },
    to: function(value) {
      return Math.round(Number(value));
    }
  },
```

And it works fine.
Thank you for pointing me in the decimal issue.
