### ISSUE TITLE
getting values from a map

### ISSUE THREAD

**Issue by frenchcdsl44** [leongersen/noUiSlider#1202]
Hi again

Here is a jsfiddle for anyone interested in mapping their values in an object property like this

```
let myMap = new Map([
  [0, {
    a: 10,
    b: "a"
  }],
  [1, {
    a: 30,
    b: "b"
  }],
  [2, {
    a: 50,
    b: "c"
  }],
  [3, {
    a: 70,
    b: "d"
  }]
]);
```
and getting the b property as a result :

https://jsfiddle.net/7fsr5v1e/5/

The only little issue is update event  is called only after formatting so I have to reset() the slider in the change event.
But it is not an issue for what I have to do.

Thanks. noUiSlider is really powerful!!!

**Comment by leongersen** [comment]
Thanks for your input here! I'm glad you are finding noUiSlider useful 😊
