### ISSUE TITLE
Slider not showing up

### ISSUE THREAD

**Issue by dmitrue** [leongersen/noUiSlider#1204]
Hi there,

I'm trying to use noUiSlider in Rails app via Stimulus controller. I have the following import statements 
`import noUiSlider from 'nouislider'`
and
`import wNumb from 'wnumb'`
and the initialization code: `this.slider = noUiSlider.create(this.sliderTarget, {
      range: {
        min: 0,
        max: 10
      },
      start: [0, 8],
      step: 1
    })`
After initialization I have a div with generated classes 'noUi-target noUi-ltr noUi-horizontal noUi-txt-dir-ltr'. However the slider isn't showing up. There are no errors in the console as well.

**Comment by leongersen** [comment]
You'll need to include/import the css as well.

**Comment by dmitrue** [comment]
Got it, thanks 👍🏻
