### ISSUE TITLE
Indication if slider was changed

### ISSUE THREAD

**Issue by skyynet** [leongersen/noUiSlider#1205]
I have a slider with min and max handle.
Let's say it shows a weight range from 10 to 100.
When querying from database, the query is from 10 to 100.

I would like to have the slider show '-' instead of 10 and '+' instead of 100 and only change to the possible numbers, when the according handle is moved. This way, I could differ between preset min and max values (which I would ignore) and user selected ones.

Is this already possible or a new feature?

**Comment by leongersen** [comment]
You could keep a variable, say `hasSliderChanged`, and set it to `true` on the first `change` event. You can then have your `update` event check that variable to handle your display logic.
