### ISSUE TITLE
draw a red line for current time on slider?  no issue

### ISSUE THREAD

**Issue by ldijkman** [leongersen/noUiSlider#1206]
Hello

my question fits better in Discussions tab (but it is not activated on this repo?)

anyone maybe has an idea how to draw a red line marker on slider for current time
or a link to an example

greet luberth
https://ldijkman.github.io/Electra/schedule.html
https://github.com/ldijkman/randomnerd_esp32_wifi_manager/tree/main/LAB_Experiments#timed-switching

![2022-06-26-080745_1920x1080_scrot](https://user-images.githubusercontent.com/45427770/175801917-f7d3d670-5c4f-4163-b91c-d9ddabb24b6e.png)

**Comment by ldijkman** [comment]
this draws a vertical red line at 50% 
wich is 12 o clock
but it messes up the slider

    <style>
        .noUi-base{
            border-left: 2px solid red;
            height: 20px;
            position:absolute;
            left: 50%;
        }
    </style>

![2022-06-26-175914_1920x1080_scrot](https://user-images.githubusercontent.com/45427770/175823000-1fa4851d-8384-464d-a002-d3af903d63a7.png)

**Comment by ldijkman** [comment]
still trying
created a div from script at 50% on 1st slider

https://ldijkman.github.io/Electra/schedule.html

![2022-06-27-194929_1920x1080_scrot](https://user-images.githubusercontent.com/45427770/176004310-19eb5bfe-0875-4b34-b127-ba170e76b6be.png)

**Comment by leongersen** [comment]
Hi Luberth,

I think the easiest way to achieve this is to fit the slider in a `div` with `position: relative`, then use another `div` (`position: absolute; left: 50%`) for the line.

**Comment by ldijkman** [comment]
to my surprise i got it a bit working

javascript adds a div class actualtime to nouibase
left position percentage is based on actual time

https://ldijkman.github.io/Electra/schedule.html

![2022-06-28-060607_1920x1080_scrot](https://user-images.githubusercontent.com/45427770/176089865-f562917d-6ddd-4f90-8726-384da7522614.png)

**Comment by leongersen** [comment]
Okay, glad you worked it out! 👍

**Comment by ldijkman** [comment]
monday
slider if actualtime in range "light on"
change color to yellow else green

https://ldijkman.github.io/Electra/schedule.html
![2022-06-30-214717_1920x1080_scrot](https://user-images.githubusercontent.com/45427770/176764751-f57f0673-9067-4a89-a8be-2ee11d0087cd.png)

**Comment by ldijkman** [comment]
and a sunrise marker

https://ldijkman.github.io/Electra/schedule.html

![2022-07-03-113906_1920x1080_scrot](https://user-images.githubusercontent.com/45427770/177034030-5161df72-5d8a-4ea7-8717-8240a2208451.png)
