### ISSUE TITLE
Adjust height?

### ISSUE THREAD

**Issue by peterlondon1** [leongersen/noUiSlider#1207]
Sorry for this very basic question: how can I adjust the height of a horizontal noUiSlider? Thanks.

**Comment by peterlondon1** [comment]
sorry, solved:

</script>
<style>
	.noUi-horizontal {
	  height: 6px;
	}
</style>

**Comment by leongersen** [comment]
Glad you worked it out 👍

**Comment by peterlondon1** [comment]
Thanks, and great to know you are keeping an eye on this excellent package!
