### ISSUE TITLE
BEst way to detect if a handle was clicked without moving

### ISSUE THREAD

**Issue by frumbert** [leongersen/noUiSlider#1209]
I want to handle an action when clicking (pressing and releasing) a _handle_ that hasn't changed position.

But not when a handle is pressed then moved then released, or if a handle was moved using keyboard or set using script.

Seems like I have to do something like

```
        noUISider.create(node, { 
           behaviour: 'unconstrained-smooth-steps-hover'
           range: { 'min': 0, 'max': 100},
           start: [10]
        });
        noUi.noUiSlider.on('set', set);
        noUi.noUiSlider.on('start', start);

        let lastvalue = [];

        function start(a,b,c,d,e,inst) {
            lastvalue = inst.get(); // might be array or single value
        }

        function set(a,b,c,d,e,inst) {
            let value = inst.get();
            if (JSON.stringify(value) === JSON.stringify(lastvalue)) {
                handleClick(inst);
            }
        }
```

which works but feels janky. Is there a better way to handle this?

**Comment by leongersen** [comment]
That's how I would do it. Note that where you are using `lastvalue = inst.get();`, the slider values are available in `b[a]`.
