### ISSUE TITLE
Steps question

### ISSUE THREAD

**Issue by HerrSammyDE** [leongersen/noUiSlider#1213]
Hi Léon!

Do you know a solution how I can fix this gap?
![mm4c2HZDFT](https://user-images.githubusercontent.com/38103916/179430725-63f30dd1-169b-4642-82dc-712bc2d41f7b.png)

```
noUiSlider.create(pipsSlider, {
    range: {
        'min': [1,1],
        '40%': [7,1],
        '60%': [8,2],
        '80%': [16,4],
        'max': [32]
    },
    start: 0,
    connect: 'lower',
    tooltips: true,
    pips: {
        mode: 'values',
        values: [1,2,3,4,5,6,6,7,8,10,12,14,16,20,24,28,32],
        density: 4,
        stepped: true
    }
});
```

--------------------

With another slider it works with the values and the steps without problems - what am I doing wrong with your range slider?
![Uz8YrREOQJ](https://user-images.githubusercontent.com/38103916/179430809-3a4b36db-1a1d-4af9-aaa5-c833baafc078.png)

```
$(".js-range-slider").ionRangeSlider({
    grid: true,
    grid_num: 10,
    values: [1,2,3,4,5,6,6,7,8,10,12,14,16,20,24,28,32],
    from: 10,
    postfix: " GB",
});
```

**Comment by leongersen** [comment]
Hi! The issue is in your `range`. You've set `7` to be at `40%`, and `8` to be at `60%`. That spacing is wider than the other values in your range.

**Comment by HerrSammyDE** [comment]
> Hi! The issue is in your `range`. You've set `7` to be at `40%`, and `8` to be at `60%`. That spacing is wider than the other values in your range.

Means I have to set 41%?
Is there also a way to do it without the range, like in my 2nd example? (ionRangeSlider) That would be a lot easier.

**Comment by leongersen** [comment]
> Means I have to set 41%?
 
 No, you have to set the 40/60/80 percentages closer together. The `pips` values are reflecting what you've set your `range` to. The 7 is shown at 40% of the slider width, the 8 at 60% of the slider width. Since you want 16 "locations" on your slider (1,2,3,4,5,6,7,8,10,12,14,16,20,24,28,32), divide 100 by 16 to determine where you want the breaks.

> Is there also a way to do it without the range

Yes, if you don't want to configure the increasing step values, you can set a linear range of `{min: 1, max: 32}`.

**Comment by HerrSammyDE** [comment]
Now I have made `{min: 1, max: 32}`, but now all steps like e.g. 13, 15 or also 31 are displayed, whereas I only want to have the numbers that come from the value.
![IMG_20220718_092602.jpg](https://user-images.githubusercontent.com/38103916/179462905-8b609fb7-b623-495f-bfb5-539d6a4bbc25.jpg)

**Comment by leongersen** [comment]
Here's how you'd do it with the steps configured:

```JavaScript
noUiSlider.create(pipsSlider, {
    range: {
        'min': [1,1],
        '46.67%': [8,2],
        '73.33%': [16,4],
        'max': [32]
    },
    start: 0,
    connect: 'lower',
    tooltips: true,
    pips: {
        mode: 'values',
        values: [1,2,3,4,5,6,7,8,10,12,14,16,20,24,28,32],
        density: 6,
        stepped: true
    }
});
```

**Comment by HerrSammyDE** [comment]
What if I had the values in a database, then I would have to calculate the percentages in addition or?

**Comment by leongersen** [comment]
Yep, if you are generating the range, you'll need to generate the percentages. 

If you'd lead with that I'd probably have pitched a different approach (use a linear slider and map the output, see [roughly this example](https://refreshless.com/nouislider/examples/#section-huge-numbers)).

**Comment by HerrSammyDE** [comment]
Alright 👍
Thanks Léon!

**Comment by leongersen** [comment]
I've updated the documentation with a more straightforward approach to doing this. Thanks for reaching out!

https://refreshless.com/nouislider/examples/#section-values
