### ISSUE TITLE
Slider Input Not Full Component Width (Regression in 15.5)

### ISSUE THREAD

**Issue by kdagnan** [leongersen/noUiSlider#1214]
Not sure how to word this (videos below), but essentially our slider input can only be dragged in a small portion of the displayed slider. The range/steps are the same as expected, but for some reason don't take up the full width of the component.

Works as intended in 15.4:
https://user-images.githubusercontent.com/44090970/181095668-7da03df5-5ae0-4fb1-9020-bad55512e8a0.mov

Behavior seen in 15.5 or greater:
https://user-images.githubusercontent.com/44090970/181095679-aeb37932-39a1-452b-ad50-275297268672.mov

Any ideas what could have changed this behavior and/or what I can do to fix it? 

Didn't provide any implementation details because we're quite literally just passing standard options (min, max, step, start, etc) to noUiSlider.create. Other components are just aligned properly to make it look fancy on top. We copy/pasted the default styles at some point (and are overriding separately as necessary), but it doesn't look like those have changed.

**Comment by kdagnan** [comment]
Update: Actually it was the minor css changes - 
![Screen Shot 2022-07-26 at 2 57 56 PM](https://user-images.githubusercontent.com/44090970/181101222-31a5333a-a8c9-418a-a960-1169d87a8a89.png)

Release notes should point out stuff like that, I had to manually compare the branches & try the changes.

**Comment by leongersen** [comment]
Yeah, this is unfortunate; I'm sorry you ran into this issue. #1167 is open with some more discussion on this. I'll update the release notes to make this clearer.
