### ISSUE TITLE
Features?

### ISSUE THREAD

**Issue by ChicagoDave** [leongersen/noUiSlider#1215]
I apologize if this is the wrong place to ask these questions...

Two things.

1. Can we make the labels vertical on a horizontal slider? I have a rather large set of values (poker tournament blinds structure) to display and it will never look right if all the labels are overwriting each other).
2. Is there a way to make a solid bar between two selectors and allow the user to move both at the same time by holding that "bar"? So if they have 100 and 500 selected, it could be moved to 200 and 600, 500 and 1000, etc.

**Comment by leongersen** [comment]
Hi!

For 1, you can style the labels using [`text-orientation`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-orientation).

For 2, you can use the [`drag`](https://refreshless.com/nouislider/behaviour-option/#section-drag) behavior.

**Comment by ChicagoDave** [comment]
Apologies again. I'm not really a web dev (I was a long time ago).

The drag solution is perfect. Thanks!

But text-orientation is opaque to me. Would I be overriding these styles or ___?

`/* Values;
 *
 */
.noUi-value {
  position: absolute;
  white-space: nowrap;
  text-align: center;
}
.noUi-value-sub {
  color: #ccc;
  font-size: 10px;
  text-orientation: sideways;
}`

**Comment by leongersen** [comment]
Sorry, I did this off the top of my head on mobile, and we're looking for `writing-mode`, not `text-orientation`.

Adding this CSS will get you this:

```CSS
.noUi-value-horizontal {
    -webkit-transform: translate(-50%, 25px);
    transform: translate(-50%, 25px);
    writing-mode: vertical-lr;
}
```

(the transform of `-50%` centers the value on the pip, the `25px` offsets it) 

![image](https://user-images.githubusercontent.com/1206361/182013289-bd3028d7-c472-416b-af22-522009dba1bb.png)

As for:

> And how can I make (numeric or non-numeric) labels uniform size?

You can use [a filter](https://refreshless.com/nouislider/pips/#section-steps).

**Comment by leongersen** [comment]
I've added this (and #1216) as an example to the documentation:

[Interacting with pips](https://refreshless.com/nouislider/examples/#section-pips).
