### ISSUE TITLE
Pip feature

### ISSUE THREAD

**Issue by HerrSammyDE** [leongersen/noUiSlider#1216]
Hey,

is it possible to set some kind of `active` class on a pip that has just been selected?

Here is an example:
![chrome_zeOCQQnzFO](https://user-images.githubusercontent.com/38103916/181923802-b2e3ba3a-c6e4-4469-8368-6e46b9ba3e93.png)

**Comment by leongersen** [comment]
Hi! 

Not as a build in feature, but you can do this using the event system.

You can do something like this (I'm on mobile so the example isn't complete):
```JavaScript
slider.noUiSlider.on('update', function(values, handle) {
    // (remove active class from current active handle)
    // (format value, handle querySelector)
    document.querySelector('.noUi-value[data-value="'+ values[handle] +'"]).classList.add('active');
});
```

**Comment by HerrSammyDE** [comment]
Thanks!
Would you perhaps have a direct example where this works?
