### ISSUE TITLE
Chrome Lighthouse - Accessibility: ARIA input fields do not have accessible names

### ISSUE THREAD

**Issue by USMortality** [leongersen/noUiSlider#1223]
Getting this error message when running the lighthouse report within google chrome.

Seems to me that a fix would be fairly easy, e.g.: 

[Option 1: Add inner text to the element](https://web.dev/aria-name/?utm_source=lighthouse&utm_medium=devtools#option-1-add-inner-text-to-the-element)
[Option 2: Add an aria-label attribute to the element](https://web.dev/aria-name/?utm_source=lighthouse&utm_medium=devtools#option-2-add-an-aria-label-attribute-to-the-element)
[Option 3: Refer to another element using aria-labelledby](https://web.dev/aria-name/?utm_source=lighthouse&utm_medium=devtools#option-3-refer-to-another-element-using-aria-labelledby)

<img width="653" alt="Screen Shot 2022-08-27 at 12 57 35 PM" src="https://user-images.githubusercontent.com/94856880/187042364-a9585ed0-9d54-492c-b184-8fb85c2ebafc.png">

**Comment by leongersen** [comment]
What option would work for your use case?

We could add an option to provide labels for handles.

For reference: https://www.w3.org/WAI/ARIA/apg/patterns/slider/#wai-aria-roles-states-and-properties-17

**Comment by USMortality** [comment]
I think it could be as easy as just adding `aria-label="Slider">`? (Option 2)

**Comment by bvauchelle** [comment]
Would the [handleAttributes option](https://refreshless.com/nouislider/slider-options/#section-handle-attributes) already fit your need by allowing to set an aria-label (or aria-labelledby) of your choice?

**Comment by leongersen** [comment]
@bvauchelle Yes, that is the correct solution here.
