### ISSUE TITLE
Disable tabindex when slider is disabled

### ISSUE THREAD

**Issue by mitar** [leongersen/noUiSlider#1227]
When I call `slider.setAttribute('disabled', true)`, I can still focus handles (but I cannot move them, as expected). Ideally, they would not be focusable anymore. Sadly, `keyboardSupport` is not among options which I could update to do this manually, either, when disabling the slider.

**Comment by leongersen** [comment]
In 15.7.0, there are now API methods to enable/disable a slider. This also takes care of the tabindex on handles. 

Thanks for contributing!
