### ISSUE TITLE
How to use text instead of numbers in pips

### ISSUE THREAD

**Issue by lucaiacono** [leongersen/noUiSlider#1230]
Hi, 
I would like to be able to use text in pips. Is there a way to do this, as I haven't found one. 
For instance, one could have a step slider with { fair, good, very good, excellent, ideal}.

If text is not available, I would like to make a request. 
Regards
L

**Comment by leongersen** [comment]
You can use a formatter to do this:

https://refreshless.com/nouislider/number-formatting/

**Comment by lucaiacono** [comment]
great thank you!
