### ISSUE TITLE
Float precision errors

### ISSUE THREAD

**Issue by xeruf** [leongersen/noUiSlider#1231]
When I use `noUiSlider.set` to update the value to an int, I still sometimes get errors where JS creates a bad float when handing the value back to me:
<img width="253" alt="image" src="https://user-images.githubusercontent.com/13354331/202556755-83d0ddbe-9702-4d11-8ab7-07e8b51c3f4d.png">

Is there a way to avoid that, is there something you can fix, or do I have to live with it and always do rounding?

**Comment by xeruf** [comment]
I get this for the `format` and the `tooltips` `to` function seemingly at random.

**Comment by andrewsm80** [comment]
The library is probably doing some math in which floating point imprecision is having this effect.

I think the library ought to be changed so that if `step == 1` then the value is rounded off before being passed to the user.
All integers in the range `[-2^53, 2^53 ]` [can be exactly represented](https://stackoverflow.com/a/12445693/4671252) in javascript IEEE 754. The library should take that into account.

**Comment by xeruf** [comment]
But how can this be if I set the raw slider value to a rounded integer?

**Comment by leongersen** [comment]
Because values aren't internally kept as integers.

**Comment by andrewsm80** [comment]
*All* values in javascript are [stored as 64 bit floats](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number). So the library's internal representation is really not a factor -- it's the same as the user's representation. Yes, doing math on floats can lead to imprecision, but if the user has told the library that he will be working only with "integers" (ie `step == 1`, or `step == 2`, ...) then the library shouldn't be returning floats -- it should round off to the nearest step requested by the user.

**Comment by leongersen** [comment]
Since all values are of type `Number`, (not `int` or ` float`), whichever representation is used to initiate a slider is not the API for setting formatting.

**Comment by andrewsm80** [comment]
There may well be a more suitable API than what I'm suggesting, so I'll leave that aside.

Of course, `Number` _is_ a floating-point type. See [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number#description)

**Comment by leongersen** [comment]
@andrewsm80 I'm open to a PR that sets the format option internally to `Math.round` if the arguments to start and step are integers.
