### ISSUE TITLE
Unable to install noUiSlider with Webpack

### ISSUE THREAD

**Issue by t-prod** [leongersen/noUiSlider#1232]
Hi,

I cannot configure NoUiSlider with webpack. This is my setup :
`import * as noUiSlider from 'noUiSlider';`

In my HTML :

`<script>
    var slider = document.getElementById('slider');
    console.log(window.noUiSlider);
    window.noUiSlider.create(slider, {
        start: [20, 80],
        connect: true,
        range: {
            'min': 0,
            'max': 100
        }
    });
</script>`

Error : 

Uncaught TypeError: Cannot read properties of undefined (reading 'create')

![image](https://user-images.githubusercontent.com/1824638/205970914-8eeaa263-4200-45d5-b567-cf5a388f930b.png)

Any idea ?

**Comment by leongersen** [comment]
A typical WebPack setup doesn't set imports on `window`. The `import * as noUiSlider` you're doing makes a `noUiSlider` variable available there.

**Comment by t-prod** [comment]
Sorry for my late answer. 
I've already tried this and same mistake. Do you  hyave an idea ?
Thanks for your help

**Comment by leongersen** [comment]
It really depends on how you're building your JS. There isn't enough info here for me to answer this.
