### ISSUE TITLE
Install via NPM return error Uncaught ReferenceError: noUiSlider is not defined but via CDN works fine

### ISSUE THREAD

**Issue by Geovanek** [leongersen/noUiSlider#1233]
I installed it via NPM in laravel and imported:

```
import nouislider from 'nouislider';
window.noUiSlider = nouislider;
```

And this way does not work, it returns:
_**Uncaught ReferenceError: noUiSlider is not defined**_

But if I import via:
`<script src="https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/15.6.1/nouislider.min.js"></script>`

It works perfectly. What could be happening to not work via NPM?

![image](https://user-images.githubusercontent.com/7670960/208091238-77df131a-7efe-4575-b596-43c82e7d272e.png)

**Comment by leongersen** [comment]
It really depends on how you're building your JS. There isn't enough info here for me to answer this.
