### ISSUE TITLE
Updating the connect direction.

### ISSUE THREAD

**Issue by iamcarlos94** [leongersen/noUiSlider#1239]
I have a use case where I need the slider's connect bar to switch direction as follows:
![image](https://user-images.githubusercontent.com/62184065/216823442-223cd9ad-da84-4734-a522-54eae3d2c263.png)
![image](https://user-images.githubusercontent.com/62184065/216823465-1d31e7d0-132f-44e2-9ccc-0e0235018d8c.png)

Right now I'm destroying the slider and creating a new one with either `connect: [true, false]` or `connect: [false, true]`, but that's being a large headache as there are other dynamic options being set elsewhere.

So my questions is if it'd be worth the effort to pursue adding the ability to update the connect option or just to keep destroying and recreating the slider.

**Comment by leongersen** [comment]
As this restructures the slider HTML, destroying and recreating is the way to go here.
