### ISSUE TITLE
Cannot read properties of undefined (reading 'destroy')

### ISSUE THREAD

**Issue by MariaAlmeidaMJ** [leongersen/noUiSlider#1243]
I have the latest version and I am having this error: Cannot read properties of undefined (reading 'destroy')-> `this.slider.destroy()`
Can you see this error, please? Thanks!

**Comment by leongersen** [comment]
There is not enough information here for me to do anything.

**Comment by MariaAlmeidaMJ** [comment]
@leongersen What information do you need?
