### ISSUE TITLE
Cannot read properties of undefined (reading 'destroy')

### ISSUE THREAD

**Issue by MariaAlmeidaMJ** [leongersen/noUiSlider#1245]
I have the latest version and I am having this error: Cannot read properties of undefined (reading 'destroy')-> this.slider.destroy()
Can you see this error, please? Thanks!
angular version: 13,
"nouislider": "^15.5.1",
"ng2-nouislider": "^1.8.3",
json where the problem is coming from:
`{key:"ngOnDestroy",value:function(){for(this.slider.destroy();this.cleanups.length;)this.cleanups.pop()()}},{key:"toValues",value:function(_){var l=_.map(this.config.format.from);return 1==l.length?l[0]:l}},`

**Comment by leongersen** [comment]
Please check [`CONTRIBUTING.md`](https://github.com/leongersen/noUiSlider/blob/master/CONTRIBUTING.md).
