### ISSUE TITLE
Event when user tries to go beyond padding limits

### ISSUE THREAD

**Issue by horatiua** [leongersen/noUiSlider#1250]
Hi,

I have a slider with padding on the left side.
When the user tries to go beyond that padding (tries to slide or tap), I want to show an alert with some message.
Is there a way to figure out when this happens?

Thank you!

**Comment by leongersen** [comment]
If you want the slider to respond to events in the padding area, you can have a looking at this example:
https://refreshless.com/nouislider/examples/#section-soft-limits
