### ISSUE TITLE
How to Make noUiSlider Handle Overlap Another?

### ISSUE THREAD

**Issue by luxorwannabe** [leongersen/noUiSlider#1251]
Hi All,

How to make one handle (in this example the blue handle in the center) can overlap another handle? I mean the blue handle movement is not limited by another handle position. Is that possible with noUiSlider?

Thanks

See the demo here [DEMO](https://jsfiddle.net/Monzalia/ow5t21yh/7/)

**Comment by scarabaeus** [comment]
@luxorwannabe Are you looking to allow JUST the blue handle to slide past the other two or ANY handle to slide past any other?

**Comment by luxorwannabe** [comment]
Oh my god! There are option to do that [](https://refreshless.com/nouislider/behaviour-option/#section-unconstrained)

**Comment by luxorwannabe** [comment]
Oh my god! There are option to do that [https://refreshless.com/nouislider/behaviour-option/#section-unconstrained](https://refreshless.com/nouislider/behaviour-option/#section-unconstrained)

**Comment by leongersen** [comment]
Glad you worked it out!
