### ISSUE TITLE
Slider for height in cm pointing the handler to the right label

### ISSUE THREAD

**Issue by moatasem0** [leongersen/noUiSlider#1252]
I want to use the slider to select the height in cm. The issue is that the slider handler is not pointing to the right value label.

Here is the live code:
https://jsfiddle.net/ekq6o7rp

I want the handler(in green) to point to the right label (160 cm). Also on dragging the handler, it should be on one of the lines. For example, if the handler is pointing to '160 cm' and I drag it to the bottom it should point to the line beneath it like that:
160 cm ____
                 -handler here (159).

I want it to act like a ruler so I can select the main values (150, 160 ..etc) and the numbers between them (151, 152, ..etc.).

Is that possible?

**Comment by leongersen** [comment]
Asked and answered here:
https://stackoverflow.com/questions/76654264/nouislider-slider-as-a-ruler-to-calculate-height-in-cm
