### ISSUE TITLE
Adding a prefix-suffix to a tooltip

### ISSUE THREAD

**Issue by rudy1976s** [leongersen/noUiSlider#1257]
It would be very useful to have the possibility of adding some prefix or suffix to the tooltip.
Actually it seems the only wai is to add a wNumb but it does work in combination with the classi format ( from to )

Rudy

**Comment by sarcanon** [comment]
+1 for adding prefix and suffix. I ran into same limitation in wNumb. Ideally, it would allow for conditional formatting.

**Comment by leongersen** [comment]
Formatting a tooltip with a prefix can be done like this:

```JavaScript
{ to: function(value) { return '❤️ ' + value; } }
```

I've added this example to the documentation:
https://refreshless.com/nouislider/number-formatting/#section-tooltips
