### ISSUE TITLE
Circular slider?

### ISSUE THREAD

**Issue by iamcarlos94** [leongersen/noUiSlider#1260]
Would it be possible to change the slider in a way that would make it a circle where both ends meet? 

Something like this: 
<img width="205" alt="IMG_2321" src="https://github.com/leongersen/noUiSlider/assets/62184065/1a812462-384f-498f-90c7-768bad94cacd">

**Comment by leongersen** [comment]
No, that's not something I think this library could do. The event handling currently only supports one axis.
