### ISSUE TITLE
Feature request: allow for connectSlider handles swap (drag handles across each-other and connect between or outside)

### ISSUE THREAD

**Issue by demonoff** [leongersen/noUiSlider#1262]
Hi there, thank you for a very nice device. Is there an option for the first handle to go beyond the second handle? 

I am doing a small student research project in which I ask participants when they go to bed and when they wake up. For that a slider with 24 hours is perfect. Although, some people go to bed at 01:00 at night and wake up at 09:00 in the morning (this situation is well handled in current settings and the sleep time can be connected). However, for people who go to bed at 22:00 in the evening and wake up at 06:00 in the morning the connection should be inverted (and people should be able to drag one handle across the other handle to be able to select this option). Is that possible?

So in brief, if **on the 24 h scale**:
- people go to bed **before** waking up, the connection will be between the `bed_time_handle` and `wake_up_handle` 
- people go to bed **after** waking up, the connection will be between 00:00 and `wake_up_handle` and between `bed_time_handle` and 24:00

**Comment by leongersen** [comment]
It sounds like you are looking for ["unconstrained" behaviour](https://refreshless.com/nouislider/behaviour-option/#section-unconstrained).

**Comment by cognostic** [comment]
Wow! That is a lot like it! But is there an option to switch the connection 
- from `h1↔h2` to `0↔h2 and h1↔24` when h1 > h2?

**Comment by demonoff** [comment]
Wow! That is a lot like it! But is there an option to switch the connection 
- from `h1↔h2` to `0↔h2 and h1↔24` when h1 > h2?

**Comment by leongersen** [comment]
This feature was contributed by @5andr0 and is in noUiSlider 15.8.0. Thanks!
