### ISSUE TITLE
why don't move range cursor whenever click or drag value on line

### ISSUE THREAD

**Issue by monteseniordev** [leongersen/noUiSlider#1265]
I use noUiSlider 13.1.5 in my project.
there is very strange issue.
I implemented all functions and work well on my workspace.
but after deploy source to other domain, whenever give action click or drag on slider, don't move range cursor.
in other ways, slider don't work for set updated value.

if I use variable maxPrice, occur above issue.
```
noUiSlider.create(slider, {
                start: [ 0, maxPrice ],
                connect: true,
                step: 50,
                margin: 200,
                range: {
                    'min': 0,
                    'max': **maxPrice**
                },
                tooltips: true,
                format: wNumb({
                    decimals: 0,
                    prefix: ' AED '
                })
            });
```
but if I use number such as 1000, all work well.

```
noUiSlider.create(slider, {
                start: [ 0, maxPrice ],
                connect: true,
                step: 50,
                margin: 200,
                range: {
                    'min': 0,
                    'max': **1000**
                },
                tooltips: true,
                format: wNumb({
                    decimals: 0,
                    prefix: ' AED '
                })
            });
```

why happened this?
![work](https://github.com/leongersen/noUiSlider/assets/161117859/adfe824e-b3e8-45ce-ace1-c8aa32ffcec2)
![error](https://github.com/leongersen/noUiSlider/assets/161117859/f135c335-0f17-4e11-9c34-f777c7f89d00)

this code work well in my workspace. very very strange

**Comment by leongersen** [comment]
I can't really answer this with this information, `console.log` `maxPrice` and see what is happening.
