### ISSUE TITLE
Update connect option

### ISSUE THREAD

**Issue by jamal-tmam** [leongersen/noUiSlider#1269]
I need to update connect option but is not working. Following is the code.
What I am trying to achieve here is that the range is from -5 to 5. and for the values greater than 0 will have connect option set to upper and color blue and for values less than 0 will connect option set to lower and color red. 

Questions:
1. How to make this updateOptions to work.
2. Is there a better way to achieve what I want?

```
slider.noUiSlider.on("change", function (values, handle) {
    let progressValue = parseInt(values[handle]);

   if (progressValue < 0) {
        slider.noUiSlider.updateOptions({
            connect: 'lower'
        });

        slider.querySelector(".noUi-connect").style.backgroundColor = 'red'; // Set the slider track color to red for negative values
  } else if (progressValue > 0) {
        slider.noUiSlider.updateOptions({
            connect: 'upper'
        });
              
       slider.querySelector(".noUi-connect").style.backgroundColor = 'green'; // Set the slider track color to green for positive values
  } else {
       slider.querySelector(".noUi-connect").style.backgroundColor = 'transparent'; // Remove background color if the value is 0
  }
});
```

Following are the screenshots of examples what I want to achieve.

![image](https://github.com/leongersen/noUiSlider/assets/132986567/9d261c5d-b3b0-4fc2-b514-9c2245d1ab7a)

![image](https://github.com/leongersen/noUiSlider/assets/132986567/35412014-da65-4fd9-b4d0-63aa4e339471)

![image](https://github.com/leongersen/noUiSlider/assets/132986567/84968e01-5de4-41bc-a9c5-9295b033ce9a)

**Comment by leongersen** [comment]
The connect option can be updated as of noUiSlider 15.8.0. 

```
slider.noUiSlider.updateOptions({
            connect: 'lower'
        });
        ```
        
Will now work.
