### ISSUE TITLE
Issue related to "Connect" option after last version update

### ISSUE THREAD

**Issue by galSzlaifer** [leongersen/noUiSlider#1276]
Hi @leongersen ,
Big thanks for all the support and effort in building and maintaining this great lib.
I wanted to ask something regarding this update - [Update connect option · Issue #1269 · leongersen/noUiSlider (github.com)](https://github.com/leongersen/noUiSlider/issues/1269#top)
we are using this lib via wrapper lib  --> ng2-nouislider.
after updating the nouislider lib to the 15.8.1 version that was by npm install ,some inner app E2E failed.
The Issue is not connected to the wrapper we use (no update was there) but is more connected to a "drag behavior" that was added to the slider.

looking at the  source code I see an  add code on line  3078  - https://github.com/leongersen/noUiSlider/blob/faa3252f84d3e2416ba43ba49b2de91b9112ce80/src/nouislider.ts#L3078

I think this is the root for the issue we have ,
 we are calling the "updateOptions"  line 2995  and passing an object to the "connect" option  ... it worked up until version 15.8.0.

From this update, we must update the code and change the "connect" option to false ... to avoid entering this section.
question is ... was that the intention of this update?
is there a way not to get that  "drag " true other than to update the "connect" option to false?

Thanks
Gal

**Comment by leongersen** [comment]
The `connect` option could not be updated previously; it can be, now.

Passing an object with an additional property into methods like this won't break anything, except for when a meaning is added for that property later, as happened here.

I don't consider this a breaking change.

**Comment by galSzlaifer** [comment]
Thanks for response
