### ISSUE TITLE
Exponentially increase range

### ISSUE THREAD

**Issue by scooterlord** [leongersen/noUiSlider#140]
Hello and well done on your excellent work on this plugin!

It would be real nice if we could have exponential increase of the range values, meaning, if there's a huge price range for example 0-2.000.000, the first values would start in steps of 1 and as the range reaches it's end it should be in steps of 10.000.

In other words, variable steps. So, you would define multiple percentage values between which you could set a different step OR define points of range values in percentage width and give the value there.

Much like how ebay price-range works for example!

**Comment by nmindab** [comment]
Fantastic! I have been looking for a range slider with good mobile support. A non-linear slider with pips was more than I even hoped to find!

**Comment by Revadike** [comment]
I developed my own dynamic idea that you may find useful. Here `max` is the range you want the slider to me (from 0 to `max`).

```js
            const digits = max.toString().split(``).length;
            const range = {
                "min": 0,
                "max": max
            };

            let percentage = 0;
            for (let i = 1; i <= digits - 1; i++) {
                percentage += 100 / (digits - 1);
                range[`${percentage}%`] = Math.pow(10, i);
            }

            noUiSlider.create(slider, {
                "start": [0, max],
                "connect": true,
                "step": 1,
                "range": range
            });
```
