### ISSUE TITLE
[Request] Allow empty values

### ISSUE THREAD

**Issue by neoascetic** [leongersen/noUiSlider#143]
Example use case: slider for price range selection for a filter in an online shop. When handles are set to their initial positions (most left and most right, respectively), "value" attribute of each corresponding form field must be empty. This means that user do not want to filter products by their price at all.

**Comment by 1234ru** [comment]
I have the same use case as the topic starter did. 
Is the solution you provided in the [https://github.com/leongersen/noUiSlider/issues/143](fiddle) still up to date?
