### ISSUE TITLE
Daterange functionality

### ISSUE THREAD

**Issue by ux-engineer** [leongersen/noUiSlider#157]
Hi,

This plugin is great in it's minimal way. The only thing that is missing for my use at this time is daterange functionality! Sadly there are so few quality plugins that do that...

I would need to set date range in the format e.g. 2013-12-28 - 2013-12-31

Is there some way I could implement this with noUiSlider, could you make an example of that to your site?

There is only one cool plugin for that purpose that I have found, but I wouldn't like to combine two plugins and your plugin is neatier :) http://ghusse.github.io/jQRangeSlider/

UPDATE: I think I figured out a way, next I have to see if it works... I could use the slider for an integer value as "x days ago" and have it masked as the actual date string in the UI.

**Comment by AsimAziz** [comment]
@leongersen, @ShaneHudson, @ux-engineer, How can we skip a date?
Input:
[1-jan, 2-jan, 5- jan]   

slider should not show 3,4 jan.

**Comment by leongersen** [comment]
@AsimAziz There's an example for [skipping steps](https://refreshless.com/nouislider/examples/#section-skipping) in the documentation.
