### ISSUE TITLE
Overlapping vs colliding handlebars 

### ISSUE THREAD

**Issue by ux-engineer** [leongersen/noUiSlider#158]
Hi,

I would like to have colliding handle bars when there are two handles. Selecting small ranges (going to implement a day range, so the smallest range is "today") is a bit confusing when the handlebars are stacked so that only one handlebar is visible.

**Comment by mg1075** [comment]
`behaviour: 'extend'` is an option?

**Comment by leongersen** [comment]
`extend` can be done [in CSS only](http://refreshless.com/nouislider/more/#section-styling).
