### ISSUE TITLE
serialization: editable "to" input values and formatting

### ISSUE THREAD

**Issue by mg1075** [leongersen/noUiSlider#167]
What if the inputs .noUiSlider writes to in a range slider, and which a user can edit to update the slider, do not have simplistic values like 0 to 100? 

For example, what if you had a range slider of dollar amounts where the dollar amounts went into the thousands of dollars, and you wanted to keep the formatting of the dollars in this style , $1,000,000.00, at least for display and after mouseleave (when done editing)? 

Let's say you have a min value of 1978.00, and you format the number as 1,978 for display purposes, and a max value of 
2004.00. If you edit the "to" input to try to be 2,000, you get kicked back 1,978, because the input does not handle the non-decimal style value.

Or what if you wanted to slide a range of dates?

Unless I am missing something, .noUiSlider only seems to like decimal style values in the editable inputs, so for now it looks like a good deal of workarounds would be necessary.

**Comment by hamdan-mahran** [comment]
Hi Leon,
how to remove coma from (1,000) to be (1000) ?
Thanks very much

**Comment by hamdan-mahran** [comment]
Hi Leon,
how to remove coma from (1,000) to be (1000) ?
Thanks very much

**Comment by hamdan-mahran** [comment]
I got it from this example
http://refreshless.com/nouislider/slider-read-write/
Thanks
