### ISSUE TITLE
Remove zeros from span output element

### ISSUE THREAD

**Issue by daniel860992** [leongersen/noUiSlider#171]
I have the range set to 1-10 and a step of 1. Its currently outputting 1.00, 2.00, 3.00 when you move the slider instead of 1, 2, 3 etc. Can you tell me if its possible just to display 1, 2, 3? I've had a go but not much luck.

**Comment by ziadeh** [comment]
here is the answer: 
            $("#range-hpips").noUiSlider({
                start: [2], 
                connect : 'lower',
                step:1,
                range: {
                    'min': [0],
                    'max': [10]
                }
            }).Link('lower').to(function (e) {
                var num = parseInt(e);
                $("#range-step").text(num);
            });
