### ISSUE TITLE
adding "tap" event

### ISSUE THREAD

**Issue by mkalac** [leongersen/noUiSlider#201]
Is there a way of detecting only "tap" event, when value is set by clicking mouse on the slider? I need to distinguish that event from dragging or setting value with other methods.

For example, i have a slider with range [1,7] with step 0.1. If user slides or sets value through serialization input, the value must be exactly that value with decimals. But, when a user taps on slider, i must set closest round value ( between 3.5 and 4.5, i must set value of 4, between 4.5 and 5.5, i must set value of 5, etc.)

Is there a way to do so?

**Comment by jgerigmeyer** [comment]
@leongersen Would you be open to a PR adding a "tap" event? Seems like it would be a simple addition, and would be beneficial for distinguishing between "drag" and "tap" firing the "change" and "set" events.

Alternatively, what about adding a fourth argument to the `change` and `set` events: `type`. It could just be a string, `drag`, `tap`, or `set`. (This could actually make the `set` event unnecessary once you can distinguish between different causes of the `change` event, but it could be left for backwards-compatibility.)

Thoughts?
