### ISSUE TITLE
Handles not draggable ie11 and ie mobile (windows phone)

### ISSUE THREAD

**Issue by sriksm19** [leongersen/noUiSlider#231]
The slider's handles are draggable in all browsers except in ie11 and ie mobile (windows phone 8) . But they do work on nouislider homepage in both of the browsers. Help.

**Comment by rkrathod** [comment]
@leongersen - I managed to make the handles draggable for IE11 using pointerdown, pointermove and pointerup.

I am not able to move them on click though. Any thoughts?
