### ISSUE TITLE
Time/clock slider

### ISSUE THREAD

**Issue by leads** [leongersen/noUiSlider#240]
Hi
Any ideas how we can use this slider with as a time selector?
So start at min: 00:00, max: 23:59. Increments of 15 minutes, 30 minutes, or an hour.

See how skyscanner have their time slider
http://www.skyscanner.nl/transport/vluchten/lond/nyca/140513/140531/vliegtarieven-van-londen-naar-new-york-in-mei-2014.html?rtn=1

**Comment by benstr** [comment]
I am getting an error from the example.

`lower: [new $.noUiSlider.Link({.....` "undefined is not a function"

**Comment by leongersen** [comment]
That's because the example uses the old API. Update version: [here](http://jsfiddle.net/leongersen/Zr8ec/2/).

**Comment by benstr** [comment]
Awesome, thanks @leongersen !

**Comment by Fire-Brand** [comment]
@leongersen, is it just me or there's a problem with the jsfiddle?

Any way to make this work with a 00:00:00 format?

**Comment by leongersen** [comment]
You are looking at an issue created before the no-jQuery port. [This example](http://refreshless.com/nouislider/examples/#section-huge-numbers) demonstrates the basic concept.

**Comment by isaachinman** [comment]
Looks like the above fiddle is broken. Has anyone implemented a slider that is agnostic of datetime and merely slides between 00:00 and 24:00? Wondering if there's a simple/straightforward way outside of doing this in minutes and reformatting later.

**Comment by banterstudios** [comment]
See https://jsfiddle.net/Banterstudios/skrb5cg3/ if you want a solution to creating a simple time / clock slider

**Comment by zackster** [comment]
Hi @banterstudios thanks for the solution!  I added upon it a bit in order to support 12-hour clock https://jsfiddle.net/skrb5cg3/134/
