### ISSUE TITLE
Using Aria for accessibility ?

### ISSUE THREAD

**Issue by gavrochelegnou** [leongersen/noUiSlider#246]
Hello, 
Is there any plan to add accessibility features like aria roles and values ?
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_slider_role

Thanks,

**Comment by felixgirault** [comment]
:+1: 

For now, there is no way to access noUiSlider with the keyboard.
Implementing an accessibility layer would be really useful, and good for the web ;)

Thanks for the lib anyway!

**Comment by leongersen** [comment]
I think the *most* accessible option would be a `Link`ed input element showing the value. It'll be tab-able, too.

-----Original Message-----

**Comment by felixgirault** [comment]
It would be a good starting point. The complete pattern involves setting a bunch of aria attributes though, but it is not so complicated. You can see an example here : http://access.aol.com/aegis/#goto_slider

I'm currently trying to implement this on noUiSlider. If it works, I'll probably publish a thin wrapper to make it accessible without touching the core code.

**Comment by felixgirault** [comment]
I'm working on the a11y layer, but I'm having troubles interacting with the lib.
I need to access different things that seems to be private for now.

For example, I would love to have methods to know the min and max values of the slider (without parsing the options myself).
Also, a method to move a handle to the previous/next step would be super useful.

Do you see a way to to these kind of things ?

**Comment by leongersen** [comment]
The options can be [retrieved](http://refreshless.com/nouislider/more/#section-options), but unparsed. Note that if there is no `min` and `max`, the values are invalid and an exception in thrown.

The previous and next steps are available in (`.noUiSlider('step')`)[http://refreshless.com/nouislider/examples/#section-keypress].

If you feel like working on this, I'd be open to a pull request!

**Comment by felixgirault** [comment]
Hi,

I worked on a tiny script that wraps noUiSlider to make it accessible : https://gist.github.com/felixgirault/3fcb18ee0268b1c3127c (note that it uses lodash)
You can see this page for reference : http://oaa-accessibility.org/example/32/

I don't really have time to make a pull request, as it would require some time to dig in the code, but the gist could be useful to someone ;)

**Comment by leongersen** [comment]
My stance on this: link an `<input>`, provide accessibility attributes on that. It'll have the best screen-reader support.

**Comment by mshwery** [comment]
While I agree that the _most_ accessible answer is a numeric input, it should still be _standard_ to include keyboard accessibility to form elements. The fact that noUISlider doesn't support keyboard interaction is the only reason I cannot use it.

**Comment by felixgirault** [comment]
Also, to complete @mshwery answer, a standard accessible slider provide finer grained control over the value.
The ability to increment or decrement the it the keyboard, by small or bigger steps, and to set it to a minmum or maximum is not implemented by default on a form input, and this can be beneficial to any kind of user.

**Comment by leongersen** [comment]
I've added a new example with keyboard support to the docs, will release it soon.

**Comment by mshwery** [comment]
Sweet! I mangled something together very similar to @felixgirault's solution, but am open to other options.

**Comment by leongersen** [comment]
Just released v8.1.0, with the [new example](https://refreshless.com/nouislider/examples/#section-keyboard) in the documentation. Feel free to discuss!

**Comment by mshwery** [comment]
Thanks @leongersen. I basically did the exact same thing, except I have it dynamically binding to however many handles there are.

I understand the desire to keep this as an extension of the library, but something like keyboard/accessibility support seems pretty integral to an input library. I would still recommend integrating some sane standard behavior in the core library itself.

That being said, this works just fine in the interim.
