### ISSUE TITLE
Multi touch with multiple sliders - 2nd touch controls both sliders

### ISSUE THREAD

**Issue by neoRiley** [leongersen/noUiSlider#247]
I have 2 sliders and on my touch device (iPad atm), if I'm adjusting one, and then use another slider at the same time, the 2nd slider's input takes over and adjust both sliders.

Have I missed something in documentation that allows for multi-touch?

Thanks much!

**Comment by QuentinRoy** [comment]
Any chance to re-open this issue. I would need this. My use case would be to modify the slider while having another finger down. Currently, if more than one finger are down, all sliders are disabled.

I'll need this quite soon so I'm thinking about having a quick look at the code and see if I can bend it my way.

**Comment by avblink** [comment]
Guys, any update on this? Or did you end up using another library?
Could you please share your solution.

**Comment by leongersen** [comment]
This is supported with a new option `multitouch` in the latest release. I haven been able to update the documentation yet, which is my bad. The `multitouch` option will be the default in the next release, which I'm hoping to get out the door before February.
