### ISSUE TITLE
Upwards swipe on bar triggers swipe on slider, not page scroll

### ISSUE THREAD

**Issue by tommhuth** [leongersen/noUiSlider#267]
Great plugin, but I've come across an issue on smaller screens where a vertical page swipe that starts on   a slider bar (the horizontal bar that gets colored) wil trigger a  slider slide instead of a page scroll. This is noticeable on smaller screens with several sliders, where it be likely you hit one of the sliders instead of some other content on the page. 
 
Would it be an idea to restrict swiping to only be triggered on the handler element, and just listen for  taps on the base bar so that page scrolling is not inhibited? 

If you need more info, I'm sure i can throw together a short example.

**Comment by leongersen** [comment]
noUiSlider *does* use pointer events where appropriate. Either play with the `touch-action` property, or keep the slider positioned outside of likely scroll positions. I've messed with this *extensively*: there is no cross-browser way of detecting differences between scroll-intent and slider control that wouldn't break the slider.
