### ISSUE TITLE
Getting max/min values after initialziation

### ISSUE THREAD

**Issue by danielsokolowski** [leongersen/noUiSlider#270]
Hello there, perhaps I've missed the obvious but how does one get the min/max range values after the `noUiSlider` has been initialized?

**Comment by Sachin51** [comment]
How to update the min/max range values after the noUiSlider has been initialized in nouislider version 7 ? Right now Iam able to display the slider with start [minValue,maxValue] , range [0,maxLimit]. I want to update the maxLimit value. Can anyone help me for this ?
