### ISSUE TITLE
Keyboard Accessibility

### ISSUE THREAD

**Issue by aristidesfl** [leongersen/noUiSlider#274]
Is it possible to interact with the slider using only the keyboard?

**Comment by tremmer** [comment]
Here is a great example of accessibility on sliders that would be great to see baked in 

http://oaa-accessibility.org/example/32/

**Comment by leongersen** [comment]
Merging with #246.

**Comment by mshwery** [comment]
Was this ever integrated? Latest from npm seems to say no.

**Comment by simevidas** [comment]
The main demo on http://refreshless.com/nouislider/ isn’t keyboard accessible, from what I can tell.

**Comment by MartinMuzatko** [comment]
Doesn't seem to work :/

**Comment by MartinMuzatko** [comment]
This is now tracked here: https://github.com/leongersen/noUiSlider/issues/724
