### ISSUE TITLE
Using image as slider background

### ISSUE THREAD

**Issue by harisree17** [leongersen/noUiSlider#280]
Hi,

I tried setting the background of the slider with an image by giving the below style. 
.noUi-background {
  background-image: url('/path/to/image.png');
}
The image is appearing, but the problem is when I do sliding, the background image will move to right as the "left" value is dynamically changing. Is there any solution for this problem?

Thanks in advance,
Sreehari

**Comment by jan-tosovsky-cz** [comment]
I use this code. It is called once after init and after on slide event. It would be nice to have this out of the box.

    $("#slider").noUiSlider({
        // ...
    });

    fixSliderBarWidth();

    function fixSliderBarWidth() {
       var right = 100 - $("#slider .noUi-background")[0].style.left.replace('%','');
       
       $("#slider .noUi-connect").css({
          "right": right + "%"
       });
    }

    $("#slider").on({
       slide: function() {   
          fixSliderBarWidth();
       }
    });

**Comment by leongersen** [comment]
You can do this by adding a new element for the `connect`  option. The documentation now has an [example that'll help you](https://refreshless.com/nouislider/examples/#section-custom-connect)!
