### ISSUE TITLE
Error: noUiSlider: Can't initialize slider on empty selection.

### ISSUE THREAD

**Issue by handoyo** [leongersen/noUiSlider#307]
Hi,i'm using the 6.2 version.When i run the code.It shows this error on the firebug console : Error: noUiSlider: Can't initialize slider on empty selection.

Here is my code : 
$('.range-slider').each(function() {
        var $this = $(this),
            configs = new Array(),
        low = $.Link({
            target: $('#min'),
            method: 'text',
            format:{
                decimals:0,
                mark: ",",
                thousand: "."
            }
        }),
            up = $.Link({
                target: $('#max'),
                method: 'text',
                format:{
                    decimals:0,
                    mark: ",",
                    thousand: "."
                }
            });

```
    configs['min'] = ( $this.data('min') === undefined ) ? 0 : $this.data('min');
    configs['max'] = ( $this.data('max') === undefined ) ? 100 : $this.data('max');
    configs['start'] = ( $this.data('start') === undefined ) ? [configs['min'], configs['max']] : $this.data('start');
    configs['step'] = ( $this.data('step') === undefined ) ? 1 : $this.data('step');
    configs['currency'] = ( $this.data('currency') === undefined ) ? $('.dropdown-money #symbol').text() : $this.data('currency');

    $this.noUiSlider({
        range: {min:configs['min'],max: configs['max']},
        start: configs['start'],
        step: configs['step'],
        connect: true,
        handles: 2,
        serialization: {
            lower:[low],
            upper:[up]
        }
    }).change(function() { priceSlider( $(this).val() ); });

    $this.siblings('.range-slider-value').find('> .min').text( configs['currency'] + $this.val()[0] );
    $this.siblings('.range-slider-value').find('> .max').text( configs['currency'] + $this.val()[1] );
});
```

Please point me where is the mistake.Thanks a lot

**Comment by nehaKeskar** [comment]
I am in need of 3 handler date range slider , I tried a lot with below code, But it is showing error like range contain invalid values. Please have a look.

		var
	weekdays = [
		"Sunday", "Monday", "Tuesday",
		"Wednesday", "Thursday", "Friday",
		"Saturday"
	],
	months = [
		"January", "February", "March",
		"April", "May", "June", "July",
		"August", "September", "October",
		"November", "December"
	];
	
	function nth (d) {
  if(d>3 && d<21) return 'th';
  switch (d % 10) {
        case 1:  return "st";
        case 2:  return "nd";
        case 3:  return "rd";
        default: return "th";
    }
}
	
	function formatDate ( date ) {
    return weekdays[date.getDay()] + ", " +
        date.getDate() + nth(date.getDate()) + " " +
        months[date.getMonth()] + " " +
        date.getFullYear();
}
		
		function timestamp(str){
    return formatDate(new Date(str));   
}


var range = document.getElementById('range');
 
var minvalue= timestamp('2010');
var maxvalue= timestamp('2020');

range.style.height = '20px';
range.style.margin = '50 auto 30px';

noUiSlider.create(range, {
	start: [ timestamp('2011'), timestamp('2015'), timestamp('2018') ], // 4 handles, starting at...
	//margin: 1, // Handles must be at least 300 apart
	//limit: 500, // ... but no more than 600
	connect: true, // Display a colored bar between the handles
	direction: 'ltr', // Put '0' at the bottom of the slider
	orientation: 'horizontal', // Orient the slider vertically
	behaviour: 'tap-drag', // Move handle on tap, bar is draggable
	//step: 1,
	tooltips: true,
	format: wNumb({
		decimals: 0
	}),
	range: {
		min: minvalue,
		max: maxvalue
		
	},
	
	
	pips: { // Show a scale with the slider
		 mode: 'steps',
        density: 1,
       // values: [10,99],
        stepped: true,
        /*format: wNumb({
            decimals: 0,
            prefix: '+',
            postfix: 'c'
        })*/
	}
	
});

var connect = range.querySelectorAll('.noUi-connect');
var classes = ['c-1-color', 'c-2-color', 'c-3-color', 'c-4-color', 'c-5-color'];

for ( var i = 0; i < connect.length; i++ ) {
    connect[i].classList.add(classes[i]);
}
		


		});
