### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by lifzgreat** [leongersen/noUiSlider#313]
I'm getting `Uncaught TypeError: undefined is not a function` when I use the following code (notice the rebuild flag). If I don't set the rebuild flag to true, the error goes away. However, then on subsequent calls, I get the error that says it was already initialized. I'd like to use the rebuild flag so I can keep calling the code below each time the user clicks a link.

``` javascript
$("#dateSlider").noUiSlider({
    start: [0, 100],
    range: {
        min: [0],
        max: [100]
    },
    step: 1,
    behaviour: "extend-tap"
}, true);
```

The error appears to be `d = this.destroy()` in the following function:

``` javascript
function X(a) {
    return this.each(function() {
        var b = c(this).val(),
            d = this.destroy(),
            f = c.extend({}, d, a);
        c(this).noUiSlider(f);
        d.start === f.start && c(this).val(b)
    })
}
```

**Comment by ablebeam** [comment]
An example here: http://jsfiddle.net/leongersen/85529yy8/1/ seems to be broken. Also I have the same issue (TypeError: $(...).noUiSlider is not a function) and also had to manually require wNumb library (haven't had to do it previously) after updating all assets. 

Dealing with it now but perhaps anyone already knows the answer?

**Comment by leongersen** [comment]
I'm simply not hosting the files in that fiddle anymore
