### ISSUE TITLE
destroy noUiSlider

### ISSUE THREAD

**Issue by xbagir** [leongersen/noUiSlider#315]
How to destroy noUiSlider?

**Comment by hilobaks** [comment]
It does not work! 
Jquery does not found a  function 'destroy' !
Please help!
How i can destroy noUiSlider?

**Comment by nietonfir** [comment]
@hilobaks Works just fine, the function just moved to the `noUiSlider` DOM property, e.g. `$0.noUiSlider.destroy()` (where `$0` is your raw DOM element).

**Comment by hilobaks** [comment]
I`m sorry, maybe i am realy stupid, but in my script, this is method doesn`t work. 
Please talk me, what i do wrong !

var idSliderAmount = '#sliderAmount',
      idSliderDate = '#sliderDate';

$(idSliderAmount)[0].noUiSlider.destroy();
$(idSliderDate)[0].noUiSlider.destroy();

**Comment by nietonfir** [comment]
@hilobaks I'd gladly help you, but I think you should ask this question at [SO](http://stackoverflow.com/) with a full-fledged example (e.g. [jsbin](http://jsbin.com/), as this is not a support forum. ;-)

**Comment by jestersimpps** [comment]
`        // Throw an error if the slider was already initialized.
        if (scope_Target.noUiSlider) {
            // throw new Error('Slider was already initialized.');
            scope_Target.noUiSlider.destroy();
        }`

**Comment by leongersen** [comment]
I'd recommend against that: make your code explicit. Why are you (expensively) destroying the slider?

**Comment by jestersimpps** [comment]
Hey Leon, first of all, thx for writing this awesome plugin. While my DOM stays the same I want to generate new sliders dynamically. Here's my code:

```
for (var i = 0; i < reviewquestions.length; i++) {
      $('#question' + i).innerHTML = reviewquestions[i].question;
      $('#slider' + i).destroy();
      noUiSlider.create($('#slider' + i), {
        start: 5,
        range: {
          'min': 0,
          '10%': 1,
          '20%': 2,
          '30%': 3,
          '40%': 4,
          '50%': 5,
          '60%': 6,
          '70%': 7,
          '80%': 8,
          '90%': 9,
          'max': 10
        },
        snap: true,
        pips: {
          mode: 'values',
          values: [1, 2, 3, 4, 5, 6, 7, 8, 9],
          density: 9
        }
      }, true);
    }
```

I am getting the following error:  $(...).destroy is not a `function. So instead of showing the warning, I decided to just destroy the sliders that were already there.
