### ISSUE TITLE
Issues with jQuery 1.9.1, $.Link = undefined is not a function

### ISSUE THREAD

**Issue by vallieres** [leongersen/noUiSlider#319]
I'm trying to initialise a very simple noUiSlider as such:

```
$('.handles-slider').noUiSlider({
    range: {
        'min': 0,
        '33%': 33,
        '67%': 67,
        'max': 100
    },
    snap: true,
    start: 33
});
```

And I get this error:

```
Uncaught TypeError: undefined is not a function 
```

That points to this line:

:614
    var index, list = [], standard = new $.Link({}, true); 

Using Bootstrap 2.3, jQuery 1.9.1 and a few more librairies.

Thanks!

**Comment by no1youknowz** [comment]
I know this is an old issue.  Where can I find Link.js?  Thanks

**Comment by leongersen** [comment]
In this repository: https://github.com/leongersen/liblink
