### ISSUE TITLE
Initialize slider with empty selection

### ISSUE THREAD

**Issue by gearsdigital** [leongersen/noUiSlider#325]
I have a dynamic page which generates sliders based on a previous selection but I have a global, minified javascript file which initializes **all** sliders.

In your current implementation your script dies if we got an empty selection. So, If all html fragments are available everything works as expected but if you remove one ore more html fragments it breaks.

Here is a fiddle which outlines the problem.

**Broken**
http://jsfiddle.net/gearsdigital/bojo82cf/

**Working**
http://jsfiddle.net/gearsdigital/bojo82cf/1/

It seems it dies because you're throwing an error. What is your intention here?

``` javascript
// file module.base.js:791

// Throw error if group is empty.
if ( !this.length ){
    throw new Error("noUiSlider: Can't initialize slider on empty selection.");
}
```

**Comment by yuvaraj147** [comment]
Where is the final solution?
