### ISSUE TITLE
Connect range lower CSS compatibility

### ISSUE THREAD

**Issue by bitxl** [leongersen/noUiSlider#335]
Hi,

love the plugin!

I noticed that when using an upper range there's a div.noUi-connect, but when doing a lower range there is no such div. This would come in handy with specific CSS situations, for example:
the connect should be a horizontal linear gradient, but not stretch only the width of the connect but the width of the entire slider. In this case I would reverse the connect and in the case of an upper range make the div.noUi-connect an overlay that hides the rest of the gradient. If the connect is lower this cannot be done. 

I hope my explanation is clear! :)

**Comment by leongersen** [comment]
You can do this by adding a new element for the `connect`  option. The documentation now has an [example that'll help you](https://refreshless.com/nouislider/examples/#section-custom-connect)!
