### ISSUE TITLE
How to stop my slider at certain point

### ISSUE THREAD

**Issue by laptev** [leongersen/noUiSlider#348]
I'm looking for a simple solution to stop the slider at certain value. For example, my range is 1000 - 5000 and I want to slider not to move less then 2000. Thanks in advance for help!

**Comment by mshwery** [comment]
Is there way to actually _prevent_ the slider from sliding below a certain point? I dont want the slider to even look like it can slide past a min or max.

**Comment by leongersen** [comment]
Add padding!

**Comment by mshwery** [comment]
Hm... are you referring to http://refreshless.com/nouislider/more/#section-styling?

**Comment by mshwery** [comment]
It's a bit tricky, because it's dependent on another input (so the minimum/maximum can be dynamic)

**Comment by giorgioriccardi** [comment]
might be a bit late, but I found a similar request and I customized it to avoid slider above and below certain values. The solution here seems to be simpler than others:
http://jsfiddle.net/Giorgio25b/cdn3mfs3/
Hope this help
