### ISSUE TITLE
`Uncaught Error: Slider was already initialized` when trying to create a slider from a cloned element

### ISSUE THREAD

**Issue by onet4** [leongersen/noUiSlider#353]
Hi, 

Sorry if this has been asked already. What's the proper way to clone the slider dynamically? 

If you run the example below, you'll see the slider event binding does not work while the element is cloned. If the line  `new_slider.noUiSlider( options );` is uncommented, it gets the error `Uncaught Error: Slider was already initialized`.

```html
<html>
    <head>
        
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <link href="jquery.nouislider.min.css" rel="stylesheet">
        <script src="jquery.nouislider.all.min.js"></script>        
        <style>
            .buttons {
                margin: 1em 1em 1em 0;
            }
            .button { 
                border: 1px solid #ccc; 
                width: 16px;
                height: 16px;
                padding: 0.24em 0.6em;
                font-size: 1.4em;
            }
            .slider-container {
                width: 300px;
            }
        </style>
    </head>
    <body>
        

        <div class='slider-container'>
            <div class='buttons'>
                <span class='button minus'>-</span><span class='button plus'>+</span>
            </div>        
            <div class='slider' id='slider-test_1' ></div>
        </div>
        
        
        
    </body>
    <script>
        $( document ).ready( function(){
        
            var increment_id = function( id ) {            
                return id.replace( /_(\d)/g, function ( entire_match, m0 ) {
                    return '_' + ( Number( m0 ) + 1 );              
                });         
            }
            var decrement_id = function( id ) {            
                return id.replace( /_(\d)/g, function ( entire_match, m0 ) {
                    return '_' + ( Number( m0 ) + 1 );              
                });         
            }        
            
            var options = {
                start: [20, 80],
                range: {
                    'min': [ 0 ],
                    'max': [ 100 ]
                }
            };
            
            $( "#slider-test_1" ).noUiSlider( options );                             
            $( '.plus' ).on( 'click', function() {
                console.log( 'clicked' );
                var container = $( this ).closest( '.slider-container' ).first();
                var new_container = container.clone( true );
                var new_slider = new_container.find( '.slider' ).first();
                new_slider.attr( 'id', increment_id( container.find( '.slider' ).first().attr( 'id' ) ) );
                // new_slider.noUiSlider( options );
                container.after( new_container );
            } );
            $( '.minus' ).on( 'click', function() {
                $( this ).closest( '.slider-container' ).first().remove();
                
            } );            
        });

        
    </script>

</html>
```

**Comment by razmo** [comment]
Have anyone found a solution to fix this issue ?
It is not possible to create an instance of noUiSlider on cloned object. Even if we rebuild it !

**Comment by albertovivar** [comment]
Hello, ok, this is the case:

1.- I was getting the error 'Uncaught Error: Slider was already initialized' where my code reuses the slider. 

2.- Then i applied the suggested code here: $( "#slider-test_1" ).noUiSlider( options, true /* Allow destruction + rebuilding */ );

3.- Ok, no error, but the problem its that SET event defined is firing multiple times and ascending each time a rebuild and operate the slider: Here is my code:

function getPrecio(resp, modelo, medida) {

	$('#slider').noUiSlider({
		animate: true,
		connect: 'lower',
		start: resp.value,
		step: resp.step,
		direction: 'ltr',
		orientation: 'horizontal',
		behaviour: 'tap-drag',
		format: wNumb({
			mark: ',',
			decimals: 0
		}),
		range: {
			'min': resp.min,
			'max': resp.max
		}
	}, true);

	$('#slider').Link().to($('#slider-input'));

	$('#slider').noUiSlider_pips({
		mode: 'positions',
		values: [0,25,50,75,100],
		density: 4,
		stepped: true,
		format: wNumb({
        		decimals: 0,
        		postfix: 'u'
        	})
	});


	$("#slider").on({
		set: function(){

			console.log('set');
		}
	});


}

**Comment by leongersen** [comment]
Sliders always need to be destroyed in 8.0.

**Comment by thgr** [comment]
Hello. I am used 8.5.1 version. I still get the error "Uncaught Error: Slider was already initialized"

**Comment by leongersen** [comment]
What are you trying to do?

**Comment by Anaghan** [comment]
Hello Everyone

Finally I have find out this Error - **" web.assets frontend.js:408 Uncaught Error: noUiSlider: Can't initialize slider on empty selection."**

**"nouislider "** lib is search slider length but lib didn't find it, So I got this error.

Following is my actual Code:

**lib code:**
if **(!this.length)** throw Error("noUiSlider: Can't initialize slider on empty selection.");

**Here is my code:**
if **(!this)** throw Error("noUiSlider: Can't initialize slider on empty selection.");


Thank you so much for your efforts

**Comment by florescuadrian86** [comment]
Hello,
I have this error in js:
`Uncaught TypeError: Cannot read property 'destroy' of undefined
    at Object.SliderPret (app_view_produse.js:197)
    at Object.initialize (app_view_produse.js:6)
    at HTMLDocument.<anonymous> (app_view_produse.js:491)
    at e (jquery.min.js:2)
    at t (jquery.min.js:2)`

On this "if(!ajax)
				   priceSlider.noUiSlider.destroy();"
You can see here http://bucatariaromaneasca.xyz/pomi-fructiferi/1

Can you help me?

**Comment by leongersen** [comment]
@florescuadrian86  You could add `&& priceSlider.noUiSlider` to your `if` condition.

**Comment by florescuadrian86** [comment]
@leongersen This code: "if(!ajax && priceSlider.noUiSlider)
				   		priceSlider.noUiSlider.destroy();" is ok?
I am a beginner with js.

**Comment by Heri-Founder** [comment]
<img width="1387" alt="Screenshot 2020-06-22 at 12 01 32 PM" src="https://user-images.githubusercontent.com/49879491/85255391-d247f980-b47f-11ea-8a5b-ac0339167273.png">
Here Check  :

//	var priceSlider 			  = document.getElementById('price-slider'),
 
priceSlider >>> value is getting or not // here you need length 1 not 0  
priceSlider.noUiSlider >>>> if coming 1 socheck also  noUiSlider keyword

**Comment by florescuadrian86** [comment]
@Heri-Founder Now, change code to `if(!ajax && priceSlider.noUiSlider)
				   		priceSlider.noUiSlider.destroy();` 
It's ok?

**Comment by Heri-Founder** [comment]
@florescuadrian86 if(!ajax && priceSlider) yes but if you are face again issue so you can add one more line.

**Comment by florescuadrian86** [comment]
Don't work. Issue persist..
