### ISSUE TITLE
Number of pips

### ISSUE THREAD

**Issue by wirk** [leongersen/noUiSlider#357]
First off, thanks a lot for this really awesome slider.

I've created a slider to select a time slice such as 5 seconds or 1 hour. The slider increments in integer steps where 1 = 5seconds, 2 = 10seconds ... 11=55seconds, 12=1minute etc.

I'm using formatters to convert between slider steps and readable formats ("2 hours") as well as to convert them to seconds which are written to an input field.

I'm also using the pips plugin in values mode with `stepped = true` and `density = 1` and a few specific pips defined such as 1 hour, 1 day etc. I was expecting to have one pip on the scale for each slider step. However, I'm getting a few extra pips (I'm talking about lines without a number). My assumption is that the specific pip values increase the number of pips, because if I increase the density to about 1.15, it works out fine.

I have created a Fiddle to illustrate the problem. This one starts at 3 minutes (controlled by the min and max attributes (in seconds) of the hidden text field). Note how the number of steps between two named pips is lower than the number of lines therein. I hope you understand what I mean?

http://jsfiddle.net/038dzqeL/3/

**Comment by nehaKeskar** [comment]
Hi , I want to display date instead of time, can any one help me please.
