### ISSUE TITLE
Feature: Range without overlapping handles. 

### ISSUE THREAD

**Issue by Montago** [leongersen/noUiSlider#364]
Currently if you specify Margin:0 the handles will overlap 

this is a problem on most devices, because you don't know which handle you will interact with when beggining to slide. 

I propose a fix / optional setting, that fixes this:
MarginZeroNoOverlap: true //feel free to invent a better name :)

What this will do, is to offset the handles from their centered position, to Right-positionend and Left-positioned respectively ... Thereby the space between the handles can be zero width, without overlapping the handles.

**Comment by mg1075** [comment]
?

Is there a working example of the proposed solution?

**Comment by Montago** [comment]
I tried and failed, so we let our designer / ux people to do it...

i just tried again at jsFiddle, and its not pretty: http://jsfiddle.net/Montago/ds53e36u/
