### ISSUE TITLE
Custom pip labels

### ISSUE THREAD

**Issue by bignickolson** [leongersen/noUiSlider#370]
Is it possible to customize the pip labels?  For instance, using 'positions' mode I'd like the pips to actually display the percentage as the label and not the value at that point.

**Comment by glendlockhart** [comment]
This would be great. I am using the system for times in 1 day and it would be cool to set labels for Midday, Midnight, 9pm etc

**Comment by leongersen** [comment]
After creating the pips, you can of course use jQuery to change their content. I'd like to see API examples of how this feature would work if that is too complicated.

**Comment by glendlockhart** [comment]
Thanks for the message. 
I have undertaken a more brutal direct route and gone for a look up in the addMarking function. 
G

**Comment by bignickolson** [comment]
You can also provide an object that has the shape of the wNumb formatter { to: function(){} } and do your formatting there

**Comment by sv1979** [comment]
I had to change values to custom, from 500k to 10M. How I did it: 	

        $('#slider-tooltip').noUiSlider_pips({
		mode: 'values',
		values: [500000,1000000,3000000,5000000,10000000],
		density: 4
	});

	$('.noUi-value.noUi-value-horizontal.noUi-value-large').each(function(){
		var val = $(this).html();
		val = recountVal(parseInt(val));
		$(this).html(val);
	});

	function recountVal(val){
		switch(val){
			case 500000: return '< $500 K'; break;
			case 1000000:return '$1 M';break;
			case 3000000:return '$3 M';break;
			case 5000000:return '$5 M';break;
			default :return '$10 M';break;
		}
	}

**Comment by leongersen** [comment]
That's a great way to do it. Three things:

- No need to `break` after `return`;
- Why are you converting the values to `int`, if you could `switch` the `string` value?
- Note that the current logic finds *all* pips in *all* sliders, use `find` on a single slider if that is your goal;

**Comment by landon1013** [comment]
Not sure if this is relevant to the question being asked or if you answered it already but I am new to using add-ons and am not sure on how to edit the code.  Currently I have:

 <div style="width: 80%; margin-left: 10%; margin-right: 10%;" id="pips-step4"></div><br>

    <script>


        // On document ready, initialize noUiSlider.
        $(function(){

            var range_all_sliders4 = {
                'min': [  0, 5000 ],
                '50%': [  5000, 5000 ],
                'max': [ 10000, 10000 ]
            };

            $("#pips-step4").noUiSlider({
                range: range_all_sliders4,
                start: 0
            });

            $("#pips-step4").noUiSlider_pips({
                mode: 'count',
                values: 3,
                density: 15
            });

        });

    </script>

I am trying to do something like this instead:

 <div style="width: 80%; margin-left: 10%; margin-right: 10%;" id="pips-step4"></div><br>

    <script>


        // On document ready, initialize noUiSlider.
        $(function(){

            var range_all_sliders4 = {
                'min': [  'Lots' ],
                '50%': [ 'Some' ],
                'max': [ 'None' ]
            };

            $("#pips-step4").noUiSlider({
                range: range_all_sliders4,
                start: 0
            });

            $("#pips-step4").noUiSlider_pips({
                mode: 'count',
                values: 3,
                density: 15
            });

        });

    </script>

Any help on how to make the pips have words instead of numbers would be GREAT!

**Comment by sergey-webfit** [comment]
If I understood you right, that I made what you have to do.
Change numbers to some custom strings. There are pieces of code which make magic:
After document loaded:
	$('.noUi-value.noUi-value-horizontal.noUi-value-large').each(function(){
		var val = $(this).html();
		val = recountVal(parseInt(val));
		$(this).html(val);
	});

extra function: 
	function recountVal(val){
		switch(val){
			case 0: return 'ALL'; break;
			case 500000: return '$500 K'; break;
			case 1000000:return '$1 M';break;
			case 3000000:return '$3 M';break;
			case 5000000:return '$5 M';break;
			default :return '$10 M+';break;
		}
	}
It works here: https://www.theicehouse.co.nz/businesses/

**Comment by landon1013** [comment]
Where do you put this code?

**Comment by sv1979** [comment]
Into attached js file - you can find it by provided link. First - activate slider (I did not put this piece of code here). Then 
 $('.noUi-value.noUi-value-horizontal.noUi-value-large').each(function(){
 var val = $(this).html();
 val = recountVal(parseInt(val));
 $(this).html(val);
 });

Then extra function somewhere else, place doesn't matter

**Comment by machineghost** [comment]
So the solution to using the library to show labeled pips is ... to not use the library, and use jQuery to replace the element's the library generates ... instead of just having the library generate the right elements?

Really?

**Comment by leongersen** [comment]
@machineghost This is a 4 year old issue, [formatting for pips](https://refreshless.com/nouislider/number-formatting/#section-pips) is a build in feature.
