### ISSUE TITLE
Positive/negative colored slider

### ISSUE THREAD

**Issue by willemx** [leongersen/noUiSlider#371]
I would like to make a slider that can deliver positive and negative values and I would like the slider color to change accordingly, like this:

![image](https://cloud.githubusercontent.com/assets/6051355/5056890/7588e714-6c9f-11e4-85f1-a89a6c1cff0b.png)

can this be done with the current version of noUiSlider?

**Comment by leongersen** [comment]
You can do this by adding a new element for the `connect`  option. The documentation now has an [https://refreshless.com/nouislider/examples/#section-custom-connect](example that'll help you)!

**Comment by iplaksiy** [comment]
I'm trying to create the same type of slider and after studying the docs, I still don't understand what you mean by using the `connect` option to achieve what was asked in the original question. OP was trying to create a slider which starts at 0 and then depending on which direction it moves, the fill follows it either left or right, switching colors based on the direction it is moving as it makes its way towards the edges of the bar. 

`Connect` seems to sort of represent this approach but it adds additional sliders to the bar which are both visible and movable. Furthermore, you would never be able to use the same slider to go in both directions _(past the other slider)_ when using `connect`. You would have one go one way and one the other. 

I know this question is a bit old but could you please elaborate a bit further on how `connect` aims to resolve what OP was asking about?

**Comment by leongersen** [comment]
You can pretty much disregard the previous answer, it doesn't apply anymore since the structure of the slider changed a bit to support transforms.

Basically, what I'd do to solve this issue:
- `append` a new element to the slider (a new `connect`, if you will)
- Use the [`positions`](https://refreshless.com/nouislider/events-callbacks/) argument from the `slide`/`update` events to set the `left`/`right` values for this new element

I'd be happy to help if you set up a basic fiddle.

**Comment by iplaksiy** [comment]
Yep, that's pretty much what I ended up doing last night:
https://jsfiddle.net/4e87qns6/

Any chance you could add this type of feature in a future release though? Doesn't feel right hacking it up this way, if you know what I mean.

Great library, btw! Thanks so much!

**Comment by leongersen** [comment]
@iplaksiy What API would you propose?

**Comment by iplaksiy** [comment]
@leongersen I’m on deadline at the moment, but I should free up in the next couple of days and can take a look then. I have some ideas in my head on how to go about doing it, I’ll just need to flush them out a bit once I get some time.

**Comment by leongersen** [comment]
I gave it a try too, and I got to a result using only one element and the `'update'` event:

https://jsfiddle.net/leongersen/9hyfv0bw/5/

If this fits your requirement, I'll got ahead and add this example to the docs.

**Comment by iplaksiy** [comment]
Nice! Love the approach! The bg fill while dragging is perfect, however, I just forked your version to see if we could apply the same fluid experience when tapping. In your version, the fill reaches it's destination faster than the handle when tapping.

**Comment by leongersen** [comment]
You can set `transition: width 0.3s` to match the handle. You'll have to tweak that a little to match transitions across the 50% boundary, though.
