### ISSUE TITLE
Only show tooltips on drag

### ISSUE THREAD

**Issue by washamdev** [leongersen/noUiSlider#372]
Is there a way to only show the tooltips when actually dragging one of the markers?

For instance, Kendo UI has this feature: http://demos.telerik.com/kendo-ui/slider/index

For spacing reasons, we can't show the tooltips all the time, which seems to be the only option right now, so just wondering if this is possible. Thanks.

**Comment by jhagberg** [comment]
How will this look with the latest version? 
It seems I cant get this working.

**Comment by leongersen** [comment]
You can do this entirely in CSS in the latest version. There's an example in the documentation:

https://refreshless.com/nouislider/examples/#section-hiding-tooltips

**Comment by jhagberg** [comment]
Sorry totally missed it.  Thanks for your reply!
