### ISSUE TITLE
Strange rounding / calculation issues

### ISSUE THREAD

**Issue by bramklg** [leongersen/noUiSlider#385]
I am using noUIslider to display a predefined range of byte sizes. This result in somewhat "strange" ranges because not every size fits a whole percentage exactly. I made a jsfiddle to show my problem:

http://jsfiddle.net/gem2xzke/5/

Somehow the slider alters the value resulting values that don't match the range I specify. I (have to) use byte values and want to convert them to human readable sizes myself. Because the slider alters the values I can't rely on the value from the slider.

Am I doing something wrong or is this a bug / wanted behaviour?

Edit: by looking at my jsfiddle again I see the problem only exists when the range is not a whole number (xx.xxxx%). I can work around that but I would like to know if this is considered a bug or not?

**Comment by oxomichael** [comment]
I get the same problem with a financial app (slider use to make filters) with billion and more. 
First i round up all numbers.

I have inputs to set lower and higher values, and when you want set 0 for the lower, it's replace by 3....

Example :
```javascript
$('#slider-bilHN').noUiSlider({
 start: [ -3000000000, 10000000000 ],
 range: {
  'min': [ -3000000000 ],
  'max': [ 10000000000],
 },
 step: 1,
 orientation: 'horizontal',
 behaviour: 'drag',
 connect: true,
 format: wNumb({ decimals: 0 }),
});
$('#slider-bilHN').Link('lower').to($('#slider-bilHN-selectmin'));
$('#slider-bilHN').Link('upper').to($('#slider-bilHN-selectmax'));
```

My workaround is to limit the number of digits of each filters, and register the unit to get the real values.  

Is it a way to have more than 7 digits ?

**Comment by leongersen** [comment]
Use the slider with a (much!) smaller range, and use the `format` option to scale up the value. Say, by `* 1000000`.

**Comment by leongersen** [comment]
The width of the slider simply isn't enough to represent every value between 0 and 3000000000.

**Comment by oxomichael** [comment]
Thanks for you answer, I understand the max digits for the display.
Perhaps an note could be added in the documentation.

Following your advice, i try other settings but i got again strange step, .... something i don't understand....

http://jsfiddle.net/oxomichael/bsLykamx/

```javascript
$('#slider-bilHN').noUiSlider({
 start: [ -2148, 9767 ],
 range: {
  'min': [ -2148 ],
  'max': [ 9767],
 },
 step: 1,
 orientation: 'horizontal',
 behaviour: 'drag',
 connect: true,
 format: wNumb({
  decimals: 0,
  encoder: function(value){ return value * 1000000; },
}),
});
$('#slider-bilHN').Link('lower').to($('#slider-bilHN-selectmin'));
$('#slider-bilHN').Link('upper').to($('#slider-bilHN-selectmax'));
```

**Comment by leongersen** [comment]
Merging this with #427.
