### ISSUE TITLE
Is it possible avoid a range inside the range?

### ISSUE THREAD

**Issue by spantons** [leongersen/noUiSlider#395]

**Comment by mgibbs189** [comment]
Could you elaborate?

**Comment by spantons** [comment]
Suppose that I have a range from 1 to 100, but at some point I want to exclude other range that is within the main range for example 20 to 30 then the main range would be 1-19 and 31-100

**Comment by leongersen** [comment]
I'm closing this issue because I am not planning on implementing this feature.

I **will** accept pull requests on this issue, provided they:
- Come with unit tests
- provide some form of documentation (I'd be willing to help formalize/improve it)
- Match the overall API style of the library
