### ISSUE TITLE
Is it possible to set the slider to have a diffrent colour in each section?

### ISSUE THREAD

**Issue by ChrisMcIntoshNZ** [leongersen/noUiSlider#396]
I want to set the color to the left of the lower handle another between the hadles and a third to the right of the higher handle. How would I go about doing that?

**Comment by darkwebdev** [comment]
short answer:
.noUi-base, .noUi-background, .noUi-connect

example here:
http://stackoverflow.com/questions/27848780/how-can-i-set-the-slider-to-have-a-diffrent-colour-before-the-first-handle-betw/28028370#28028370
