### ISSUE TITLE
Typescript definition file

### ISSUE THREAD

**Issue by kasperoo** [leongersen/noUiSlider#398]
Hi,
fantastic plugin! I'm using it in my typescript project, would it be possible for you to create a definition file? I've mocked something simple just for myself so my code compiles, but would be great to have this done properly.

Example of definition files:
https://github.com/borisyankov/DefinitelyTyped

**Comment by leongersen** [comment]
I won't be adding this, since I can't possibly support *every* project out there. Feel free to make a pull request, though.
