### ISSUE TITLE
Choppy animations

### ISSUE THREAD

**Issue by robertmain** [leongersen/noUiSlider#400]
I've noticed that if I have a few of these on a page and I'm moving them programatically (with Angular) that the animations are quite choppy. 

Anyone know where to start debugging this?

**Comment by leongersen** [comment]
Are you moving multiple sliders at the same time? You can set `animate` to `false`, btw.

**Comment by robertmain** [comment]
Yes I am. Setting animate to false helps but the problem is still there.
I'm not sure if it's a browser issue though..

On Thu, Jan 15, 2015 at 1:07 PM, Leon Gersen <notifications@github.com>
wrote:

> Are you moving multiple sliders at the same time? You can set animate to
> false, btw.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/leongersen/noUiSlider/issues/400#issuecomment-70082821>
> .
>



-- 
Regards

-Robert Main

**Comment by scrobbleme** [comment]
Seems that this occurs when the moving is triggered externly, but multiple times fastly consecutively, for instance on a mouse move event, which triggers a slider move.

**Comment by robertmain** [comment]
Yeah, the jank happens if I move the slider programmatically as well.

**Comment by leongersen** [comment]
Can you set up a jsfiddle?

**Comment by scrobbleme** [comment]
@leongersen I think this will show it: http://jsfiddle.net/bxz3osL7/1/

(Btw. I've tried to contact you via Facebook some weeks ago, per private message)

**Comment by leongersen** [comment]
I'm not at all surprised that code is slow. Why do you need to update the slider on mousemove? It invalidates noUiSlider's touch support. Even if there is a good reason for this, you'll need to [debounce](http://davidwalsh.name/javascript-debounce-function) the event.

(Facebook has no notifactions for messages from 'others', and I keep missing them. Sorry about that!)

**Comment by robertmain** [comment]
Well I can't speak for anyone else, but I'm using it to build a lighting
control board which has "scenes". Therefore, I need to move the slider
programmatically.

**Comment by scrobbleme** [comment]
Debounce is nice, but not exactly what is wanted here, as this also defers the moving. Maybe some tweaks to the example will do it. 
In combination with animate:false it even makes the effect more worse.

**Comment by leongersen** [comment]
Mousemove fires *way* too often to set the slider every time. You aren't going to get this to be fast. On top of that, calls to [offset() are slow](http://jsperf.com/offsettop-and-offsetleft-vs-jquery-s-offset/5), while you don't even need them. Getting the delta for `event.pageX` would do. (`previousPageX - currentPageX`). Try fixing that and debounce for ~40ms.

**Comment by scrobbleme** [comment]
Thanks,
What I wanted was a "throttle" and not a "debounce". Without animation and some throttling it works much better, at least for my usecase: http://jsfiddle.net/bxz3osL7/7/

(@leongersen Still waiting for your reply on FB ;) I wanted to send you some donation for noUiSlider. If you have an IBAN and BIC, you may also just send this data to adrian [at] adrian-moerchen.de)
