### ISSUE TITLE
Pips Add-On overlapping bottom of slider

### ISSUE THREAD

**Issue by Z33** [leongersen/noUiSlider#401]
The Pips add-on is overlapping the bottom section of the slider. It's keeping the user from dragging the knob if they don't click an exact area. I noticed this on my own local copy but found that the same is happening on the live site: http://refreshless.com/nouislider/pips/ 

I may not have explained it thoroughly but if needed I can send a video to show an example.

**Comment by leongersen** [comment]
Hmm, you are right. I hadn't noticed this. Setting `.noUi-base { z-index: 1 }` fixes the issue. I'll add this when I ship a new version. Thanks for the report!

**Comment by leongersen** [comment]
Fixed!
