### ISSUE TITLE
How would I set soft limits on a two-slider range?

### ISSUE THREAD

**Issue by allenwlee** [leongersen/noUiSlider#402]
http://refreshless.com/nouislider/examples/#section-soft-limits

**Comment by leongersen** [comment]
By checking both values for the limits:

[Example](http://jsfiddle.net/leongersen/L5ynppvy/).

**Comment by markanthonyuy** [comment]
Any updates on this? Example seems to be broken. Thanks!

**Comment by leongersen** [comment]
The example doesn't run because it references a newer, non-jQuery version of noUiSlider. The `set` code is valid, though.
