### ISSUE TITLE
Incorrect documentation - triggering 'set' event on .val() is no longer optional

### ISSUE THREAD

**Issue by oldboyxx** [leongersen/noUiSlider#403]
Documentation:
> SET event
> Whenever a slider is changed to a new value, this event is fired. This function will trigger every time a slider stops changing, **optionally** even on calls to the .val() method. Because this creates the hazard of an infinite loop, **any .val() call will have to explicitly request this event**. You can consider this 'end of slide'.

Source code:
> // Fire the 'set' event. As of noUiSlider 7,
> // this is no longer optional.
> fireEvents(['set']);

I'm also wondering why this feature was removed...

For anyone else needing a replacement you can do something like this:

Before it was:
```javascript
slider.on("set", doSomething)
slider.val(val, set: true)
```
Change it to:
```javascript
slider.on("change setVal", doSomething)
slider.val(val).trigger("setVal")
```

**Comment by leongersen** [comment]
Fixed. This was removed to simplify the API (all other `.val()` modifiers where replaced, too). As you've shown, sensible alternatives are available.

Additional arguments to `.val()` where also rather unintuitive.
