### ISSUE TITLE
IPad, slider in scrollable element, not responsive

### ISSUE THREAD

**Issue by Bohdan-Anderson** [leongersen/noUiSlider#405]
My main window is scrollable, the slider is contained within this element. On all other platforms the slider works, perfect.

When the element is moved out of the scrollable parent the slider functions correctly.

Any one have a similar experience with these elements, I'm thinking it has to do with how this particular IPad deals with touch events.

The IPad is
 * os version 7.0.4
 * IPad 2 (2012)
 * Safari

**Comment by Bohdan-Anderson** [comment]
Sorry, Just found a solution that does not require me to move the element...
 > -webkit-overflow-scrolling: touch; 
 > -moz-overflow-scrolling: touch; 
 > -ms-overflow-scrolling: touch; 
 > -o-overflow-scrolling: touch; 
 > overflow-scrolling: touch; 
by removing this from the element it allowed the slider to be selectable. But then I also lose the nice scrolling...

**Comment by fromvega** [comment]
Hi Bohdan, I was having the same problem as you but there is a work around. Please check this:
http://stackoverflow.com/questions/18736297/webkit-overflow-scrolling-touch-broken-for-initially-offscreen-elements-in-i
