### ISSUE TITLE
slidestop event not firing when mouse outside slider

### ISSUE THREAD

**Issue by shaunakv1** [leongersen/noUiSlider#407]
I am referring to this issue logged with jQuery here.. What I am seeing with no-ui slider is exactly the same problem. 

http://bugs.jqueryui.com/ticket/7992

In my case, I have the slider over a leafletjs map. If I start dragging the slider and then without letting go the mouse click , move the mouse to the map (out of the div, that has slider) and leave the mouse click, the slider never registers this mouseup.  Now if I move the mouse back in the slider div, it moves with the mouse back and forth without needing to drag..

**Comment by ijon57** [comment]
Confirm this issue for me. It happens only with 'slide' event, 'set' and 'change' work as expected.

**Comment by leongersen** [comment]
Merging with #418.
