### ISSUE TITLE
Expose start() and end() to external scripting.

### ISSUE THREAD

**Issue by gruns** [leongersen/noUiSlider#408]
Because mouseup events are lost in iframes. To reproduce, go here

  http://jsfiddle.net/x4f4fLs4/5/

and

  1. Click (mouse down) on the left slider handle.
  2. Drag the cursor left, into the iframe, and release (mouse up).
  3. Move the cursor back into the page. The left handle is vertically stuck to
     the cursor. noUiSlider thinks the mouse click is still down.

A hacky workaround is to call end() when the cursor enters an iframe, like

```
$('iframe').mouseenter(function() {
  slider.end();
});
```

This isn't possible if `end()` isn't exposed. Please expose `end()`.

**Comment by leongersen** [comment]
Sounds good. What'd you need `start()` for?

**Comment by gruns** [comment]
Symmetry.

Every action should be reversible, if possible. end() is reversed with start().

**Comment by gruns** [comment]
Any progress?

**Comment by leongersen** [comment]
No. I'll include this in a next update, but I haven't gotten around to it, yet. Replacing `slider.end();` in your example by `$(document).trigger('mouseup')` would be a good workaround.

**Comment by gruns** [comment]
`end()` and `start()` remain inaccessible to external scripting in the latest v8.3.0 .The original iframe problem, and other related problems, remain unsolvable.

Please expose `end()` and `start()` to external scripting.
