### ISSUE TITLE
Possible to control the animate speed?

### ISSUE THREAD

**Issue by bearstar** [leongersen/noUiSlider#409]
Sorry if this is obvious, but is it possible to slow down the animation speed?

**Comment by leongersen** [comment]
Yes: change the value (currently `0.3s` in the stylesheet [here](https://github.com/leongersen/noUiSlider/blob/master/src/jquery.nouislider.css#L47).

**Comment by bearstar** [comment]
Fantastic. Thank you very much. Great tool, btw.
James

--------------------------------
James Alborough
907-766-2082
