### ISSUE TITLE
How to allow a maximum selection of 5 in double range slider?

### ISSUE THREAD

**Issue by aaeda** [leongersen/noUiSlider#410]
hello

I wanted to know if it is possible to limit the selection from say for example , 1 to 5 when selection a range.
I am using the code below, but I can actually select more than 5 years.
$("#drag-fixed").noUiSlider({
	start: [ 2000, 2005 ],
	step: 1,
	behaviour: 'drag',
	connect: true,
	range: {
		'min':  2000,
		'max':  2015
	},
	format: wNumb({
		decimals: 0
	})
});

thanks a lot
Aaeda

**Comment by leongersen** [comment]
You'll want the [`limit`](http://refreshless.com/nouislider/slider-options/#section-limit) option for this!

**Comment by aaeda** [comment]
Yes that's works perfect ! thanks a lot
