### ISSUE TITLE
Animate the value in the tooltip?

### ISSUE THREAD

**Issue by bearstar** [leongersen/noUiSlider#411]
When I move the handle manually, the tooltip value changes dynamically.
However, when using animate, the end value gets populated from the start. Is there a setting to make the tooltip count up during an animation?

**Comment by leongersen** [comment]
The animation is pure CSS: animating the handle in JS would be rather slow. You could just `.val()` the slider in increments, if you *really* want to.

**Comment by bearstar** [comment]
OK, understood. Follow on question: my slider has a value from 1-11 Million. I noticed that when I manually drag the handle, it is respecting the decimal wnumb formatting only on the 100's. Every number inbetween is getting about 5 decimal places. Ever seen that?

**Comment by leongersen** [comment]
Do you have a code sample?

**Comment by bearstar** [comment]
Hi Leon,
You can see it here (it’s running on Drupal and uses the built-in jquery 1.7)

http://www.hexiscyber.com/dashboard-test-0

code pasted below:

<div id="frame">

<div class="panel">
<button id="set-sliders">Threats found by Hawkeye G</button>

<div id="slider-direction" class="sliders noUi-base noUi-ltr noUi-horizontal noUi-background">
<div class="noUi-origin noUi-stacking" style="left: 100%;">
</div>
</div>
</div>

<div class="panel">
<button id="set-sliders2">Customer Savings</button>

<div id="slider-direction2" class="sliders2 noUi-base noUi-ltr noUi-horizontal noUi-background">
<div class="noUi-origin noUi-stacking" style="left: 100%;">
</div>
</div>
</div>

<div class="panel">
<button id="set-sliders3">Malware Missed by Others</button>

<div id="slider-direction3" class="sliders3 noUi-base noUi-ltr noUi-horizontal noUi-background">
<div class="noUi-origin noUi-stacking" style="left: 100%;">
</div>
</div>
</div>



<div id="scrollerWrapper">

<script type="text/javascript">
(function ($) {
$(document).ready(function(){
    var speed = 4;
    var items, scroller = $('#scroller');
    var width = 0;
    scroller.children().each(function(){
        width += $(this).outerWidth(true);
    });
    scroller.css('width', width);
    scroll();
    function scroll(){
        items = scroller.children();
        var scrollWidth = items.eq(0).outerWidth();
        scroller.animate({'left' : 0 - scrollWidth}, scrollWidth * 100 / speed, 'linear', changeFirst);
    }
    function changeFirst(){
        scroller.append(items.eq(0).remove()).css('left', 0);
        scroll();
    }
});
}(jQuery));
</script>
<ul id="scroller">
<li>Currently HawkEye G is deployed in several different industries with multi-tiered security solutions. In 100% of these deployments, our solution found malware on-site, beaconing out and hostile files on disk. Our leading HSOC analysts are researching issues and providing clients with deeper insight to the data.</li>
<li>HawkEye G collected forensic data on 5,277 Windows devices regularly.</li>
<li>HawkEye G analyzed over 11 million files every day.</li>
<li>HawkEye G observed malware-related Web traffic a total of 27,270 times over the past 90 days.</li>
<li>HawkEye G identified 207 files as malicious.</li>
</ul>
<div id="scrollerbutton"></div>
</div>

</div>


<script src="/scripts/slider/jquery.nouislider.all.js"></script>
<script src="/scripts/slider/wNumb.min.js"></script>
<link href="/scripts/slider/jquery.nouislider.css" rel="stylesheet">
<script>
(function ($) {
			 // On document ready, initialize noUiSlider.
$(function(){

$('#slider-direction').noUiSlider({
start: 0,
direction: "ltr",
connect: "lower",
step: 1,
animate: true,
	range: {
		'min': 0,
		'max': 41002100
	},
	format: wNumb({
		decimals: 0,
		thousand: ',',
	})
});		

$("#slider-direction").Link('lower').to('-inline-<div class="tooltip"></div>', function (value) {

	// The tooltip HTML is 'this', so additional
	// markup can be inserted here.
	$(this).html(
		'<div class="bignum">' + value + '</div><div class="blurb">' + 'HawkEye G has found over 41 million instances of advanced threats getting into customer networks...and counting. These threats – which have eluded the other security measures - can then be removed by HawkEye G, preventing network compromise and saving remediation costs.</div>'
	);
});

$('#set-sliders').hover(function(){
	$('.sliders').val(41002100);
$( ".tooltip" ).show();
});

$('.noUi-handle').click(function(){
	$('.sliders').val(41002100);
$( ".tooltip" ).show();
});



$('#slider-direction2').noUiSlider({
start: 0,
direction: "ltr",
connect: "lower",
step: 1,
animate: true,
	range: {
		'min': 0,
		'max': 11209600
	},
	format: wNumb({
		decimals: 0,
		thousand: ',',
		prefix: '$',
	})
});		

$("#slider-direction2").Link('lower').to('-inline-<div class="tooltip2"></div>', function (value) {

	// The tooltip HTML is 'this', so additional
	// markup can be inserted here.
	$(this).html(
		'<div class="bignum">' + value + '</div><div class="blurb">' + 'Time is a huge factor for remediation. Speed of response is critical. Gartner and other industry experts indicate that incident response takes an average of 4 hours to investigate EACH incident and a cost of $64/hr per security ops professional. This formula does not include the actual time of removal costs since that can take weeks or months.</div>'
	);
});

$('#set-sliders2').hover(function(){
	$('.sliders2').val(11209600);
 $( ".tooltip2" ).show();

});

$('.noUi-handle').click(function(){
	$('.sliders2').val(11209600);
 $( ".tooltip2" ).show();

});




$('#slider-direction3').noUiSlider({
start: 0,
direction: "ltr",
connect: "lower",
step: 1,
animate: true,
	range: {
		'min': 0,
		'max': 728000
	},
	format: wNumb({
		decimals: 0,
		thousand: ',',
	})
});		

$("#slider-direction3").Link('lower').to('-inline-<div class="tooltip3"></div>', function (value) {

	// The tooltip HTML is 'this', so additional
	// markup can be inserted here.
	$(this).html(
		'<div class="bignum">' + value + '</div><div class="blurb">' + 'Every organization has existing hardware and software in their network. Because HawkEye G sits behind these wares, it captures malware that other solutions have misdiagnosed. As a result, this is a clear indicator that typical cybersecurity and AV solutions aren’t working properly. Our solution also captures and remediates inside threats which no other vendor can provide.</div>'
	);
});

$('#set-sliders3').hover(function(){
	$('.sliders3').val(728000);
 $( ".tooltip3" ).show();
});

$('.noUi-handle').click(function(){
	$('.sliders3').val(728000).stop();
 $( ".tooltip3" ).show();
});
			
});
}(jQuery));
</script>

--------------------------------
James Alborough
907-766-2082

**Comment by leongersen** [comment]
Ok, for future reference: when someone asks for a code sample, try to reduce it and only include the absolute minimum required code to demonstrate the issue. Try setting up a [jsFiddle](http://jsfiddle.net/), so I can change code and help debug :)

You have some problems in your code:

Your HTML should not start containing any noUiSlider elements:

```HTML
<div id="slider-direction2" class="sliders2 noUi-base noUi-ltr noUi-horizontal noUi-background">
<div class="noUi-origin noUi-stacking" style="left: 100%;">
</div>
```

Should be:
```HTML
<div id="slider-direction2" class="sliders2"></div>
```

Why are you using `.stop()`?

**Comment by bearstar** [comment]
My apologies. I consider myself schooled! 

Here is the fiddle using the cleaned up code you pointed out.
http://jsfiddle.net/bearstar/8vb6tLvn/

The part I focused on is after the animation when you drag the handle back and you see the large decimal output between the 100 hops.

Thanks,
James

--------------------------------
James Alborough
907-766-2082

**Comment by leongersen** [comment]
Great, now I can see what I'm doing!

I've further [simplified your fiddle](http://jsfiddle.net/leongersen/8vb6tLvn/2/).

The problem is caused by an older version of *wNumb*, which had a bug when using `decimals: 0`. *jquery.nouislider.all.js* already contains the latest version of *wNumb* (that's what *all* is for!), so you don't need to include it again.Removing the external file solves the problem!

**Comment by bearstar** [comment]
Much appreciated.
Thank you!

--------------------------------
James Alborough
907-766-2082
