### ISSUE TITLE
range option initialisation failed when the object order is different from min, 50%, max

### ISSUE THREAD

**Issue by solo999** [leongersen/noUiSlider#412]
I am not sure that is a bug, but it takes me an hour to realise, that I can not initialise the slider if the range option object has the following order of it's properties:
range: {
  'min': [0],
  'max': [1000],
  '50%': [100, 100]
}
it was properly set only when I make it as:
range: {
  'min': [0],
  '50%': [100,100],
  'max': [1000]
}
May be I am wrong, but because the order of object properties is not guarantied in javascript, seems it should be array, but not object, if an order should be preserved. 
Anyway this post could save some time to anyone who bump into the same issue...

**Comment by leongersen** [comment]
What version are you using? This was [fixed](https://github.com/leongersen/noUiSlider/commit/6ce02c7105fc2364ae532a9d037f8b79a1e7623c) a while back.

**Comment by solo999** [comment]
/*! noUiSlider - 7.0.10 - 2014-12-27 14:50:47 */
