### ISSUE TITLE
Whole numbers instead of numbers with decimals?

### ISSUE THREAD

**Issue by mwsasser** [leongersen/noUiSlider#413]
How do I get noUiSlider to give whole numbers instead of numbers with decimals?  I am stuck with version 6.1.0 at the moment.

**Comment by DUAB-Johan** [comment]
User wNumb and format with decimals set to 0. Se below.

        $("#slider-filter").noUiSlider({
            connect: true,
            behaviour: 'tap',
            start: [priceMin, priceMax],
            range: {
                'min': [priceMin],
                '1%': [10],
                'max': [priceMax]
            },
            format: wNumb({
                decimals: 0,
                thousand: ' '
            })
        });

**Comment by mwsasser** [comment]
That as a great idea but it didn't work with 6.1.0.  This is what I have, any suggestions?

$('#slider_<?php echo $value; ?>').noUiSlider({
    direction: (Metronic.isRTL() ? "rtl" : "ltr"),
    start: <?php echo $start_num; ?>,
    connect: 'lower',
    step: 1,
    range: {
        'min': 0,
        'max': 5
    },
    serialization: {
        lower: [
            $.Link({
                target: $("#slider_input_<?php echo $value; ?>"),
                method: "val"
            })
        ]
    }
});

**Comment by leongersen** [comment]
Is there a reason you can't upgrade to 7.0?

You could also round numbers using `math.round()`. 6.0 also has a format option, but I don't have the documentation readily available. You could have a look at the documentation repository, it'll be in there.

-----Original Message-----

**Comment by mwsasser** [comment]
Thanks for the response.  I am stuck with the current version in a pre-made bootstrap theme.  I've tried upgrading to 7 but it doesn't work because (I assume) of the custom css.  So until they upgrade to version 7, I am stuck unfortunately.  And although I am very comfortable with php, javascript & jquery aren't things I know very well.  So I appreciate the responses here.

**Comment by leongersen** [comment]
Glad you figured it out!

For reference: the documentation is [here](https://github.com/leongersen/noUiSlider-documentation). The page on number formatting for v6 is [here](https://github.com/leongersen/noUiSlider-documentation/blob/94d09754cc9c943d0a09d5d6a5bb7b2d040d9469/number-formatting.php) and it's acompanying example is [here](https://github.com/leongersen/noUiSlider-documentation/blob/94d09754cc9c943d0a09d5d6a5bb7b2d040d9469/number-formatting/format.js).
