### ISSUE TITLE
pips add-on when updating slider options

### ISSUE THREAD

**Issue by tanloverluke** [leongersen/noUiSlider#414]
hi, as per the section "Updating slider options" on the More page of your website (http://refreshless.com/nouislider/more/) I have this working perfectly EXCEPT for when I introduce the pips-addon. when I click a button to dynamically change the range, the pips bar disappears. is this a bug? I have tried this for my setup and I have tried this for the exact setup as shown on your page, no luck. Thanks.

**Comment by leongersen** [comment]
This isn't properly documented, and I'll have to fix that: using the rebuild option removes the pips, and you'll have to re-add them using `.noUiSlider_pips()`. It'd probably be better to fix it in the plugin, too, though that would complicate rebuilding logic.

**Comment by tanloverluke** [comment]
thanks for replying Leon. I tried to rebuild the pips add-on with .noUiSlider_pips() inside the click function but that didn't seem to work. I'll tread water until you're able to work on a fix. Cheers.

**Comment by leongersen** [comment]
Do you have a code sample of what you are doing now?

**Comment by tanloverluke** [comment]
Leon I was making a fiddle to show you and for some reason it worked this time. very strange indeed but thanks for your time. I can confirm in fact that the pips add-on does work when updating slider options. great script!
