### ISSUE TITLE
Mobile left to right gesture goes back to previous page when moving slider

### ISSUE THREAD

**Issue by homerocavazos** [leongersen/noUiSlider#415]
Is there a solution for mobile browsers registering the left to right swipe? As it is, even the homepage example for noUiSlider has the issue. Basically when I move the slider to the right, the browser registers the gesture as a back button.

Is this a known issue or is there a solution for it?

**Comment by leongersen** [comment]
Those gestures can be tricky. What browser, what device?

**Comment by homerocavazos** [comment]
Chinese 360 and Baidu browser on Android devices. I tested other sliders like jQuery's mobile version and all have the same issue. I am concluding that its a built-in setting for that browser on that device. Unfortunately the site is in Chinese and for that audience. :-)

It's not an issue if one drags slowly.

Thanks for the quick response.

**Comment by homerocavazos** [comment]
BTW, this slider is the best. Really appreciate you creating it.

**Comment by leongersen** [comment]
I reported something similar to Chrome once, with a workaround. You could [have a look](https://code.google.com/p/chromium/issues/detail?id=369982).
