### ISSUE TITLE
Specify thousands and decimal separators

### ISSUE THREAD

**Issue by otmezger** [leongersen/noUiSlider#416]
Hi, 

I'm starting to love this code, it's so awesome!!! 

it works pretty well, except from the fact that I need to specify the thousands separator in the pips. So, instead of `10000.00` I need to have `10.000,00`. 

Is there a way in doing so?

thanks

**Comment by leongersen** [comment]
Yes! You can use `format`, and pass a `wNumb` instance. See this (example](http://refreshless.com/nouislider/pips/#section-steps) and [all options](http://refreshless.com/wnumb/options/).

**Comment by otmezger** [comment]
WOOOOO. just amazing. You really rock! 

Thanks.
