### ISSUE TITLE
Handle stays active after drag

### ISSUE THREAD

**Issue by Clonk801** [leongersen/noUiSlider#418]
I am having an issue with my vertical slider that when I drag the handle and while it is animating to the next step I release the mouse button, the handle stays active and will follow my mouse up and down the screen. It almost has the same functionality of the snap behavior but I have mine set to drag-tap.

**Comment by Clonk801** [comment]
![screen shot 2015-03-02 at 2 59 11 pm](https://cloud.githubusercontent.com/assets/3944071/6451594/c3513694-c0ec-11e4-80ab-a9581f864a2c.png)

We were able to recreate it on that slider in the pips section but are not sure how we did it.

**Comment by Clonk801** [comment]
http://codepen.io/clonk/pen/qEydqM

here is my code

**Comment by Clonk801** [comment]
http://codepen.io/clonk/pen/qEydqM

To recreate the issue in that code pen you have to drag the slider and while your mouse is clicked move your cursor into the area where the html, css and js is and release the click. You have to do all that while it is sliding to the next step. Then go back to the slider and DO NOT click again and the slider should follow your mouse up and down the screen. 

In my site where i'm using that slider you can move your cursor anywhere.

**Comment by Clonk801** [comment]
I believe I figured out my issue. I needed to call a function of mine in change instead of slide.

**Comment by leongersen** [comment]
Releasing the mouse in an iframe doesn't propagate the event back. Workaround:

```
$('iframe').mouseenter(function() {
  slider.end();
});
```
