### ISSUE TITLE
0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'getInfo'

### ISSUE THREAD

**Issue by AbbaTheHorse** [leongersen/noUiSlider#419]
Hello, your slider looks great.

I'm trying to get your PIPS example working, as follows:

        $(document).ready(function () {
            $("#divSlider").noUiSlider_pips({
                mode: 'count',
                values: 6,
                density: 4,
                stepped: true
            });
        });

When my page loads, I get the error "0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'getInfo'" and the slider doesn't render.

I am referencing the following in the HEAD my page

jquery-1.11.1.min.js
jquery.nouislider.all.min.js

Best regards,

Abba the Horse

**Comment by leongersen** [comment]
Can you show me the code you are using?

-----Original Message-----

**Comment by AbbaTheHorse** [comment]
Hi there

Thanks for getting back so quickly.

My HEAD looks like:

<head>
    <title></title>
    <link href="/CSS/est-RIF.min.css" rel="stylesheet" type="text/css" />
    <link href="/CSS/jquery.nouislider.pips.min.css" rel="stylesheet" />

    <script src="/Scripts/jquery-1.11.1.min.js"></script>
    <script src="/Scripts/jquery-ui.min.js"></script>
    <script src="/Scripts/jquery.nouislider.all.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=geometry,places"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <script>
        $(document).ready(function () {
            $("#divSlider").noUiSlider_pips({
                mode: 'count',
                values: 6,
                density: 4,
                stepped: true
            });
        });
    </script>
</head>

My HTML looks like:

                <div id="divSlider" class="SliderWrapper">
                </div>

The error I get is:

Unhandled exception at line 3, column 17991 in http://localhost:60908/Scripts/jquery.nouislider.all.min.js

0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'getInfo'

Thanks once again,

Matt

_____________________________________________________

Matt Alexander
Senior Software Developer

Telephone:  +44 (0)1473 820040
Mobile: +44 (0) 7805 290483
Web:  www.solstice.eu.com<http://www.solstice.eu.com/>
Email: matt.alexander@solstice.eu.com<mailto:matt.alexander@solstice.eu.com>
Lync: matt.alexander@solstice.eu.com<sip:matt.alexander@solstice.eu.com>

Solstice Associates Limited
7 Seager Court, Crockatt Road, Hadleigh, Suffolk. IP7 6RL
__________________________________________________________________
Does your school need a new website? www.EasySchoolWebsite.com<http://www.easyschoolwebsite.com/>

**Comment by leongersen** [comment]
Hi Matt, You'll need to initialize a slider before calling `.noUiSlider_pips()`.

-----Original Message-----

**Comment by AbbaTheHorse** [comment]
Superb, thanks!
