### ISSUE TITLE
Slider range values are reset on postback

### ISSUE THREAD

**Issue by aaeda** [leongersen/noUiSlider#421]
Hello

I am using the range slider and asp.net and the values are reset on button postback. 
Can you please advise how this can be achieve?

Thanks
Regards
Aaeda

**Comment by leongersen** [comment]
This should help:

[noUiSlider set values on page load](http://stackoverflow.com/a/23325226/775265).

**Comment by aaeda** [comment]
Yes that helped a lot.

thanks
