### ISSUE TITLE
Angular Conversion

### ISSUE THREAD

**Issue by ehorodyski** [leongersen/noUiSlider#422]
Hello, 

I'm looking to create an Angular conversion of your slider since it's the only one I can find that meets the business requirements I require for this project. 

I'm running into some snags. There is code inside the regular slider that links up to LibLink values such as: `$Target[0].LinkIsEmitting`. There's actually an entire section named `// libLink integration`, are those events _just_ for the additional `libLink` library I want to include, or not? 

I think I can take it from there, just need to make some mental notes about the `closure` function. 

Thanks!

**Comment by leongersen** [comment]
Yes, everything in the [scope_link.js](https://github.com/leongersen/noUiSlider/blob/master/src/js/scope_link.js) section is for `libLink`. If you haven't seen it, there is [some developer documentation](http://refreshless.com/liblink/developer/) for the libLink internals.

**Comment by ehorodyski** [comment]
@leongersen 

Thank you for the help! Right now I'm just using the code as a jQuery extension and wiring it in my directive so I can get the job done, then go back and probably refactor it. Any ideas to do an Angular port yourself? 

If not, maybe what I'd like to accomplish could help out. Since Angular directives aren't run the same way that noUiSlider is now, I'd like to factor out the jQuery extension into a prototype since the code could be run more than once (because we'd be negating the whole "apply this code to all the #sliders", etc). Where I'm having trouble is nesting Spectrum prototype inside my NoUiSlider prototype. Again, something I hope I can get to!

Thanks for the response!

**Comment by leongersen** [comment]
I don't know if you continued working on this, but the new version of noUiSlider doesn't require jQuery anymore!

**Comment by ehorodyski** [comment]
@leongersen Not yet -- we had to abandon this slider for now, but it's in my plans for a future release of our project. Once that hits I'll fork this repo.
