### ISSUE TITLE
Rounding issue and decimals 0 has no effect

### ISSUE THREAD

**Issue by axelf** [leongersen/noUiSlider#423]
Hi,

There is an rounding issue with the following code:

    $("#slider-price").noUiSlider({ 
        range: { min: 120, max: 700 }, 
        start: [120,700],
        step: 5,
        connect: true,
        format: wNumb({decimals: 0})
    });
    $('#slider-price').Link('lower').to($('.price-value-lower'),null,wNumb({prefix: 'min ',postfix: ' &euro;'}));
    $('#slider-price').Link('upper').to($('.price-value-upper'),null,wNumb({prefix: 'max ',postfix: ' &euro;'}));
 
I get values of 180.00000001 or 199.99999997 but it should be 180 and 200. 
Here is an example to see it in action: http://jsfiddle.net/axelf/8py24rm4/

**Comment by leongersen** [comment]
Setting a formatter for a `Link` overrides the formatting options on the slider itself. [Set `decimals: 0` on the `Link`](http://jsfiddle.net/leongersen/8py24rm4/2/) to get decimals formatting there, too. In your case, the `format` option *does* apply to `.val()`.

**Comment by axelf** [comment]
Thank you for the explanation.
