### ISSUE TITLE
Events going crazy when slider rebuild (true parameter)

### ISSUE THREAD

**Issue by albertovivar** [leongersen/noUiSlider#424]
Hello, ok, this is the case:

1.- I was getting the error 'Uncaught Error: Slider was already initialized' when my code reuses the slider.

2.- Reading here, I applied the suggested code here (true parameter): $( "#slider-test_1" ).noUiSlider( options, true /* Allow destruction + rebuilding */ );

3.- Ok, no error now, but the problem its that 'set' event defined below is firing multiple times and ascending (each time I rebuild and operate the slider) Here is my code:

function getPrecio(resp, modelo, medida) {

	$('#slider').noUiSlider({
		animate: true,
		connect: 'lower',
		start: resp.value,
		step: resp.step,
		direction: 'ltr',
		orientation: 'horizontal',
		behaviour: 'tap-drag',
		format: wNumb({
			mark: ',',
			decimals: 0
		}),
		range: {
			'min': resp.min,
			'max': resp.max
		}
	}, true);

	$('#slider').Link().to($('#slider-input'));

	$('#slider').noUiSlider_pips({
		mode: 'positions',
		values: [0,25,50,75,100],
		density: 4,
		stepped: true,
		format: wNumb({
        		decimals: 0,
        		postfix: 'u'
        	})
	});

	$("#slider").on({
		set: function(){
                     console.log('set');

		}
	});

}

**Comment by leongersen** [comment]
Just move the event binding out of the re-initialization loop.

**Comment by albertovivar** [comment]
tested and sorry but there was no luck: even defining only once the event, the event keeps firing multiple times and ascending. this is the test:



function getPrecio(resp, modelo, medida) {
	$('#slider').noUiSlider({
		animate: true,
		connect: 'lower',
		start: resp.value,
		step: resp.step,
		direction: 'ltr',
		orientation: 'horizontal',
		behaviour: 'tap-drag',
		format: wNumb({
			mark: ',',
			decimals: 0
		}),
		range: {
			'min': resp.min,
			'max': resp.max
		}
	},true);

	$('#slider').Link().to($('#slider-input'));

	$('#slider').noUiSlider_pips({
		mode: 'positions',
		values: [0,25,50,75,100],
		density: 4,
		stepped: true,
		format: wNumb({
        		decimals: 0,
        		postfix: 'u'
        	})
	});

    if (!$._data($("#slider")[0], "events")){
		console.log('was not defined, now is defined');
		$("#slider").on({
			set: function(){
                              console.log('set');
			}
		});
    }else{
     	console.log('was already defined! skipping');
    }

**Comment by leongersen** [comment]
Can you set up a [jsfiddle](http://jsfiddle.net/) that show's what you are doing? I'd be happy to have a look, but it's tough to look at the current snippets and see the whole structure.

**Comment by albertovivar** [comment]
Hello, here http://jsfiddle.net/fuztteg9/8/
sorry i dont know how to use fully jsfiddle, but the problem can easily reproduce. The 'true' parameter is not doing the anounced 'destruction + rebuilding', because the events continues there and rebulding the slider causes multiple set event fire.   This part of code check the event, for you to see, even deplacing once the event, it displays multiple set in log each time i operate the slider:

 if (!$._data($("#slider")[0], "events")){
        console.log('was not defined, now is defined');
        $("#slider").on({
            set: function(){
                  console.log('set');
            }
        });
    }else{
        console.log('was already defined! skipping');
    }
