### ISSUE TITLE
drag feature with limit

### ISSUE THREAD

**Issue by BernardA** [leongersen/noUiSlider#425]
Hello
I am using jquery-ui RANGE SLIDER today, which has all features I need.

Unfortunately it is not touch friendly, so I am now forced to deactivate the slider on mobile.

noUiSlider seems to have all features, except the ability to drag the handles on limit, ie, if you are, for instance,  moving the upper handler and reaches the limit, you should be able to continue your movement and the lower handle  would be dragged along, keeping the set limit value.

I found that it can drag, but according to the initial values, which is not practical. 

Did I miss something?

Pls. advise. 

Regards
Bernard

Pls. visit https://www.soeezauto.ma for the current jquery-ui installation

**Comment by leongersen** [comment]
This combination of features is unfortunately not available (seems like a good addition). The `limit` option, in combination with `behaviour: drag` is close (see [this example](http://refreshless.com/nouislider/slider-options/#section-limit)).

**Comment by mg1075** [comment]
+1. This functionality would be a good addition.

**Comment by silverhammermba** [comment]
A similar feature would allow dragging when you hit the lower limit (i.e. 0). So if you move the upper handle past the lower handle, it drags both handles together.

**Comment by lkrombeen** [comment]
You can currently do this as follows. However, the set function is too slow to give a nice animation:

```
<script>
    var limit = --your limit goes here--,
        slider = --your slider goes here--;

    noUiSlider.create(slider), {
        connect: true,
        animate: true,
        margin: 1,
        start: [0 , 1],
        behaviour: 'snap-drag',
        step: 1,
        range: {
            'min': 0,
            'max': 100
        }
    });

    slider.noUiSlider.on('slide', function( values, handle ) {
        if (values[1] - values[0] > limit) {
                if (handle) {
                    slider.noUiSlider.set([parseInt(values[1]) - limit, null]);
                } else {
                   slider.noUiSlider.set([null, parseInt(values[0]) + limit]);
                }   
            }        
    });
</script>
```

**Comment by MathieuDR** [comment]
I found the solution to the bug before:

At "attachEvent" there is a snipper
`// Stop if an active 'tap' transition is taking place.
if (hasClass(scope_Target, options.cssClasses.tap)) {
	return false;
}`

This will block the tap transitions, however in touch when it's moving (duo to set) it will be in this 'tap transition' and block any events. Even the 'touchend' transition.

To solve this bug I've added to the if statement:
`// Stop if an active 'tap' transition is taking place.
if (hasClass(scope_Target, options.cssClasses.tap) && e.type !== "touchend") {
	return false;
}`

I might make a pull request to fix this issue. Greetings.

**Comment by leongersen** [comment]
@MathieuDR I think we could make this a little more robust by never rejecting any end event for the "tap is active" reason. Similarly, I think this issue could occur if the slider was disabled (for whatever reason) on the `start` event.

**Comment by leongersen** [comment]
We could add a `doNotReject` property to the `data` argument for `attachEvent`. `endEvent` and `outEvent` could activate this parameter.
