### ISSUE TITLE
format issue with basic range slider

### ISSUE THREAD

**Issue by jamez14** [leongersen/noUiSlider#426]
I've searched around the various issues here and on stackoverflow but was not able to find a suitable solution. I've created a [jsFiddle](https://jsfiddle.net/jamez14/st61kpse/1/) showing my issue.

I'm using the **all** plugin with jQuery 1.11.2. What I am having trouble with is using `format` along with `Link`. I have a price range slider with a min & max range that I want to be formatted with a dollar sign in front. My basic plugin code looks like this:

```
$('#price-range').noUiSlider({
    start: [20, 100],
    step: 1,
    connect: true,
    range: {
        'min': [20],
            'max': [100]
    },
    format: {
        to: function (value) {
            var returned = '$' + value;
            console.log(returned);
            return returned;
        },
        from: function (value) {
            var returned = '$' + value;
            console.log('returned2: ' + returned);
            return returned;
        }
    }
});


$('#price-range').Link('upper').to($('.max-price'), 'html');
$('#price-range').Link('lower').to($('.min-price'), 'html');
```

and my HTML is simply:
```
<div class="uislider-wrap">
    <div class="noUiSlider" id="price-range"></div>
</div>

<div class="min-max-price"> 
    <span class="min-price"></span>
    <span class="max-price"></span>
</div>
```

On initialization of the plugin, what is displayed in the `.max-price` and `.min-price` `<span>`'s is `$undefined`. I then put some log messages within the `format` option and I see that the `format` option is being called 5 times total between the `to` and `from` functions. This obviously means it is trying to format the values multiple times for some reason, even before I touch the slider. You'll also notice the slider's `start` position is not correct.

If I leave the `format` option out then everything works as expected. 

With all that being said, I am not sure if this is a "user error" or possibly something with the plugin (less likely I'm sure). Any assistance in the right direction would be great.

**Comment by leongersen** [comment]
You are returning a string from both `to` and `from`, while one method should encode (add the `$`) and the other should decode (return a number). Anyway, since you are using the *all*  file, you've got the `wNumb` formatter included. You can use that, as [this updated fiddle](https://jsfiddle.net/leongersen/st61kpse/2/) shows.

Does that help?

**Comment by jamez14** [comment]
Yes, that worked perfectly @leongersen. Thanks! I didn't realize `wNumb` was included with that file and the explanation of how the `to` and `from` work helped out as well. Thanks again.
