### ISSUE TITLE
accurateNumber() Causes Inaccurate Numbers

### ISSUE THREAD

**Issue by J-Griffin** [leongersen/noUiSlider#427]
Because of javascript number handling quirks, the rounding done in the accurateNumber function can cause slightly bad values to come back. Note that this is probably the same problem as in Issue #385.

For a simplified example of this issue, run this in console

```javascript
    // Expect 1.01, but get 1
    Number((Math.round(1.005*100)/100).toFixed(2));
```

This is happening to us for some values. The end effect is that we are prevented from reaching our "Max" value when the slider is at 100%.

A second effect is that some larger values actually lose fidelity even though they have no decimals at all. Try this:

```javascript
    // Expect same number back, but actually get
    //             8301034833169289000  
    accurateNumber(8301034833169290000);
```

A way to fix this is to avoid using math to do the shifts.

```javascript
    // Get 1.01 as expected
    Number(parseFloat(Math.round(1.005 + "e+2")+"e-2").toFixed(2));
```

Some stackoverflow references
- http://stackoverflow.com/a/18358056
- http://stackoverflow.com/a/21323513

A complete solution is pretty dirty, but looks something like this:

```javascript
    // Rounds a number to 7 supported decimals.
	function accurateNumber(number) {
	    var shiftedNumber = shiftNumber(number, 7);
	    var roundedShiftedNumber = Math.round(shiftedNumber);
	    var roundedNumber = shiftNumber(roundedShiftedNumber, -7);
        return Number(roundedNumber.toFixed(7));
	}
    // Shift numbers. Handle numbers even if they already have an exponent.
	function shiftNumber(number, places) {
	    var splitNumber = number.toString().split("e");
	    var numberPart = splitNumber[0];
	    var currentExponent = splitNumber[1] ? parseInt(splitNumber[1]) : 0;
	    var newExponent = currentExponent + places;
	    return Number(numberPart + "e" + newExponent);
	};
```

Let me know what you think. I can submit a PR if you want to fix this.

**Comment by leongersen** [comment]
Ah, floating point. Always fun. Any reason we couldn't replace [`accurateNumber()`](https://github.com/leongersen/noUiSlider/blob/master/src/js/helpers.js#L20) by `return Number(parseFloat(Math.round(number + "e+2")+"e-2").toFixed(2));`?

**Comment by J-Griffin** [comment]
That mostly works, and probably a good idea if you want to avoid more complicated code. It does not work for very large numbers. 

```javascript
// returns 10.0000001 as expected
Number(parseFloat(Math.round(10.00000005 + "e+7")+"e-7").toFixed(7));

// Expect 100000000000005 or 1.00000000000005e+14
// Actual                    1.00000000000005e+21
Number(parseFloat(Math.round(100000000000005 + "e+7")+"e-7").toFixed(7));
```

This happens because shifting 7 places causes the number to always be represented with an exponent by toString(). So, the string `"1.0e+21" + "e-7" == "1.0e+21e-7"` which will not have the correct effect when re-parsed. Hence all the exponent parsing gymnastics in my original "solution".

**Comment by leongersen** [comment]
Could you help me setup a test case that demonstrates this issue?

**Comment by J-Griffin** [comment]
Sure, I should be able to get that sometime. Is calling directly against accurateNumber() acceptable, or would you like it to go through an entire end to end flow?

**Comment by leongersen** [comment]
Ideally, I'd have a slider with a 'start' setting, and a get method call that returns the wrong value.

-----Original Message-----

**Comment by utricularian** [comment]
Howdy @leongersen , why are we worried about the 7 digits of precision? Is there are reason to not let javascript play out the precision as far as it can? We're hitting problems with this code as well as its making it very difficult to guess where the percentages will be when the change event fires.

**Comment by J-Griffin** [comment]
I created pull request #504 with two new tests that demonstrate the issue.

**Comment by leongersen** [comment]
I've [added this example](http://refreshless.com/nouislider/examples/#section-huge-numbers) to the documentation discussing numbers that can't be stored as double precision floating points. I had some code in place that tried to work around it, but it got overly complicated. [This lib](https://github.com/MikeMcl/big.js/) gives an idea about working with arbitrary precision numbers.
