### ISSUE TITLE
Disable slider...

### ISSUE THREAD

**Issue by Mark-Mark** [leongersen/noUiSlider#430]
Hello,

On page:  http://refreshless.com/nouislider/more/

An example is given to disable the slider. All good. The slider changes color to indicate the slider is disabled.

Looking through the page source I do not see how the color is changed. The disable example is clear and I have that working in my code.

Can anyone point me to how the color is changed?

Thanks,

Mark

**Comment by leongersen** [comment]
Mark, the color change is defined (in the CSS)[https://github.com/leongersen/noUiSlider/blob/master/src/jquery.nouislider.css#L159].

**Comment by Mark-Mark** [comment]
Hi,

Thanks for the response.

OK. I am confused. When I disable the slider and try to move the thumb the pointer cursor changes to the not allowed image and the slider does not change. The color of the slider does not change like it does on the web pages. 

Is the slider designed to be an automatic color change or is there some code I must execute to change the slider color from normal to disabled?

Ciao,

Mark

**Comment by leongersen** [comment]
As long as the slider has the `disabled` attribute, by default it'll have the changed color. The documentation uses no code you can't see.

**Comment by Mark-Mark** [comment]
Hi,

Thanks for the response.

>by default it'll have the changed color.

Not sure what that means. So, is there some case where it will not have the changed color because, I have found that it does not change when the attribute is added. The slider is disabled but the color does not change. I have already changed the color as part of the setup, could that prevent the disable color from being applied?

Cheers,

Mark

**Comment by leongersen** [comment]
Yes, if your new rule is 1) more specific or 2) equally specific but placed after the rule in the noUiSlider stylesheet.

**Comment by Mark-Mark** [comment]
Hi,

Thanks for the response.

I made it part of the div:

<div id="D2" style="position:fixed;left:52px;top:190px;width:494px;height:10px;background-color:#0000FF"></div>

Cheers,

Mark

**Comment by leongersen** [comment]
Jup, that explains it!
