### ISSUE TITLE
Provide package on npm

### ISSUE THREAD

**Issue by mediafreakch** [leongersen/noUiSlider#433]
Hello, can you publish this great plugin/package on npmjs.com as well?
I should mention that there is already a version of the library on npm, but it is outdated: https://www.npmjs.com/package/nouislider-browser

**Comment by leongersen** [comment]
I should note, I didn't publish the package you link to. Looking at the documentation, I could probably publish noUiSlider this way, but in all fairness, the amount of of third-party systems I'm maintaining already is rather large. I'll look into it.

**Comment by Puffton** [comment]
+1, it would be great!

**Comment by Dimasdanz** [comment]
+1. Would be really great!
Or at least at main on package.json so we can "require" its name instead of full path to node_module

Thanks

**Comment by leongersen** [comment]
There is already a package named noUiSlider.

**Comment by lennerd** [comment]
For everyone, who want to use this library with `npm`, just use the Github syntax when using `npm install`:

````
npm install leongersen/noUiSlider
````

**Comment by leongersen** [comment]
Thanks, @lennerd. Consider that the 'fix' for this issue.
