### ISSUE TITLE
Initialising sliders dynamically

### ISSUE THREAD

**Issue by abtx** [leongersen/noUiSlider#437]
Hi, I'm looking for a way to initialise more sliders on the go. I'm using jQuery clone to add new sliders to the list, which I guess is causing the issue ("slider already initialised") when I try to reinitialise it. I create class name dynamically and pass it to initSlider function to initialise the new slider, trying to use destroy() on the element before passing code for noUISlider:
function initSlider(slider){
  $(slider).destroy()
  $(slider).noUiSlider({
    start: [ 15 ],
    step: 15,
    range: {
      'min': [  15 ],
      'max': [ 120 ]
    }
  });
  $(slider).Link('lower').to($('#slider-range-value'));
}
With this code, however, I get '$(...).destroy is not a function'. Any ideas how to solve this? Thanks

**Comment by leongersen** [comment]
`destroy` is a method on the DOM element, so on `slider`, not `$(slider)`.

**Comment by abtx** [comment]
so slider or Slider throw an error 'Slider is not defined'. or if I use getElementsByClassName to get the slider I want to destroy, I get 'slider[0].destroy is not a function'.

**Comment by abtx** [comment]
ok, I just cloned it before initialising noUISlider. Cheers for the plugin
