### ISSUE TITLE
Safari (iOS 7.x and 8.x) slider not working if it is very close to the page border

### ISSUE THREAD

**Issue by fguillen** [leongersen/noUiSlider#441]
When I click&drag the slider-handler to the right in an *iPhone 6 plus* the browser starts to drag the whole page and to show me the previous page making the slider not usable.

Only happen if there is a previous page in the history.

Check [jsFiddle](https://jsfiddle.net/fguillen/t3vxkwLj/embedded/result/) in an iPhone 6 plus (or simulator).

Check the screen-shot:

 ![screen shot](https://cloud.githubusercontent.com/assets/23043/7569243/c1470cb4-f807-11e4-9e18-931fbe37e686.png)

**Comment by leongersen** [comment]
Do you have a meta viewport set?

-----Original Message-----

**Comment by fguillen** [comment]
@leongersen yes, in the jsFiddle I have this: 

    <meta name="viewport" content="width=device-width, initial-scale=1">

![screen shot 2015-05-11 at 18 43 11](https://cloud.githubusercontent.com/assets/23043/7570105/d054ce16-f80d-11e4-8e21-92cc1fc75459.png)

(Injected by JS, I must say)

But in my [production case](https://surveyinterface-v2.opinionsample.com/#/surveys/8a161a60-d78f-0132-3093-0a81e8b09a82/init?publisher_user_id=07b59010-86d2-0131-c9a9-0a424708edaa&panel_user_id=PANEL_USER_TEST_6cb3d2b0-da25-0132-d566-0a81e8b09a82&panel_user_id_kind=PANEL_USER_KIND_TEST&pparam_offer_click_id=OFFER_CLICK_TEST_6cb3d2b0-da25-0132-d566-0a81e8b09a82&is_test=true), I have this:

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">

Not JS injected and the same issue is happening over iPhone 6 plus.

f.

**Comment by leongersen** [comment]
I once reported this exact bug to the chrome team. ([issue 169982](https://code.google.com/p/chromium/issues/detail?id=369982)

**Comment by fguillen** [comment]
The interesting part is that I can't reproduce the issue with the [official page of noUiSlider](http://refreshless.com/nouislider/).. so must be a solution or workaround, but I don't find it.

**Comment by leongersen** [comment]
Right. One step back: why are you using 6.2.0? 7.x is mostly compatible and has many bug fixes.

**Comment by fguillen** [comment]
Updating to `7.0.10` did not fix the issue. I tried to use the exactly same versions than in the official page of noUiSlider and the issue was still there.

But, while I was doing this I figure out why the issue is not happening in the official page: because the sliders in this page are out of the _activity zone_ for this gesture.

In the [new version of the jsFiddle](https://jsfiddle.net/fguillen/t3vxkwLj/embedded/result/) I have set up several sliders each one with a different separation from the left border.

We can see that for some of them we can't use the left handler because the safari gesture gets activate. But for the ones with wider left margin we can use the handler.

- iPhone 4s: no problem
- iPhone 5: no problem
- iPhone 5s: problems with < 60px margin
- iPhone 6: problems with < 40px margin
- iPhone 6 plus: problems with < 100px margin
- iPad: no problem

(All with iOS 8.3)

.. can we say this this a Safari bug?

**Comment by leongersen** [comment]
Yes, I think so. [Discussion on StackOverflow](http://stackoverflow.com/questions/18889666/ios-7-is-there-a-way-to-disable-the-swipe-back-and-forward-functionality-in-sa).

**Comment by fguillen** [comment]
I see.. :/ .. thanks @leongersen

**Comment by leongersen** [comment]
One thing you could try is something I talked about in relation to Hammer.js: [see this comment](https://github.com/hammerjs/hammer.js/issues/494#issuecomment-42651000).

**Comment by fguillen** [comment]
Thanks for the support @leongersen, I have fixed the issue adding a bit of extra lateral margins to the _sliders elements_ in my page. This workaround is enough for me, I can't spend more time with this. Feel free to consider this issue as _closed_.
