### ISSUE TITLE
simple request: add link to github repository on nouislider site

### ISSUE THREAD

**Issue by mg1075** [leongersen/noUiSlider#443]
Just a simple request: 
can you please add a link to the github repository on the nouislider website?

**Comment by leongersen** [comment]
It is on the [download page](http://refreshless.com/nouislider/download/)!

-----Original Message-----

**Comment by mg1075** [comment]
Sorry, guess I missed it. 

I am too used to projects having a link to the github repo on their **landing page**, either via the "Fork..." github banner or via an obivous link with a github icon.
