### ISSUE TITLE
How to make color to the left of a slider? 

### ISSUE THREAD

**Issue by nd7141** [leongersen/noUiSlider#445]
In many examples (for example [here](http://refreshless.com/nouislider/slider-options/#section-Connect)), there is a color in a bar, to the left of the slider, and white color to the right of it. How can I do it? What css class should I add to my slider?

**Comment by leongersen** [comment]
You can move the color to the other side by setting `connect: "upper"`. The class that styles the coloring is `.noUi-connect`.

**Comment by nd7141** [comment]
Unfortunately, it doesn't work.

I have in `html`: `<div id="slider-range" class="noUi-connect" type="range"/></div><br>`
and in javascript:

    $('#slider-range').noUiSlider({
		start: [ start ],
		step: 1,
		connect: "upper",
		range: {
			'min': [ 1 ],
			'max': [ 10 ]
		}
	});

But the whole bar is colored blue. I use [jquery.nouislider.min.css](https://github.com/leongersen/noUiSlider/blob/master/src/jquery.nouislider.css) (link is to not minimized version).

**Comment by leongersen** [comment]
Why are you adding the class manually? The `connect` option does that for you.

-----Original Message-----

**Comment by nd7141** [comment]
Thanks, it works!
