### ISSUE TITLE
Load noUiSlider with jQuery's each function - error

### ISSUE THREAD

**Issue by kreativwolke** [leongersen/noUiSlider#446]
I have multiple sliders on one page with different ranges. 

The Error: "Uncaught TypeError: Cannot read property 'toFixed' of undefined"

My Code looks like:
 div class="range"  id="range-01" data-rfrom="18" data-rto="70" data-rprefrom="24"  data-rprefrom="50"></div

AND JS:

    $(".range").each(function(){
    
    var el = this;
    var rangeFrom =  $(el).data("rfrom");
    var rangeTo =  $(el).data("rto");
    var rangePreFrom =  $(el).data("rprefrom");
    var rangePreTo =  $(el).data("rpreto");

    $(el).noUiSlider({
    start: [rangePreFrom, rangePreTo],
    range: {
    'min': rangeFrom,
     'max': rangeTo
    }
    });

    $(el).Link('upper').to('-inline-<div class="tooltip"></div>', function ( value ) {
      $(this).html('<span>' + value + '</span>');
    });

  });

What is wrong?

**Comment by leongersen** [comment]
I guess you figured it out, then?

**Comment by kreativwolke** [comment]
Yes

--

Mit freundlichen Grüßen
Manuel Grasse



kreativwolke
Digital- und Printmedien. Mit Leidenschaft.
———

Manuel Grasse, Chemnitzer Straße 17, 09366 Stollberg

Tel.: 03 72 96 / 97 32 40 | Mobil: 0174 / 34 30 866
post@kreativ-wolke.de // www.kreativ-wolke.de


///// Soziale Netzwerke
facebook.com/KreativWolke // twitter.com/KreativWolke

///// Rechtliches
Steuernummer: 224/225/00328 // USt-IdNr.: DE274555656 // Finanzamt Stollberg
