### ISSUE TITLE
Non linear slider breaks after using more than 9 ranges.

### ISSUE THREAD

**Issue by quamsta** [leongersen/noUiSlider#448]
Not sure if this is an error on my part or not (or if the slider is not designed to have this many ranges). When I have 9 or more ranges in the slider, all of the values get bunched in at the lower end of the slider. 
As seen here:
![screen shot 2015-05-20 at 4 41 30 pm](https://cloud.githubusercontent.com/assets/472923/7737226/27520a14-ff0f-11e4-9cd5-56535c1053a9.png)

https://jsfiddle.net/xqqp2095/1/

When I remove one of the values from the range array (doesn't matter which one), things seem to work alright:

![screen shot 2015-05-20 at 4 41 43 pm](https://cloud.githubusercontent.com/assets/472923/7737230/310ab772-ff0f-11e4-8de5-f282290ac0cd.png)

https://jsfiddle.net/xqqp2095/2/

Any ideas?

**Comment by leongersen** [comment]
Sorry for the delay, I overlooked this issue. This seems to have to do with the `step` you are using. The logic seems to have a problem with steps the same size as the ranges, I'll look into it. Are you perhaps looking for the [snap](http://refreshless.com/nouislider/slider-values/#section-snap) option?
