### ISSUE TITLE
Unable to delete decimals

### ISSUE THREAD

**Issue by albert28** [leongersen/noUiSlider#449]
Hi,

I've been struggling trying to remove the decimals from noUiSlider. I've tried:

> format: wNumb({decimals: 0 })

and:

> $('#slider_1').Link('lower').to($('#slider_1_input_start'));

> $('#slider_1').Link('upper').to($('#slider_1_input_end));

But both options didn't work. I also get this error: $(...).Link is not a function

I'm using wNumb.min.js and I inserted it in the file. My HTML is:

<div class="noUi-control noUi-warning rangestyle" id="slider_1">
																</div>
																<div class="input-group input-medium margin-top-20">
																	<input id="slider_1_input_start" type="text" class="form-control" name="from">
																	<span class="input-group-addon">
																	a </span>
																	<input id="slider_1_input_end" type="text" class="form-control" name="to">
																</div>

**Comment by leongersen** [comment]
The format option should do. Are you calling `Link` *after* `.noUiSlider()`? Also, did you include the .all file (which includes `Link`)?

**Comment by albert28** [comment]
Thank you! I was missing the .all file :)

**Comment by leongersen** [comment]
Glad it worked out :)
