### ISSUE TITLE
Unable to change values dynamically

### ISSUE THREAD

**Issue by albert28** [leongersen/noUiSlider#452]
Hi,
I've tried to change the values(min,max) from noUiSlider using this code:
>alert("before");
$('#slider_1').noUiSlider({
start: [ageMin,ageMax]
});
alert("after");

...but nothing happens. In fact, alert "after" never runs. Is it possible to change the values dynamically without rebuilding noUiSlider?

**Comment by leongersen** [comment]
As documented [here](http://refreshless.com/nouislider/slider-read-write/), use the `val` method.

-----Original Message-----

**Comment by albert28** [comment]
Thank you, it worked! :)
