### ISSUE TITLE
Slider changes values on middle/right mouse click

### ISSUE THREAD

**Issue by Fidel90** [leongersen/noUiSlider#454]
Hello,

I have come across some unexpected behaviour with noUiSlider. If i use the middle or right button of the mouse the slider changes its value. I think this is unexpected to users and should be avoided. I this can't be fixed I'll be thankfull for a nice workaround. I already tried to capture the mousedown event from outside of the plugin to stopPropagation but this doesn't work very well.

**Comment by leongersen** [comment]
Fixed in 8.0.0 :)

**Comment by Fidel90** [comment]
Thank you very much! Can't wait for 8.0.0 :)

**Comment by leongersen** [comment]
It is available right now :)

**Comment by Fidel90** [comment]
Nice. I've migrated from 7.0.9 without any problems. Thank you for the good work :+1:
