### ISSUE TITLE
Slider Issue afte 3-4 time move

### ISSUE THREAD

**Issue by cbvora** [leongersen/noUiSlider#457]
Err is like,

too much recursion
	

...d=b(a[f],f,c),null!=d&&i.push(d);return e.apply([],i)},guid:1,proxy:function(a,b...

	
jquery-1.11.0.js (line 2, col 3862)
too much recursion
	

...,f,g];h.prototype.set=function(a){var b=Array.prototype.slice.call(arguments),c=...

**Comment by leongersen** [comment]
That doesn't get me anywhere. Could you set up a [jsFiddle](http://jsfiddle.net/) demonstrating the problem?

**Comment by cbvora** [comment]
Thanks,
Pls check this.

http://jsfiddle.net/ctvxd7a7/

include css and js as follow:
<link href="css/jquery.nouislider.min.css" rel="stylesheet" type="text/css">
<link href="css/jquery.nouislider.pips.min.css" rel="stylesheet" type="text/css">
<script src="js/jquery.nouislider.all.min.js"></script>

**Comment by leongersen** [comment]
Ok! The `'set'` event fires when you call `.val()`. Use the `'change'` event instead:

http://jsfiddle.net/leongersen/ctvxd7a7/1/

**Comment by cbvora** [comment]
It's working !! Thank you
