### ISSUE TITLE
How to set exact value, when using step parameter

### ISSUE THREAD

**Issue by Tpona** [leongersen/noUiSlider#458]
Hi!
I need to use step parameter (e.g. step = 100000), but when i use some external calculation i want in the same time set exact value (e.g. 12321005).
Slider linked to text input field.
is it possible?
Thx

**Comment by Tpona** [comment]
Ok, i decided it )
Just first set value to slider then to text field.
Perfect control, thx!

**Comment by leongersen** [comment]
Ok, glad you worked it out ;)
