### ISSUE TITLE
Link to jQuery noUiSlider Documentation

### ISSUE THREAD

**Issue by rajeshtomjoe** [leongersen/noUiSlider#460]
Please provide the link to the jQuery version of the noUiSlider Documentation.

**Comment by leongersen** [comment]
I'll be back up tomorrow :)

-----Original Message-----

**Comment by leongersen** [comment]
It is available [here](http://refreshless.com/nouislider7/). For new projects, use [noUiSlider 8](https://refreshless.com/nouislider/).

**Comment by strigga** [comment]
why no jquery version any longer?
it was nicer to have everything in one function or create more sliders with one function. the .create allows only one element - not classes.
