### ISSUE TITLE
Lazy Initialization

### ISSUE THREAD

**Issue by fshowalter** [leongersen/noUiSlider#462]
Hi, I was wondering if you would be interested in supporting lazy initialization. I've been hacking it into the last few versions locally and thought it might be worth proposing.

By lazy initialization I mean pre-rendering the slider HTML and initializing the component when the user mouses/taps on one of the handles. 

Why such craziness, you ask?

Well, the pre-rendered HTML means faster load times without the layout jumps as the nodes are added to the dom. The initialization on mousedown or tap ensures that the user doesn't drag or tap before the component is initialized and has the added benefit of never initializing the component if the user never uses it. Not a big deal on desktops, but on resource constrained phones, it's nice. Mostly it makes an already light weight component nearly weightless.

The way I have it working now is that the script checks to see if the elements exist before creating them, but I could change it to take references to existing nodes. 

After a few modifications to the noUiSlider script, I included the slider HTML (which could be included in the docs) on my page, something like:

```html
<div class="noUiSlider noUi-target">
  <div class="noUi-base noUi-background noUi-horizontal">
    <div class="noUi-origin noUi-origin-lower" style="left: 0%;">
      <div class="noUi-handle noUi-handle-lower"></div>
    </div>
    <div class="noUi-origin noUi-origin-upper" style="left: 100%;">
      <div class="noUi-handle noUi-handle-upper"></div>
    </div>
  </div>
</div>
```

That, and a little event listener code, something like:

```javascript
noUiSliderElement.addEventListener('mousedown MSPointerDown touchstart', function(e) {
  e.preventDefault();

  if (!noUiSliderElement.noUiSlider) {
    noUiSlider.create(noUiSliderElement, opts..)
    setTimeout(function() { e.target.dispatchEvent(e); }, 10);
  }
});
```

Is all I had to do. I'd be happy to submit my local hacks as a starting PR, but wanted to get your thoughts first.

**Comment by knownasilya** [comment]
Yes please!

**Comment by leongersen** [comment]
Thanks for this! I'm about to go on a fairly long vacation, so I can't do anything with this *right now*. I'm very interested in the idea, though, and I think it is worth pursuing. One potential issue: won't the slider response speed drop?

**Comment by fshowalter** [comment]
I haven't noticed any decrease in responsiveness. The only real delay is the 10ms delay to re-raise the initial touch/mouse event the very first time the user interacts with the slider. I'm not sure anyone clicking/touching could notice 10ms, but even so, I suspect that number could be adjusted down. Since all the markup is already in place, all the component needs to do is wire up its event listeners. After that initial interaction, the component works as it does now.

I'll clean up my local copy and post a PR as a starting point. If you think it's a good idea, I'm sure we can get it working to your satisfaction.

**Comment by leongersen** [comment]
I'm closing this issue because I am not planning on implementing this feature.

I **will** accept pull requests on this issue, provided they:
- Come with unit tests
- provide some form of documentation (I'd be willing to help formalize/improve it)
- Match the overall API style of the library

Feel free to comment on this issue, I'll reopen if applicable.
