### ISSUE TITLE
Unresolved variable

### ISSUE THREAD

**Issue by PaparazzoKid** [leongersen/noUiSlider#464]
My code editor was reporting an 'unresolved varaible' error on line 1161 of nouislider.js and was flagging my file red, meaning angry or hungry. 

It turns out it wasn't hungry but found the unresolved variable in question was ***i***, so I changed this:

`for ( i = 0; i < data.handles.length; i++ )`

to:

`for ( var i = 0; i < data.handles.length; i++ )`

and she stopped whinging.

**Comment by leongersen** [comment]
Thanks, I'll fix this. I don't know why jsHint didn't bark on this, so I'll have to figure that out, too.

**Comment by leongersen** [comment]
Fixed! Thanks again :)

**Comment by PaparazzoKid** [comment]
Glad I could help.
