### ISSUE TITLE
Zoom feature request

### ISSUE THREAD

**Issue by denism7** [leongersen/noUiSlider#465]
Though the slider is absolutely awesome, there is one missing feature doesn't allow me replace input fields completely.
Some ranges are quite big, so one step may be less than 1px in terms of screen coordinates. So it would be very useful to shrink the range and increase precision when user tap and hold the thumb for a couple of seconds. I mean the thumb position on screen will remain the same but behavior and pips will be replaced with more precise subrange until user releases the thumb.

It's even more important for touch devices with small screens.

Thanks!

**Comment by leongersen** [comment]
There are some usability issues:

+ This is something I haven't seen on sliders before, users likely won't find this feature;
+ Range sliders shouldn't be used for exact value input. If your ranges are so large that values can't be selected, even though this is required, you might need to find an alternate solution/slider implementation;

Other than that, this'll be **very** complex to implement, so I won't be adding this to the main source.
