### ISSUE TITLE
Slider steps and pips go crazy with certain data sets

### ISSUE THREAD

**Issue by pehiv** [leongersen/noUiSlider#470]
I have a custom slider I created for selecting ram usage based .. I  noticed when my ranges are large (more steps) then pips+steps get all wonky and broken .. I tracked the issue down to the Spectrum sorting the range object like it was a number when in fact it was an array:

`		// Sort all entries by value (numeric sort).`
`		ordered.sort(function(a, b) { return a[0] - b[0]; });`

Here is my hack-job fix :)
`		// Sort all entries by value (numeric sort).`
`		ordered.sort(function(a, b) { if(typeof(a[0]) === 'object') a = a[0]; if(typeof(b[0]) === 'object') b = b[0]; return a[0] - b[0]; });`

Here is the bug in action .. (you can flip the BROKEN bool to false to see that same code function)
https://jsfiddle.net/fzm2yh85/

**Comment by leongersen** [comment]
Fixed, merged #473. Thanks -a lot- for reporting!
