### ISSUE TITLE
publish v8.x.x to npm

### ISSUE THREAD

**Issue by fhemberger** [leongersen/noUiSlider#471]
Current version on npm is still 7.x: https://www.npmjs.com/package/nouislider

**Comment by leongersen** [comment]
I haven't published that package, so there is nothing I can do to update it, unfortunately. You can always get the latest version using `npm install leongersen/noUiSlider`.

**Comment by fhemberger** [comment]
Yes, but then I can only match exact tags/commits, not semver ranges (pulling the lastest commit already broke my existing project, so I want to select a version range).

Could you please contact https://www.npmjs.com/~approach (who published the package) and ask them to hand it over to you? I think I won't be the only one running into that issue, so it would be great to get this settled at an early point in time.

**Comment by vvo** [comment]
@approached could you please give leongersen npm ownership so that we can publish npm updates?

```sh
npm owner add leongersen
```

thanks!

**Comment by approached** [comment]
@leongersen has now access...

https://www.npmjs.com/package/nouislider/access

**Comment by markoshust** [comment]
@approached great, thanks much!

@leongersen let me know when you can update npm to latest version or if you need a hand. i'm getting a nasty bug with nouislider on npm and think it may be because of the older version up there now.

**Comment by leongersen** [comment]
Updated.

**Comment by fhemberger** [comment]
Great, thanks!

**Comment by markoshust** [comment]
@leongersen Might be a good idea to mark https://www.npmjs.com/package/nouislider-browser with a deprecated notice -- noticed a lot of people are using that npm package.

**Comment by leongersen** [comment]
I don't control that package either. @kapouer, any chance you can add me as an owner to `npmjs.com/package/nouislider-browser` so I can maintain it?

**Comment by kapouer** [comment]
Good idea ! Done for both https://www.npmjs.com/package/nouislider-browser and https://github.com/kapouer/nouislider-browser
