### ISSUE TITLE
tap-drag behaviour broken

### ISSUE THREAD

**Issue by knownasilya** [leongersen/noUiSlider#472]
Using the latest version I get the following error:

> Uncaught TypeError: Cannot read property 'classList' of undefined

`connect` is set to `false` as well.

`drag[0]` is `undefined` here: https://github.com/leongersen/noUiSlider/blob/master/src/js/scope_events.js#L232

**Comment by leongersen** [comment]
`tap-drag` looks for `.noUi-connect` elements, and makes the connecting bar draggable, while allowing handles to be moved by tapping the slider. This *is* a bug, the correct behaviour would be to **throw an error** when setting the `drag` behaviour when `connect` is `false`. What are you trying to do?

**Comment by knownasilya** [comment]
It's not clear what 'drag' is, I thought it meant you can tap on the slider, and drag it. I was seeing some adverse behavior (probably unrelated) so I thought that 'drag' would help. The `behaviour` and `connect` properties both need better documentation.

**Comment by leongersen** [comment]
I've updated the docs a little. I'll add an error on incompatible options in the next release.

**Comment by knownasilya** [comment]
Nice

**Comment by skiano** [comment]
Does the label inDev mean this fix is not in npm yet?

**Comment by leongersen** [comment]
Nope, this is fixed. I don't remove labels from closed issues.
