### ISSUE TITLE
Multiple Handles on One Slider

### ISSUE THREAD

**Issue by jbownzino** [leongersen/noUiSlider#474]
I am well aware that you have no plans to support this feature.  I want to work on a plugin to make this possible with your library as I have seen a few other requests for this feature and can't find one single example. I am working on a project where I need five handles. Any chance you can point me in the right direction with getting going modifying for this feature? Thank you.

**Comment by leongersen** [comment]
Most logic already iterates over `handles.length`. You could start hacking by changing the option validation to accept more than two start values, and step through the code from there. The real work will be in `setHandle`, which checks if handles try to move past others.

**Comment by jbownzino** [comment]
thank you! working on it now.

**Comment by jamesdixon** [comment]
@jbownzino let me know if you need any help/want to collaborate on this as I need to be able to support multiple handles as well. Not sure if what you're doing is similar, but I want to be able to do something like this:

![image](https://cloud.githubusercontent.com/assets/110114/9422954/f696ec6a-4869-11e5-833a-9d09d05ff4ed.png)

**Comment by leongersen** [comment]
Merging with #592.
