### ISSUE TITLE
Add support for displaying values on hover.

### ISSUE THREAD

**Issue by jgerigmeyer** [leongersen/noUiSlider#475]
It would be great if the API exposed a "hover" event which could report the value of wherever the mouse is hovering on the slider bar. Or am I missing an obvious way to do this already?

Thanks!

**Comment by leongersen** [comment]
This is fairly tricky. You could use the [tap event](https://github.com/leongersen/noUiSlider/blob/master/src/js/scope_events.js#L176) logic to find the position.

**Comment by jgerigmeyer** [comment]
Understood. Given that the logic is already there, it's not difficult to find the location of the `hover`. Translating that percentage into the potential slider value if clicked is trickier without modifying the plugin itself. I still think this would be a worthwhile feature to add (a la the YouTube slider, where you can hover to see the time of that location in the slider), but I understand it's not a simple fix.

**Comment by JobaDiniz** [comment]
+1

**Comment by JobaDiniz** [comment]
@jgerigmeyer have you implemented this? If so, can you share?

**Comment by jgerigmeyer** [comment]
No, unfortunately I haven't had the time to dig into it and submit a PR.

**Comment by leongersen** [comment]
This is now a [new `behaviour` flag](http://refreshless.com/nouislider/behaviour-option/#section-hover). Thanks for the idea, sorry for the wait.
