### ISSUE TITLE
Showing marks on the slider range

### ISSUE THREAD

**Issue by Fidel90** [leongersen/noUiSlider#477]
Hello,

in my project it would be great if I could define and display marks on the slider. So for example I have a slider with a range from 0 to 100 and when the user goes below 20 or beyond 80 I want to show him a message or sth. But the user should be able to see these "soft limits" on the slider so he knows that something might happen if he pulls the knob towards the marks. Would be great if I could define an array of values for this in the slider options.

Thank you very much :)

**Comment by leongersen** [comment]
I'm not sure if you've seen this, but [this example](http://refreshless.com/nouislider/examples/#section-soft-limits) seems to show exactly what you are asking.

**Comment by Fidel90** [comment]
I have looked into your example but unfortunately that's not what i meant as it limits the user input. What I need are just marks on the slider that have no impact on what the user selects.

Meanwhile, as I'm using your slider in an angularJS directive, I was able to draw such marks onto the slider without changing your plugin. That's good enough for my needs at the moment but thanks anyway :)
