### ISSUE TITLE
Anywhere I can find the documentation for 7?

### ISSUE THREAD

**Issue by kenyiu** [leongersen/noUiSlider#480]

**Comment by tanloverluke** [comment]
http://refreshless.com/nouislider7/

**Comment by leongersen** [comment]
Thats it. Thanks, @tanloverluke :)

I forgot to put the link in the documentation, and I don't have SSH access right now (on vacation).

**Comment by kenyiu** [comment]
thanks @tanloverluke @leongersen 
Enjoy your time, @leongersen
