### ISSUE TITLE
drag slide does not work in Edge

### ISSUE THREAD

**Issue by lucienimmink** [leongersen/noUiSlider#482]
While testing the demo website on a surface pro with win10 I've noticed that drag & slide does not work. This same behaviour is noticed on a windows 10 mobile device (same browser).
Tapping a pip does work, but sliding does not; while it is no problem on an iPad.
Using the mouse instead of my finger the sliding does work.

Perhaps pointer-events need to be included? https://msdn.microsoft.com/en-us/library/dn304886(v=vs.85).aspx

**Comment by koenpeters** [comment]
+1

**Comment by leongersen** [comment]
NoUiSlider already uses pointer events for IE11. Did they change the spec?

-----Original Message-----

**Comment by lucienimmink** [comment]
the ms prefix is removed as stated in included URL:
> As of IE11, the Microsoft prefixed versions of pointer events APIs are no longer supported and have been completely removed from the EdgeHTML in Microsoft Edge.

**Comment by lucienimmink** [comment]
Change to (7.0.10)
```javascript
actions = window.PointerEvent ? {
    start: 'pointerdown',
    move: 'pointermove',
    end: 'pointerup'
} : window.MSPointerEvent ? {
    start: 'MSPointerDown',
    move: 'MSPointerMove',
    end: 'MSPointerUp'
}
```
to make it work

**Comment by lucienimmink** [comment]
Somehow the pointermove does not work. I've tried to debug but ended up with false positives since the initial check failed and the touch events were used instead (but they work though).

**Comment by lucienimmink** [comment]
Does this help? http://stackoverflow.com/questions/25620397/pointermove-does-not-fire-for-touch-on-ie

**Comment by clockwisemusic** [comment]
+1

**Comment by clockwisemusic** [comment]
Here's the info on touch events in Edge - http://blogs.msdn.com/b/ie/archive/2015/02/24/pointer-events-w3c-recommendation-interoperable-touch-and-removing-the-dreaded-300ms-tap-delay.aspx

**Comment by leongersen** [comment]
Got my hands on windows 10 and found the issue: Edge [drops support](https://msdn.microsoft.com/en-us/library/windows/apps/hh767313.aspx) for `-ms-touch-action`, only using `touch-action` instead. I'll include the fix in the next release.

**Comment by clockwisemusic** [comment]
Awesome, thanks @leongersen  ! Such a simple fix :)
