### ISSUE TITLE
direction 'rtl' breaks value display

### ISSUE THREAD

**Issue by bwente** [leongersen/noUiSlider#485]
As soon as I change the direction to 'rtl' the value is undefined.

```
noUiSlider.create(otherSlider, {
	start: 0,
	orientation: 'vertical',
	step: 10,
	direction: 'rtl',
	range: {
		'min': 0,
		'max': 1000
	}
});
```

It doesn't seem to be working on the example page either...
http://refreshless.com/nouislider/slider-options/#section-direction

**Comment by SasaPrskalo** [comment]
Same thing here. I noticed that it  only works when you put the array for the 2 handles.

**Comment by SasaPrskalo** [comment]
Hei bwente, I managed to solve the problem by deleting the input.value = values<code>[handle];</code>   <---this in the example when you add the <code> on.('change', 'update') </code> events, hope this helps..

**Comment by bwente** [comment]
That works for me!

Just need to get the example fixed for us js novices.
