### ISSUE TITLE
Please add copyright statement

### ISSUE THREAD

**Issue by onlyjob** [leongersen/noUiSlider#490]
Something like

    Copyright 2011-2015 Leon Gersen <email@address.com>

Also it would be nice to include full text of the license somewhere in source tree.

Thanks.

**Comment by leongersen** [comment]
noUiSlider is licensed [WTFPL](http://www.wtfpl.net/about/). I'm not littering that everywhere.

**Comment by onlyjob** [comment]
There should be evidence of the chosen license in the source code. 
You have to add license somewhere to the source, perhaps to the `README.md` for compliance with copyright law. Proper copyright statement and license grant are important for free (and open source) software.
Also those who (re-)distribute your work as well as package maintainers need licensing information in the source. FYI I've seen packages rejected from Debian due to lack of licensing (and copyright) information.
Please apply license properly.

**Comment by onlyjob** [comment]
As very minimum please consider adding copyright statement.

**Comment by leongersen** [comment]
If you want a copyright statement, fork the project, add it yourself. I'm not going to.
