### ISSUE TITLE
Set the slider range dynamically

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [leongersen/noUiSlider#493]
In my specific use case I have to update the slider range in real time. I can set values, but I can't see any setter for the range. I can recreate the control with every iteration, but it seems to be quite inefficient. Has anybody an idea how to incorporate something like this into the original script?

**Comment by chickenwing** [comment]
This used to be possible in version 7, http://refreshless.com/nouislider/new-version/.

In version 8 now you have to destroy everything and rebuilt, as described here: http://refreshless.com/nouislider/more/#section-update

I also wish there would be a way to dynamically update the range again, without tearing down everything.

**Comment by leongersen** [comment]
V7 also destroyed the slider and rebuild it. There was just a shorthand for doing it.

-----Original Message-----

**Comment by chickenwing** [comment]
Oh, I thought in V7 it did not replace the whole noUiSlider dom but just adjust the calculation and dom elements associated with the range.

I used to do:

```javascript
$("#slider").noUiSlider({
	range: {
		"min": newMin
		"max": newMax
	}
}, true)
```

**Comment by glampr** [comment]
Are there plans to allow for changing the options without destroying & rebuilding?
This could be very useful (i.e. keep reference for listeners, etc...)

**Comment by vvo** [comment]
I did a quick hack to be able to dynamically update the ranges and it works, see #515

**Comment by leongersen** [comment]
Merging to #515.

**Comment by dimkoug** [comment]
How to set ranges  min and max via ajax call  ? Is there an event  onLoad ;
