### ISSUE TITLE
Have slide event fire when using .set

### ISSUE THREAD

**Issue by ndeimler** [leongersen/noUiSlider#495]
I'm using the slider to run a series of animations and I think a great feature would be to animate the value itself when .set is used. So for example, if I set the value from 0 to 30, it transitions 1 value at a time up to 30, rather than switching immediately from 0 to 30. That way animations (or whatever the slider is changing) can slide to that value.

**Comment by leongersen** [comment]
I'm closing this issue, as it is not a feature I intend to implement, there seems to be no additional interest beyond the initial request, and I'm trying to clear the issue tracker. If there is further interest in a feature like this, feel free to comment - I'll reopen this issue. I'm also open to pull requests.
