### ISSUE TITLE
"TypeError: [slidername].noUiSlider.on is not a function", pips not working.

### ISSUE THREAD

**Issue by JustinWestphal** [leongersen/noUiSlider#496]
Using the UISlider package for Meteor (*edit: RCY) released on atmosphere.

.on apparently isn't a function that works with Meteor. What is the solution here? Additionally, pips don't work. Implementing them exactly as shown in the docs and they aren't rendering in Meteor.

**Comment by leongersen** [comment]
I'm not providing a Meteor package. What version is it?

-----Original Message-----

**Comment by JustinWestphal** [comment]
I got it from here, it's pretty much the only slider for Meteor: https://atmospherejs.com/rcy/nouislider

I guess all they did was wrap the library in a meteor package because reactivity is broken. I really need a range slider for my app... any advice?
