### ISSUE TITLE
Getting false and null values when trying to retrieve step values

### ISSUE THREAD

**Issue by TheCrow1213** [leongersen/noUiSlider#499]
I may be doing this wrong, so please point me in the right direction:

```
	noUiSlider.create(slider, {
		start: selectedTerm,
		range: {
                    "min": 270,
                    "50%": 360,
                    "max": 540
                }
		snap: true,
		connect: 'lower'
	});
```

And when I call noUiSlider.steps() on the created slider I get this:

![image](https://cloud.githubusercontent.com/assets/1562516/9396790/f8ba529c-475c-11e5-87d8-f237132f0015.png)

What am I doing wrong?

**Comment by leongersen** [comment]
You haven't set any `step` values, so the next step is undetermined and thus `false`.

-----Original Message-----

**Comment by TheCrow1213** [comment]
Thank you sir! I'll play around with it and see if I can get it working. Thanks for the direction

**Comment by TheCrow1213** [comment]
Got it all fixed up, thanks mate! *fist bump*

**Comment by leongersen** [comment]
Alright! Can I ask what you are using it for? I haven't been asked about the step-getting feature a lot, so I'm interested!

-----Original Message-----

**Comment by TheCrow1213** [comment]
So I have two buttons, an increment and decrement. In the onclick handlers for those buttons I retrieve the step values and increment or decrement the slider values by one step.
