### ISSUE TITLE
WTF man? ))) how i can get slide event?

### ISSUE THREAD

**Issue by Tpona** [leongersen/noUiSlider#500]
Hi, leongersen!

My old code not working after last update (((
How i can to hook "slide" event now?
Similarly, i cant link slider to edit, but it not general problem, if i understand how to get "slide" event.
Thx! / Tpona

**Comment by mgibbs189** [comment]
@Tpona no need for hostility. Leon offers noUiSlider for free with no expectation of anything in return.

If you want help, then please share the version you upgraded from, as well as your current code.

**Comment by Tpona** [comment]
mgibbs189 no no no, it's not a hostility. I'm sorry if I gave you a reason to think so )
I moved from 7.0.10 to last master version (8.*.*) using Composer.
I was just very surprised that was removed this useful functionality, which I wrote above.

**Comment by leongersen** [comment]
The slide event is still available:

http://refreshless.com/nouislider/events-callbacks/#section-binding

Linking is replaced by binding a change handler yourself. See the third code block in the following example:

http://refreshless.com/nouislider/examples/#section-html5

-----Original Message-----

**Comment by Tpona** [comment]
I found when I read, sorry)
I'm not angry, guys! peace!

Thanks! great work!
