### ISSUE TITLE
feature request: change values during the animation

### ISSUE THREAD

**Issue by verybigelephants** [leongersen/noUiSlider#506]
would it be possible for the slider to periodically call the "slide" function callback when the slider has just been tapped somewhere and option 'animate' is set to true, so it moves by itself?

it would be cool to have as an option, whether to update slider values during sliding animation or not

now when you want to make some smooth transitions you have to use some forms of hack to animate stuff after the 'change' function

**Comment by leongersen** [comment]
Merging with #495.
