### ISSUE TITLE
Feature request: ability to select multiple ranges

### ISSUE THREAD

**Issue by SteinMaerivoet** [leongersen/noUiSlider#507]
It would be nice to have the ability to select multiple ranges in the slider. Below is an example.
http://www.jqueryscript.net/slider/jQuery-Plugin-For-Multi-range-jQuery-UI-Range-Slider.html

It can be used for example in an hour schedule to select working hours.

**Comment by clemsos** [comment]
Is this on the map ?

**Comment by leongersen** [comment]
This isn't trivial to implement, and I haven't planned to work on it, to be honest. What would the API look like, ideally?

**Comment by clemsos** [comment]
On the user side,  the best thing will be to have more than 2 numbers in the init ```start``` range to create more handles.

see an example 

```
var slider = document.getElementById('slider');

noUiSlider.create(slider, {
	start: [20, 30, 70, 80], // will create 4 handles 
	connect: true,
	range: {
		'min': 0,
		'max': 100
	}
});
 ```

**Comment by leongersen** [comment]
Merging with #592.
