### ISSUE TITLE
Fire event when ".noUi-active" gets set

### ISSUE THREAD

**Issue by JonasDoebertin** [leongersen/noUiSlider#508]
I think it would be a nice addition to have noUiSlider fire an event when the user clicks (mousedown) on a handle. This is already captured and the handle gets a `.noUi-active` class added so I think it might be an easy modification to fire an event from that function, too.

What do you think about it?

**Comment by leongersen** [comment]
Sorry for waiting so long to respond; this is now in my dev build, will release soon.

**Comment by leongersen** [comment]
I've added [`start` and `end` events](http://refreshless.com/nouislider/events-callbacks/)!

**Comment by JonasDoebertin** [comment]
Cool! 👍 Thanks a lot!
