### ISSUE TITLE
Handle may get stuck to the mouse

### ISSUE THREAD

**Issue by Ceremony64** [leongersen/noUiSlider#509]
The following issue can be replicated in all browsers, with Firefox being the easiest to replicate and most prone to happen to a user.

To replicate ...
1. ... pick up the handle and start dragging. Dont let go yet!
2. While still holding the handle...
Firefox: ... leave the browser window with the mouse and let go of the mouse button
Chrome/IE: ... switch applications (e.g. Alt+Tab) and let go of the mouse button
3. Reenter the browser of choice and click on any handle of a slider. May even be the same one!
4. The slider you picked in step 1 will be permanently stuck to your mouse until you reload the page.

**Comment by Fidel90** [comment]
I was able to reproduce this in Firefox (40.0.3) and IE11. Chrome showed no issue for me (45.0.2454.85).

In step 3 for me it was enough to reenter the browser window to get the slider stuck to the mouse, no click on the handle needed.

**Comment by joepenzo** [comment]
Does any of you guys has a (temporary) solution for this issue?
I encountered this on Chrome (v 45.0.2454.93 (64-bit))

**Comment by leongersen** [comment]
This proved a little tricky, but 8.1.0 fixes it. Thanks for the report, the `alt-tab` clue helped.

**Comment by Ceremony64** [comment]
Unfortunately, it doesn't seem to be fixed in Firefox: The behavior there remains the same and I cannot get it to "unstuck". Seems to be the same issue as #543, just in another environment (iframe vs window)

**Comment by leongersen** [comment]
Yes, this is the same issue. I've been playing with if for a bit, but  haven't found a combination of `which`, `button` and `buttons` that works cross browser. IE9 has a bug, IE10 mobile has a different bug, Firefox has a bug. No fun.

**Comment by Nihilivin** [comment]
I had a very similar issue on another JS piece of code some months ago. Gonna look at your issue, as i'd like to use it on my enterprise's website.

**Comment by d13g0** [comment]
Oops this happens to me too! I am using Firefox on Ubuntu Linux.

**Comment by leongersen** [comment]
I've tweaked a little more, should be fixed now. There is also a minimum test case in the repository.

**Comment by elinake** [comment]
Reproduced on Android:

It works fine on web browsers, so it's not about accidentally binding it multiple times. On android happens following:

- sliding once works fine
- sliding back and forth without stops:
  - start and slide are fired multiple times
  - change and end are fired after all the starts and slides

Result: Clicking anywhere on the screen results onChange and onEnd being fired, making everything except slider inaccessible.

**Comment by leongersen** [comment]
`on Android` means very, very little. I'm testing various configurations fairly extensively on every device I can get my hands on, and I'm not seeing this. To debug any issue, I'd need to know the exact device, the exact android version or which ROM, the exact browser and version, and *some* clue as to what might be happening on your device.
