### ISSUE TITLE
Set event called twice

### ISSUE THREAD

**Issue by mrself** [leongersen/noUiSlider#510]
When i set handle for 'set' event, it calls handler twice. Is it right?

**Comment by Yankovsky** [comment]
Update event called 4 times during initialization and then 3 times on any change. You could reproduce the problem by logging [events example](http://refreshless.com/nouislider/events-callbacks/)

**Comment by leongersen** [comment]
`update` fires once for every handle on it, then at most three times when `set` is called. It does this because of the following example:
```
A = 5; B = 10;
set(15, 20);
update A = 10; (limited by B)
update B = 20; (desired value)
update A = 15; (desired value)
```

`set` fires once for every handle, with the second parameter set to the handle number (`0` or `1`, corresponding to the index in the first function parameter).
