### ISSUE TITLE
Find created slider  with JQuery Selector

### ISSUE THREAD

**Issue by Stanja219** [leongersen/noUiSlider#512]
I'm using noUiSlider.8.0.2 . In an earlier Version i simply could use JQuery and everything was fine but now I have no idea how to use the slider events like set, slide and so on.
(The sliders are created dynamically in another file.)

 $('.myslider').on('set', function () {
        var value = wzkp_noUISlider_getValues($(this));
        console.log(value);
    });

----------------------------------------
// Read Values
function wzkp_noUISlider_getValues(aSlider) {
    return aSlider.get(0).noUiSlider.get();
}

Can anybody help me to make this working again?
Thanks a lot

Stanja

**Comment by Ceremony64** [comment]
A new object is attached to the DOM of a created slider called "noUiSlider". The following code cycles through all .myslider elements and attaches a set-event that will log new values to the console:
```javascript
$('.myslider').each(function(id, element){
	element.noUiSlider.on("set", function ( values, handle ) {
		console.log(values);
	});
});
```

**Comment by Stanja219** [comment]
Thank you.That worked for me
