### ISSUE TITLE
0 decimals shows strange values

### ISSUE THREAD

**Issue by Stanja219** [leongersen/noUiSlider#514]
Hallo, 
I would like to create a slider that shows values between 7.500 und 40.000 without decimals but a point a thousand - separator. 
When I move the slider to the right i get 24.499 instead of 24.500 ... 24.999 instead of 25.000  ... When i move it further to the right I get 25.500 but the nex step is worong again with 25.999.

How  can I make this working correctly without setting decimals to a value greater than 0?

I'm looking forward for any help :-)
Anja

// Slider
noUiSlider.create(slider, {
    start: 24000,
    step: 500,
    connect: 'lower',
    snap: false,
    range: {
        'min':7500, 
        'max':40000
    },
    format: wNumb({
        'thousand': '.'
    })
});

---------------------------

// When the slider value changes, update the inputfields
        slider.get(0).noUiSlider.on('update', function (values, handle) {
            // One / Left handle
            if (handle == 0) {
                tinput.value = values[handle];
            }
   });

**Comment by leongersen** [comment]
This happens because you've replaced the default formatter by your own. The default handles decimals, your replacement does not. I'll be the first to admit that this is confusing. Setting the formatter like this will fix your issue: 

```JavaScript
wNumb({
	thousand: '.',
	decimals: 0
})
```
