### ISSUE TITLE
Slider does not obey step -rule when having non-linear range

### ISSUE THREAD

**Issue by juhamust** [leongersen/noUiSlider#520]
Slider does not obey step -rule when having non-linear range: When only `min` and `max` defined, the `step` works as expected. But as soon more range values are given, the step -rule is not used after first range. See jsbin:

http://jsbin.com/hijiwo/edit?html,output

**Comment by leongersen** [comment]
Specify the step for each range pointed, as documented here: http://refreshless.com/nouislider/slider-values/#section-non-linear-step

-----Original Message-----

**Comment by juhamust** [comment]
Ah, thanks! I knew I must be doing something wrong (even tried `step` option with few different values). 

Maybe documentation in http://refreshless.com/nouislider/slider-options/#section-step could contain a link to another section?
