### ISSUE TITLE
Range with negative minimum ignores text boxes

### ISSUE THREAD

**Issue by yepnamesjames** [leongersen/noUiSlider#522]
I have an example here: http://codepen.io/anon/pen/avpvVz

You can see two sliders work because in the html I defined the ranges to start at 0. The two sliders with ranges that go into the negatives do not work with their textbox bindings.

**Comment by leongersen** [comment]
This got answered on stackoverflow, correct?

**Comment by yepnamesjames** [comment]
Yeah, thanks for getting back to this though.
