### ISSUE TITLE
font-family: arial on pips/labels

### ISSUE THREAD

**Issue by camilodelvasto** [leongersen/noUiSlider#523]
Hi, I really love the simplicity of this plugin, it's definitely the best I've tried! But I just noticed that the labels are being hard-coded to arial, on line 12, file nouislider.pips.css. As I was using another font face, I had to override the style with a rule, but as a plugin I'd expect it to honor my font selection and not force me to use arial.
Thanks for the great work!
Camilo

**Comment by vvo** [comment]
:+1:

**Comment by leongersen** [comment]
I guess we can just scratch that declaration. Good catch.

**Comment by leongersen** [comment]
Fixed it!
