### ISSUE TITLE
Handles to move on either side of each other

### ISSUE THREAD

**Issue by Dodotree** [leongersen/noUiSlider#527]
Is it possible? 

I actually need the option for negative ranges. I can make a hack so it would appear so, but if you have this option already I would gladly use it.

Thank you very much

**Comment by leongersen** [comment]
I'm closing this issue, as it is not a feature I intend to implement, there seems to be no additional interest beyond the initial request, and I'm trying to clear the issue tracker. If there is further interest in a feature like this, feel free to comment - I'll reopen this issue. I'm also open to pull requests.
