### ISSUE TITLE
Usage Q: labels in pips

### ISSUE THREAD

**Issue by avalanche1** [leongersen/noUiSlider#529]
Hi!
Can I attach labels to pips scale instead of numbers?
I want to make an options scale, where choosing slider position will mean selecting different options.
E.g. slider value 1 will be equal to option1 is selected, slider value 2 will be equal to option1 and option2 are selected and so on...

**Comment by leongersen** [comment]
Yes! This is discussed in [this issue](https://github.com/leongersen/noUiSlider/issues/370).

**Comment by avalanche1** [comment]
jQuery, sure. But a pity no way to do via noUi api..

**Comment by leongersen** [comment]
Vanilla translation is trivial:

```JavaScript
var nodes = document.querySelectorAll('.noUi-value.noUi-value-horizontal.noUi-value-large');
Array.prototype.forEach.call(nodes, function( el ){
    el.innerHTML = recountVal(this.innerHTML);
});
```
