### ISSUE TITLE
Allow custom step values

### ISSUE THREAD

**Issue by teoulas** [leongersen/noUiSlider#53]
The current `step` option, allows for linear values in the slider. It would be nice if the slider allowed a custom array of values. I can think of two use cases for this option:
1. A slider with non-linear numeric values, eg:
   100, 200, 500, 1000, 2000, 5000, 10000
2. A slider with non-numeric values (I know, a bit extreme), eg:
   "never", "rarely", "sometimes", "often"

Both cases can be implemented with a custom `slide` function, but it would be nice if this functionality was built-in. Here's a jsfiddle with the above examples: http://jsfiddle.net/KheWe/

**Comment by ChrisCinelli** [comment]
The jsfiddle does not work anymore. I tried to fix the link to the js and css but I cannot find the Link.js. Is this supposed to work?

**Comment by mg1075** [comment]
@ChrisCinelli 
Hmmm, did the api change radically with the 8.0 release of the project? It has been a while since I looked at this plugin.

Maybe try this ad-hoc fiddle based on the new api: 
http://jsfiddle.net/w3gbq126/

(Apparently Link.js is part of the .min version of the plugin.)

**Comment by itisconor** [comment]
@mg1075 
Looking at the ad-hoc fiddle you added here, is there a way to display percentage values that the values are attached to also?
