### ISSUE TITLE
require-ing nouislider break build by  window not being defined at the server

### ISSUE THREAD

**Issue by bobiblazeski** [leongersen/noUiSlider#533]
I'm using webpack as my build tool in an isomorphic application. The build step fails due to window not being defined.
I've  temporary solved it by adding checks for  window !== 'undefined' at:
https://github.com/leongersen/noUiSlider/blob/master/distribute/nouislider.js#L135
actions = typeof window !== 'undefined' && window.navigator.pointerEnabled ? {

and 
https://github.com/leongersen/noUiSlider/blob/master/distribute/nouislider.js#L139
} : typeof window !== 'undefined' &&  window.navigator.msPointerEnabled ? {

**Comment by vvo** [comment]
Why would you build a DOM slider server side? I guess you should be able to split or do the require only in browser mode. Otherwise you can use webpack to shim the whole dependency.

**Comment by leongersen** [comment]
I'll need @vvo's question answered before I can do anything here. Checking for `window` or defaulting to touchevents is not the fix here.

**Comment by bobiblazeski** [comment]
I have an React isomorphic (universal) application that is rendered both client and server side 100%. When user loads the route it receives the both the rendered DOM and the complete state of the application, React checks the DOM sees that there are no changes and user  continues to interact with the application immediately, application is much faster which leads to better user experience.
Another plus is that whole application is very testable, I just use JSDOM & mocha, without need to run phantom or something like that. All my tests run in few seconds,.
So why wouldn't I  render the on the server, the benefits are obvious? 
I could make some kind of workaround, and add nouislider to client side only code, which currently is limited to two files (one to instantiate the application on the client and second handling REST & socketIo data transfer) but that's an ugly hack not a solution, especially since its used just one control.

**Comment by leongersen** [comment]
This is fixed.
