### ISSUE TITLE
slider with "required" option

### ISSUE THREAD

**Issue by joelmora** [leongersen/noUiSlider#534]
Hi, is there any way to make the slider be required like an input field? I need the user set the slider before submit but always the slider start with on the most left value, in my case, with a 0.

I wanna display HTML5 validations, but I don't wanna display the actual input field, because is hidden, I set the value through 'update' event.

I don't know if this could be achieved in a different way

**Comment by leongersen** [comment]
You'll have to sync the slider value to an `input` element, clear it when you don't like the value, and set `required` on that. That's the only way to trigger the browsers native validation warning.

**Comment by somethumb** [comment]
I use this:

// Validate hidden number fields so that the slider isn't zero!
		add_filter( 'gform_field_validation_28_3', 'stc_gform_field_validation_28', 10, 4 );
		function stc_gform_field_validation_28( $result, $value, $form, $field ) {
				if ( $result['is_valid'] && intval( $value ) == 0 ) {
						$result['is_valid'] = false;
						$result['message'] = 'Please choose a value greater than 0';
				}
				return $result;
		} //
