### ISSUE TITLE
Options object is modified in setting defaults

### ISSUE THREAD

**Issue by leongersen** [leongersen/noUiSlider#537]
The only time we change the original options object is [here](https://github.com/leongersen/noUiSlider/blob/master/src/js/options.js#L259), where we could change [this line](https://github.com/leongersen/noUiSlider/blob/master/src/js/options.js#L282) to `|| defaults[name]` to achieve the same effect without ever modifying the `options` object.

#526

**Comment by vvo** [comment]
Hi @leongersen I want this one to be fixed but was wondering if || defaults[name] was sufficient in case where we pass objects as options (like ranges being an array).

Otherwise I am not sure where to add || defaults[name].

Thanks
