### ISSUE TITLE
Possible to get current slider on update?

### ISSUE THREAD

**Issue by Yearhouse** [leongersen/noUiSlider#540]
Hi 

I have multiple sliders which is defined by document.querySelectorAll( '.js-slider' );
on tooltips.format I would like to insert a label above the value, which is defined on the current slide object via data-label.

On init this works fine
```javascript
var len = sliders.length,
	slider, settings;

while( len-- ) {			
	slider = sliders[len];
	settings = {
		tooltips: {
			format: function( value, handle ) {
				
				var dformat = wNumb({
					decimals: 0,
					thousand: ".",
					prefix: "<span class=\"noUi-tooltip__label\">" + slider.getAttribute( "data-label" )+ "</span>",
					postfix: "$"
				}); 
				
				return dformat.to( parseFloat( value ) );
			}
		}
	};

	noUiSlider.create( slider, settings );
}
```

But on update it gets the last initialized slider, which is obvious :)
But can I somehow get the current slider object or id inside the tooltips.format or inside the update event or get a hold of the settings object for the current slider?

Havent been able to figure this out.

**Comment by leongersen** [comment]
If you could create a runnable jsFiddle (so I can play with it) and post your question to stackoverflow, I'll have a look. I'm trying to keep issues and support separate. You can use these for the resources:

```
https://refreshless.com/noUiSlider/distribute/nouislider.min.css
https://refreshless.com/noUiSlider/distribute/nouislider.js
```

Just link your question here.

**Comment by Yearhouse** [comment]
Hi Leon

Sorry for that :)

I have submitted my question to Stackoverflow and created a Fiddler.
The question can be seen her:

https://stackoverflow.com/questions/33411671/nouislider-get-current-slider-in-format-or-via-update-event

**Comment by leongersen** [comment]
No problem! I've answered your question :)
