### ISSUE TITLE
Thin slider,  wider click area needed

### ISSUE THREAD

**Issue by miketeix** [leongersen/noUiSlider#545]
Hi @leongersen, I'm running into a useability issue in styling the slider only a couple of pixels wide.
  Any idea how I might implement a wider click area?
<img width="53" alt="screen shot 2015-10-31 at 12 32 06 am" src="https://cloud.githubusercontent.com/assets/3904862/10861858/db08ae1e-7f66-11e5-8ce4-36a39f021e66.png">

**Comment by d13g0** [comment]
I think I have actually solved this problem while working on styling my sliders:

Expand the area of .noUi-handle, something like this:
}
.noUi-horizontal .noUi-handle {
    width: 54px;
    height: 32px;
    left: -18px;
    top: -11px;
    border: 1px solid transparent;
}

The transparent border allowed me to see how big the area was, as I was trying to make it adequate for a touch-based interface.

![screenshot from 2015-11-18 15 14 18](https://cloud.githubusercontent.com/assets/976342/11253077/7a67786a-8e07-11e5-9ee9-d8feab7797f2.png)

I hope this helps!

**Comment by miketeix** [comment]
Hey thanks for following up, it was just the ticket!

Though, my handle had a coloured background and if I set a transparent border and applied background-clip, I wouldn't be able to shape the box into a circle using border-radius.

So i instead used background-image coupled with transparent border worked like a charm.

Cheers!

```
 .noUi-handle {
        ...
       border: 15px solid transparent;
        background-clip: padding-box;
        padding: 6px;
        background-image: url("../assets/images/sliderHandle.png");
        background-repeat: no-repeat;
        background-origin: content-box;
        background-size: 12px 12px;
        background-position: -6px, 0;
        background-color: transparent;
}
```

**Comment by d13g0** [comment]
Fantastic! glad to hear you solved it.
