### ISSUE TITLE
Uislider break other html pages

### ISSUE THREAD

**Issue by Shehab-Eltawel** [leongersen/noUiSlider#546]
Hi, 
I am using noUiSlider V 8.0.2 and facing trouble at other html pages where I don't need a slider. Isn't there anyway to stop that error (TypeError: a is null) when I don't need to use the slider ?

Thanks

**Comment by leongersen** [comment]
Yes, test for element existence before calling noUiSlider. 

    var slider = document.getElementById('slider');
    if ( slider ) { 
    //     noUiSlider.create
    }

**Comment by Shehab-Eltawel** [comment]
Thank you Leon :)
