### ISSUE TITLE
different tooltip-postfixes when using range slider

### ISSUE THREAD

**Issue by thepercival** [leongersen/noUiSlider#549]
Hello,

I want to show a different label at each handle. 

format: {
            to: function ( value ) {
                return value + ' first handle'; /* or second handle */
            }
        }

is this possible? I could not find this in the docs. 

maybe something like a extra param in the to-function to be able to check?

**Comment by leongersen** [comment]
Not yet, just added this to my dev version. Will release soon.

**Comment by leongersen** [comment]
There is now full support for [tooltip formatting](http://refreshless.com/nouislider/slider-options/#section-tooltips).

**Comment by thepercival** [comment]
great, fast support!
