### ISSUE TITLE
Update event fires between steps (even if there is no value update)

### ISSUE THREAD

**Issue by ekrokowski** [leongersen/noUiSlider#550]
When using steps the update event fires between steps (on every mouse event). 
Fiddle showing this bug: https://jsfiddle.net/yhbomm5p/

**Comment by leongersen** [comment]
You are right, it makes more sense for the `update` event to only fire when the step value actually changes. I'll look into it.

**Comment by ekrokowski** [comment]
Actually that was the case before 8.1.0 (tested in 8.0.2)
