### ISSUE TITLE
Handler dragging issue in iOS Mobile Safari 

### ISSUE THREAD

**Issue by chickenwing** [leongersen/noUiSlider#551]
The Problem:

![dragbug](https://cloud.githubusercontent.com/assets/853022/10908304/3ca0419c-8231-11e5-8d54-dc36be0323b1.gif)

It happens quite often, when touching the handler a little too low.
You can see, that the handler actually gets "focused" somehow. Weird, because I see that "-webkit-user-select: none" css rule is set.
Any ideas how to fix this? thx :)

**Comment by leongersen** [comment]
Is this just the simulator? I haven't seen this in any real iOS devices.

**Comment by chickenwing** [comment]
Its a real device (from browserstack). I have the same on my iPhone.

**Comment by leongersen** [comment]
I've got my hands on some iOS devices over the last couple days, and I can't reproduce this at all. What is the iOS version?

**Comment by chickenwing** [comment]
Its iOS 9.1. I made another somewhat crappy recording of it. I happens when you hold your finger to long and low on the handle before you start the actual drag.

![out2](https://cloud.githubusercontent.com/assets/853022/11449101/34081658-956a-11e5-8f36-09922b80f81a.gif)

**Comment by leongersen** [comment]
That helps, I'll look into it today 

-----Original Message-----

**Comment by leongersen** [comment]
Found and fixed the issue. Will release soon!

**Comment by chickenwing** [comment]
awesome, thx alot!
