### ISSUE TITLE
`updateOptions` when using `snap: true` and an explicit range doesn't seem to work together.

### ISSUE THREAD

**Issue by mshwery** [leongersen/noUiSlider#558]
If you instantiate a new noUiSlider with something like:

```js
{
    start: 0,
    snap: true,
    range: {
        min: 0.25,
        '10%': 1,
        '20%': 2,
        max: 10
    }
}
```

this works fine. however, if you only provide these explicit ranges you wish to be snapped by using `updateOptions` it fails. You can witness it here:

http://jsbin.com/waxibit/2/edit?js,output

**Comment by leongersen** [comment]
I've [updated](https://github.com/leongersen/noUiSlider/commit/33b678b1cd7895ed51670eaaff85092b92aa31b8) the `updateOptions` method. It now **only** updates options that were passed to the function. The slider now resets the value it had before updating, and fires the `update` and `set` events to reflect this. I've also added support for the `snap` option, which is set in `scope_Spectrum`. 

*Technically*, these changes are not fully backwards compatible, but this method wasn't in the documentation yet. Do you see any problems with this, @vvo?

**Comment by vvo** [comment]
No problem at all, thanks a lot that was the right way to do it!
