### ISSUE TITLE
Feature Request: Highlight slider range

### ISSUE THREAD

**Issue by osi-oswald** [leongersen/noUiSlider#559]
I'd like to be able to highlight a certain slider range:
![foo](https://static.dyp.im/vCvBYytfLL/90d5d2fbede43c1650dabcf862796c39.png)
For example up to a value of X, the sliders background is highlighted (ex. orange) and then "normal" again. 

If you are not planing to add this feature, could you maybe give me some hints how to achieve (hack) this?

**Comment by cuu508** [comment]
A really hacky way to achieve this (and also multiple ranges) would be to look up DOM elements with .noUi-connect and .noUi-background classes. Then,

- set the background of .noUi-connect element to transparent
- set the background of .noUi-background to a carefully prepared horizontal CSS gradient. Or simply set it to a picture if the range is static.

As I said, this would definitely be a hack, and performance would suffer quite a bit, but that would be one way to get this done without invasive changes to slider's code.

**Comment by leongersen** [comment]
You can indeed do this using `linear-gradient`, it's not even too difficult. I've just answered [a stackoverflow question](http://stackoverflow.com/questions/35561800/nouislider-set-a-background-color-for-the-limited-area/35606623#35606623) the other day doing exactly this:

```
.noUi-background {
    background-image: linear-gradient(to right, #a2ea4c 20%, #07aa91 20%, #07aa91 80%, #a2ea4c 80%);
}
```
