### ISSUE TITLE
Dynamically loading noUiSlider

### ISSUE THREAD

**Issue by cSmout** [leongersen/noUiSlider#561]
I have a bank of sliders that I am dynamically moving between bootstrap collapse elements (simply by moving innerHTML).

The sliders are initialised in the document.ready() function as normal, and work perfectly in their initial positioning in the markup. 

However, once I trigger a new collapse element, and thus move the sliders into it, the sliders cease to function and receive the error:
"Uncaught TypeError: Cannot read property 'apply' of undefined.

I assumed this was because the sliders were no longer initialised in their new position. However, reinitialising them gave me an error stating that they had already been initialised.

I'd appreciate any thoughts.

TIA

**Comment by leongersen** [comment]
Because you are changing `innerHTML` you are losing the reference to the node, but not the `noUiSlider` property. This is why the reinitialisation error fires. If you move the slider node using `.insertAfter` or the like it should work.

**Comment by cSmout** [comment]
Thanks for your quick response! I will give it a try

**Comment by cSmout** [comment]
You are correct, insertAfter worked.

Thankyou
