### ISSUE TITLE
Slider becomes "sticky" if too close to browser's right edge and mouse moves outside window

### ISSUE THREAD

**Issue by dynamicdriverepo** [leongersen/noUiSlider#565]
Hi:
I noticed a debilitating bug when the slider is positioned at the browser window's right edge, and the user's mouse moves out of the browser while dragging the slider. In that case the range control becomes sticky, continuing to follow the mouse around even if I try to click on the control/ anywhere else on the document to try and release it...

**Comment by dynamicdriverepo** [comment]
So I've added a temporary fix to address the issue. Inside the .js file just above the comment:

//unbind move events...

add the following code:

	document.body.addEventListener('mouseleave', function(e){
		var d = document.documentElement;
		var active = scope_Base.querySelector( '.' + cssClasses[15] )
		if (active != null){
				d.noUiListeners.forEach(function( c ) {
				d.removeEventListener(c[0], c[1]);
			})
		}
	}, false)


	// Unbind move events on document, call callbacks.

Now dragging the handle bar pass the right edge of the browser window doesn't cause the handle to continuously follow the mouse around. See http://editor.javascriptkit.com/ for implementation of the updated code.

**Comment by leongersen** [comment]
I'm merging this with #543, which is the same problem. The slider already checks whether any buttons are pressed on mousedown, but this fails in FireFox because it doesn't match its own spec.
