### ISSUE TITLE
perfomance increasing

### ISSUE THREAD

**Issue by boomsya** [leongersen/noUiSlider#566]
hi! slider very good but have some problems

just add  this:
if(scope_Locations[trigger].toFixed(6) == to.toFixed(6)) return false;

to 
function setHandle(handle, to, noLimitOption){

this increasing perfomance and fireEvent('update', trigger); triggered only when handle was change position

in my test i have decrease callbacks from 250 to 46 (slider 14-60 range)

i am inserting my code after this:
// Handle the step option.
to = scope_Spectrum.getStep(to);

**Comment by boomsya** [comment]
i think it would better to move my code after  that:
// Return false if handle can't move and ranges were not updated
if(to === scope_Locations[trigger] && newScopeValue === scope_Values[trigger]) return false;

**Comment by leongersen** [comment]
Makes sense, I'll get it in.

**Comment by leongersen** [comment]
Merging this with #550.
