### ISSUE TITLE
Auto tooltip width?

### ISSUE THREAD

**Issue by landaire** [leongersen/noUiSlider#567]
I just incorporated noUiSlider into a project and noticed that for large numbers the tooltip does not look nice at all since the text overflows. For example:

![screen shot 2015-11-23 at 2 30 51 pm](https://cloud.githubusercontent.com/assets/1313522/11352037/e2a47438-91ee-11e5-9354-b4a5665478d3.png)

I noticed though that by changing `.noUi-tooltip` width from `50px` to `auto` it actually looks just fine. Is there any particular reason why this is hardcoded to 50px ([here](https://github.com/leongersen/noUiSlider/blob/a153b9fd4f753dbabbbff710269d1f0b41cb9ef1/src/nouislider.tooltips.css#L10)?

**Comment by vvo** [comment]
Yep @landaire, [at some point](https://github.com/leongersen/noUiSlider/commit/a153b9fd4f753dbabbbff710269d1f0b41cb9ef1) it was not harcoded, I wonder why it is now

**Comment by leongersen** [comment]
I merged the styling with an example previously in the documentation, this should've been left out. I've finally got some time this weekend, I'll go through the issues and do a release. Sorry for making you wait, @vvo!

**Comment by vvo** [comment]
no prob

**Comment by leongersen** [comment]
I've removed centered tooltips, including this line.
