### ISSUE TITLE
8.2.0 throws Error "must pass a formatter for all handles"

### ISSUE THREAD

**Issue by rejas** [leongersen/noUiSlider#568]
After upgrading to 8.2.0 I now get the following error: "Uncaught Error: noUiSlider: must pass a formatter for all handles."

With 8.1.0 this code of mine worked:

            var settings = {
                snap: snap,
                connect: true,
                range: range,
                start: [startMin, startMax],
                tooltips: false,
                format: {
                    to: function (value) {
                        return Math.round(value);
                    },
                    from: function (value) {
                        return Math.round(value);
                    }
                }
            };

            if (slider.noUiSlider !== undefined) {
                slider.noUiSlider.destroy();
            }
            noUiSlider.create(slider, settings);

So, is that now a bug or feature? ;-)

**Comment by leongersen** [comment]
That's a bug. Remove `tooltips: false` as a workaround (`false` is not a accepted value, but it should be!). Come to think of it, passing `false` as a formatter assumes the default formatter is wanted, but should mean 'no tooltip'.

**Comment by rejas** [comment]
Thanks for the quick response, removing the tooltip-param indeed fixed it.

**Comment by vvo** [comment]
Ah yes tooltips: false should be fixed

**Comment by leongersen** [comment]
I've fixed and release this, thanks. Shouldn't have missed this one ;)
