### ISSUE TITLE
rtl vertical slider tooltip show wrong value

### ISSUE THREAD

**Issue by KentriLuigi** [leongersen/noUiSlider#569]
Hello

I have a slider :

noUiSlider.create(slider, {
        range: {
                'min':  [      0],
                'max':  [  50000]
        }
        start: [ 1000, 40000 ],        //two handles
        direction: 'rtl',                     // max at top and min at bot 
        orientation: 'vertical',
        tooltips: true                      //show the tooltip
}

The problem is that the value of  my upper tooltip from the upper handle show the value from the bottom handle and vice-versa... 

How can I solve this ?

**Comment by leongersen** [comment]
This is related, but no equal to, #568. You can use `tooltips: [false, false]` as a workaround. I'll release an update soon.

**Comment by leongersen** [comment]
Fixed in 8.2.1. Thanks for the report!
