### ISSUE TITLE
Double tap on the slider

### ISSUE THREAD

**Issue by KentriLuigi** [leongersen/noUiSlider#570]
I have two handles and when i double tap on the slider i would like to move both handles on the same position. 

Is it possible ?

**Comment by KentriLuigi** [comment]
Hi, 

I will need it for the end of this week.
If you have not the time to had this feature, tell me if I can create a new event inside the NoUiSlider.js

I hope you could help me ;)

**Comment by leongersen** [comment]
Use any way of [detecting double taps](http://stackoverflow.com/questions/24058241/touch-device-single-and-double-tap-events-handler-jquery-javascript), then use the `.set()` method to set the handles.

**Comment by KentriLuigi** [comment]
I have a conflict with your tap event and I would like to add a condition in your event.
Below the algo of my idea:

```javascript
//IF tap event is already called AND under 1s
     //I move both handles on the current value
//ELSE
    //code for a simple tap
//ENDIF
```

What do you think about it ?

**Comment by leongersen** [comment]
You could disable the tap event by changing the `behaviour` parameter.
