### ISSUE TITLE
Please publish 8.2.1 to npm

### ISSUE THREAD

**Issue by JamesHenry** [leongersen/noUiSlider#571]
Maybe you could also think about setting up automatic `npm publish` as part of your release process?

**Comment by leongersen** [comment]
Yeah, I forgot. Will run it when I get home.

**Comment by JamesHenry** [comment]
Thanks, man!

**Comment by leongersen** [comment]
Forgot to comment yesterday, it's up. I've also added NPM to my publishing checklist, I kept forgetting ;)

**Comment by JamesHenry** [comment]
:+1:
