### ISSUE TITLE
event recursion

### ISSUE THREAD

**Issue by kozchka** [leongersen/noUiSlider#572]
I have a problem and hope you can help me.
I have 2 sliders (slider A and slider B). Than user changes slider A it has to take affect on slider B. And than user changes slider B it has to take affect on slider A. 

So i have to run this code(example):

sliderA.noUiSlider.on("set", function () {
	sliderB.noUiSlider.set(dummyValueB);
        sliderA.noUiSlider.updateOptions({range: {
				'min': dummyValueBMin,
				'max': dummyValueBMax
			}});
});

sliderB.noUiSlider.on("set", function () {
	sliderA.noUiSlider.set(dummyValueA);
        sliderA.noUiSlider.updateOptions({range: {
				'min': dummyValueAMin,
				'max': dummyValueAMax
			}});
});

The problem is than i call "set" or "updateOption" function on sliderB, than it fires 'set' event on sliderB, than it calls "set" or "updateOption" function on sliderA, than it fires 'set' event on sliderA ... 
And so on.
Can i fix it using your API?
In jquery UI slider i can check like this https://forum.jquery.com/topic/setting-a-sliders-value-without-triggering-the-change-event

Thank you.

**Comment by leongersen** [comment]
You can use the `change` event. It fires when `set` does, exept after calling `.noUiSlider.set()`. Here is an example: http://refreshless.com/nouislider/examples/#section-lock.

**Comment by kozchka** [comment]
Great. Thank you!
