### ISSUE TITLE
Missing docs/examples for serialization

### ISSUE THREAD

**Issue by rejas** [leongersen/noUiSlider#573]
It seems to me that there is a serialization-option alas I cannot find any info about it, the example page about it seems to be gone. Would be nice to know what one could do with that.

**Comment by leongersen** [comment]
The previous documentation for noUiSlider, version 7, is here:

http://refreshless.com/nouislider7/linking-input-fields/

**Comment by rejas** [comment]
Thanks once again. Is that documentation outdated or why isnt it in v8?

**Comment by leongersen** [comment]
Serialization (`Link()`) was completely integrated into jQuery methods, so it didn't make sense to port in to plain js: 

http://refreshless.com/nouislider/new-version/

**Comment by rejas** [comment]
Of course, I used the update event to work around the missing serialization doc, now it makes even more sense :-D Have a nice weekend!
