### ISSUE TITLE
[SUPPORT] Converting to nouislider 8 problems

### ISSUE THREAD

**Issue by cSmout** [leongersen/noUiSlider#574]
Hi, 

I have previously used nouislider 7 with much success. I am trying to convert to using the new version, but am stumbling at the first hurdle; just creating a slider.

I have a simple test page, with one slider, and a document.(ready) function in which the slider should be configured:

```
    <script>
      $(document).ready(function() {

        var tempo_slider = document.getElementById('slider');

        noUiSlider.create(tempo_slider, {
          start: [120],
          step: 1, 
          connect: "lower",
          orientation: "horizontal",
          direction: "ltr",
          behaviour: 'drag',
          range: {
            'min': 40,
            'max': 295
          }
        });

      });//$(document).ready
    </script>

    <div id="slider"></div>
```

The slider loads, but I receive the error:
"Uncaught TypeError: Cannot read property 'classList' of null"

Triggered by the create method, and pointing to line 96 in nouislider.js. 

Any help would be greatly appreciated.

I should add, that this error is thrown, no matter where I place the javascript (in head, at the bottom of body etc.). It seems like the div is not being picked up as being part of the dom.. but as far as I understood, at the point when Document.ready() fires, the Dom should be ready. 

Also, this exact configuration, but using jQuery and nouislider 7 works.

**Comment by leongersen** [comment]
That looks ok, and a minimal setup works fine:

https://jsfiddle.net/leongersen/jnmamfc2/

What else are you doing that isn't shown here?

**Comment by cSmout** [comment]
Hi, Thanks for your response! I got this working late on Friday evening... but after the weekend I can't remember what I did sorry! And my test case has evolved quite a lot since then.

Thanks for your help anyway!

**Comment by sjee** [comment]
I encountered the same error. As a result the `start `value did not work and the update event (which I had set up to populate the slider's value to an input field) was not being triggered. 

When I removed the line: `behaviour: 'tap-drag'` the start value worked, the update event was triggered and the error _"Uncaught TypeError: Cannot read property 'classList' of null"_ disappeared.
