### ISSUE TITLE
8.2.1 - rtl vertical slider tooltip show wrong value

### ISSUE THREAD

**Issue by KentriLuigi** [leongersen/noUiSlider#575]
The issue #569 is not fixed

I tried this :

noUiSlider.create(slider, {
range: {
'min': [ 0],
'max': [ 50000]
}
start: [ 1000, 40000 ], //two handles
direction: 'rtl', // max at top and min at bot 
orientation: 'vertical',
tooltips: true //show the tooltip
}

RESULT : the upper tooltip still shown the value from the lower handle and not from the upper :/

**Comment by leongersen** [comment]
I ran your example to be sure, and the behaviour is correct:

![image](https://cloud.githubusercontent.com/assets/1206361/14580816/a6f4f62a-03da-11e6-81c0-068a065f0b20.png)

Sliding the handle changes the appropriate value.
