### ISSUE TITLE
Error: noUiSlider: 'range' 'min' and 'max' cannot be equal

### ISSUE THREAD

**Issue by ghost** [leongersen/noUiSlider#578]
Hi, I have the problem, how fix this?
![2015-12-17_19 50 31](https://cloud.githubusercontent.com/assets/1108013/11871170/e6f66a7a-a4f7-11e5-9fdc-2fc550acf31d.png)

**Comment by leongersen** [comment]
By not having the `min` and max` parameters equal? There is no range between `300` and `300`.

**Comment by onedeadear** [comment]
Depends on your definition, but allowing min and max to be the same would be usefule. e.g. I've a process whose version increments by 1 with each event that occurs. If the process fails, I use the a slider with a single handle to select which version to retry from. This works well unless the process fails on the first step, then I need to do some faffing to display something other than the slider in this instance.

**Comment by leongersen** [comment]
I've [concluded before](https://github.com/leongersen/noUiSlider/issues/236) that there is no sane way to handle this setup in the slider. There just *isn't* a value between `x` and `x`. To create a proper solution that is both accessible and user friendly, this must be caught on the dev's end.

**Comment by jhoanborges** [comment]
Comment this line  in nouislider.js

		if ( entry.min === entry.max ) {
			//throw new Error("noUiSlider: 'range' 'min' and 'max' cannot be equal.");
		}

**Comment by spostad7** [comment]
> By not having the `min` and `max` parameters equal? There is no range between `300` and `300`.

from UX aspect, this is absolutely correct. The range can change from for example 1000 to 1000 by dragging the slider. why not?

**Comment by leongersen** [comment]
I'm open to a PR on this.

**Comment by leongersen** [comment]
noUiSlider 15.4.0 adds support for sliders with ranges where min = max. In this case, handles are spaced evenly across the slider.

Thank you for your feedback, everybody!
