### ISSUE TITLE
margin: 0 throws needless error

### ISSUE THREAD

**Issue by b9chris** [leongersen/noUiSlider#582]
https://jsfiddle.net/b9chris/0rohoeLg/2/

margin: 0 is the default, but if you pass it as an argument it throws an innaccurate error and fails to display the slider:

Uncaught Error: noUiSlider: 'margin' option is only supported on linear sliders.

Not an issue for example code, but it is if you start to abstract how the control is initialized - for example, if you build things so that people can declare controls in HTML without having to write any Javascript to render a slider:

https://jsfiddle.net/b9chris/0rohoeLg/4/

*kaboom*:

https://jsfiddle.net/b9chris/0rohoeLg/5/

**Comment by leongersen** [comment]
Makes sense. We can change this behaviour without problems. I'll admit I missed this issue, sorry for the delay!

**Comment by leongersen** [comment]
This is fixed in 8.3.0. Thanks for the report!
