### ISSUE TITLE
alternate `snap` behavior functionality with drag, delayed tap

### ISSUE THREAD

**Issue by markoshust** [leongersen/noUiSlider#583]
I was wondering if there was a way out-of-the-box to have this alternate snap behavior configuration.

Currently when using `behavior: 'snap'`:
- on tap down, slider is immediately updated
- on tap down, slider is updated, and immediately triggers `change` event
- user can continue to drag slider, and another `change` event is fired upon release

Desired functionality when using `behavior: 'snap'`:
- on tap down, slider isn't immediately updated, therefore no `change` event is triggered
- when user starts to drag up/down, slider is updated as user drags, and `change` event is fired upon release
- on tap up (no drag), slider is updated, and `change` event is triggered

The need for this is because I'm implemented noUiSlider within a carousel-like display. Therefore, a swipe left-right is needed. I don't want a tap down to trigger anything within noUiSlider, as a tap down may not be a slider set, but a swipe left/right within the carousel.

**Comment by leongersen** [comment]
This won't work, sorry. once noUiSlider has captured the initial touch event, it will handle it. There isn't a sane way to 'reject' the event based on the swiping motion after it, regardless of the `behaviour` setting. The case you're proposing frankly isn't implementable.
