### ISSUE TITLE
Weird behaviour of the "Custom connect" example when clicking to set handle positions

### ISSUE THREAD

**Issue by wopian** [leongersen/noUiSlider#584]
The [custom connect](http://refreshless.com/nouislider/examples/#section-custom-connect) example behaves weirdly when you click to set handle positions. 

Dragging the handles snaps the bar back into the correct place - but only for the side you're dragging. 

![](https://zippy.gfycat.com/PlaintiveImportantAvocet.gif)

Happens on Chrome 47.0.2526.106 m (64-bit)

**Comment by tannerhodges** [comment]
Looks like this is an issue with the Tap behavior—seeing it across browsers:

- Bar doesn't show up until you set both handles
- Tapping the slider causes the position error
- Dragging the handles fixes the positions

**Comment by tannerhodges** [comment]
Gonna take a deeper look at this today, but some more observations:

- Bar is being set to previous value
- Using the `change` event instead of `update` resolves the position issue

**Comment by tannerhodges** [comment]
It's a timing issue:

- `slide` fires before the DOM is updated, so `offset` is set the previous value
- `update` doesn't fire on `end`, so when `slide` misses the final position it's never resolved

Will put an example together later today.

**Comment by tannerhodges** [comment]
Sorry for the delay—caught in a project deadline this week.

Originally I used a `setTimeout` to patch the issue, but that was a bit unstable (and difficult to replicate when it didn't fire on page load).

I realized the handle styles are applied in a `window.requestAnimationFrame`, so I'm trying that now to see if it fixes the issue.

For example (note, I'm not supporting IE 10):

    slider.noUiSlider.on('update', function(values, handle) {
      window.requestAnimationFrame(function() {
        updateCustomConnect(values, handle, connectBar, connectHandles);
      });
    });

**Comment by leongersen** [comment]
This is fixed in the documentation now. The example is shorter and performs better, too! You'll need version 8.3.0, which adds a new event argument. I've also [added a note](https://refreshless.com/nouislider/events-callbacks/#section-note) about this to the documentation: using the `style` properties on the `handles` won't work due to the use of `requestAnimationFrame`.
