### ISSUE TITLE
Get Current Slider Settings/Options v8.x

### ISSUE THREAD

**Issue by Tekanewa** [leongersen/noUiSlider#585]
With v7.x, one could retrieve the current slider options/settings simply via ...

var opts = $(".slider").noUiSlider("options");

... but I can't find anything similar with v8.x.

Any help would be appreciated!

Thank you!

**Comment by leongersen** [comment]
The slider no longer modifies the options variable that is passed to it, so you can store the options in a variable and use them later.

**Comment by johndubya** [comment]
I was about to ask the same question as Tekanewa. I don't want to modify the options variable; I want to **read** the options variable.

In my case with v7.x, I use the values of range.min and range.max from each slider (from a call like `$("#price").noUiSlider("options")`), which I am not able to do with v8, that I can tell. I've got three sliders on a page, and I will not be keeping three global vars to store the options for each slider. It would be easiest to just simply be able to read the options of each slider. Something like:

    var slider = document.getElementById("price"); //assume noUiSlider.create() has already been run on this
    var options = slider.options;
    console.log(options.range.min + " to " + options.range.max);`

**Comment by leongersen** [comment]
that makes sense, we can add it.

**Comment by johndubya** [comment]
That's awesome, @leongersen, thank you!

**Comment by johndubya** [comment]
Forgive me, as I am not familiar with making changes to a Git project, but I believe I got the `options` variable publicly available by simply adding it to scope_Self:

    scope_Self = {
        destroy: destroy,
        steps: getCurrentStep,
        on: bindEvent,
        off: removeEvent,
        get: valueGet,
        set: valueSet,
        updateOptions: updateOptions,
        options: options
    };

Is that right?

**Comment by leongersen** [comment]
Yes, that's it. Feel free to make a pull request

**Comment by johndubya** [comment]
I believe I just made my first pull request. :) Did I do it right?

**Comment by leongersen** [comment]
I'm afraid not: I don't see it yet:

https://github.com/leongersen/noUiSlider/pulls

I **do** see the commit in your clone:

https://github.com/johndubya/noUiSlider/commit/30e20f7c675b90bbb629ad138f494bafe5ada30f

**Comment by leongersen** [comment]
I've merged this. Thanks :)
