### ISSUE TITLE
Interchangeable lower and upper handle

### ISSUE THREAD

**Issue by gogibob** [leongersen/noUiSlider#586]
It will be good to have interchangeable handles because when you want to select one value from the interval you will have the both handles in the same place. As a result if you want to go back to the initial state you did not know witch handle is on the top and need to try if the handle give possibility to go to the right or to the left. If the handles were interchangeable the issue will not present. 

It is more a feature, but one that affect the User experience.

**Comment by leongersen** [comment]
I'm closing this issue, as it is not a feature I intend to implement, there seems to be no additional interest beyond the initial request, and I'm trying to clear the issue tracker. If there is further interest in a feature like this, feel free to comment - I'll reopen this issue. I'm also open to pull requests.
