### ISSUE TITLE
On click slide to next

### ISSUE THREAD

**Issue by Bobz-zg** [leongersen/noUiSlider#587]
Hi,

Is there an option to make 'on click', slide to next/prev value?
I cannot see that sort of thing in docs.

I have managed to make it work because my slider has equal steps, then I can do +/- step.

```javascript
$('.amount .slide').click( function(event) {
  if(event.preventDefault) {
    event.preventDefault();
  }

  if( $(this).data('action') === 'minus' ) {
    slideto = parseInt( slider_amount.noUiSlider.get().replace(/\D/g,'') ) - 50;
  }
  else {
    slideto = parseInt( slider_amount.noUiSlider.get().replace(/\D/g,'') ) + 50;
  }

  slider_amount.noUiSlider.set( slideto );
});
```

**Comment by leongersen** [comment]
Yes, you can call `slider.noUiSlider.steps()`. An example is here:

http://refreshless.com/nouislider/examples/#section-keypress

**Comment by Bobz-zg** [comment]
Hi Leon,

Thanks for the answer, I have seen this. But I don't understand what should I do, sorry.
If I understand well this works if 'step' is defined, and it will increase slider by 'step' value, or it will go to entered value.
I have done it in my way, like:
```
// My steps
steps   = [ 1,3,6,9,12,18,24,36 ];

// Get index position of current slider value
current = $.inArray( parseInt( slider_period.noUiSlider.get().replace(/\D/g,'') ), steps );

// Get previous/next step from array
if( $(this).data('action') === 'minus' ) {
  slideto = steps[ current - 1];
} else {
  slideto = steps[ current + 1];
}

// Set slider value
slider.noUiSlider.set( slideto );
```
However example on page doesn't work for me, on OSX, Chrome/Firefox Latest.
I enter 400, hit enter, and nothing happens.
Not sure if I'm doing something wrong, or..

**Comment by leongersen** [comment]
The example was broken, I didn't notice. Fixing it now.

**Comment by leongersen** [comment]
It's fixed. Thanks for reporting!
