### ISSUE TITLE
Disabled handle prevents - impossible to click near disabled handler

### ISSUE THREAD

**Issue by FDiskas** [leongersen/noUiSlider#589]
I got 
```js
noUiSlider.create(element[0], {
                        start: [0, 100],
                        step: 1,
                        range: {
                            min: [0],
                            max: [100]
                        }
                    }).on('change', function( value ) {
                        console.log('Clicked and changed');
                    });
element[0].getElementsByClassName('noUi-origin')[1].setAttribute('disabled', true);
```
So the second handler is disabled. Now I'm trying to click on slider near the second handler and nothing happens. If I click closer the first handler the value is changed corectly.
I think that if the handler is disabled only the first handler must change the value and no mater where I click.
The problem I think is here 
https://github.com/leongersen/noUiSlider/blob/master/src/js/scope_events.js#L228

How can I allow to change the first handle value no mater where I click?

**Comment by FDiskas** [comment]
Here is a demo: https://jsfiddle.net/xvfoe568/1/

**Comment by leongersen** [comment]
Makes sense, I'll merge this in.

**Comment by FDiskas** [comment]
Updated distribute files
