### ISSUE TITLE
How to update pips

### ISSUE THREAD

**Issue by sentenza** [leongersen/noUiSlider#594]
Is also possible to call `noUiSlider.updateOptions()` for updating the pips scale values? I've tried to set the `pips` element again but my HTML does not change.

**Comment by denism7** [comment]
AFAIK you should rebuild the slider or update the pips manually element by element.

However, I think we need a function to update the pips without affecting the slider.

**Comment by sentenza** [comment]
So, I need to remove the component and rebuild it, each time I need to update pips? I think it should be possible at least to build different pips scales and swap between them.

My problem is to build a tab based layout on which I can pre-set the slider with correct values and proceed from a tab to another one.

**Comment by denism7** [comment]
Yes, you need to destroy existing slider and create a new one. I agree with you, it's a bit weird. It would be nice to have noUiSlider.createPips() method for seamless update and ability to create several scales.

**Comment by leongersen** [comment]
The pips method shouldn't be hard to expose, it's completely decoupled. See [the call](https://github.com/leongersen/noUiSlider/blob/master/src/js/scope.js#L274) to the pips function. I can add it to the public API. I guess it would make sense the remove any existing pips when a new set is created?

**Comment by denism7** [comment]
I guess it will be better to keep existing pips, since removal can be done in single line of code, but sometimes we need several pips scales. Alternatively, you can simply add optional keepExistingPips parameter for these scenarios.

**Comment by leongersen** [comment]
The `pips` function is now exposed as `slider.noUiSlider.pips`. Thanks for thinking along, everyone :)
