### ISSUE TITLE
is there a way to get to the element that triggered the nouislider event?

### ISSUE THREAD

**Issue by robkorv** [leongersen/noUiSlider#597]

**Comment by robkorv** [comment]
Hi!

I have an example over here https://github.com/robkorv/nouislider-events.
The situation is that I have some generated elements that are turned into nouisliders onload with an attached event.

index.html
```html
<!DOCTYPE html>
<html>
<head>
    <title>How do I know which slider triggered?</title>
    <script type="text/javascript" src="bower_components/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="bower_components/nouislider/distribute/nouislider.min.js"></script>
    <link href="bower_components/nouislider/distribute/nouislider.min.css" rel="stylesheet">
</head>
<body>
    <h1>Slider 1</h1>
    <div data-slider='{"start":[20,80],"connect":true,"range":{"min":0,"max":100}}'></div>
    <h1>Slider 2</h1>
    <div data-slider='{"start":[0,10],"connect":true,"range":{"min":0,"max":100}}'></div>
    <pre id="log">
    </pre>
    <script type="text/javascript" src="mystuff.js"></script>
</body>
</html>
```

mystuff.js
```javascript
var doSomething = function ( values, handle, unencoded, tap ) {
    // Here i want to know which slider triggered
    var $log = $('#log');
    $log.html(JSON.stringify({ values: values, handle: handle, unencoded: unencoded, tap: tap}, null, 4));
};

var initSliders = function (index, element) {
    var $slider = $(element);
    var sliderOptions = $slider.data('slider');
    noUiSlider.create(element, sliderOptions);
    element.noUiSlider.on('update', doSomething);
};

var init = function() {
    var $sliders = $('[data-slider]');
    $sliders.each(initSliders);
};

$(init);
```

In `doSomething` I want the slide element that triggered the event, is this possible?

**Comment by robkorv** [comment]
@leongersen, can you pitch in? For what a read in the source and the docs I should also generate javascript functions for every slider, because the event doesn't contain any references to the element that triggered it.

Is this correct or is there another solution for this use-case?

**Comment by leongersen** [comment]
Sorry, I've been crazy busy. You can use `this` in the event, which contains the slider's public API.

Quoting the [docs](http://refreshless.com/nouislider/events-callbacks/):

    "For all events, this is set to the current slider's public API, containing (among others) the 'get' and 'set' methods."

**Comment by robkorv** [comment]
Tnx @leongersen for putting me in the right direction, when I alter `scope_Self` like this:

```javascript
	scope_Self = {
		destroy: destroy,
		steps: getCurrentStep,
		on: bindEvent,
		off: removeEvent,
		get: valueGet,
		set: valueSet,
		updateOptions: updateOptions,
		currentTarget: scope_Target
	};
```
I can use `this.currentTarget` to get the element that triggered the update.
Are you interested in a pull request for this?

**Comment by leongersen** [comment]
I'll add it in, working on some other pull requests right now.

**Comment by robkorv** [comment]
Great! :+1: Thank you.

**Comment by leongersen** [comment]
You can now use `this.target` in 8.3.0. Thanks for reporting this!
