### ISSUE TITLE
Can't float slider

### ISSUE THREAD

**Issue by Worldindustry91** [leongersen/noUiSlider#598]
I want to have text to the left side of the slider. The best way to do this would be to float the slider and the text and clearfix the container element. When I float the slider, however, it collapses. I've tried using more than one container, and many other techniques such as using display: inline-block. Every technique that I try, however, results in the slider getting collapsed.

**Comment by Worldindustry91** [comment]
So the strangest thing happened. As soon as I wrote this comment... my code started working. I've been tinkering with this code for a while. I even tinkered around with jQuery UI slider and the same thing was happening. I tried everything and nothing worked (both floats and inline-block).

Then I come back to my code (without making any major changes), and it worked exactly as expected. I'm closing the issue, but I was wondering whether you could maybe shed some light on why this happened. Could there have been a single property that was disrupting everything?

**Comment by leongersen** [comment]
There's two things I think might have happened:
- Browser cache. Bitten me more than once ;)
- You changed *which* element you are floating. Is it `.noUi-target` or its parent? I'd recommend the latter. Also, when floating, you can use `display: table` to prevent the element collapsing.

Sorry for the delay in my answer!
