### ISSUE TITLE
Can't update start property when calling updateOptions

### ISSUE THREAD

**Issue by johndubya** [leongersen/noUiSlider#602]
In version 7.x, we would make a call to update a slider and would update the range _and_ the start.

For example, a price slider would have a range of 0 to 20000 and start at the same (`[0, 20000]`). Later, on the same page, we would update the slider with new options, like changing the range to 10000 to 50000, and when updating, it needs to change the start to `[10000, 50000]` as well.

In version 8.x, it seems that we can only update the range of a slider. What this means is that the slider maintains the old values, which may not even be valid any more. It also means we would have to call the `.set()` method to update the values of the slider after changing the range. But for us, when we call `.set()`, it runs filters on a data source, so this would trigger extra unnecessary processing that didn't occur in version 7.

Are we missing something with how to implement this correctly, or does v8 just not allow for our scenario?

Thanks for this awesome plugin, leongersen!

**Comment by leongersen** [comment]
This is a valid scenario, which is why it was supported in 7.x. I'm adding it back in the next release. Sorry for the delay in my response.

**Comment by leongersen** [comment]
You can now (as of 8.4.0) pass [`values` as a property in `updateOptions`](http://refr.less/nouislider/more/#section-update). That function also supports a new argument, `fireSetEvent`, which takes a boolean. Thanks for this suggestion!
