### ISSUE TITLE
Suggested improvement: rename 'postfix' to 'suffix'

### ISSUE THREAD

**Issue by rorysmorris** [leongersen/noUiSlider#603]
The opposite to 'prefix' is 'suffix' but in noUiSlider it's labelled as 'postfix', I guess it'd be logical to change this to 'suffix'.

Not essential, but it makes sense to change it in my opinion.

**Comment by leongersen** [comment]
This was a wNumb issue, but I've fixed it there. Thanks!

**Comment by Abelilito** [comment]
@leongersen Hello Leon. Con you help me please. I have a problem with my Nouislider. I would like to have this `€100` for English and `100€` for french. I tried this but it doens't work. 

`
noUiSlider.create(master_slider, {
    start: [start_value],
    tooltips: [true],
    range: setRange(min_invest, max_invest, unit_price),
    format: wNumb({
      decimals: 2,
      thousand: delimiter,
      mark: separator,
      undo: function(value) {
        if (format === '%u&nbsp;%n') {
          return unit + '&nbsp;' + value;
        } else {
          return value + '&nbsp;' + unit;
        }
      }
    })
  });
`

**Comment by leongersen** [comment]
@Abelilito Your question seems unrelated to this issue, please open a new issue for new questions.
