### ISSUE TITLE
Update value manually without snapping to closest value

### ISSUE THREAD

**Issue by emmet1982** [leongersen/noUiSlider#605]
Hey,

Is there a way to have the slider snap to values, BUT when updated manually using an input it doesn't snap to the nearest value but just slides to the exact value entered in the input?

Basically my client wants to snap between values, but allow the user to also have the option of manually adding any value within the range if they want.

Thanks

**Comment by leongersen** [comment]
I've [answered this question before](http://stackoverflow.com/questions/26062335/nouislider-adjusting-rounded-input-values/26073155#26073155) using the jQuery version of noUiSlider. I'll rewrite it and add it to the docs.

**Comment by emmet1982** [comment]
Hey,

No problem and thank you for responding. Couldn't figure out from the jQuery version the correct approach, is guard still a valid variable in the current version?

Thanks

**Comment by emmet1982** [comment]
Used a combination of the updateOptions method to temporarily turn snap on and off when using the input to update a custom figure.

Thanks
