### ISSUE TITLE
optional requestAnimationFrame() usage

### ISSUE THREAD

**Issue by tommoze** [leongersen/noUiSlider#606]
Hey,
On iOS then destroying and creating slider there's a flicker while handler gets it's value using requestAnimationFrame() on setHandle method, maybe there could be an option on rAF usage, or anybody know some work around how I could solve my problem.

**Comment by leongersen** [comment]
Yeah, that's the cost of completely rebuilding, I'm afraid. What option are you updating?

**Comment by tommoze** [comment]
Main problem was on iOS Safari, if I was using slider handle and destroy() method is called on slider - browser got stuck. Mainly I have update the range, so I guess I have to go with updateOptions method and not bother anymore.
Anyway thanks for great library and a quick response

**Comment by leongersen** [comment]
`updateOptions` now supports all options that can be updated without rebuilding the DOM, so I think this has become redundant. Thanks for the report, it might point others to `updateOptions`.
