### ISSUE TITLE
How to get options form the instance?

### ISSUE THREAD

**Issue by stratboy** [leongersen/noUiSlider#607]
Hi! I need to get the range after instantiation. Something like this:

slider.noUiSlider.get('range');

Or similar.. I saw you pointed some other user to http://refreshless.com/nouislider/more/#section-options but there's not real infos about this specific issue.

**Comment by leongersen** [comment]
`slider.noUiSlider.options.range` contains your initial setting.

**Comment by stratboy** [comment]
Thank you, but It gives me undefined. And if I check the whole object I get this:

```
animate true
connect 0
dir 0
events Object { tap=true,  drag=false,  fixed=false,  altri elementi...}
format wNumb { to=function(),  from=function()}
handles 2
limit 0
margin 0
ort 0
pips undefined
spectrum Spectrum { xPct=[2],  xVal=[2],  xSteps=[2],  altri elementi...}
start [24, 190]
style "left"
```

So no range property. My init is this:

``` javascript
noUiSlider.create(slider, {
  start: data.values
  ,behaviour: "tap"
  ,format:wNumb({
    mark: '.',
    thousand: '',
    prefix: '',
    postfix: '',
    decimals: 0
  })
  ,range: {
    'min': data.min,
    'max': data.max
  }
});
```

The slider works properly.

**Comment by leongersen** [comment]
This is a bug, I've written the parsed options to `slider.noUiSlider.options`, instead of the original set. Fixed in next release.

**Comment by nuke123** [comment]
I'm trying to set endless max range but having a similar issue where get('range') returns the value same as get(). 

```javascript
slider.noUiSlider.on('end', function() {
    // Increase max range at 95%
    if (slider.noUiSlider.get() >= slider.noUiSlider.get('range') * .95) {
    	slider.noUiSlider.updateOptions({
            range: {
            	'min': slider.noUiSlider.options.range.min,
            	'max': slider.noUiSlider.get('range') * 2
            }
        });
    }
});
```
