### ISSUE TITLE
Handler

### ISSUE THREAD

**Issue by PirataNervo** [leongersen/noUiSlider#608]
![ranger](https://cloud.githubusercontent.com/assets/1008807/13142628/a125fec0-d63e-11e5-8928-28b94f40b642.png)

I'm having this problem. It should start at the left, but it doesn't, and I cannot drag it beyond that point (to the left). Dragging to the right works fine and stops at the end.

The example at the bottom here: http://refreshless.com/nouislider/slider-read-write/ works fine so it shouldn't be a browser problem.

`
<td align="center" class="trow2">
	
		<div style="margin: 20px">
			<div id="slider-format-1" class="noUi-target noUi-ltr noUi-horizontal noUi-background"><div class="noUi-base"><div class="noUi-origin" style="left: 0%;"><div class="noUi-handle noUi-handle-lower"></div></div></div></div>
		</div>
		
		<br>
		
		<form method="post" action="mysubscriptions.php">
			<input type="hidden" value="1" name="sid">
			<input type="hidden" value="c457bdbabf7e44990d57948f893a93dc" name="my_post_key">
			
			US Dollars:<br>
			<input type="text" style="margin: 5px" class="textbox" id="input-paypal-1"><br>
			
			Points:<br>
			<input type="text" style="margin: 5px" class="textbox" id="input-newpoints-1"><br>
			<input type="submit" style="margin: 5px" class="button" value="Proceed" name="submit">
		</form>
	
		<script type="text/javascript">
			var sliderFormat = document.getElementById('slider-format-1');

			noUiSlider.create(sliderFormat, {
				start: [ 0 ],
				step: 10,
				range: {
					'min': [ 0 ],
					'max': [ 500 ]
				},
			});
			
			var inputPayPal = document.getElementById('input-paypal-1');

			sliderFormat.noUiSlider.on('update', function( values, handle ) {
				inputPayPal.value = 5-values[handle]/100;
				
				inputPayPal.value = Math.round(inputPayPal.value * 100) / 100;
			});

			inputPayPal.addEventListener('change', function(){
				sliderFormat.noUiSlider.set(this.value);
			});
			
			
			var inputNewPoints = document.getElementById('input-newpoints-1');

			sliderFormat.noUiSlider.on('update', function( values, handle ) {
				inputNewPoints.value = values[handle];
			});

			inputNewPoints.addEventListener('change', function(){
				sliderFormat.noUiSlider.set(this.value);
			});
		</script>
	</td>
`

The first text box represents the payment in US dollars (default is full amount). The points represents the handle - when to the right, we have max points and zero US dollars; when to the right, we have max US dollars and zero points.

Any idea why might this be happening?

**Comment by leongersen** [comment]
I missed this issue, but it should have gone to a support/question platform like http://stackoverflow.com
