### ISSUE TITLE
Time range

### ISSUE THREAD

**Issue by Subramaniyan** [leongersen/noUiSlider#610]
Hi,

is there a easy way to get steps by time.

For example slider range from 12.AM TO 11.59PM and steps by 30 minutes.

can i use this in angularjs script?

Best, 
maniyan

**Comment by leongersen** [comment]
Yes, you'd use the `format` option to get the values you need. To get a more detailed answer, I recommend posting to a forum with a wider audience, such as http://stackoverflow.com/. Include the code you've already tried.
