### ISSUE TITLE
Accidentally moving slider when scrolling on touch

### ISSUE THREAD

**Issue by mattra** [leongersen/noUiSlider#613]
On a touch device it is possible to accidentally set the slider value when scrolling down a page if the digit is placed on the body of the slider. Would it be possible to prevent this? Alternatively is it possible to prevent touch on the slider body (so that only dragging the handle works). The example I am using only uses one handle.

**Comment by leongersen** [comment]
You can use the `behaviour` option to disable the tap-to-move feature when 'clicking' the slider.

**Comment by mattra** [comment]
I did try this - I had this working in previous version of nouislider but it seems not to work in latest. I've created a jsfiddle here - https://jsfiddle.net/yrb1f7qv/5/ . If you remove the behaviour line it works. Is it failing because there is only one handle (the docs for 'drag' seem to refer to examples where there are >1 handle)
