### ISSUE TITLE
long number rounding error

### ISSUE THREAD

**Issue by serGlazkov** [leongersen/noUiSlider#614]
Hello, i initialize slider with data
```
var settings = {
  connect: "lower",
  range: {
    max: 87654567890,
    min: 0
  },
  start: 30679098762,
  step: 1
}
```
after initialization slider value is 30679098761.50 why?
Demo here - https://jsfiddle.net/serGlazkov/yrppsmvo/5/

**Comment by leongersen** [comment]
Numbers that large cannot be accurately represented on the sliders width. Have a look at [this example in the docs](http://refreshless.com/nouislider/examples/#section-huge-numbers) of how to deal with it.

**Comment by serGlazkov** [comment]
On initialization i set a integer value and why slider change it? I know what slider change value, because translate value to percent and back, and it not bad, but not on initialization. And more, i can't set value, plugin change it. Demo here https://jsfiddle.net/serGlazkov/yrppsmvo/6/

**Comment by leongersen** [comment]
I've made some changes to the way decimals are handled, which resolves this issue. Thanks for the test case!

**Comment by tsirilson** [comment]
How limited is the slider then? What the width/range combination that starts causing this problem? Not even numbers below 50,000 are calculated correctly.

**Comment by leongersen** [comment]
The bug mentioned here is resolved, so the slider properly maintains values `set` to it. In most browsers, the user can select to 1-pixel accuracy, so in practice the range will allow as many steps as the range is wide, in pixels.
