### ISSUE TITLE
Margin with non-linear slider

### ISSUE THREAD

**Issue by joeldavuk** [leongersen/noUiSlider#615]
Hi,

I've come up with a solution for a margin on a non-linear slider and would be grateful if anyone could code review, the only minor issue i've noticed is when you do get to the margin there is a slight stickyness no doubt due to the many if statements.

https://jsfiddle.net/joeldav/rqeup9kr/8/

**Comment by leongersen** [comment]
There is a lot of seemingly unrelated code in the fiddle. I could have a look at it, but could you reduce the example to its essence? Sorry for the delayed follow up!

**Comment by leongersen** [comment]
Closing for lack of response. Feel free to reopen.
