### ISSUE TITLE
Wrong event order?

### ISSUE THREAD

**Issue by FDiskas** [leongersen/noUiSlider#618]
Its impossible to update the slider value by clicking or dragging if there is an set() function is running at the same time.
example: https://jsfiddle.net/czb48y3e/
Probably on clicking or dragging needs to dismiss the set() or other method for setting or updating the slider values.

**Comment by leongersen** [comment]
Why are you running `set` in a `setInterval`? Is there a practical use case or just as example. Sorry for the delayed follow up.

**Comment by FDiskas** [comment]
Its just an example. I'm using this plugin with angularjs. Angular is updating the value about 1s intervals.
As the result I need to see the progress as progress bar but have ability to change the value by dragging.

**Comment by zenorocha** [comment]
I'm having the same issue. A practical use case is a audio progress bar, where you have to call `set` every second.

![slider](https://cloud.githubusercontent.com/assets/398893/16596928/0ea5baac-42ab-11e6-9a83-39c8829ee147.gif)

**Comment by leongersen** [comment]
setting `animate: false` should help with that case.

**Comment by zenorocha** [comment]
It worked! Thanks @leongersen :)

**Comment by FDiskas** [comment]
It's worked for me to. Thanks.
