### ISSUE TITLE
Update options breaks step option

### ISSUE THREAD

**Issue by ram-one** [leongersen/noUiSlider#619]
https://jsfiddle.net/79ubw0of/1/
When slider options are updated, the step option is no longer used.
A workaround is to update the slider with step.
```slider.noUiSlider.updateOptions({ range: { max: 200 ,min: 0 }, step :50 });```

**Comment by cesarve77** [comment]
same issue

**Comment by leongersen** [comment]
This is fixed, thanks for the report!
