### ISSUE TITLE
Update Range option doesn't update pips

### ISSUE THREAD

**Issue by dapriett** [leongersen/noUiSlider#620]
Hello,

Saw a bug where the pips are not getting recreated when you change the range options (set a new min/max).

Thanks!

**Comment by dapriett** [comment]
As a workaround I destroy and recreate the slider whenever I need to update the range.

**Comment by derouck** [comment]
I have a similar issue. When I change the range the direction rtl is not set anymore.

**Comment by cesarve77** [comment]
same issue here

**Comment by leongersen** [comment]
As per issue #594, the pips API is exposed and new pips can be (re)generated on demand. This isn't done by default for performance reasons. To update pips:

```
// Remove current pips
var p = slider.querySelector('.noUi-pips'); p.parentElement.removeChild(p);
// Add pips with current options (or pass new options)
slider.noUiSlider.pips(slider.noUiSlider.options.pips);
```
