### ISSUE TITLE
Accessibility 

### ISSUE THREAD

**Issue by mike-nelson** [leongersen/noUiSlider#621]
This is a nice slider which I am currently using in my Cordova app Speaking Email. It works well on mobile html5 app. 

However... It would be great if noUiSlider supported aria accessibility. It doesn't appear to unless I am mistaken? I'm doing an accessibility upgrade so will need to change this component out if it's too hard to make it accessible.

**Comment by leongersen** [comment]
My \*official\* recommendation: Add properly labelled `<input>` elements.

**Comment by leongersen** [comment]
Merging to #685.
