### ISSUE TITLE
on update - there is no position value

### ISSUE THREAD

**Issue by axelf** [leongersen/noUiSlider#622]
Hi,

like in the documentation, there are 5 paramters in the callback-function for the update event. (values, handle, unencoded, tap, positions). For positions i get always undefined. Is this a bug or do i misunderstand something?

**Comment by axelf** [comment]
Hi,

i used Version 8.2.0 and by updating to version 8.3.0 it worked :-)

**Comment by leongersen** [comment]
Glad it worked out ;)
