### ISSUE TITLE
Only use step if directly interacting with slider

### ISSUE THREAD

**Issue by thisispiers** [leongersen/noUiSlider#623]
I'd like to be able to set and use a non-step value that the user types explicitly into a nearby textbox.

Otherwise, if they drag or click on the slider it should snap to the nearest step.

Any thoughts on this as a feature? Any possible workarounds in the meantime?

**Comment by leongersen** [comment]
Merging this with #627.

**Comment by leongersen** [comment]
This is available by passing true for the third argument (`exactInput`) to `set`:

https://refreshless.com/nouislider/slider-read-write/#section-setting
