### ISSUE TITLE
Disable handlers with attributed "disabled" is not w3c valid

### ISSUE THREAD

**Issue by KingSora** [leongersen/noUiSlider#625]
Hi!

First of all, very nice library, its perfect for the project I am currently working on.
I've just found some "issue" in disabling handlers / the whole slider.
In your example you're doing it with the attribute "disabled="true" or just "disabled". There is no issue on the function, its working great, with this attribute the handlers / the slide gets disabled and you cant move it anymore.

But if you validate your HTML with the official w3c markup validation service (https://validator.w3.org/#validate_by_input) you will get errors, because this attribute isn't allowed on div elements.

I would suggest using a "data-*" attribute or even a class for this.
I hope you understand the point and you will update this soon :)

Best regards,
Sora

**Comment by leongersen** [comment]
Thanks Sora! Are you using the project anywhere public? I always like to see public examples.

I understand the concern with w3 validation, but I doubt it *really* matters. In my opinion, using the plain `[disabled]` attribute is easier to understand and to style than a random `data-` attribute. If this really is an issue, it could probably made configurable rather easily:

https://github.com/leongersen/noUiSlider/search?utf8=%E2%9C%93&q=disabled

**Comment by KingSora** [comment]
The project is not public yet, but I can inform you If it will be launched. :)

Yeah, I understand your logic behind the "disabled" attribute, its really easy to understand and to use.

In the end it is your choice if you will change this or not... I just thought it would be nice for everyone to have a fully valid HTML.

You could also add this as an alternative (disabled AND data-disabled for example), so everyone could choose and users which are just updating your plugin in their projects must not change anything.

Thanks for your answer mate :)

**Comment by leongersen** [comment]
Making a connection to #685.

**Comment by leongersen** [comment]
I'm not planning to work on the change requested here, so I'm closing this issue. I'm open to further discussion or a pull request, but that'll have to be in a new issue.
