### ISSUE TITLE
Custom Slider

### ISSUE THREAD

**Issue by mrTBBW** [leongersen/noUiSlider#626]
Hi Leon,

Working with your slider, super !
I would like to change the standard look to custom look.
an image for the handle one for the background and one for the movement part.
I tried the last two/three weeks to make a working sample, but i'm unable to succeed...
would you be so kind to make a workings sample, so I can see where I go wrong.
I use IE

Best Regards,

Gerwin, the Netherlands.

![background](https://cloud.githubusercontent.com/assets/13126038/13952216/7ff8541c-f035-11e5-8ce9-c749c35e4c4e.png)
![handle](https://cloud.githubusercontent.com/assets/13126038/13952215/7ff4fede-f035-11e5-8de8-95b2bb2fb0f6.png)
![inset](https://cloud.githubusercontent.com/assets/13126038/13952214/7ff37a0a-f035-11e5-88bc-3dec2210cc89.png)

**Comment by leongersen** [comment]
First of, what have you tried? Try setting up a https://jsfiddle.com or the like, so I can see what you did. I can hardly start doing everyone's work for them on demand. Second, this would be the kind of question to ask on a more public forum, such as https://stackoverflow.com, not in an issue tracker. As a bonus you'll get an answer a lot quicker :)
