### ISSUE TITLE
Use steps but having a fluid drag

### ISSUE THREAD

**Issue by danieljuhl** [leongersen/noUiSlider#627]
I was wondering if it is possible to have step values/ranges of step values, but still have a fluid drag experience. What I would like to accomplish is that the drag is fluid, and that the handle can be placed anywhere (no snapping), but only emits an event with the updated value, when the value changes (based on the ranges and steps).

As far as I can see, this feature is not in the library at the moment. Right?

**Comment by leongersen** [comment]
So basically, you want to 'round' the slider output to the nearest step?

**Comment by danieljuhl** [comment]
Yes, right now, the slider is visually snapping to the steps, but I would like it to move fluid between the steps in the ranges, but only output the nearest step.

**Comment by leongersen** [comment]
Are you steps linear?

**Comment by danieljuhl** [comment]
No... I have a sample here:

```
{
  'min': [0, 2],
  '35%': [10, 5],
  '50%': [25, 5],
  '75%': [50, 10],
  'max': [100]
}
```

**Comment by cesarve77** [comment]
probably  you are updating the options, and losing the step, see
https://github.com/leongersen/noUiSlider/issues/619

**Comment by danieljuhl** [comment]
@cesarve77 I don't think so... first, I'm not updating the options, and second, I read that issue as the opposite. I need the slider to slide without steps, but return values as steps.

**Comment by danieljuhl** [comment]
@leongersen are you willing to accept a PR if I give it a shot?

**Comment by leongersen** [comment]
Absolutely. I think you basically want to feed [`valueGet`](https://github.com/leongersen/noUiSlider/blob/master/src/js/scope.js#L146) through [`toStepping `](https://github.com/leongersen/noUiSlider/blob/master/src/js/range.js#L223). Shouldn't be too hard. What API would you propose?

**Comment by sjelfull** [comment]
If I understand your request correctly, @leongersen, I was about to ask for the same.

Look at example here: http://jmp.sh/nDH5TIE

You notice that there is an abrupt snapping between the points. I think it would be more user-friendly if it was moving smoothly between the steps, and snapping to the near point only if you let go. As it is now, if you want steps, it can't.

Heres another example: http://jmp.sh/cWQbhQx

**Comment by rmbaumer** [comment]
I'm looking for this functionality as well. Any update on this?

**Comment by rejas** [comment]
I'm currently wishing for the opposite issue (which was mentioned in https://github.com/leongersen/noUiSlider/issues/623 and is merged into this). So anyone working on this orwhats the common status?

**Comment by phpanos** [comment]
I'm also looking for this feature.

**Comment by heilwood** [comment]
is it any update on this feature?

**Comment by leongersen** [comment]
I've just added this in noUiSlider 15.6.0. There is a new [`smooth-steps` `behaviour` flag](https://refreshless.com/nouislider/behaviour-option/#section-smooth-steps), which implements this feature.

**Comment by prabathgamage** [comment]
What is the version of Jquery, which the current version of nouislider compatible with?
