### ISSUE TITLE
Range equals

### ISSUE THREAD

**Issue by danieljausovec** [leongersen/noUiSlider#633]
Hi.

In version 8.1.0 i set equal range and works perfect.
Example:

```
noUiSlider.create(slider, {
	start: minValue,
	step: interval,
	connect: 'lower',
	range: {
		min: 30,
		max: 30
	}
});
```

Now i update plugin to version 8.3.0 and get this error: Error: noUiSlider: 'range' 'min' and 'max' cannot be equal.

How to fix this in new version?

**Comment by leongersen** [comment]
by not passing the same values? Why are you doing that?

**Comment by danieljausovec** [comment]
Because i create dynamical sliders and some values (range) are equals.

Example:
I change with one slider range in other slider and start value is equal.

**Comment by leongersen** [comment]
Catch it before init. The user can't change the slider anyway. Either hide the UI element altogether, or display a message.

**Comment by leongersen** [comment]
Closing, see #236.
