### ISSUE TITLE
More than 10 pips wrong on Chrome

### ISSUE THREAD

**Issue by daniele-castellini** [leongersen/noUiSlider#634]
Hi,
thanks for you plugin. I have this problem: in my implementation I need a variable number of pips and range mode. Something like this: https://jsfiddle.net/castellinid/smbe0ysb/
In browsers like Firefox and Safari everything is ok but in Chrome (also Opera) when I have more than 10 pips, not all pips are drawn and range max (100 in my example) is not selectable.

If I reduce pips (eg < 10) Chrome behavior is perfect.

My wish is to have Firefox and Safari behavior also in Chrome.

Does anyone know how to fix this issue?

**Comment by leongersen** [comment]
Ok, first off, if you are submitting an issue, reduce the code to the **absolute minimum**. Now I have to dig through *trying*  to figure out what all of it does.

I ran your code, and it generates a range like this:

```
range: {"min":[0,10],"10%":[10,20],"20%":[20,30],"30%":[30,40],"40%":[40,50],"50%":[50,60],"60%":[60,70],"70%":[70,80],"80%":[80,90],"90%":[90,100],"max":100}
```

This doesn't look right. `"70%":[70,80]` means, loosely translated: *70% of the sliders range should be at 70% of the sliders' width, increasing by increments of `80`.* That doesn't work, because the next step is at the value of 80.

What I *think* you mean to do is:

```

noUiSlider.create(slider, {
	connect: true,
	range: { min: 0, max: 100 },
	start: [0, 100],
	step: 10,
	pips: { mode: 'steps' }
});
```

![image](https://cloud.githubusercontent.com/assets/1206361/14580800/34fc3d3a-03da-11e6-80f3-a751776d37b7.png)

**Comment by daniele-castellini** [comment]
That was just an example. I use noUiSlider like a price range filter and I can't have fixed steps like you did in quoted code. I must specify ranges in range property.

For example:

`{ min: [0,140], '9%': [140, 150], '18%': [150, 160], '27%': [160, 170], '36%': [170, 180], '45%': [180, 190], '54%': [190, 200], '63%': [200, 220], '72%': [220, 230], '81%': [230, 260], '90%': [260, 290], 'max': 290 }`

Trust me, I reduced my code to the minimum, but I left it dynamical like really it is because I can have lots of combinations of price ranges. Of course, since you can't really inspect every bug through each single step, this is the minimum you asked:

https://jsfiddle.net/smbe0ysb/

Like I said, unfortunately I can't use fixed steps. Is there a way to fix it with initial property?

**Comment by leongersen** [comment]
What is happening here is:

`min: [0,140], '9%': [140, 150], '18%': [150, 160]`

- Start the slider at 0. Step with increments of 140.
- Then, at 9% of the slider width, the value should be 140. Start stepping with 150 increments.
- Then, at 18% of the slider width, the value should be 150. Start stepping with 160 increments.

It is not possible to increment by `150` between the values `140` and `150` on the slider.

The two value do **not** mean the beginning and end of the (sub)range: they are they starting value and the step.

**Comment by leongersen** [comment]
If you intend to have the handle snap between the steps, you can use the [`snap` option](http://refreshless.com/nouislider/slider-values/#section-snap).

**Comment by daniele-castellini** [comment]
Ok, so if it works perfectly on Firefix it's just a collateral effect masked by feature? :(

And if I use this range (< 10 steps) it works perfecty also on Chrome

`{"min":[0,140],"12%":[140,150],"25%":[150,160],"37%":[160,170],"50%":[170,190],"62%":[190,220],"75%":[220,250],"87%":[250,290],"max":290}`

https://jsfiddle.net/castellinid/smbe0ysb/28/

**Comment by leongersen** [comment]
Yes, what you are seeing is an edge case math issue. Interesting to see that it occurs differently in different browsers.

The step vales you are using are too large. The last example you've linked would be achieved by removing the step values and enabling `snap`.

**Comment by daniele-castellini** [comment]
Ok, that's it! With snap it works fine:

http://jsfiddle.net/castellinid/smbe0ysb/29/

Thank you!! 👍
