### ISSUE TITLE
CSS classes

### ISSUE THREAD

**Issue by demrks** [leongersen/noUiSlider#635]
I was wondering if there are already plans to allow custom class names for all slider elements? I had a look at the code and saw that there's a `cssPrefix` option that you can set to change the class name prefix (defaults to `noUI`). The class name "suffixes" (like `handle`, `handle-left` and so on) can't be changed though.

I think we should allow people that want to use an existing design system (like BEM) for all their page components to update these class names too. Since this is a relatively minor change that won't affect file size or other functionality, it'll be a nice-to-have feature.

I'm willing to do the necessary changes in the code and create a pull request (if you agree that this improvement is useful?).

**Comment by leongersen** [comment]
I can _partially_ see why this'd be useful. What I'll **not do** is add a dynamic building system for the CSS. I'll make the `cssClasses` variable dynamic.

**Comment by demrks** [comment]
Currently the `cssClasses` variable is an array with all class names. I think, we could either just create a new [slider option](http://refreshless.com/nouislider/slider-options/) `cssClasses`, so everyone can edit this array, or we could use a new slider option for every CSS class name. The second way is probably easier to use, but a little "harder" to implement:

```javascript
noUiSlider.create(el, {
    // ...
    baseClass: 'noUI-base',
    handleClass: 'noUI-handle',
    // ...
});
```

That's how most other libraries are doing it at least. What do you think?

**Comment by leongersen** [comment]
I was thinking converting the array to an object (`{ origin: 'origin', handle: 'handle' }`), and allowing a new object to be passed.

**Comment by demrks** [comment]
That'll work too. If you want and I find some time in the next days, I can create a pull request for this feature. Shouldn't be that much work.
