### ISSUE TITLE
OSX/Safari focus bug

### ISSUE THREAD

**Issue by bajzarpa** [leongersen/noUiSlider#640]
When i clicking long on the handle, and move my cursor down from that the handle is still moving. And then unable to focus out from the handle. 
OS X 10.11.4 (15E65)
Safari Version 9.1 (11601.5.17.1)
and also on iPad 2 /w Safari

![da](https://cloud.githubusercontent.com/assets/943893/14645544/60e77512-0656-11e6-8010-7129ee8340f6.gif)

**Comment by leongersen** [comment]
I don't have a Mac at hand. Does this happen in the documentation, too?

**Comment by bajzarpa** [comment]
Nope. Sorry for not this was the first what i tried.

**Comment by leongersen** [comment]
Ok, so do I keep this issue open or is it on your end?

**Comment by bajzarpa** [comment]
You can close. The issue is in our system.
