### ISSUE TITLE
Decouple handle and connect

### ISSUE THREAD

**Issue by jorth3** [leongersen/noUiSlider#642]
I have a use case where I need to control the slider connect separate from the handle.  Think of a video buffering - the filling of the slider is only based on how much of the video is buffered.  The handle can be moved to play anywhere in the buffered amount.  I've tried going through the code but can't figure out how to do this.   Is there a way to achieve this with the library?

**Comment by leongersen** [comment]
I think you can use [this example](http://refreshless.com/nouislider/examples/#section-custom-connect).
