### ISSUE TITLE
Dragging the handle bar flickers from smallest to largest ios 6 ipad 3

### ISSUE THREAD

**Issue by Hidejec** [leongersen/noUiSlider#643]
When dragging the bar slowly to resize the picture to the right (make it bigger), the bar handle flickers by suddenly going to the smallest(left edge of slider) then going back to where the slider is. This only occurs on ios 6 ipad 3. Please help!

**Comment by leongersen** [comment]
iOS 6 has been superseded by 7, 8 and 9, and as such I'm not explicitly supporting it. If you want to propose changes/fixed I'll look into them, but I don't have an iOS 6 device on hand so I can't help you here.
