### ISSUE TITLE
Connector bar inaccurately advertised as disabled with one handle disabled

### ISSUE THREAD

**Issue by ABM-Dan** [leongersen/noUiSlider#644]
When disabling one of the two handles, the connector bar is displayed in gray, and shows the not-allowed cursor, yet it can be clicked, this is inconsistent behavior (displaying a signal of non-interactivity on an interactive area).

**Comment by leongersen** [comment]
Will be fixed in upcoming release. Thanks for reporting!

**Comment by leongersen** [comment]
9.0.0 fixes this. Thanks for the report!
