### ISSUE TITLE
Suggested improvement: Not user friendly behaviour when handle is larger than bar

### ISSUE THREAD

**Issue by lucap86** [leongersen/noUiSlider#645]
If handle is larger than bar and i click in a zone that is outside the bar but in the 'projection' of the handle the slider does not update its value.

I think that it can be useful specially when slider is very small

![ex](https://cloud.githubusercontent.com/assets/15343100/14910955/21d8896c-0df2-11e6-9f45-a7bf53b4a5ce.png)

**Comment by leongersen** [comment]
In noUiSlider, a slightly changed DOM structure will make it easier to style the background independently of the slider dimensions.
