### ISSUE TITLE
Using noUiSlider in a progressively enhanced way.

### ISSUE THREAD

**Issue by aaronstezycki** [leongersen/noUiSlider#646]
Is there a way to use noUiSlider in a progressively enhanced way. My project needs to support users who choose to turn off javascript, or hasn't loaded. Is there a way to get noUiSlider to work from a set of populated select inputs once the javascript is enabled? This means that if js in disabled, the users can simply use the select inputs instead of the sliders.

There is a example here: http://refreshless.com/nouislider/examples/#section-html5. However this is slightly different to having pre-populated select inputs.

Thanks.

**Comment by leongersen** [comment]
The example you link to will work, if you populate the select server side
instead of client side. You shouldn't have to make any other changes.
