### ISSUE TITLE
iPhone 6s

### ISSUE THREAD

**Issue by morettolss** [leongersen/noUiSlider#647]
Hi, the slider appears not to works (not display :D) on iPhone 6s.

On iphone 5, android and web is perfect.

Anyone have this issue?

**Comment by leongersen** [comment]
I don't have one on hand, so I can't test it. Does the documentation work?

**Comment by tomas789** [comment]
I have iPhone 6s with iOS 9.3.1. I have no problem using it. I browsed documentation and tried a few examples and all worked (they appeared and worked as expected).

**Comment by leongersen** [comment]
Thanks for the feedback @tomas789. I'll keep this issue open for any new information, but I won't consider this a priority until more information becomes available.

**Comment by morettolss** [comment]
I just check with the same iphone, now it's solved. I think it is a iOS problem fixed with the last update.
