### ISSUE TITLE
.get() - optional argument: ignore formatting ?

### ISSUE THREAD

**Issue by skftn** [leongersen/noUiSlider#648]
Thanks for creating such a wonderful library.

So I made this, a slider with tooltips: 
![e](http://i.imgur.com/Mbr9i2j.png)

Using `format` for the tooltips:
```
noUiSlider.create(size_slider, {
...
    format: {
        to: function(value) {
            console.log(value);
            if(value == 8589934592) return '>8 GB';
            return filesize(value, {round: 0, base:2});
        },
        from: function(value) {
            return value.replace(',-', '');
        }
    }
});
```

Somewhat hacky, but it works. Then after a while I'd like to get the values so I use `get()` and get back `>8gb`. Ideally I'd want to get back `8589934592`.

Any idea?

**Comment by leongersen** [comment]
I'll assume you closed this because you figured it out? You can pass the `format` option directly to the tooltip.
