### ISSUE TITLE
Doesn't work on mobile. Is it caused of jQUERY .load()?

### ISSUE THREAD

**Issue by ibart** [leongersen/noUiSlider#650]
I don't know how to debug this.

Go here: http://www.cauto-acquisto.it 
in the search box type something: es. "XIAOMI". 
On my develop machine (CHROME BROWSER) your slider is working fine but on my mobile device (CHROME BROWSER) doesn't work at all. 

It is not an issues of your code (because your website is working on my same mobile device) but I don't know how to debug this problemi. I think it is related to the jquery load. Can you help? Thanks.

**Comment by ibart** [comment]
bad code. Solved fixing a lot of micro bug. Thanks ^_^

**Comment by leongersen** [comment]
Glad you figured it out. Just as a pointer: digging through the full code of any site and trying to debug it is a practically impossible for any open-source maintainer. Try to isolate the issue to the absolute minimum required code. Usually you'll be able resolve issues that way, too :)

**Comment by ibart** [comment]
Eheh ok.  Thanks anyway. :)
