### ISSUE TITLE
Use directly in an input

### ISSUE THREAD

**Issue by odahcam** [leongersen/noUiSlider#651]
Why don't you extend the plugin to be used directly in an input, where it should creates a div, hides the input e syncronize them?

I just wanna know why, because the major use of this plugin is to "mask" a simple input.

**Comment by leongersen** [comment]
Because you can connect to slider to any data point on a page/in an application. This could be an input, but also a graph or a filter. A progressive implementation for this slider is completely possible (in <10 lines). See also issue #646.

**Comment by odahcam** [comment]
Yeah, I saw it before making the question, my point is: I believe that is not usual when you need to create the elements and sync them N times as the user wants. Take a look: http://imgur.com/0B9Qip5

I would be very grateful if you could clarify this for me.

**Comment by leongersen** [comment]
What do the 'testes' fields mean?

**Comment by odahcam** [comment]
From portuguese "teste", they are like a title for a type of progression, that in the front-end will be displayed like: "Teste: [progress bar with a floating 50.5%]". The noUiSlider is used to set the progression, that is sync with a `type="hidden"` input.
