### ISSUE TITLE
Formatter with Date

### ISSUE THREAD

**Issue by sepans** [leongersen/noUiSlider#653]
First thanks for the great library.

I have had some problem using a date formatters and the tooltips where getting rendered as `undefined` in the wrong position.

I realized with the custom date formatters, [here](https://github.com/leongersen/noUiSlider/blob/master/distribute/nouislider.js#L1720) the `setHandle` function is never get called since `isNaN(to)` is true and js doesn't bother calling `setHandle` so the `scope_Values` never get set.

The workaround hack I used in my formatter function was to check the type of the value and return it as is if it is a `string` to make sure it passes `isNaN` and `setHandle` gets called:
``` javascript
  function _formatDate(value) {
      var monthNames = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
        "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
      ]

    console.log(typeof value)
    if(typeof value === 'string') 
    {
     /* when type of value is string (why?!) return it as is so isNaN returns false and 
     *  setHandle gets called
     */
      return value
    }
    else if(typeof value === 'number') 
    {
      var date = new Date(value)
      var ret = monthNames[date.getMonth()] + ' '  + date.getFullYear()
      return ret
    }
    else { // e.g. undefined
 
      return false  // or whatever
    }
  }
```

Doesn't `setHandle` need to be called before the `if` clause to have the `scope_Values` set regardless of formatting?

Thanks

**Comment by leongersen** [comment]
This may have to do with the return types in the to/from methods in your `format` option. Can you expand your code sample?

**Comment by sepans** [comment]
I am using the [react wrapper](https://github.com/algolia/react-nouislider) but I can make the extended code sample (will post it soon).
Regardless of this specific issue is there a reason [here](https://github.com/leongersen/noUiSlider/blob/master/distribute/nouislider.js#L1720) the `setHandle` function is *not* being explicitly called? At least it makes the code less readable.

**Comment by leongersen** [comment]
What that line does:
1) If the value is `false`: handle **will** not move. `update` must fire so external inputs can be set to the slider state.
2) The value is not a number: failed to parse. `update` must fire to reset external inputs.
3) `setHandle` fires: the handle **did** not move. `update` must fire as with (1).

**Comment by leongersen** [comment]
I've rewritten the code handling this. Much cleaner now :smile:
