### ISSUE TITLE
Infinite loop when pip values are very close

### ISSUE THREAD

**Issue by hobzcalvin** [leongersen/noUiSlider#654]
I don't have the issue totally nailed down, but I think it happens if I pass in a `values` array like this to pips:
`[ 11.3, 21.3, 31.3, 1.3, 11.2999999 ]`

Basically we wind up in a state where `safeIncrement()` is called with a small enough `step` value that it never actually increments `i`, so the for loop using it goes forever. Browser tab crashes, etc. Not very "safe", eh? ;-)

**Comment by leongersen** [comment]
That sounds like a problem! Do you have a minimum example where this happens?

**Comment by hobzcalvin** [comment]
This reproduces for me:
```
slider = document.getElementById('theSlider');
noUiSlider.create(slider, {
  start: 0,
  range: {
    min: 0,
    max: 1000
  },
  behaviour: 'snap',
  pips: {
    mode: 'values',
    values: [172.57000000000005, 172.57000000000016]
  }
});
```

**Comment by leongersen** [comment]
I've added a small safety in the upcoming release that prevents the pips function from looping indefinitely. You'll probably want to add some safeties to your own code, too, so that pips aren't too close and become overlapping.

**Comment by leongersen** [comment]
Version 9.0.0 fixes this. Thanks for the report!
