### ISSUE TITLE
Soft ranges

### ISSUE THREAD

**Issue by benvankruistum** [leongersen/noUiSlider#655]
For a usecase i needed a way to interface a suggested price range. For the user this range is not a hard boundary but more a way to advice him. I could not get it done with available awesome features so i came up with this solution http://codepen.io/buksie_nl/pen/JKXdyW 
For me it would be a great feature to have in the noUiSlider.

**Comment by leongersen** [comment]
The way you added this seems like the most straightforward way to do it. What changes to noUiSlider are you suggesting?
