### ISSUE TITLE
slider.noUiSlider.on('set',function () {}) as a delegated event

### ISSUE THREAD

**Issue by lathamios** [leongersen/noUiSlider#660]
Hi

I am new to jquery so I am wondering how would i write slider.noUiSlider.on('set',function () {stuff}) as a delegated event. Basically on set I want to do a submit via ajax. I have it working on first age load, but unless I have it within a delegated event, it doesn't fire again. I have tried:

$(document).on('set', 'slider.noUiSlider', function () {, $(document).on('set', slider.noUiSlider, function () {

with no success so any help would be much appreciated!

Thanks!

**Comment by leongersen** [comment]
I don't understand your sample, but if you want to connect an event to a slider you'll have to add it to every slider individually. 

```
function createSlider(node, options) {
    noUiSlider.create(node, options);
    node.noUiSlider.on('set', stuff);
}
```

**Comment by lathamios** [comment]
Thanks a lot for your fast reply. I should have included more detail in my initial comment. Basically what I am doing is submitting a form via ajax on a "set" event of the slider. The code I am using for that is:
```javascript
slider.noUiSlider.on('set',function () {
        $.ajax({
            url: '/search',
            type: 'GET',
            data: $('#filter').serialize(),
            success: function (result) {
               //stuff
}
```
This works on the first submit, but after that it doesn't. I want the form to submit via ajax on every subsequent "set" of the slider. From what I have read the way to do that is by using a delegated event, hence my example above. Also from what I have read the syntax for a delegated event is
```javascript
$(document).on('[event]', '[element]', function () {
//stuff
});
```
But none of versions I tried for the slider events worked. Any ideas? Thanks again!

**Comment by leongersen** [comment]
The events noUiSlider emits are not native events, you can not use delegation in this way. There's (always) workarounds, such as  using jQuery's `trigger`, but that's beyond the scope of this issue tracker.
