### ISSUE TITLE
Multitouch support

### ISSUE THREAD

**Issue by adrianescat** [leongersen/noUiSlider#663]
When I touch the two nodes at the same time it breaks... One of the nodes starts to follow the other. Sometimes this bug occurs with only one finger touch.

**Comment by Enweave** [comment]
Same problem! 
Moreover, when it breaks, it may start to prevent interaction with anything(on document, where it's placed) but itself.

**Comment by leongersen** [comment]
I've tried it with any device I could get my hands on. This should be fixed by the suggestion provided in #649. The latest release (9.0.0) includes this fix. Please reopen this issue if you still have this issue, we can dive into it together. Thanks for the report!

**Comment by leongersen** [comment]
(maybe related to #704)
