### ISSUE TITLE
drag-fixed not supporting start/end events?

### ISSUE THREAD

**Issue by vincentaudebert** [leongersen/noUiSlider#664]
Hi there,

Is there any reason why the start/end events are not supported when using behaviour "drag-fixed"?

Demo here: https://jsfiddle.net/9ffod3mz/

**Comment by leongersen** [comment]
No good reason. I've added the `start` and `end` events to this behaviour. This change will be included in the next release.

**Comment by leongersen** [comment]
Thanks for the report, btw!

**Comment by leongersen** [comment]
9.0.0 fixes this. Thanks for the report!
