### ISSUE TITLE
noui slider keypress error when change direction(jsfiddle included)

### ISSUE THREAD

**Issue by chungchi300** [leongersen/noUiSlider#666]
When I set my nouislider to **ltr** as following,it can up and down by keypress smoothly.
http://jsfiddle.net/jeff_chung/L8md5251/

    <div class="example">
        <div id="keypress" class="noUi-target noUi-ltr noUi-horizontal noUi-background">
    
        </div>
        <input type="text" id="input-with-keypress">
    </div>
    <script>
        var keypressSlider = document.getElementById('keypress'),
            input = document.getElementById('input-with-keypress');
    
        noUiSlider.create(keypressSlider, {
            start: 0.66,
            direction: 'ltr',
            connect: 'lower',
            range: {
                'min': [0.66, 0.22],
                '14.29%': [1, 0.33],
                '28.57%': [2, 0.67],
                '42.86%': [5, 1.67],
                '57.14%': [10, 3.33],
                '71.43%': [20, 6.67],
                '85.71%': [40, 13.33],
                'max': 80
            }
        });
    
        keypressSlider.noUiSlider.on('update', function(values, handle) {
            input.value = values[handle];
        });
    
        input.addEventListener('change', function() {
            keypressSlider.noUiSlider.set([null, this.value]);
        });
        // Listen to keydown events on the input field.
        input.addEventListener('keydown', function(e) {
    
            // Convert the string to a number.
            var value = Number(keypressSlider.noUiSlider.get()),
                sliderStep = keypressSlider.noUiSlider.steps()
    
            // Select the stepping for the first handle.
            sliderStep = sliderStep[0];
    
            // 13 is enter,
            // 38 is key up,
            // 40 is key down.
            switch (e.which) {
                case 13:
                    keypressSlider.noUiSlider.set(this.value);
                    break;
                case 38:
                    keypressSlider.noUiSlider.set(value + sliderStep[1]);
                    break;
                case 40:
                    keypressSlider.noUiSlider.set(value - sliderStep[0]);
                    break;
            }
        });
    </script>

However,if I set it to **rtl**,it cannot up and down when it reach 2 but okay when mouse scrolling
http://jsfiddle.net/jeff_chung/po2rcj7z/1/

    <div class="example">
        <div id="keypress" class="noUi-target noUi-ltr noUi-horizontal noUi-background">
    
        </div>
        <input type="text" id="input-with-keypress">
    </div>
    <script>
        var keypressSlider = document.getElementById('keypress'),
            input = document.getElementById('input-with-keypress');
    
        noUiSlider.create(keypressSlider, {
            start: 0.66,
            direction: 'rtl',
            connect: 'lower',
            range: {
                'min': [0.66, 0.22],
                '14.29%': [1, 0.33],
                '28.57%': [2, 0.67],
                '42.86%': [5, 1.67],
                '57.14%': [10, 3.33],
                '71.43%': [20, 6.67],
                '85.71%': [40, 13.33],
                'max': 80
            }
        });
    
        keypressSlider.noUiSlider.on('update', function(values, handle) {
            input.value = values[handle];
        });
    
        input.addEventListener('change', function() {
            keypressSlider.noUiSlider.set([null, this.value]);
        });
        // Listen to keydown events on the input field.
        input.addEventListener('keydown', function(e) {
    
            // Convert the string to a number.
            var value = Number(keypressSlider.noUiSlider.get()),
                sliderStep = keypressSlider.noUiSlider.steps()
    
            // Select the stepping for the first handle.
            sliderStep = sliderStep[0];
    
            // 13 is enter,
            // 38 is key up,
            // 40 is key down.
            switch (e.which) {
                case 13:
                    keypressSlider.noUiSlider.set(this.value);
                    break;
                case 38:
                    keypressSlider.noUiSlider.set(value + sliderStep[1]);
                    break;
                case 40:
                    keypressSlider.noUiSlider.set(value - sliderStep[0]);
                    break;
            }
        });
    </script>

**Comment by leongersen** [comment]
This is indeed a bug. I've resolved it in the upcoming release.

**Comment by leongersen** [comment]
9.0.0 fixes this. Thanks for the report!
