### ISSUE TITLE
Issues controlling nouislider while used with setInterval (jsfiddle included)

### ISSUE THREAD

**Issue by helloworlder** [leongersen/noUiSlider#667]
I have made a jsfiddle at https://jsfiddle.net/w7urLsr4/2/

The slider moves because it is animated by a setInterval. However, if you try to click somewhere on the bar to change the position of the slider, it often doesn't work (i have to click multiple times). Same when I try to grab hold of the slider when it is moving.

Does anyone have a workaround for this behavior? Thanks.

**Comment by leongersen** [comment]
Clicking the bar does not work because your interval (200ms) is smaller than the click animation (300ms). You'll need to cancel the interval when you start dragging to keep the movement uninterupted.

Updated example:
https://jsfiddle.net/leongersen/w7urLsr4/3/

**Comment by leongersen** [comment]
I'm assuming this is solved, closing.
