### ISSUE TITLE
Touch events activating on touch scroll 

### ISSUE THREAD

**Issue by iwakun** [leongersen/noUiSlider#668]
I've created a horizontal slider with steps. On mobile devices, after dragging to a position, when I scroll up and down, the handle moves. Any idea why?

**Comment by leongersen** [comment]
What device/OS does this happen on?

**Comment by VictorPhilipp** [comment]
I have the same issue. I am using Android 4.4.4 with Google Chrome 52.0.2743.98. After sliding all touch events anywhere on the page are converted into slider movements.

**Comment by duvillierA** [comment]
Same issue on Nexus 5X, Android NOUGAT

**Comment by leongersen** [comment]
I think this is the same issue as #663, the latest release (9.0.0) should fix this.

Thanks for the report!

**Comment by leongersen** [comment]
(maybe related to #704)
