### ISSUE TITLE
Updating range with updateOptions keeps invalid pips

### ISSUE THREAD

**Issue by darkalor** [leongersen/noUiSlider#669]
In steps/range mode pips are automatically calculated based on range. However, if a new range is passed via updateOptions, the old pips are kept and no longer match the right scale.

**Comment by marosko** [comment]
You can easily reproduce the issue in: http://refreshless.com/nouislider/more/ in the 'updateSliderRange' function.

Just add:
`console.log("new max: " + updateSlider.noUiSlider.options.range.max);`
it will print out an old range value...

**Comment by synologic** [comment]
to fix this, you need to remove the old pips, so in function pips (around line 1177) add this before the return statement:

```
if (scope_Target.childNodes.length == 2)
			scope_Target.removeChild(scope_Target.childNodes[1])
```

Also, in function updateOptions, before the end add:

```
if ( options.pips ) {
			pips(options.pips);
		}
```

**Comment by leongersen** [comment]
This is fixed in version 10. Thanks for reporting.
