### ISSUE TITLE
Native android browser support

### ISSUE THREAD

**Issue by adrianescat** [leongersen/noUiSlider#670]
The slider does not work on native android browsers. The touch events do not work, but the component initializes correctly (visually).

**Comment by leongersen** [comment]
I'll need more information than that. What device(s), what browser version?

**Comment by adrianescat** [comment]
I tested it in a few android devices with 4.3 and 4.4 Android OS. All of them with the same problem

**Comment by leongersen** [comment]
Connecting to #700.

**Comment by leongersen** [comment]
1) Can you try again on release 9.x? I don't have an Android device with Jelly Bean/KitKat. 2) What exact browser are we talking about? There's a lot of them out there. 3) Any errors in the console or in `window.onerror`?

**Comment by leongersen** [comment]
Closing for lack of feedback.
