### ISSUE TITLE
Adding more handles

### ISSUE THREAD

**Issue by coding-saints** [leongersen/noUiSlider#671]
I love this lib. Is it possible to add more handles to the same slider? The example would be to show multiple break points ( 2-4 then 6-8 ) I'm guessing this would be a feature? If this can already be done I apologize.

**Comment by leongersen** [comment]
There is a pull request I have yet to merge (#592) for this feature.

**Comment by coding-saints** [comment]
Should I just close this? Also is there a way to pull the commit and play around with whats been done? It's so hard to find something this amazing, and not using jQuery. Ive been finding time to play around with it and I really want to implement it! And of course, great job!

**Comment by leongersen** [comment]
Thanks! I should have merged that pull requests months ago, but I just haven't gotten around to it :astonished:
