### ISSUE TITLE
cssPrefix breaks slider?

### ISSUE THREAD

**Issue by wyattp11** [leongersen/noUiSlider#672]
So the cssPrefix option appears to change entire CSS prefix requirement is that correct? I was hoping it only changed the stylable elements so I could more easily add my own styling to the slider but it breaks every time I change from "noUi-"...

**Comment by leongersen** [comment]
Yes, if you change `cssPrefix` you'll have to replace `.noUi-` in your entire CSS.

**Comment by wyattp11** [comment]
Ok, I've been able to access the :before and :after events succefully in a single slider, but how would I class that on a double handle?

This works for single handle(inserting an icon on the handle):
```
#custom-slider > div > div > .noUi-handle,
#custom-slider > div > div > .noUi-handle:after, #custom-slider > div > div > .noUi-handle:before {
font-family: "Ionians";
content: "\f4ae";
font-size: 46px;
}
```
