### ISSUE TITLE
Reset slider?

### ISSUE THREAD

**Issue by kkashou** [leongersen/noUiSlider#673]
Is there a way to reset the slider to it's original min value set ?

Thanks

**Comment by kkashou** [comment]
Anyone?

**Comment by coding-saints** [comment]
https://github.com/leongersen/noUiSlider/issues/304

**Comment by leongersen** [comment]
[ ] add `reset` method to api as shorthand for `.set(options.values)`.

**Comment by leongersen** [comment]
This is a new feature in 9.0.0. Thanks for the request!

**Comment by selay** [comment]
Just in case you still reach this page from Google search, you can call reset() method on the instance. 

    slider.noUiSlider.reset();
