### ISSUE TITLE
update range using updateOptions will impact slider values

### ISSUE THREAD

**Issue by gsouquet** [leongersen/noUiSlider#677]
Hi,

First thanks for the amazing plugin! Really useful. 
I've spotted a weird behaviour in the version 8.5.1.

For the following HTML:
```html
<div class="slider"></div>
```

And the following JS:

```js
var slider = document.querySelector('.slider');
noUiSlider.create(slider, {
	start: [20, 80],
	range: {
		'min': [ 0 ],
		'max': [ 100 ]
	},
    connect: true,
    margin: 5,
    animate: false,
    behaviour: 'drag'
});

slider.noUiSlider.get() // ["20.00", "80.00"]

slider.noUiSlider.updateOptions({
  range: {
    'min': [40],
    'max': [1000]
  }
});

slider.noUiSlider.get() // ["40.00", "88.00"]
```

By updating the `range` minimum above the set value on the slider I would have expect the value of the first handle to be set to `40`, and the second handle to remain at `80`.

Is that the intended behaviour?
Thanks

EDIT: 
I have done a bit more testing, if I remove the `margin` options when I instantiate the slider it's all fine.
And when `margin` is set, then the problem occur only for `max` values above `840` ...

**Comment by gsouquet** [comment]
Weirdly enough, this only happen when I put a `max` value above `840`

**Comment by leongersen** [comment]
Sorry for my slow response.

This is a bug in the `updateOptions` method. It forgets to re-apply the margin option if the range changes. I've changed this. The fix will be included in the upcoming release.

Thanks for your report!

**Comment by leongersen** [comment]
9.0.0 fixes this. Thanks for the report!
