### ISSUE TITLE
Expose slider options publicly

### ISSUE THREAD

**Issue by gsouquet** [leongersen/noUiSlider#678]
Hi,

So I was playing around with the plugin, let's assume the following JS code:

```js
var slider = document.querySelector('.slider');
noUiSlider.create(slider, {
  start: [20, 40],
  range: {
    'min': [0],
    'max': [100]
  }
});

slider.noUiSlider.options.range.min[0] // will print `0`

slider.noUiSlider.updateOptions({
  range: {
    'min': [10],
    'max': [90]
  }
});

slider.noUiSlider.options.range.min[0] // will print `0`
```

I expected the second one to print `10`. So I went through the source code and saw that you were referencing #600 , saying that you expose the original options.
Shouldn't it expose two keys: 
* options
* originalOptions

Alternatively, if you subscribe to the `update` event, you could send the updated options in the callback.

There's different places in my code that can update the slider options, so I have to keep track of those changes myself (even if the plugin is already doing that kind of things).

What do you think? 
Thanks,

PS: I'd be happy to help and do a PR for this if you can guide me a bit on how to do this.

**Comment by leongersen** [comment]
In 9.0.0, `slider.noUiSlider.options` stay in sync after update. That should fix this issue. Thanks for the report!
