### ISSUE TITLE
Handle shows the value

### ISSUE THREAD

**Issue by chabbrik** [leongersen/noUiSlider#684]
I would like to request a feature of being able to show the value of the handle on it. 
I have attached a visual example how it could look like.

![slider](https://cloud.githubusercontent.com/assets/2061262/18046704/650a4cba-6dd9-11e6-9265-a55fe40a450c.png)

**Comment by leongersen** [comment]
You can use the [`tooltips`](http://refreshless.com/nouislider/slider-options/#section-tooltips) option to do this.

**Comment by chabbrik** [comment]
Ah, thanks! I was not aware of that. Is it ARIA-friendly?

**Comment by chabbrik** [comment]
The suggested solution was even better. Thanks!
