### ISSUE TITLE
angular 2 support ?

### ISSUE THREAD

**Issue by patrioticcow** [leongersen/noUiSlider#688]
I'm trying to have this work using typescript and angular 2

any ideas if there is away to import the lib in my project?

**Comment by patrioticcow** [comment]
Managed to use it by declaring it `declare var noUiSlider: any;`

**Comment by eliteproxy7** [comment]
hi @patrioticcow , can you provide how you did this please? i can't event find the nouslider folder in node_modules   and i get 

├── nouislider@9.2.0 
└── UNMET PEER DEPENDENCY zone.js@0.7.6

npm WARN ng2-scrollimate@0.1.1 requires a peer of zone.js@^0.6.12 but none was installed.
