### ISSUE TITLE
Problem with steps when width of the slider is small and values - high

### ISSUE THREAD

**Issue by Volosojui** [leongersen/noUiSlider#690]
Hi there.
My issue is this:
handlers are moved not in accordance with the values of steps in the range object. This occurs at high values and when the slider takes a small width.
Example: https://jsfiddle.net/pb28bp1y/18/

Maybe I'm doing something wrong and someone will show me mistake.
Thanks in advance.

**Comment by leongersen** [comment]
If the slider is very narrow, not every step can be represented. Remember that a handle can only be on one pixel at a time, so if your slider is (for example) only 40px wide, it can only show 40 + 1 different steps out of the 2000000/1000 = 2000 possible ones in your configuration.

**Comment by Volosojui** [comment]
Thank you for your clarification.
