### ISSUE TITLE
Bunch of problems with interlinked sliders

### ISSUE THREAD

**Issue by spirit-infernal** [leongersen/noUiSlider#691]
Here is a few issues, which I found using nouislider:

First issue is when, according to documentation, making two interlinked sliders and give them two different ranges, i.e. 1650, 2550,4600,11900 for first and 3,5,10,30 for second they become interlinked, but useless, because second slider will be always at full state. Check [codepen](http://codepen.io/spirit-infernal/pen/ozjJpy) and try to drag first slider right.
I temporary solved this problem equally multiplied second slider values for having bigger digits and have a correct working interlinked sliders, but I think it possible to make somehow else.

Second issue: unable to insert values from slider to input fields, or at least not described this moment in documentation. 

And third moment is that ordinary code, taken from documentation and examples working incorrect - using this [example ](http://refreshless.com/nouislider/examples/#section-lock) script did not inserting slider values to input field or any kind of spans linked for it. May I do something wrong or did not understand something?

Sorry for my (probably) bad english.

**Comment by leongersen** [comment]
1) The example is just that: an example. If your requirements are different, you'll have to create custom code. You could, for example, use the format option to rescale the value between the sliders. The slider is a user interface component: it won't (and can't) support every possible use case right out of the box.
2) [this example](http://refreshless.com/nouislider/examples/#section-keypress) is one of several connecting an input element.
3) The documentation runs the exact code displayed, so if your copy doesn't work you'll have missed something. I can't help you there, as you didn't show any of your code.

Your English is fine, btw. No need to apologize!

**Comment by leongersen** [comment]
You can do something like the following in your `crossupdate` function:

```
var scalingFactor = a ? 1000 : 1;
slider.noUiSlider.set(value / scalingFactor);
```
