### ISSUE TITLE
pips

### ISSUE THREAD

**Issue by flythird** [leongersen/noUiSlider#692]
Hello from frog land ! 

I use this tool and thanks it's very usefull.

I am not sure this is an issue but : 

i tried to work with [0, 25, 50, 75, 100] option data values

i set:  step: 25, range[0,100] pips { mode : 'steps', density: 5}
all works fine. i limit the users to choices the 5 values (modulo 25)

but now i want to work with the option data values : 

[0, 25, 33, 37.5, 50, 75, 100]

In fact i just want the user to be able to move the cursor on just these values.
i found and tested the pips mode 'values' without success

so, in fact, i dont want to manage a step or a density but to limit the users to the pips values array 
i propose to him.

is it possible ? if yes do you have a sample ?  if not it could be a fonctionality....

thanks for your attention and have a nice day...

alien, from cheese land

**Comment by leongersen** [comment]
You can use the `values` mode:

http://refreshless.com/nouislider/pips/#section-values

**Comment by flythird** [comment]
i tried your solution 'values mode'. I wrote it in my first remark

my need : [0, 25, 33, 37.5, 50, 75, 100]  (we guess !  it is a beer volume)

in your sample

http://refreshless.com/nouislider/pips/#section-values

you can't reach 2251 value and the slider is influenced by the density of 4

i don't know if it's possible but i just want to slide on the pips values.

I bind a onChange event.
if i set a density : the event is triggered with each slide

in my first solution [0,25,50,75,100] my step of 25 solve the problem
the events are plugged on the good values

with [0, 25, 33, 37.5, 50, 75, 100] there are two problems:

the 37.5 pip value is displayed 38  (it's another problem)
and i don't know how to set the density value to avoid to slide between the pip values.

every event i display an image filtered by the value. 
of course i can modify the code event to filter the good values. 
in this configuration the slide must pass by all the values unfortunatly it does'nt pass. 
just the 33 (export) is reached 0 and 100.

It was possible  just when i set the step parameter to 0.5
Ok it works but i have an event for each slide ??? it is not pheng shui

do you have a solution.
alien, from france

**Comment by leongersen** [comment]
`density` in pips has nothing to do with how the slider steps. Make the slider follow the steps you want, then use `steps` mode in the pips.

Is this what you want?

https://jsfiddle.net/leongersen/yvgh06t5/

**Comment by flythird** [comment]
yes you're the best messie of the universe ! 
a small step for you, a big step for my application

i am happy, it's red, it's green, it's blue, it's constantinople, bysance !

i think you' ll be agreed. without you,  just with the documentation and the api 
i wasn't able to solve the problem.

it is a trick. the scale is not respected but i don't care the user will have what he want.

i tried a lot of library and yours is the most adapted and design i found.
i use it with angular-formly


thank you for your answer, the time you spent to help me and have a nice day

alien, in the south of france

**Comment by leongersen** [comment]
Glad it worked out :smile:

**Comment by nehaKeskar** [comment]
I have 1 problem while displaying date range values in pips... can any one help me plz
