### ISSUE TITLE
"start" option not work when format it as time

### ISSUE THREAD

**Issue by juicy-tangerine** [leongersen/noUiSlider#693]
0.problem:
i want to initialize slider like this:
![qq 20160914173805](https://cloud.githubusercontent.com/assets/3712986/18507265/39ef552c-7aa2-11e6-8a43-18bdf57b2644.png)
but it doesn't work when i use the code below, it was initialized like this:
![qq 20160914173530](https://cloud.githubusercontent.com/assets/3712986/18507317/7337927c-7aa2-11e6-869f-b51fb4b7f2f5.png)
and i found "set" command not work too:
`connectSlider.noUiSlider.set([0, 86400]);`
it bothered me several days, any help will be appreciated !
1.env: nouislider - 8.5.1/jQuery v2.1.1/
2.code:
`var start = 0;
        var end = 86400;
noUiSlider.create(connectSlider, {
                connect: true,
                range: {
                    'min': [start],
                    'max': [end]
                },
                //range: {
                //    'min': 0,
                //    'max': 24*60*60
                //},
                start: [start, end],
                tooltips: [true, true],
                format: {
                    from: function (value) {
                        return own.getSecToDate(value); //change data from 86400 to "24:00:00"
                    },
                    to: function (value) {
                        return own.getSecToDate(value);
                    }
                }
            }, true);`
ps: English is my second language, if I not describe clear, please let me know.

**Comment by leongersen** [comment]
Your `to` and `from` functions in the formatter are identical. `to` takes a number, returns a formatted string, `from` takes a formatted string, returns a number.

**Comment by juicy-tangerine** [comment]
thank you so much, it really helped !
