### ISSUE TITLE
Handle is moving properly on click of some numbers in the slider

### ISSUE THREAD

**Issue by Swathi8** [leongersen/noUiSlider#694]
I'm trying to implement the slider in my cordova based android app.
I have initialized the noUiSlider as below:

```javascript
var gradeRange = document.getElementById('gradeRange');

noUiSlider.create(range, {
                start: 1,
                step: 1,
                range: {
                    'min': 1,
                    'max': 5
                },
                behaviour: "tap",
                connect: "lower",
                pips: {
                    mode: 'steps',
                    values: [1, 5]
                }
            });
```

And the slider looks as given in the below image:

![screenshot_2016-09-19-15-13-33](https://cloud.githubusercontent.com/assets/13765124/18629050/e1f2a198-7e80-11e6-8467-10ad0ed99a9f.png)

But handle doesn't move properly on click of some number on the horizontal bar.
on click of 1, 2, 3 handle moves properly - but on click of 4 and 5 it doesn't move. I had to click some where in between 4 and 5 to get the handle at 4.

It works perfectly fine in the normal browser even in the mobile device mode.

**Comment by leongersen** [comment]
I'm not really sure what to do with this issue. Do you suspect this to be an issue with noUiSlider or with the integration in your app?

**Comment by Gaserd** [comment]
@leongersen we will have tap on pips, because now it don't work

**Comment by leongersen** [comment]
Closing for lack of response. Feel free to comment.

**Comment by Swathi8** [comment]
@leongersen Sorry for very late reply. 

I issue comes up in mobile phones. In browser it is working fine - I even tried in mobile mode in brower.

But when I use the same think in the mobile app - tap doesn't work properly as explained in th isue description.

So, i tried to check value of slider handle on change event. When I tap on 4, the value is 3.7 or so(not sure about value but the value is between 3 and 4). That is why handle is not being placed at 4.

**Comment by leongersen** [comment]
What are you tapping? The pips or the slider?

**Comment by Swathi8** [comment]
On slider.

**Comment by leongersen** [comment]
Is there another element on top of the slider? You've concluded this isn't happening in any browser you are trying, so I think I can only be of limited help here.

**Comment by Swathi8** [comment]
No, there is no element on top of the slider.
I would like to send video of the slider action, then you might get clear idea of it. how can I do that?

**Comment by leongersen** [comment]
This is going outside of the scope of this issue tracker. If you can isolate your issue, you could post a question on a site like https://stackoverflow.com/. 

I'm not trying to be mean, but I hope you understand that I don't have the time to follow through on a wild goose chase through code that has very little or nothing to do with this library, and which I can't even have a look at.
