### ISSUE TITLE
frequent drag slide cause browser crash

### ISSUE THREAD

**Issue by juicy-tangerine** [leongersen/noUiSlider#695]
0.problem: I use noUiSlider  work with graph, graph changed when slide scope dragged. But I encountered a problem, when frequent dragging slide cause browser crash.  And the browser told something happend in nouislider.js(line:1772), 
I have no idea how to fix this, any suggests ?
0.1: first look like this:
![20160920001](https://cloud.githubusercontent.com/assets/3712986/18654935/674b3b2a-7f17-11e6-8d08-eea25bd2b172.png)
0.2: after several times move handle, cause browser crash:
![2016092002](https://cloud.githubusercontent.com/assets/3712986/18654867/f2cd9784-7f16-11e6-9440-8255da9db991.png)
0.3: code in line1772, browser crashed and can not be debugged :
![qq 20160920100147](https://cloud.githubusercontent.com/assets/3712986/18655271/ff057262-7f19-11e6-88e9-0a57861cf99b.png)
1.code:
`noUiSlider.create(connectSlider, {
                    behaviour: 'drag',
                    connect: true,
                    range: {
                        'min': [start],
                        'max': [end]
                    },
                    step:600, //10 minutes
                    start: [start, end],
                    tooltips: [true, true],
                    format: {
                        //from: takes a formatted string, returns a number
                        from: function (value) {
                            return own.getDateToSec(value); //change data from "24:00:00" to 86400 
                        },
                        //to: takes a number, returns a formatted string
                        to: function (value) {
                            return own.getSecToDate(value); //change data from 86400 to "24:00:00"
                        }
                    }
                }, true);
connectSlider.noUiSlider.on('end', function (value) {
                //console.log("滑块移动结束触发-firstData: ", own.options.firstData);
                var str = JSON.stringify(own.options.firstData);
                var data = $.parseJSON(str);
                var newData = own.filterDataByRange(data, value, type);
                console.time("reflushData");
                own.reflushData(newData, own.rate); // draw stacked bar chart
                console.timeEnd("reflushData");
            });`

**Comment by juicy-tangerine** [comment]
ps, env: use nouislider - 8.5.1/jQuery v2.1.1

**Comment by juicy-tangerine** [comment]
solved ! It was caused by bounding a new "end" function every time draw a graph.

**Comment by leongersen** [comment]
Glad you worked it out!
