### ISSUE TITLE
two sliders with output

### ISSUE THREAD

**Issue by basemwahba** [leongersen/noUiSlider#698]
Thanks for the great work.

Is there a way to do the following:

slider(1) (product's quantity) values are: 7,8,9
slider(2) (product's options) values are: a,b,c

Price (output) will be as follows:
When slider(1) is "7" and slider(2) is "a" price is "78"
When slider(1) is "7" and slider(2) is "b" price is "13"
When slider(1) is "7" and slider(2) is "c" price is "58"
When slider(1) is "8" and slider(2) is "a" price is "41"
When slider(1) is "8" and slider(2) is "b" price is "36"
When slider(1) is "8" and slider(2) is "c" price is "94"
When slider(1) is "9" and slider(2) is "a" price is "20"
When slider(1) is "9" and slider(2) is "b" price is "65"
When slider(1) is "9" and slider(2) is "c" price is "87"

Thanks so much

**Comment by leongersen** [comment]
Sure!

```
var values = {
7: { a: "78", b: "13", c: "58" },
8: { a: "41", b: "36", c: "94" },
9: { a: "20", b: "65", c: "87" }
};

var output = values[slider1.noUiSlider.get()][slider2.noUiSlider.get()];
```

**Comment by basemwahba** [comment]
Thanks so much for your care.
Special thanks for your quick response.

May you please have a quick look at https://jsfiddle.net/wd7Lr68t/5

How can I integrate your above `var values` and `var output` into the example?

Thanks again.

**Comment by leongersen** [comment]
Maybe give it a try yourself next time, alright?

https://jsfiddle.net/leongersen/wd7Lr68t/7/

**Comment by basemwahba** [comment]
Alright :) 

I agree that it's small task for JavaScript developers.

But I swear that I'm not lazy. I swear that I have tried. Since two days, I started to learn JavaScript in order to finish this task by myself. But I couldn't. My skills are around building websites using applications like RapidWeaver, Sparkle, Fission ..etc. 

Thank you so much. I really appreciate your help so much.

**Comment by leongersen** [comment]
No problem, glad I could help. All the best in learning 😃

**Comment by basemwahba** [comment]
Thanks so much 😃

**Comment by basemwahba** [comment]
Hi again,

I wish you are fine.

I'm trying to show slider 1 values inside the sliding box. May you please advise about the appropriate value for the CSS's **"content"** element?

https://jsfiddle.net/wd7Lr68t/9/

```
.noUi-base .noUi-handle {
  background-color: #5e378e;
  border: none;
  border-radius: 6px;
  box-shadow: none;
  color: #FFFFFF;
  display: table;
  font-size: 15px;
  height: 40px;
  left: 0;
  margin-left: -22px;
  margin-top: -13px;
  padding: 0;
  position: absolute;
  text-align: center;
  top: 0;
  width: 80px;
  z-index: 2;
}

.noUi-base .noUi-handle::before {
  background: transparent;
  content: "";
  display: table-cell;
  font-size: 18px;
  font-weight: 100;
  position: static;
  width: 100%;
  vertical-align: middle;
}

.noUi-base .noUi-handle::after {
  display: none;
}
```
Thanks so much

**Comment by leongersen** [comment]
I don't understand the question, sorry.

**Comment by basemwahba** [comment]
Thanks for your response . And no sorry at all.

I'm just trying to show slider 1 values inside the sliding box.
https://jsfiddle.net/wd7Lr68t/9/
May you please advise regarding this?

Thanks again so much.
