### ISSUE TITLE
Using variables for step

### ISSUE THREAD

**Issue by pararrayos** [leongersen/noUiSlider#699]
Hi Mr. Gensen. I'm using your incredible mega-nouislider, and I'm facing a minor problem. Is it posible to use a variable assigned to **step**? Something like this:

```
var interval = whatever useful;
noUiSlider.create(slider, {
     start: [ whatever], // Handle start position
     step: interval,
     (more code)
});
```	
I'm trying as stated in example but it doesn't work. Thanks :)

**Comment by leongersen** [comment]
Yeah, that'll work. "It doesn't  work" is a **really** bad description of a problem :cry:

**Comment by pararrayos** [comment]
My bad... I got it, it works. Just a missmatch in variables' names. Thank you anyway.

**Comment by pararrayos** [comment]
Hi again, Mr. Gensen :) Please let me re-open this ticket.

In my first comment, I asked about the possibility of using a variable for step parameter when creating a slider. As we said, it's possible and there's no problem.

Ok, now I'm required to change programatically the step parameter, not only when the slider is created as in my first comment, but when a button is clicked and a certain value is 'retrieved' from a database. I'm coding this:

```
$('#mybtn').on('click', function(){
    var dataString = whatever;
    $.ajax({ type: "POST", 
        url: "whatever.php",
        data: dataString, 
        cache: false, 
        success: function(html) { 
             if (html) { 
                 var interval = html; //numeric value
             } 
         });
});
noUiSlider.create(slider, {
     start: [ whatever],
     step: interval,
     (more code)
});
```
If I'm not wrong, this won't work because when the button is clicked the slider have been already created, so no changes in step parameter will be produced.

I wondered if something like this would work;
```
var interval = 0;
noUiSlider.create(slider, { //first, create slider
     start: [ whatever],
     step: interval,
     (more code)
});
$('#mybtn').on('click', function(){ // then, retrieve value from DB and pass it to interval
    var dataString = whatever;
    $.ajax({ type: "POST",  
        url: "whatever.php",
        data: dataString, 
        cache: false, 
        success: function(html) { 
             if (html) { 
                 interval = html; //numeric value
                 slider.set.step(interval); // <<<<<------- does this method exist?
             } 
         });
});
```
Unfortunately, it doesn't work and I'm stuck in this task. What am I doing wrong? Thanks.

**Comment by leongersen** [comment]
You can [update the slider options](https://refreshless.com/nouislider/more/#section-update).

**Comment by pararrayos** [comment]
Thank buddy, it works ;) Just letting the code if it helps anyone later or sooner

```
var interval = 0;
noUiSlider.create(slider, { //first, create slider
     start: [ whatever],
     step: interval,
     (more code)
});
$('#mybtn').on('click', function(){ // then, retrieve value from DB and pass it to interval
    var dataString = whatever;
    $.ajax({ type: "POST",  
        url: "whatever.php",
        data: dataString, 
        cache: false, 
        success: function(html) { 
             if (html) { 
                 newinterval = html; //numeric value 
                 slider.noUiSlider.updateOptions({ 
                     range: { whaterver }, 
                     step: newinterval
                 });
             } 
         });
});
```
