### ISSUE TITLE
Getting error due to undefined `e.points`

### ISSUE THREAD

**Issue by PikachuEXE** [leongersen/noUiSlider#700]
The error is:

```
TypeError
Cannot read property '0' of undefined
```
### Env

browser
Chrome 52.0.2743
os
Android 4.1.2

The line that throws error should be
https://github.com/leongersen/noUiSlider/blob/master/src/js/scope_helpers.js#L37

**Comment by leongersen** [comment]
I have fixed this in release 9.1.0. Thanks for the report!
