### ISSUE TITLE
Custom colors for each bar segment

### ISSUE THREAD

**Issue by thomashaselwanter** [leongersen/noUiSlider#705]
It would be good to have an easy way to specify a color for each segment in a multi handle slider, eg in the same way the connection between handles is currently turned on/off (connect: [false, true, true, true, false]).

**Comment by leongersen** [comment]
You can add a class to all (`slider.querySelectorAll('.noUi-connect')`) and style them that way. What approach would you suggest?

**Comment by thomashaselwanter** [comment]
Thanks for responding so quickly. Adding a class to .noUI-connect would give each of them the same color right? For my use case I am looking to have different colors for each connect bar to make it easier for the user to visually quickly see the significance of each range. Example: Image a slider with 4 handles for a 24 hour interval to regulate a heater. The 4 handles give me 5 heating periods where the heater has a certain temperature. I want to give different colors to the connect bars to visualize the temperatures. I am open for any approach that allows me to set a different class/style for each connect bar. Maybe something like this fits with your library: connectclasses: [18deg-color,  22deg-color, 24deg-color, 20deg-color, 22deg-color]?

**Comment by leongersen** [comment]
I've put something together really quick:

https://jsfiddle.net/leongersen/mdp0awp1/

(classes cannot start with a number)

**Comment by thomashaselwanter** [comment]
Thanks! Works for me. I think this should be an example on the projects homepage. It's a feature.

**Comment by nomad-cam** [comment]
Brilliant, just was I was looking for! Works a treat, very useful.

**Comment by leongersen** [comment]
If either of you publishes a project using noUiSlider with more than three handles, could you let me know? I'd like to see it in practice!

**Comment by thomashaselwanter** [comment]
Sure, will do. The current project in which I am using it is just for private use, but I am sure I will use it in the future and have something to share with you. Thanks again for you quick help, it is much appreciated.

**Comment by leongersen** [comment]
This example [is now in the documentation](https://refreshless.com/nouislider/examples/#section-colored-connect).
