### ISSUE TITLE
nouislider 2 handles, application bug using android and iOS emulators

### ISSUE THREAD

**Issue by dalegrebey** [leongersen/noUiSlider#706]
Good day, I hope all is well. I had been using nouislider.js for a hybrid mobile application I am working on. Everything looked great, worked well, when tested locally in my web browser.

As soon as I put it into an emulator though (ripple) for both android and iOS, the multi-handle functionality breaks. You can move either the lower or the upper handle in whichever order and at first it appears to work, but as soon as you touch the second handle, they both occupy the same space/value.

For example, if I have a range of 0-100, lower handle defaulted to 20 and upper handle defaulted to 80, I can move either one of them to whatever value. As soon as I touch the second handle though (doesn't matter which), the first handle always jumps to the same value as the second one I interfaced with.

To elaborate, if I move lower handle to, say, value 30. As soon as I move the upper handle to value 70 or whatever the case may be, the first handle then becomes value 70 as well. Now they both share the same value and slide atop one another.

I created a separate installation where all that is in the install is just the includes for the js/css and the html for the slider and it still has this behavior.

```
var slider = document.getElementById('slider');
noUiSlider.create(slider, {
    start: [20, 80],
    connect: true,
    range: {
        'min': 0,
        'max': 100
    }
});
```

`<div id="slider"></div>`

This is the code that is producing that behavior (ripple emulator) for both iOS and Android.

**Comment by dalegrebey** [comment]
![screenshot-nouislider](https://cloud.githubusercontent.com/assets/6771561/19414181/97762e4a-9312-11e6-8e9b-a3aa7821d1ed.jpg)
![screenshot-nouislider-2](https://cloud.githubusercontent.com/assets/6771561/19414182/9779744c-9312-11e6-800b-8b0a05bb7a9f.jpg)

**Comment by dalegrebey** [comment]
To further follow up with additional information. This seems to be an issue with "drag" behavior and mobile touch events. If I "tap" somewhere, it works fine. As soon as I try to "drag", it seems to get confused as to which handle is which.

Thoughts?

**Comment by leongersen** [comment]
I don't know this particular emulator, although I'd be willing to check it out when I get a chance. It sounds like the `end` event doesn't fire, although I have no idea why that would happen.

**Comment by dalegrebey** [comment]
@leongersen Thank you for the prompt response and your diligence. I try to avoid libraries as much as possible, which is what attracted me to your code in the first place. I am using Tools for Apache Cordova in Visual Studio to create the Hybrid app. Built into Visual Studio is the "Ripple" emulator -- though as I understand it, the emulator is separate and its own identity altogether.

I suppose more importantly, whether the emulator works properly or not, do you know how well this has been tested on the actual devices themselves? I am a few days out on the "test flight" for my alpha testing. If it works fine on the actual devices and the emulator is just being squirrely -- who cares. Either way, I'll report back with some updates as I have them.

Thanks again,
~Dale

**Comment by leongersen** [comment]
I've tested myself on iOS 8.x, 9.0-3 and 10, and on Chrome on several Android devices (5.x and 6.x, as well as 4.3/4.4.x, although that's been a while - I'd be much obliged if you have results there). I also test on Windows Phone 8.1 and Windows Mobile 10, as well as Firefox, IE9, IE10, IE11, Chrome, Edge and Opera. I don't have permanent access to a Mac to test Safari regularly.

**Comment by dalegrebey** [comment]
When I have the results, I will be sure to post them. It may be a few days, but I will post them.

**Comment by dalegrebey** [comment]
@leongersen I have not forgotten about your work. Moving targets on my end as per software requirement specifications... I will create a separate build to test your functionality; although w/ our User Interface initially it was decided that for practical application -- we are clumsy.

**Comment by dalegrebey** [comment]
@leongersen have you thought about writing (or have you) written a nouirangeslider as a progress bar? The one I wrote using ECMAScript5 (not 6/typescript) seems to work pretty well.

**Comment by leongersen** [comment]
Closing this because it has nothing actionable anymore. Feel free to comment, I'll re-open.

**Comment by gitlovenotwar** [comment]
This issue still persist till today for mobile devices

**Comment by AntoineWtrnd** [comment]
Still have the same issues 3 years later...

**Comment by leongersen** [comment]
@AntoineWtrnd Feel free to submit a patch or further debugging information.

**Comment by AntoineWtrnd** [comment]
https://codepen.io/enweave/pen/xOYJEV
