### ISSUE TITLE
Lock handles?

### ISSUE THREAD

**Issue by Nav33d** [leongersen/noUiSlider#707]
Not exactly an issue was just wondering if it is possible to lock handles?

I'm building a slider with 4 handles and trying to lock two handles based on their values.

Many thanks

**Comment by leongersen** [comment]
Yes, you can give a handle a `[disabled]` attribute:

https://refreshless.com/nouislider/more/#section-disable

**Comment by Dhiraj-Rai** [comment]
in angular: Changing color and disable knobs
/////////////////////////////////////////html:
 <nouislider #SliderIdentity id="SliderIdentity" [connect]="true" [min]="0" [max]="100" [step]="1" 
     [(ngModel)]="RangeOfSlider" [limit]="sliderPointsLeft" [config]="Changes 
      (change)="TriggerUpdate($event)" style="cursor: pointer;">  
 </nouislider>   
/////////////////////////////////////////in ts file:
import { Component,ElementRef,ViewChild,NgModule } from '@angular/core';
import { NouisliderModule } from 'ng2-nouislider';
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  @ViewChild('slider', { read: ElementRef }) slider: ElementRef;
  ColorSlider;
  tooltips: true;
  SomeRange:any= [ 0, 45 ,75,100];
  Changes: any = {
    behaviour: 'hover-snap',
    tooltips: [true, true,true, true],
    keyboard: true,
    orientation: 'horizontal',
  }

  triggerUpdate(event) { 
   
  }
  func() {
    const connect = this.slider.nativeElement.querySelectorAll('.noUi-connect');
    this.SomeRange[0];
    const classes = ['color1','color2', 'color3'];
    console.log(connect.length);
    for ( let i = 0; i < connect.length; i++ ) {
      connect[i].classList.add(classes[i]);
    }
    var slider1 = document.getElementById('slider');
    //connect[100].setAttribute('disabled', 'true');
    var origins = slider1.getElementsByClassName('noUi-origin');
   // element.setAttribute('disabled', true);
    origins[0].setAttribute('disabled', 'true');
    origins[3].setAttribute('disabled', 'true');
    //document.getElementById('slider').setAttribute('disabled', 'true');//
  }
  ngAfterViewInit() {
    this.func();
  }
}
/////////////////////////////////////style.css:
/* You can add global styles to this file, and also import other style files */
/*.noUi-handle*/
@import "~nouislider/distribute/nouislider.min.css";

.noUi-tooltip {
    display: none;
}

.noUi-active .noUi-tooltip {
    display: block;
}
.noUi-handle{
    color:black;
}
.noUi-tooltip::after {
    content: "";
    position: absolute;
    top: 100%;
    left: 50%;
    margin-left: -10px;
    border-width: 10px;
   border-style: solid;
    border-color: orange transparent transparent transparent;
}

.color1 {
    background: green;
     }
.color2 { 
    background: yellow;
 }
.color3 {
     background: #802A00; 
    }
