### ISSUE TITLE
Downloaded ZIP contains duplicate filename

### ISSUE THREAD

**Issue by lcrocker** [leongersen/noUiSlider#709]
ZIP file noUiSlider.9.0.0.zip contains two files named "nouislider.css", one of which seems to be a superset of the other.

**Comment by leongersen** [comment]
Thanks for reporting this! One of them contains the styles for the `pips` feature. I think I messed up something in the deploy script. I'll get it fixed.

**Comment by leongersen** [comment]
I have fixed the release script. Thanks for this report!
