### ISSUE TITLE
Can't slide handle when using min-height

### ISSUE THREAD

**Issue by BrnoPCmaniak** [leongersen/noUiSlider#710]
Example here:
http://codepen.io/BrnoPCmaniak/pen/yakNWa

```html
<div id="vertical" style="min-height: 300px; padding-top: 20px;"></div>
```
```js
var options = {
	start: [ 4000],
  orientation: "vertical",
	range: {
		'min': [  2000 ],
		'max': [ 10000 ]
	},
}

var verSlider = document.getElementById('vertical');
noUiSlider.create(verSlider, options);
```

**Comment by leongersen** [comment]
The `.noUi-base` element inserted inside the slider has `height: 100%`, which doesn't 'inherit' from `min-height`. See this [stackOverflow question](http://stackoverflow.com/questions/8468066/child-inside-parent-with-min-height-100-not-inheriting-height).

**Comment by BrnoPCmaniak** [comment]
Working solution http://codepen.io/BrnoPCmaniak/pen/VKgpvY

@leongersen Thank you very much
