### ISSUE TITLE
Pips position,density

### ISSUE THREAD

**Issue by vAhyThe** [leongersen/noUiSlider#712]
Hi guys !

On start i must thank you for this perfect slider.

My issue is. Can i somehow change position of pips, like on different part of slider. Now i can put them just bellow slider. I need them on top :/

And second question is. Can i somehow remove density not to be there ??.

Thx much

**Comment by domahub** [comment]
I would assume you can put "density: 0".

As for the position of the pips you would have to change the CSS on .noUi-pips.

**Comment by 1qlee** [comment]
I would assume you can put "density: 0".

As for the position of the pips you would have to change the CSS on .noUi-pips.

**Comment by vAhyThe** [comment]
I try this but not work. I have solution to set `density: 200` because i have range from `1 ~ 15` it works, but it not nice solution :)

As for position i know i can do with css but i think if there is no better solution :)

**Comment by leongersen** [comment]
Merging with #497.
