### ISSUE TITLE
Event propagation in eventStart and eventTap

### ISSUE THREAD

**Issue by gsouquet** [leongersen/noUiSlider#714]
Hi, 

For some reason, I need to bind an event on my `.noUi-connect` element. But this doesn't work because in the `eventStart` and in the `eventTap` functions, the propagation of the event is stopped.

In `eventStart`, I can see this comment:

```
// A drag should never propagate up to the 'tap' event.
```

Basically, I commented out those two statements and it does what I need.
I was just wondering the reasons for those? Are there any use case that makes the slider not work if I remove them?

Thanks,

**Comment by leongersen** [comment]
It depends on whether you have the `behaviour` option set to tap (which is default). In that case, we want to capture events on the handle in another way than on the rest of the slider. How are you binding to the connects?

**Comment by leongersen** [comment]
Closing for lack of feedback.

**Comment by pedropcruz** [comment]
Hello @leongersen 
Well, i had a behaviour on "drag-tab" on my slider that i'm building, but how i can access to the events for stop propagation? Like, on mobile, when you tap to much time, will appears menu from iOS/Android devices. How i can resolve this?
Many thanks.

**Comment by leongersen** [comment]
I don't really understand what you are asking, sorry. Feel free to open an issue with some more details (maybe an example?)
