### ISSUE TITLE
"format" option breaks the slider completely

### ISSUE THREAD

**Issue by i-fail** [leongersen/noUiSlider#717]
Here's the reduced case. If you remove the **format : { ... }** section, everything works (well, except the custom formatting). It looks like your code sends NaN as parameters to the from() and to() methods.

````
<link href="https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/9.0.0/nouislider.min.css" rel="stylesheet" type="text/css">
<div id="range"></div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/9.0.0/nouislider.min.js" type="text/javascript"></script>
<script>
	var months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
	slider = document.getElementById('range');
	slider.style.width = "50%";
	slider.style.margin = "50px";
	var date_range = {min: 1468951379, max: 1477116021};
	var options = {
		start: [date_range.min, date_range.max],
		connect: true,
		range: date_range,
		format: {
			to: function(v){
				var a = new Date(v * 1000);
				return months[a.getMonth()] + " " + a.getDate();
			},
			from: function(v) {
				var a = new Date(v * 1000);
				return months[a.getMonth()] + " " + a.getDate();
			}
		},
		tooltips: true
	};
	noUiSlider.create(slider, options);
</script>
`

**Comment by leongersen** [comment]
Why are your `to` and `from` functions the same? `to` should to *to* the formatted value, `from` should convert *from* a `string` to a `number`.

**Comment by i-fail** [comment]
leongersen, your comment made me test a few things. Turns out from() method actually gets a number, not a string - you can console.log it, if you don't believe me.

So this change made everything work:

```
		format: {
			to: function(v){				
				var a = new Date(v * 1000);
				return months[a.getMonth()] + " " + a.getDate();
			},
			from: function(v) {
				return v;
			}
		},

```

**Comment by MSCAU** [comment]
Yes. I am trying to do exactly the same thing and the "to" function always only receives a NaN.

It's also not really clear to me what "to" and "from" are supposed to do. I thought they were supposed to return strings that would then appear in the tooltips, but maybe this will become clearer if you fix this issue.

**Comment by leongersen** [comment]
Maybe this helps. The simplest form of to and from would be: `to: String, from: Number`.

**Comment by i-fail** [comment]
leongersen, as I said in my previous comment, I don't think that's true, there must be a bug that sends incorrect parameters to **from()**

**Comment by leongersen** [comment]
- [ ] Throw exception if input to `to` and `from` is not of the correct type;

**Comment by i-fail** [comment]
Another related bug I discovered is that **on('update', ...** returns formatted values instead of the raw numbers. I just got tired of all the formatting bugs, and decided not to use the builtin option and replaced it with a few lines of my own code, which simply formats the tooltip on update:

```
	slider.noUiSlider.on('update', function(values, handle){
		elFormatDate($('.noUi-handle[data-handle="0"] .noUi-tooltip')); // left
		elFormatDate($('.noUi-handle[data-handle="1"] .noUi-tooltip')); // right
	});

	function elFormatDate(el) {
		var v = el.text();
		if (v.indexOf('.') == -1) return;
		var a = new Date(v * 1000);
		el.text(months[a.getMonth()] + " " + a.getDate());
	}
```

In general, I think you made a bad choice in the way the whole formatting system is done. The conversion function (from) that converts formatted -> unformatted shouldn't even be needed, for many reasons. The formatting should happen for display only, so you only need **to()** method in some form. The second reason is that from() might not even exist, because, like in my example with the dates, the reverse function doesn't really exist. I convert timestamp seconds to day/month. You can't reverse day/month to get the original timestamp.

**Comment by leongersen** [comment]
The system works this way so it can be synced with user-editable inputs. The argument order (`values, handle, unencoded, tap, positions`) to all events is the same, and is entirely documented.

**Comment by leongersen** [comment]
You can simply specify the `Number` constructor as the `from` function if you want to input only unformatted numbers.

**Comment by alex88** [comment]
So this should work?

```
    const formattingFunction = (value) => {
      console.log(value);
      return value;
    }

    noUiSlider.create(this.slider.nativeElement, {
      start: [this.steps[0], this.steps[this.steps.length - 1]],
      tooltips: {
        to: formattingFunction, from: formattingFunction
      },
      connect: true,
      range: {
        'min': 0,
        'max': 100
      }
    });
```

I'm trying to format the tooltips, however just with such a simple function, it never gets called nor it throws any error, the slider just never appears. Commething the tooltips lines make it working again
