### ISSUE TITLE
Request to use transform in mobile or for modern browser

### ISSUE THREAD

**Issue by gitlovenotwar** [leongersen/noUiSlider#718]
I would like to use this on mobile browser, it would be good if there's an option to set to use transform than moving it left/top.

**Comment by leongersen** [comment]
This'd work for the handles, but not for the `connect` option.

**Comment by leongersen** [comment]
I prototyped a little, and it could possibly be done using the `scale` option:

![image](https://cloud.githubusercontent.com/assets/1206361/20463090/2d07583c-af2c-11e6-8a93-94447ee002da.png)

- With handles and connect at a width of 1%, a 2000% transform is 20% of the parent element;
- With a width of 1%, a scale of 60x is 60% of the parent element. We'd then have to adjust the transform to match for the visual disparity.

**Comment by leongersen** [comment]
Combined with `transform-origin` this becomes rather easy:

```CSS
.noUi-connect {
    transform-origin: 0 0;
}
.noUi-vertical { {
    height: 1%;
}
.noUi-horizontal { {
    width: 1%;
}
```

```Javascript
function getSupportsCSSTransform ( ) {
    return window.CSS && CSS.supports && CSS.supports('transform','translate(0,0)');
}
```


```Javascript
function generateConnectCSSRule ( offset, width ) {
    var o = options.ort;
    var a = (100 * offset) + '%' ;
    var b = width;
    return 'translate(' + (o ? '0' : a) + ', ' + (o ? '0' : a) + ') scale(' + (o ? '0' : b) + ', ' + (o ? '0' : b) + ')';
} 
```

Then the inline style for connect would be: `transform: translate([ 100 * left offset ]%, 0) scale([ width of connect bar in pct ], 0)`.

This formula needs to be applied in [this inline style change](https://github.com/leongersen/noUiSlider/blob/856f5ad531f01aa17584f9aeeb6e05adec4884fd/distribute/nouislider.js#L2013).

The handles are more straightforward and only need `transform`. The setter is [here](https://github.com/leongersen/noUiSlider/blob/856f5ad531f01aa17584f9aeeb6e05adec4884fd/distribute/nouislider.js#L1952).

**Comment by leongersen** [comment]
Released in noUiSlider 11!

**Comment by asaarnak** [comment]
One issue we had with scale() introduced in version 11.
Is that when '.noUi-connect'.innerHtml is set, it's also scaled.
We set '.noUi-connect'.innerHtml to display time on the slider.
