### ISSUE TITLE
Issue with start[min,max] 

### ISSUE THREAD

**Issue by shkodasv** [leongersen/noUiSlider#719]
Hi!
I have the issue with formatting
```
 noUiSlider.create(slider, {
            start: [3666.6, 21053.8],
            connect: true,
            step: step,
            format: wNumb({
                decimals: 2,
               mark: ',',
               thousand: '.'
        })
        });
```
In this case initial range set incorrect. Could you please suggest how to fix it ?

**Comment by leongersen** [comment]
You'll have to be more specific. Can you describe what you mean by 'incorrect', and perhaps setup a jsFiddle (or similar) so I can have a look?

**Comment by shkodasv** [comment]
Yep, you are right
Example here https://jsfiddle.net/ValentinaSmirnova/Lk956f49/
First slider show incorrect range due to start: [ 2000.79,3000.56 ],
Second one correct start: [ 2000.00,3000.00 ],

**Comment by leongersen** [comment]
There are two things happening:

- The `start` option uses the `format` option to parse the input;
- The `step` option rounds the decimals away (to the nearest step);

Changing those options, you get the expected result: https://jsfiddle.net/Lk956f49/9/

**Comment by shkodasv** [comment]
thank you!
