### ISSUE TITLE
IE8 - Handle stuck to cursor after slider handle click

### ISSUE THREAD

**Issue by vladdypwnz** [leongersen/noUiSlider#720]
![4f5df47a63c63d7f1dfa9050e2a1f98a](https://cloud.githubusercontent.com/assets/841644/20238525/84ca69aa-a8a2-11e6-96fc-fa2a4e54b607.gif)

Every now and again, once the cursor clicks & drags on the handle and moves outside of it, it'll stay attached forever.

<img width="500" alt="screen shot 2016-11-12 at 6 33 29 am" src="https://cloud.githubusercontent.com/assets/841644/20238508/118b3cf8-a8a2-11e6-9b5c-0eeddeb2078f.png">

Object expected error leads [here](https://github.com/leongersen/noUiSlider/blob/2671350675b791b97129280d8dd29d73f0dd529a/distribute/nouislider.js#L1509) and class list is null leads [here](https://github.com/leongersen/noUiSlider/blob/2671350675b791b97129280d8dd29d73f0dd529a/src/js/helpers.js#L74)

**Comment by leongersen** [comment]
(Maybe related to #704)

**Comment by leongersen** [comment]
Probably related to #700

**Comment by leongersen** [comment]
This issue is fixed in release 9.1.0. Thanks for this report!
