### ISSUE TITLE
Using pips mode 'count' crashes Chrome

### ISSUE THREAD

**Issue by MSCAU** [leongersen/noUiSlider#721]
"Chrome ran out of memory when trying to display this web page":

```
		noUiSlider.create(slider_dates, {
			start: [1,4],
			connect: true,
			tooltips: true,
			range: {
				'min': 0,
				'max': 5
			},
			pips: {
				mode: 'count',
				density: 2
			}
		});
```

**Comment by leongersen** [comment]
It should `throw` instead of crash, but the issue here is that mode `'count'` also requires `'values'` to be set.

**Comment by leongersen** [comment]
Slider now throws an exception on this config.
