### ISSUE TITLE
Disable the snapping into certain values in slider

### ISSUE THREAD

**Issue by sabbiu** [leongersen/noUiSlider#722]
Hey, this is my slider. 
noUiSlider.create(exactSlider, {
    start: 1995,
    step:1,
    range: {
        'min': 1950,
        'max': 2016,
    },
}
How do I disable the array of values (for eg, [2000, 1965, 2013]), so that the slider can't get snapped into those values?

**Comment by leongersen** [comment]
[This example](https://refreshless.com/nouislider/examples/#section-skipping) could help.

**Comment by sabbiu** [comment]
Yeah, I saw that, but could not understand like,
Should I add all the allowable selection into key value pairs as {'percentage': value}? Isn't there an easier way? Because adding all allowable selection into key value pairs is really cumbersome.

**Comment by leongersen** [comment]
No, you can set up ranges with step values between the unacceptable positions.

**Comment by sabbiu** [comment]
Then, how do you suggest me to write range:{ /*sth */ }, if I want to disable these three values [2000, 1965, 2013] in the above slider?

**Comment by leongersen** [comment]
quick pseudo code, may be off by one:
```
var range = {'min': 1950, max: 2016};
var diff = 100/(2016 - 1950);

for ( var i = 1951; i < 2016; i++; ) {
	if ( [2000, 1965, 2013].indexOf(i) === -1 ) {
		range[(i-1950) + '%'] = i;
	}
}
```

**Comment by sabbiu** [comment]
Works nicely! Thanks.
But what if I want to disable min and max value too?

**Comment by sabbiu** [comment]
Hey! If I want to disable the selection of min and max value too ...
What is the way around it?

**Comment by leongersen** [comment]
Pull #711 implements this, but I haven't gotten around to merging it yet.

**Comment by leongersen** [comment]
The `padding` feature is now part of release 9.1.0, so you can disable the slider's edges.
