### ISSUE TITLE
"undefined" at specific range level

### ISSUE THREAD

**Issue by basemwahba** [leongersen/noUiSlider#723]
Based on your solution :+1: [here](https://github.com/leongersen/noUiSlider/issues/698#issuecomment-250558890
), I have created the same fiddle but slider2 ranges are:
`min: 1` and `max: 7`

https://jsfiddle.net/wd7Lr68t/10/

The problem is that range 6 is always **undefined** 

Kindly advise.

Thank you very much.

**Comment by leongersen** [comment]
At 6, the actual value = 6.000000000001, which is not a position in the array. You can round that away:

https://jsfiddle.net/wd7Lr68t/11/

**Comment by basemwahba** [comment]
Thank you. Thank you very much for your solution.
Special thanks for your immediate reply.
