### ISSUE TITLE
Multiple noUiSlider instantiation issue

### ISSUE THREAD

**Issue by Giuseppe-Scalese** [leongersen/noUiSlider#726]
Hello,
I'm trying to create multiple noUiSliders in one page, but I'm getting this error "noUiSlider.create requires a single element".
Basically, I'm instantiating two (or more) sliders (with different class) from different functions but I'm getting the above errors.
Can you advise anything? What am i doing wrong?

Here is the example:
```
var Slider1Handler = function(){

 var slider1 = document.getElementsByClassName('slider1');
 noUiSlider.create(slider1, {
      start: [ 0 ],
      connect: [true, false],
      step: 1000,
      tooltips: true,
      orientation: "horizontal",
      range: {
        'min': [  2000 ],
        'max': [ 10000 ]
      }
 });
 };

var Slider2Handler = function(){

 var slider2 = document.getElementsByClassName('slider2');
 noUiSlider.create(slider2, {
      start: [ 0 ],
      connect: [true, false],
      step: 1000,
      tooltips: true,
      orientation: "horizontal",
      range: {
        'min': [  2000 ],
        'max': [ 10000 ]
      }
 });
 };
```

**Comment by leongersen** [comment]
`getElementsByClassName` returns a `nodeList`, not single elements.

**Comment by Giuseppe-Scalese** [comment]
Thanks for getting back to me.

Does it mean I can do this by using only IDs?

**Comment by leongersen** [comment]
Answered on [stackOverflow](http://stackoverflow.com/questions/40746577/multiple-nouislider-instantiations-issue/40762768).

**Comment by Giuseppe-Scalese** [comment]
Just seen, thanks!

**Comment by riskaverse** [comment]
You can use this method:
var nonLinearSlider = document.getElementsByClassName('rangeSliderComponent');
		$(nonLinearSlider).each(function(i, val){
			noUiSlider.create(nonLinearSlider[i], {
				connect: true,
				behaviour: 'tap',
				start: [ 500, 4000 ],
				range: {
					// Starting at 500, step the value by 500,
					// until 4000 is reached. From there, step by 1000.
					'min': [ 0 ],
					'10%': [ 500, 500 ],
					'50%': [ 4000, 1000 ],
					'max': [ 10000 ]
				}
			});
		})
