### ISSUE TITLE
Event not firing on slider change

### ISSUE THREAD

**Issue by Giuseppe-Scalese** [leongersen/noUiSlider#727]
Hello,

I'm struggling to fire the slider event when using it.
Nothing happens when I change position of the slider cursor.

Below is both the html and the JS I'm using. Below u can see the jQuery event I'm binding to the slider ID.

I don't understand what's wrong with it. 
Can you help?

 `  <div id="getting-to-know-slider1" class="slider slider--no-tooltip"></div>`

```
//check whether or not namespace exist
var MyApp = MyApp || {};

//create my app namespace
var MyApp = (function(){

  var _highlightLabel = function($this) {

    $('.slider-labels li').removeClass('active');
    var index = parseInt($this) + 1;
    var selector = '.slider-labels li:nth-child(' + index + ')';
    $(selector).addClass('active');
  };


  var sliderHandlerGettingToKnow1 = function(){
   var gettingToKnowSlider1 = document.getElementById("getting-to-know-slider1");
  
     if(gettingToKnowSlider1 !== null){
     noUiSlider.create(gettingToKnowSlider1, {
          start: [ 0 ],
          connect: [true, false],
          step: 3.3333,
          tooltips: true,
          orientation: "horizontal",
          range: {
            'min': [  0 ],
            'max': [ 10 ]
          },
          serialization: {
          format: {
            decimals: 0
          }
        }
     });
    }

     $('#getting-to-know-slider1').on('update',     function(){
        console.log('in');
      //highlightLabel($(this).val());
      });
   };
};

  return {
      sliderHandlerGettingToKnow1: sliderHandlerGettingToKnow1
  };

})();
MyApp.sliderHandlerGettingToKnow1();



```

**Comment by leongersen** [comment]
The events emitted by noUiSlider are not compatible with jQuery events. You could emit them:

```
gettingToKnowSlider1.noUiSlider.on('update', function(){ $(gettingToKnowSlider1).trigger('update'); });
```

**Comment by Giuseppe-Scalese** [comment]
I've found out I can use the object returned by noUiSlider.Create to access its events and It works fine.
Thanks for your answer, that works too.

var sliderEventListener = noUiSlider.create(gettingToKnowSlider1, {
          start: [ 0 ],
          connect: [true, false],
          snap: true,
          tooltips: false,
          orientation: "horizontal",
          range: {
            'min': 0,
            '33%': 1,
            '66%': 2,
            'max': 3
          }
     });
       sliderEventListener.on('update',function( values, handle ){
       doSomething($(this), values);
       });
