### ISSUE TITLE
Disable click on handle(s) not possible?

### ISSUE THREAD

**Issue by stl99** [leongersen/noUiSlider#728]
Hi there. Maybe I misinterpreted the user interaction settings but after I set the slider behaviour to "none" noUi-handle is still clickable, only noUi-connect is disabled. Can clicking on handles be disabled? Thanks.

**Comment by leongersen** [comment]
`none` removes the tap on `.noUi-connect`. You can [disable handles](https://refreshless.com/nouislider/more/#section-disable).

**Comment by stl99** [comment]
Thanks, I did spot that setting though. What I want to do is to only trigger the slider action when the handles are dragged AND released.  Right now, a tap on the handle (e.g. when it is at zero) already triggers the action. I get complains from some users that the slider fires prematurely when they try to drag it (they probably do a quick tap rather than actually dragging without realizing it but still...).

**Comment by leongersen** [comment]
That's not a setting, no. I'd recommend saving the slider values on every `change`, then only triggering an action if they are different.
