### ISSUE TITLE
input field inside tooltip - for slider with 3 handles

### ISSUE THREAD

**Issue by saratSubramaniam** [leongersen/noUiSlider#729]
This issue is related to an already closed issue.
https://github.com/leongersen/noUiSlider/issues/659
The method shown in the JS Fiddle (https://jsfiddle.net/leongersen/6oc2pqpz/2/) works perfectly fine with 2 handles. 
With the new version of no Ui slider, when I added one more hand and added this chaining logic, the input boxes get initialized for each handle. Unfortunately, on sliding, the values in the input box does not change. The update event fires and the input box values get updated too. But the view doesn't reflect that.
Any one having any thoughts ?

**Comment by saratSubramaniam** [comment]
Closing the issue, since it was a code mistake.
        input.addEventListener('change', function () {
            var values = [null, null, null];
            ............

The 3rd array element was missing in my code.

**Comment by sivdwulp** [comment]
I am new to programming but am struggling with the third (and fourth) tooltip handles

having added the 3rd and 4th element in values & the entries [2] and [3] for the tooltipInputs, i had NO luck getting the editable tooltips for the inner handles (not equal to 'noUi-handle-lower' ||  'noUi-handle-upper'

Any recommendations?

**Comment by leongersen** [comment]
Yes, the 2nd out of two handles won't have `noUi-handle-lower` or `noUi-handle-upper`. Each handle has an `data-handle` attribute with a value starting at 0. That value is the index of the `values` array. (so `Number(handle.getAttribute('data-handle'))`).

**Comment by sivdwulp** [comment]
I apologize in advance for the level of my questions, i'm a beginner in this matter.

But how is this applicable to append the input box to the relevant tooltip as done in the following line?:

slider.querySelector(i ? '.noUi-handle-upper' : '.noUi-handle-lower').appendChild(tooltip);

**Comment by leongersen** [comment]
`slider.querySelector('[data-handle="' + i+ '"]').appendChild(tooltip);`

**Comment by sivdwulp** [comment]
I thank you very much for your advice

**Comment by sivdwulp** [comment]
This worker perfectly!
