### ISSUE TITLE
How to make colour different for each step to the left of a slider?

### ISSUE THREAD

**Issue by Giuseppe-Scalese** [leongersen/noUiSlider#730]
Hello,

I'm wondering if it's possible to give the UI-Connect class a different background colour each time I move the slider towards the right. 
For example, If the slider has 5 steps, the left side of the slider has different colours every time I slide towards the right. Also, can the tooltip colour change accordingly?
Is it possible?

Thanks!

**Comment by leongersen** [comment]
On the change event, change a class on the slider and add a color in CSS.

**Comment by Giuseppe-Scalese** [comment]
Yeah that's what I've done in the end. I've added a class to "noUi-connect" to overwrite the existing background.
Thanks
