### ISSUE TITLE
click on the "noUi-value"

### ISSUE THREAD

**Issue by sergey-kozlov** [leongersen/noUiSlider#733]
Maybe you need to add the ability to set the value by clicking or tapping on the item "noUi-value"?

**Comment by leongersen** [comment]
You can `querySelectorAll` them and `addEventListener` externally.

**Comment by sergey-kozlov** [comment]
Yes) But it would be a good opportunity to "out of the box". Due to the formatting of the text labels calculation values to be set, it is difficult.  Maybe, if it was at the label data-attribute with the raw value of the range, it would be easier. But I still think that this functionality is needed. Thanks for the answer.

**Comment by leongersen** [comment]
- [ ] add `data-value` to pips;

**Comment by leongersen** [comment]
There's a new [example in the documentation](https://refreshless.com/nouislider/examples/#section-click-pips) that shows how to do this. Thanks for participating in this project!

**Comment by ehassan66** [comment]
I have use the same code but when i click on any value my slider move from start. It should move on respective value. Here is my code . Can anyone please help. 

https://jsfiddle.net/xfrtho8m/1/

<div id="slider-pips" style="top: 0px; right: 1px; margin: 10px 25px;"></div>
var pipsSlider = document.getElementById('slider-pips');

                noUiSlider.create(pipsSlider, {
                    //connect: true,
                    range: {
                        min: 0,
                        max: 100
                    },
                    start: [50],
                  // start: [1100,1850],
                    pips: {mode: 'count', values: 5}
                });
                var pips = pipsSlider.querySelectorAll('.noUi-value');
                function clickOnPip() {
                    var value = Number(pipsSlider.getAttribute('data-value'));

                    pipsSlider.noUiSlider.set(value);
                }

                for (var i = 0; i < pips.length; i++) {

                    // For this example. Do this in CSS!
                    pips[i].style.cursor = 'pointer';
                    pips[i].addEventListener('click', clickOnPip);
                }

**Comment by dartess** [comment]
@ehassan66 
a) data-value attr from one pipe, not from pips collection. 
b) you use old version library. data-value was added in 11 version.
https://jsfiddle.net/8f2pwboa/
