### ISSUE TITLE
is the option exist ?

### ISSUE THREAD

**Issue by flythird** [leongersen/noUiSlider#734]
Hello from cheese land ! 

alien, again, i continue to use your library and i wonder ....is it possible to set the pips above the slide ? 

you can manage orientation, direction, but what about the pips positions ?

my question is not very important... i just need to win place and lisibility... somewhere 

Is it possible to do that by changing a class parameter ?

Thank's for your attention and have a nice day.
p.s.: frog with cheese it's good too !

**Comment by leongersen** [comment]
Change the CSS, basically flipping `top` properties with `bottom`. It is not an option in the library.
