### ISSUE TITLE
decimal steps & margin: 'margin' must be divisible by step error

### ISSUE THREAD

**Issue by spoutnikz** [leongersen/noUiSlider#736]
Hello there!

The validity check in the getMargin method does not work when step is smaller than 1:
margin: 5
step: 0.2

`if ( step && (value % step) ) {
	throw new Error("noUiSlider: 'limit' and 'margin' must be divisible by step.");
}`

value % step = 5 % 0.2 = 0.19999999999999973 ..
but 5 % 0.2 = 25

It could probably use another way to validate if step < 1.

Cheers and thanks for the good work!

**Comment by leongersen** [comment]
Yep, that should be fixed.

**Comment by spoutnikz** [comment]
Works like a charm, thanks!

cheers

spoutnik
