### ISSUE TITLE
Bug with touch events

### ISSUE THREAD

**Issue by DavidGonzalez21** [leongersen/noUiSlider#739]
Hello, i am having an issue with the library, i have 3 sliders on one page, and i have a validation that if two sliders i.e slidera * sliderb > 30 it will block the values, with set value method, and it will let you down the value but not increment it, with the pointer action it works very well but with touch action it crashes, can you take a look at this please

![image](https://cloud.githubusercontent.com/assets/15733951/21329667/7d43706c-c5ff-11e6-904e-8ecc2e723052.png)

**Comment by leongersen** [comment]
Closing this as no code has been provided, as per contributing requirements.
