### ISSUE TITLE
'set' event moves cursor at the end of linked input.

### ISSUE THREAD

**Issue by studio404pl** [leongersen/noUiSlider#740]
I am trying to update value of slider after keypress with that code.

Everything works good but i want active cursor to stay in the same place instead of going at the end of the value to allow user to easily correct value in case of mistake instead of moving cursor again through few digits to left by mouse or keyboard arrows.

`activeUsersInput.addEventListener('keydown', function(){
        setTimeout(function(){
          activeUsers.noUiSlider.set(activeUsersInput.value);
        }, 200);
      });`

**Comment by leongersen** [comment]
You can probably use `selectionstart`:

http://stackoverflow.com/questions/14508707/updating-an-inputs-value-without-losing-cursor-position
