### ISSUE TITLE
API Doc page not accurate

### ISSUE THREAD

**Issue by knod** [leongersen/noUiSlider#742]
This page is the one I'm looking at specifically: https://refreshless.com/nouislider/events-callbacks/

The description at the top says `update` fires when "A handle is released after dragging". When I use the demo, that doesn't happen. `update` fires while the handle is being dragged, but on release only `set`, `change`, and `end` are fired.

Using:
MacBookPro OSX 10.11
Firefox 50.1

**Comment by leongersen** [comment]
Thanks for bringing this to my attention, I've updated the documentation.
