### ISSUE TITLE
Start and end to tap event

### ISSUE THREAD

**Issue by knod** [leongersen/noUiSlider#743]
The `start` event would be fired when the tap occurs and the `end` event would be fired after the value is changed. Maybe the events that are fired work that way, I'm not sure, but if so, it's not clear and it'd be great if it matched the dragging behavior so the same events could be used to gather data from both actions.

If it would help, I could give a description of my specific use case, but I think it would be more broadly applicable.

**Comment by leongersen** [comment]
For this situation, the `change` event with the `tap` parameter would be `start`, and `end` would occur (`animationDuration`](https://refreshless.com/nouislider/slider-options/#section-animate) later. Could you elaborate on your use case?

**Comment by knod** [comment]
That sounds reasonable. I spent some time trying to work out other possibilities, but it mostly depends on how `tap` behavior is set up. I just think the `tap` events could behave similarly enough to the `drag` events that desired behaviors could be implemented for them both at once. Maybe that's not possible.

In detail, my use case is this:

I'm making a Chrome extension that shows an article to the user one word at a time in a bar at the top of the screen. You can look up RSVP if you want to see the kind of behavior I'm talking about. It's mostly seen in the context of speed reading, but it has other applications, which I'd be happy to describe if you're curious. I'm creating a scrubber bar for controlling playback - scrubbing to whatever words you want to see. You can use this scrubber bar in two ways - you can drag the scrubber to where you want it, or you can click to the spot you want to go to. This bar also shows the progress of the extension (how far it's gotten in the text). At the moment, as the text progresses the position of the scrubber/progress bar is updated with `.set()`, so I can't use the `set` event to trigger anything.

I started off by implementing the drag use case. When the drag operation was started (`start`) the play/pause state of the app was saved (so it could be restored when the user was done with the action), the playback was paused, so it wouldn't interfere with the actions of the user, and progress updates with `.set()` were paused. As the bar was dragged (I played with both `slide` and `update`), the index of the words was retrieved using the value of the slider and new words were displayed. At the `end` event, the previous state of the app was restored.

I then tried to add in the ability to click to a position in the slider. I was a bit unclear about what events I could use that would give me the result I wanted. I guess I was expecting the ability to tie into similar behavior. I ended up using the `start` event to stop progress updates, then the `slide` event for the state storing, the pausing, and the updating, then the `change` event for restoring state. I used the `snap` behavior to make the interaction with the words that appear feel right. That seems to be working pretty well. Maybe it's just not the interaction that I'd expected.

`end`, `set`, and `change` seem to be a bit intertwined there. I can understand why `change` is attractive - it does mesh with `<input>`'s `change` event name, but it seems unclear to me. I have to say, I disagree with how that particular `<input>` event is named and get confused about it constantly, but there's not much to do about that. The spec is the spec. Also, I understand if you don't change your whole API over this.

Great tool, btw. Makes it pretty darn easy to implement sliders.

**Comment by leongersen** [comment]
Thanks for elaborating. I don't quite understand what you'd need the `start` and `end` behaviors for if you are using `snap`, so maybe you could clarify there. 

I get your point about confusing event names, but as you mention, I chose `change` to match `<input>`. I've found that the `slide` event isn't as useful as `update`, as the later allows keeping other elements or an application state in sync with the slider.

Would you propose any changes to the event model (other than renaming, perhaps)? I'd be interested in proposals to add event types if there is a use case that can't really be implemented by the current event set.

On a practical note, the `start` and `end` events could be fired from change:

```
slider.noUiSlider.on('change', function(values, handle, unencoded, tap, positions){
	if ( tap ) {
		yourStartEvent.call(this, values, handle, unencoded, tap, positions);
		setTimeout(function(){
			yourEndEvent.call(this, values, handle, unencoded, tap, positions);
		}, 300); // Default animation duration
	}
});
```

**Comment by knod** [comment]
Other than adding `start` and `end` to tap, I have no suggestions at the moment. The purpose would be so that the same code could easily be applied to tapping and dragging in an intuitive way. That's based on my experience working with the code, but mileage may vary of course.

I used `snap` partially because of the issues with having no `end` to the `tap` event. Things look weird otherwise. A different configuration would let me use whatever method I want. A different code architecture would allow me that choice. Basically, its the principle of the thing that seems important to me - it seems like the right behavior to have in this situation, regardless of whether I, myself, currently need it.

Thanks for the tip on `update`, I'll try that out. I thought I had understood from the docs that `slide` was primarily used for syncing with other apps:

> "This event is useful when you want to update a value or perform an actions every time a handle is dragged. For example, you can use the 'slide' event to update graphs."

As for firing the `start` and `end` events in that way, I'd be reluctant to use a timer to trigger the `end` functionality, even if it has the same value as the animation duration. Asynchronicity being what it is, that's just not reliable enough if other code needs precise behavior. It would be better if it could be synced up with the actual animation somehow. In fact, it seems to me that the changing of the sliders values in general should be synced up with the movement of the handle. If it takes 2000ms for the handle to arrive at a new position, it seems strange that the input element (if it exists) would change instantly to the end value.

In my use case specifically, if I wasn't using snap it would look strange if the word on the display jumped to the end result while the handle was still traveling to its final position.

All that said, I haven't looked into how you handle the animation. I suspect that you leave that up to the user, and if that's the case, then I'm not sure how much there is to do about it. If it's all handled through css animations, you might be able to at least hook into a `transition-end` event as long as the person using the library used the right classes. There might be other `animation` and/or `transition` events as well. It's a bit fiddly, but it would still be usable. The documentation about it would have to be pretty clear, prominent, and easily searchable. Putting an explanation on stackoverflow might help with that. I think it stackoverflow is ok with someone asking a question and then answering it just to get the info out there, but if not, I'd be happy to ask the question.

**Comment by leongersen** [comment]
I'll extend on this later: Animation works two-fold: the slider disables all interaction for [`animationDuration`](https://refreshless.com/nouislider/slider-options/#section-animate) milliseconds (and only if `animation` is `true`), the slider CSS `transition`s the handle to the new position.

**Comment by monstermudder78** [comment]
I believe I have experienced a manifestation of the issue described here. I am submitting slider values via ajax - when the handles are dragged the correct value is submitted. However, when the the slider is tapped, it appears the slider.noUiSlider.on('set', function()) is called before the slider updates the linked input. To solve the problem I added a 200ms delay, before submitting, which seems to be working (I have not experimented with shorter times, I just know this is working for me now). However it seems odd that 'set' is fired before the updating is complete.

If there is a better way or I missed a configuration that would prevent this, please, I am all ears.

Code:
`// add listener to submit the new response when the slider is done changing
    slider.noUiSlider.on('set', function(){
        // set timeout is need to deal with taps, which blur before the slider is done moving
        setTimeout(function() {
            submitResponseOnBlur(answer);
        }, 200);
    });`

**Comment by leongersen** [comment]
You can override this: set `animationDuration: 0`, and add `.noUi-state-tap .noUi-origin { -webkit-transition: none; transition: none; }` to your CSS. This'll disable the tap animation so the update seems in sync.

**Comment by leongersen** [comment]
Just to clarify, events on tap fire in this order: `slide`, `set`, `change` and `update`.

**Comment by leongersen** [comment]
I'm closing this, favoring #775. Feel free to reopen if you have anything to add.
