### ISSUE TITLE
Unconstrained handle

### ISSUE THREAD

**Issue by marcovc** [leongersen/noUiSlider#747]
Hi,
I wan't to have three handles where the position of one of them is not constrained to the positions of the others. Is this possible?
Thanks
Marco

**Comment by leongersen** [comment]
This currently isn't a feature within noUiSlider.

**Comment by marcovc** [comment]
@leongersen, thanks for the reply! I will try to solve the problem by stacking two sliders, and making one of them invisible.

**Comment by AdansBatista** [comment]
Yep, that is a significant improvement in my case too.

**Comment by akhlesh** [comment]
Looking forward to use this feature, any ETA for 12.1?

**Comment by leongersen** [comment]
This is now a feature in noUiSlider 12.1.0. Thanks for contributing!

[Documentation on the `"unconstrained"` option](https://refreshless.com/nouislider/behaviour-option/#section-unconstrained).
