### ISSUE TITLE
How to get options programatically

### ISSUE THREAD

**Issue by iongion** [leongersen/noUiSlider#751]
Is there a way to get the options after initialization(the current slider options) ?
Currently I store them in a global, but that is dirty. I've googled and the only reference I found to something similar is here:
https://github.com/leongersen/noUiSlider/issues/270

"You can read your options back with $('#slider').noUiSlider('options'). See 'reading options back' for more details"

But the *reading options back* link does not work properly.

**Comment by leongersen** [comment]
Options are in `slider.noUiSlider.options`. This should be in the documentation, I'll have to add that.

**Comment by iongion** [comment]
Great! Please add it, it was that simple!

**Comment by leongersen** [comment]
This is now in the documentation.
