### ISSUE TITLE
No css style applying to slider, and hence slider is not showing at all

### ISSUE THREAD

**Issue by JGupta-A1** [leongersen/noUiSlider#753]
Here is my component  code: 

`import { Component, OnInit } from '@angular/core';`
`@Component({`
`selector: 'app-slider-bar',`
`templateUrl: './slider-bar.component.html',`
`styleUrls: ['./slider-bar.component.scss' ]`
`})`
`export class SliderBarComponent implements OnInit {`
`    someRange: any = 5;`
`  constructor() { }`
`  ngOnInit() { }`
`}`

Here is html code : 
`<nouislider [min]="0" [max]="15" [(ngModel)]="someRange"></nouislider>`

But the slider is not showing. And when I inspected element, I found that `nouislider` element and it child elements are not picking up the styles.

**Comment by leongersen** [comment]
This is regarding an implementation in another framework and not actionable for me, so I'm closing this issue.

**Comment by geewhizbang** [comment]
I had nothing appearing because I have overflow hidden as the default for divs in my stylesheet.
