### ISSUE TITLE
Show a vertical line for each value and nothing more.

### ISSUE THREAD

**Issue by jongio** [leongersen/noUiSlider#754]
What is the best way to show a line for every value?

I just want to show a line on the slider for each selectable value.

I've tried just about every option imaginable for pip but can't figure it out.

For example, if my slider has [2,4,10]. I only want to show a vertical line for each of those values and no dashes in between those values.

Thanks
Jon

**Comment by leongersen** [comment]
This isn't currently a setting in pips, but it could be added.

**Comment by jonbgallant** [comment]
Any ideas for how to hack it in there until implemented?  Thanks.

**Comment by leongersen** [comment]
Take out [this line](https://github.com/leongersen/noUiSlider/blob/master/src/js/pips.js#L215).

**Comment by leongersen** [comment]
I just released noUiSlider 12.0.0 where this feature is added. You can now return `-1` from the `filter` function. Thanks for contributing!
