### ISSUE TITLE
Drag more than 2 connected handles together

### ISSUE THREAD

**Issue by h0gar** [leongersen/noUiSlider#756]
Instead of dragging only the two connected handles, is there a way to drag all the connected handles together?

Here for example the three handles should move together when I drag either range.
![Handles](http://i.imgur.com/4cOO48q.png?1)

**Comment by leongersen** [comment]
Addressed in #841

**Comment by leongersen** [comment]
The changes requested here are partially implemented in #841. The code could be migrated to the latest noUiSlider version. To accept a PR I'd need the introduced `dragAllHandles` option to be a part of the current `behaviour` option.

**Comment by satendra02** [comment]
Hi, @leongersen I am looking for the exact same feature. 
Is there any workaround for now until you release this feature. i.e something like, override `update` event and add logic there to move all connect together externally.

**Comment by leongersen** [comment]
This feature is now available in noUiSlider 15.4.0. Thank you for contributing!
