### ISSUE TITLE
Handle not draggable for a 'vertical' 'rtl' slider

### ISSUE THREAD

**Issue by 00SteinsGate00** [leongersen/noUiSlider#758]
When I create a vertical slider everything works fine. But I want 0 to be at the bottom and 1 at the top. So I used the `direction: "rtl"` option to change that.

But as soon as I do that, the handle is not draggable anymore. If I color `noUi-connect` and `noUi-target` differently, I see that the movement happens in the slider bar though. But the handle itself does neither move nor can I drag it.

<img width="232" alt="bildschirmfoto 2017-02-03 um 15 23 18" src="https://cloud.githubusercontent.com/assets/19982919/22594772/c2d03d74-ea24-11e6-8bfa-d9f53ccb690d.png">

To make sure it has nothing to do with my styling I checked it with the default css. And it has the same Problem.

Here is my code to initialize the slider

```
noUiSlider.create(sensitivitySlider, {
	'start': 0,
	'orientation': 'vertical',
	'direction': 'rtl',
	'range': {
		'min': 0,
		'max': 1
	}
});
```

Let me no if you need any more information.

**Comment by leongersen** [comment]
I have no issues using the example you provided. Have you tried setting up a minimal case and add your code from there to see what breaks it?
