### ISSUE TITLE
NPM package nouislider-algolia-fork is not synced with this repo

### ISSUE THREAD

**Issue by amar439** [leongersen/noUiSlider#759]
Hi,

I found the difference in the testConnect function
in the npm package it shows

function testConnect ( parsed, entry ) {

		if ( entry === 'lower' && parsed.handles === 1 ) {
			parsed.connect = 1;
		} else if ( entry === 'upper' && parsed.handles === 1 ) {
			parsed.connect = 2;
		} else if ( entry === true && parsed.handles === 2 ) {
			parsed.connect = 3;
		} else if ( entry === false ) {
			parsed.connect = 0;
		} else {
			throw new Error("noUiSlider: 'connect' option doesn't match handle count.");
		}
	}

but in the downloadable js file
it is

function testConnect ( parsed, entry ) {
		console.log('MYCONSOLE :::: ' +  entry)
		var connect = [false];
		var i;

		// Map legacy options
		if ( entry === 'lower' ) {
			entry = [true, false];
		}

		else if ( entry === 'upper' ) {
			entry = [false, true];
		}

		// Handle boolean options
		if ( entry === true || entry === false ) {

			for ( i = 1; i < parsed.handles; i++ ) {
				connect.push(entry);
			}

			connect.push(false);
		}

		// Reject invalid input
		else if ( !Array.isArray( entry ) || !entry.length || entry.length !== parsed.handles + 1 ) {
			throw new Error("noUiSlider (" + VERSION + "): 'connect' option doesn't match handle count.");
		}

		else {
			connect = entry;
		}

		parsed.connect = connect;
	}

the last one is correct. Can we get these two synced

**Comment by leongersen** [comment]
React-noUiSlider was started by @algolia and is on noUiSlider 8.x. There's [an issue about updating noUiSlider](https://github.com/algolia/react-nouislider/issues/34). Updating should be without problems, but they don't have time to do integration testing on their end, which I completely understand.

**Comment by leongersen** [comment]
It's fixed!
