### ISSUE TITLE
Stylesheets with overflow:hidden set globally cause all sorts of stuff to not appear

### ISSUE THREAD

**Issue by geewhizbang** [leongersen/noUiSlider#760]
It shouldn't be necessary to assume that overflow visible is true in the application where this tool is used. Some of us think this is a rather awful default for divs, since it messes up auto sizing.

     .noUi-base, .noUI-pips, .noUI-pips *, .noUi-base *, .noUi-target, .noUi-pips-horizontal {
          overflow: visible;
     }

(I'm not using it vertically, probably has similar issues)

**Comment by leongersen** [comment]
`overflow: visible` is a sensible default to assume. If you are doing something like `* { overflow: hidden; }`. expect odd performance issues. I won't try to prevent this in the style sheet.

**Comment by geewhizbang** [comment]
I showed you the four places where it needs to be changed and then it works fine. I expect divs to autosize themselves to their contents unless specified otherwise. I don't see how this affects the performance of the page.
