### ISSUE TITLE
noUiSlider should wrap itself in a properly sized div so that it can flow properly in layout

### ISSUE THREAD

**Issue by geewhizbang** [leongersen/noUiSlider#761]
Currently the div for noUiSlider is the bar itself, with all sorts of stuff hanging out from it. There should really be an outer element that flows in the layout, handles its margins and padding so you don't have to have a specially formatted div wrapper.

**Comment by leongersen** [comment]
`.noUi-target` specifies **no** dimensions or margin, and these **can be freely** applied. There is no need to wrap it in an additional element just for the sake of it.

**Comment by geewhizbang** [comment]
It's not good style to have an element that writes outside of its own container.
