### ISSUE TITLE
Slider not moving at all in IE8

### ISSUE THREAD

**Issue by vladdypwnz** [leongersen/noUiSlider#764]
I'm back. ( #720 )

This time - I can't get it to work. After about 3 hours wasn't able to figure out how I did it last time. 😂 I'm hoping I missed something super simple.

Here's my most fruitful attempt to hopefully shed some light as to where I went wrong. 

Setup: barebones [html skeleton](http://pastebin.com/G9mAMAG0), `nouislider.js` & `nouislider.css`. This setup doesn't actually render anything, complaining about line 853:

```javascript
Object.keys(tests).forEach(function( name ){
```

Ok, I guess that means polyfill isn't working. So I tried adding [es5-shim](https://github.com/es-shims/es5-shim) and sham. That resolved that but 1303 complained about `element.addEventListener(eventName, method, false);`, so I substituted `attachEvent` there. Seems like I'd missed something having to dig in so much.

Now the bar and handles are visible but 1853 is complaining:

```javascript
scope_Connects[index].style[options.styleOposite] = toPct(100 - h);
```

Turns out `h` is undefined causing `toPct` to return `NaN`. Changed to 99.

Now, no errors but the handles are still immobile. 

S.O.S.

**Comment by leongersen** [comment]
That `h` being undefined means the handle position is not set, which could come from *anywhere*. You'd have to follow calls to `setHandle`. 

What location do you serve where IE8 is still a real demographic, if you don't mind me asking?

**Comment by vladdypwnz** [comment]
It may not be a real demographic... kind of banking on it not being a real demographic. For a landing page though, every half of a percent counts though (at least in theory... if it's less than 0.5% then maybe not)

Still, is there a way I could investigate what's causing this if the barebones html+shim+nouislider is behaving like this?

**Comment by leongersen** [comment]
You'll have to check the values of `scope_Locations` when `setHandle` is called.
