### ISSUE TITLE
Please add a OSI recognized license

### ISSUE THREAD

**Issue by dhruv** [leongersen/noUiSlider#765]
Thank you for making your code available! Could you please add an OSI-approved LICENSE file to the repo so that it's clear under what terms the content is provided, and under what terms user contributions are licensed? The types are listed here: https://opensource.org/licenses

Thanks!

**Comment by leongersen** [comment]
Sorry, but no. This project is licensed under the WTFPL, which I think is very clear. If this doesn't suit you, you are allowed to fork the project and change the license.

**Comment by leongersen** [comment]
As of noUiSlider 12.0.0, the license changes to MIT.
