### ISSUE TITLE
`document` incorrect in iframe

### ISSUE THREAD

**Issue by knod** [leongersen/noUiSlider#767]
nouislider v9.2.0
Chrome v56.0.2924.87

I tried implementing nouislider in an iframe, and the sliders wouldn't move when I attempted to drag them with my cursor. Strangely enough, clicking on the connection bar itself, or on the input element, worked just fine. I didn't get a chance to look into why those cases were different.

Maybe I can look into injecting the nouislider scripts into the iframe instead of the parent document, but I found that redefining `document` in the distribution file fixed the issue. I'm pretty sure I can figure out how to make it work in the source files as well. It's a bit crude, but it works.

I could make a pull request with that change, but your contribution guidelines specify creating a test for the change and, having not worked with ui tests before, and this being such an strange case with the iframe, I'm not quite sure how to build those tests in a useful way. Specifically, I'm not sure how to simulate a dragging event in order to make sure that all the dragging stuff is happening in the correct document (which it isn't atm) by checking that the handle actually moves.

Any hints would be welcome. Also, let me know if you have another way in mind that you'd rather implement this change, or if you don't want this implemented at all. I do think using the target element's `.ownerDocument`, in whatever way it's done, is a more flexible way of creating sliders, but let me know if there are drawbacks that you see.

**Comment by leongersen** [comment]
Thanks for the detailed description. Unit tests on the event functionality is currently limited, although I've been playing around with extending them. This issue would be a good starting point. If you can provide a minimal reproduction (say, a document with an iframe and a description of what actions cause the issue),  I'd be happy to work on this issue with you.

Redefining `document` to `element.ownerDocument` in the noUiSlider scope would probably best be placed in `src/js/intro.js`. There's another usage of this document reference already in one of the [internal methods](https://github.com/leongersen/noUiSlider/blob/master/distribute/nouislider.js#L52).

**Comment by knod** [comment]
I'll work on cooking up an example. It should be pretty simple to set up (famous last words).

I put the declaration in `src/js/interface.js` and gave it a value in `src/js/intro.js` because that made it easier to read the distribution file. I could put them both in `src/js/intro.js`, though, if that's what you'd prefer. Another option is to declare a `doc` variable on the top level and go through and change every `document.` reference to `doc.`. Whatever works best for your setup.

I did see that use of `.ownerDocument`, but I didn't think it would be useful to go through every scope creating that `doc` variable in each one of them, so I did it "globally". If the top-level `document` variable is what you want to go with, I can also edit out that section to go back to using document.

**Comment by knod** [comment]
@leongersen: Tell me if this example works for what you need: https://knod.github.io/slider-bug/

**Comment by leongersen** [comment]
That example is as clear as it gets, thanks!

**Comment by knod** [comment]
I went ahead and edited two possible versions. They have a new test script, but it doesn't really do anything except contain a lot of useless comments. I'll link them soon, but first I need to make a different pull request.

**Comment by leongersen** [comment]
This is fixed in noUiSlider 10.0.0. Thanks for reporting!
