### ISSUE TITLE
Using noUiSlider for optional inputs

### ISSUE THREAD

**Issue by ValerioBulla** [leongersen/noUiSlider#769]
Is it possible to initialize the slider without a start position?
This is the behavior that I'd like to achieve: a slider that has no handles when initialized, but a value can be set (and handle will consequently appear) when the user clicks the slider. This would be great for optional fields.
As of now, omitting the start property (or using undefined values) causes a "noUiSlider (9.2.0): 'start' is required." error.

**Comment by leongersen** [comment]
No, but you could hide the handle with CSS. `.noUi-handle { display: none; }`.

**Comment by ValerioBulla** [comment]
@leongersen it's a clean solution, but unfortunately it still requires an initial value. I could set the initial value to the minimum range value, but then it wouldn't be optional anymore.

**Comment by emonidi** [comment]
@ValerioBulla  what you are saying does not make sense to me. Can you please elaborate on what you're trying to achieve? Or perhaps give an example from a site? I think that if you've got an optional field you can either disable the slider when not in use and neglect its value when the vield's value is missing or you can hide the slider when the optional field is not filled. Or maybe I've got your idea wrong?

**Comment by ValerioBulla** [comment]
@emonidi I apologize if I was unclear, I hope this makes more sense:
I am developing an app that requires the user to input a series of parameters to order a product. Some of those parameters are optional, i.e. they have no starting value. If the user sends the order without inputing the optional parameters, ther value is calculated server-side by the software that receives and manages the orders.
I'd like to use a slider for each parameter, initializing it without a starting value. This way, the user could click directly on the "empty" slider in order to set the parameter value / handle position.
The slider being disabled or hidden would prevent user input to begin with.
I'm using ng2-nouislider since it's an Angular 2 app, but the issue itself is present in the original noUiSlider plugin; simply binding the undefined model to the slider value throws the error.

**Comment by emonidi** [comment]
@ValerioBulla no need to apologise. Now I get it. My personal opinion is that this is more of an UX problem as it is slider functionality problem. Again that is my personal opinion. For me showing a slider with no handle makes no sense. Sure you could DOM-query the handle of the slider and show it when user clicks or hovers over the slider area but the user will probably wonder just as I do why there is a slider without a handle. I personally would take the default value from the server for that optional field an set the slider with the default value. For the server it should be pretty much the same if you are passing the default value or an empty value. So just set the slider to the same default value that the server would use and then pass it on with the server post request. I hope I helped in some way.

**Comment by ValerioBulla** [comment]
@emonidi thanks for your suggestions, unfortunately the server does not expose a default value, it is calculated when the order is sent in place of any missing optional inputs.
I agree that this is a UX issue; I was thinking about wrapping the slider in a custom component to keep track of the input value and set the form model accordingly, but it adds too much complexity for my taste for such a small feature.
I think I'll just hide the sliders until the user sets a value, as it has been suggested: it seems the cleanest solution. Thanks!
