### ISSUE TITLE
Different Padding values for Left and right

### ISSUE THREAD

**Issue by malaiselvan** [leongersen/noUiSlider#771]
Hi,

I am trying to setup this slider with different padding left and right values.  Something like as below

Min: 0
Max: 10
paddingleft: 3
paddingright: 8

Essentially the user can slide between 3 to 8.

It is now only possible for me to set a single padding which sets for both the sides.  How can I set different padding values for left and right?

**Comment by leongersen** [comment]
Addressed in #822
