### ISSUE TITLE
Step not calculating correctly for date ranges

### ISSUE THREAD

**Issue by malaiselvan** [leongersen/noUiSlider#772]
I am setting up the slider for date ranges with step 1 day.  The code snippet is as below

    var matPipsPositions = document.getElementById('pips-maturity');
    
    noUiSlider.create(matPipsPositions, {
    	range: {
            min: timestamp('2010'),
            max: timestamp('2015')
        },
    	step: 24 * 60 * 60 * 1000,
    	start: [ timestamp('02-21-2012') ],
    	connect: [true, false]
    });

Range is for 5 years and step value is 1 day.  But when I move the slider it jumps for more than 1 day.  If the slider is on full width (100%) it jumps for 2 to 3 days.  If the slider is 50% it jumps for 4 to 5 days.

I want the slider to jump only for 1 day irrespective of the slider width.  Is that something doable?

**Comment by rzb** [comment]
I don't think so. You are asking for a precision that is below the minimum your mouse can handle.

**Comment by leongersen** [comment]
@rzb is correct. There's only so many steps that can be represented on a small width.
