### ISSUE TITLE
noUi-connect no border radius

### ISSUE THREAD

**Issue by putyn** [leongersen/noUiSlider#773]
Hi,

I just starting playing with this pretty slider and i have to say that between all the available options this looks/works best.

Anyway now to the issue - not sure if its by design but if you use the option connect, the noUi-connect class doesn't have the same border radius like the noUi-target (4px)  making it look...not right :D (see the attached picture)
![no_border_radius](https://cloud.githubusercontent.com/assets/1035189/24447788/cb69d492-147a-11e7-9e85-70a27e57d6bc.PNG)

Vlad

**Comment by leongersen** [comment]
This is fixed in noUiSlider 10.0.0. Thanks for reporting!
