### ISSUE TITLE
Inconsistent priority of the set and update events

### ISSUE THREAD

**Issue by petervukovic** [leongersen/noUiSlider#775]
Given the user is **dragging** the slider, the set and update events fire in this order:

1. update
3. set

Given the user  **clicks or taps**  to a new location on the slider, the events fire in this order:

1. set
2. update

This makes it impossible to program behavior that relies on set and update events being fired consistently. It would seem logical and expected that the set event is the final event in the series (i.e. the value is set, there are no further events after that).

**Comment by leongersen** [comment]
The current order is undocumented, which is in itself a flaw. I agree on the need to change this.

**Comment by leongersen** [comment]
This is fixed in noUiSlider 10.0.0. Thanks for reporting! I've added the order of events ('start' > 'slide' > 'update' >  'change' > 'set' > 'end') to the documentation.
