### ISSUE TITLE
Reduce package size

### ISSUE THREAD

**Issue by evilebottnawi** [leongersen/noUiSlider#777]
Package contains unnecessary directories and files - `scripts`, `tests`, `.travis.yml` and others. I can do PR if your accept this issue.

**Comment by leongersen** [comment]
What package do you mean?

**Comment by evilebottnawi** [comment]
@leongersen `nouislider`, try to intstall `npm i nouislider` and see `node_modules/nouislider`, there are many unnecessary files

**Comment by leongersen** [comment]
Makes sense! I'm ok with a pull request.

**Comment by leongersen** [comment]
Addressed in #833
