### ISSUE TITLE
Warnings after upgrading from Angular 2 to 4

### ISSUE THREAD

**Issue by lebsral** [leongersen/noUiSlider#779]
After attempting to upgrade to Upgrade and Angular CLI project yarn gives this warning:

warning "ng2-nouislider@1.6.0" has incorrect peer dependency "@angular/common@^2.0.0".
warning "ng2-nouislider@1.6.0" has incorrect peer dependency "@angular/core@^2.0.0".

my current setup
$ ng version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0
node: 6.10.0
os: darwin x64
@angular/animations: 4.0.2
@angular/common: 4.0.2
@angular/compiler: 4.0.2
@angular/core: 4.0.2
@angular/forms: 4.0.2
@angular/http: 4.0.2
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.0.2
@angular/platform-browser-dynamic: 4.0.2
@angular/router: 4.0.2
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.2

**Comment by leongersen** [comment]
What are you looking for from me?

**Comment by lebsral** [comment]
nothing in particular, as long as you are aware. @leongersen
