### ISSUE TITLE
Windows is null on server

### ISSUE THREAD

**Issue by undergroundwires** [leongersen/noUiSlider#781]
Hi, I'm using noUiSlider with server-side prerendering but I cannot compile it while using the library with TypeScript. The reason is that server side prerendering does not set the "window" variable and I get exception.

Can we have null checks for logic that uses window variable here : https://github.com/leongersen/noUiSlider/search?utf8=%E2%9C%93&q=window&type=

A null check such as `if (typeof window !== 'undefined') { }` would make it easier to build the project in server context.

**Comment by leongersen** [comment]
As per #533, noUiSlider doesn't access window unless an actual slider is initialized. Is that insufficient in you setup?

**Comment by undergroundwires** [comment]
Thanks for the quick response, sir!.

I've just realized that I was using an older version to match the typing definitions in TypeScript. Updated noUiSlider, and both typings and window code works flawlessly now.

Sorry for the disturbance and taking your time.
