### ISSUE TITLE
Support stacked mode to divide into shares

### ISSUE THREAD

**Issue by mikehaertl** [leongersen/noUiSlider#782]
It would be great if the slider would support a "stacked" mode. For example, if you want to divide 100% into 4 shares. Something like this (showing 4 equal shares of 25% each):

![noui_stacked](https://cloud.githubusercontent.com/assets/675062/25435136/5db1f1fc-2a8f-11e7-80f9-b23ebbdaa91b.png)

I've already tried to use the existing API but I failed to achieve this. If you think, this is already possible, maybe you can let me know, how. Somehow I'm missing a way to update the tooltip content dynamically.

**Comment by leongersen** [comment]
You can use the `format` option on the tooltip, and supply in with a function that devides the value by the sliders maximum: `100 * (value / MAX) + '%'`.

**Comment by mikehaertl** [comment]
Hmm, I think you misunderstood. I can not use the formatter, as I need *all* values to calculate the tooltip content. For example if the first handle is moved to "10%", the red tooltip should read "10%" and the yellow "40%". But I found a way now. Here's what I did:

```js
    percentTooltips = percentSlider.querySelectorAll('.noUi-tooltip');
    percentSlider.noUiSlider.on('update', function (values) {
        percentTooltips[0].innerHTML = values[0] + '%';
        percentTooltips[1].innerHTML = (values[1] - values[0]) + '%';
        percentTooltips[2].innerHTML = (values[2] - values[1]) + '%';
        percentTooltips[3].innerHTML = (100 - values[2]) + '%';
    });
```

So unless you see a way to support something like this with a built in option, you can close this issue.

**Comment by mikehaertl** [comment]
For completeness let me show you a better example than the 4 equal sized shares above:
![nouslider_stack2](https://cloud.githubusercontent.com/assets/675062/25436052/5abd315c-2a92-11e7-98fd-88430e38de2d.png)

Basically the tooltips should be proportional to the width of the "connect" bars between them, not their position. That's what my code above does.

**Comment by leongersen** [comment]
Glad you figured it out!
