### ISSUE TITLE
Histogram chart + nouislider

### ISSUE THREAD

**Issue by rarkins** [leongersen/noUiSlider#783]
Has anyone managed to implement this type of Histogram chart (screenshot from Airbnb)?

![image](https://cloud.githubusercontent.com/assets/6311784/25561851/7c694234-2d74-11e7-873a-fc0005b85d28.png)

**Comment by leongersen** [comment]
I'd add say, 100 `<div>` elements with a width of `1%` above the slider, set a background to the color you want and then set the height to however many pixels/ems/etc are in that segment.
