### ISSUE TITLE
Content Security Policy console errors

### ISSUE THREAD

**Issue by x1c0** [leongersen/noUiSlider#784]
Hi,

I'm facing an issue using nouislider with CSP enabled on my server:

`Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'".`

`addMarking	@	nouislider.js:1229`
`pips	@	nouislider.js:1247`
`closure	@	nouislider.js:2114`
`initialize	@	nouislider.js:2135`

Basically this happens because the html markup is created in a huge string with inline styles and as soon as you do `element.innerHTML = out;`

`function addMarking ( spread, filterFunc, formatter ) {`
  ` ...`
  `element.innerHTML = out;`
  `return element;`
`}`

Then the CSP complains about inline style. 
(UPDATED) this only happens if I enable pips, the normal slide behavior is CSP compliant. 

Are you guys aware of this?

ps. Thanks for the great plugin!

**Comment by leongersen** [comment]
What exactly is you csp?

**Comment by x1c0** [comment]
> Content-Security-Policy HTTP response header helps you reduce XSS risks on modern browsers by declaring what dynamic resources are allowed to load via a HTTP Header

[https://content-security-policy.com/](url)

basically, when enabled for the right headers, it blocks inline styles from being used directly in HTML. If you want to prevent this you have to use HTML DOM style property like this:

instead of:
`const content = '<span  style="color: red">red text</span>';`
`htlmElement.innerHTML = content;`

you should do:
`const spanElem = document.createElement('span');`
`content.innerText = 'red text'`
`content.style.color = 'red';`
`htlmElement.append(spanElem);`

`htlmElement` -> the HTML element container where you want to render your element

**Comment by leongersen** [comment]
This only happens [here](https://github.com/leongersen/noUiSlider/blob/master/src/js/pips.js#L206). Shouldn't be too hard to fix.

**Comment by leongersen** [comment]
This is fixed in noUiSlider 10.0.0. Thanks for reporting!

**Comment by x1c0** [comment]
Great job! thank you ;)
