### ISSUE TITLE
"[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive."

### ISSUE THREAD

**Issue by tayvano** [leongersen/noUiSlider#785]
> [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.

I believe it's stemming from here: https://github.com/leongersen/noUiSlider/blob/dc6a43e67926e239732f00515c8c2e4f27b1062c/src/js/constants.js

**Explanation of message: http://stackoverflow.com/a/39187679/4358621**

> Passive event listeners are a new feature in the DOM spec that enable developers to opt-in to better scroll performance by eliminating the need for scrolling to block on touch and wheel event listeners. Developers can annotate touch and wheel listeners with {passive: true} to indicate that they will never invoke preventDefault. This feature shipped in Chrome 51, Firefox 49 and landed in WebKit.

Just started seeing it in Chrome Version 58.0.3029.96. It's not an urgent need nor an issue, but it is a pretty sweet feature - especially for mobile. 👍

**Comment by leongersen** [comment]
Yep, that'd be a nice fix. We'd need to detect support for objects as the third argument to `addEventListener`. This'd be a good first bug to make a pull request for, if you're interested.

**Comment by tayvano** [comment]
I'm tapped out for the moment after too much debugging / polishing, but may circle back around when I regain my sanity. :)

**Comment by leongersen** [comment]
This is fixed in noUiSlider 10.0.0. It's always nice to add performance features. Thanks for reporting!
