### ISSUE TITLE
how can use noUiSlider in Vue component?

### ISSUE THREAD

**Issue by xybin1990** [leongersen/noUiSlider#786]
i want use the slider in vue component, Is there any other repository?

**Comment by leongersen** [comment]
Have a look at [VueJS-noUiSlider](https://github.com/BradKriss/VueJS-noUiSlider).

**Comment by xybin1990** [comment]
@leongersen thanks!

**Comment by horans** [comment]
that one is out of date, and not compatible with vue 2.x
i've rewritten a new component: [vue-nouislider](https://github.com/horans/vue-nouislider)
