### ISSUE TITLE
javascript error after noUiSlider.updateOptions on start and connect

### ISSUE THREAD

**Issue by FalkenFalkesand** [leongersen/noUiSlider#787]
I'm trying to add handles on a slider by updating the options for that slider.

```
var sliderOptions = slider.noUiSlider.options;
var start = sliderOptions.start;
var connect = sliderOptions.connect;

start.splice(position,0,minutes);
start.splice(position+1,0,minutes+step+margin);
connect.splice(position,0,false);
connect.splice(position+1,0,true);

slider.noUiSlider.updateOptions({
  start: start,
  connect: connect
});
```

The handles are added to the slider correctly but in the console i get the error
```
nouislider.js:1791 Uncaught TypeError: Cannot read property 'style' of undefined
    at stateUpdate
```

It breaks under updateHandlePosition() when running stateUpdate().
```
// Called synchronously or on the next animationFrame
var stateUpdate = function() {
  scope_Handles[handleNumber].style[options.style] = toPct(to);
  updateConnect(handleNumber);
  updateConnect(handleNumber + 1);
};
```

**Comment by leongersen** [comment]
On first glance, I'd think this happens because you are 'messing' with the internal slider state. `slider.noUiSlider.options` is a *reference* to the options. Copying it into a variable (`var start = sliderOptions.start;`) still leaves you with a reference. Calling `splice` then *changes* the sliders internal variable.

**Comment by FalkenFalkesand** [comment]
What I should have done was to use noUiSlider.get() and noUiSlider.set(), but adding one more handle in the set method does not work either. So my workaround is to copy the options, get the handle positions and then destroy the slider and create it with the new handles I want to add with some updated options such as connect.

I guess the feature to request here is the ability to add more handles on the set() method.

**Comment by leongersen** [comment]
- [ ] `freeze` the `options` variable.

**Comment by leongersen** [comment]
That's requested in #789 (merging)
