### ISSUE TITLE
Change handles count without recreating

### ISSUE THREAD

**Issue by Deilan** [leongersen/noUiSlider#789]
Requesting a feature: capability to change handles count without recreating the slider.

**Comment by leongersen** [comment]
This is non-trivial, but you could give it a try.

**Comment by aqwsez** [comment]
+1

**Comment by hillct** [comment]
This is an important feature, critical to mu use case. My assumption is that I can perform this operation with careful updating of the SliderOptions object. The presence of this issue suggests that's not currently possible. Is that accurate?

**Comment by leongersen** [comment]
The flow code through the code assumes: create elements > attach events > wait for them to happen. Recreating isn't very expensive.

**Comment by leongersen** [comment]
Working on this is currently outside the scope of this project for me, so I'm closing this issue. I'm open to further discussion or a pull request, but those'll have to be in a new issue.
