### ISSUE TITLE
Add classes to handles

### ISSUE THREAD

**Issue by AlecRust** [leongersen/noUiSlider#79]
If you have a slider with two handles, there's no way to target them individually - they're both just a `<div>`.

Could you add `.slider-from` and `.slider-to` (or similar) classes to these handles to allow this?

**Comment by afroty** [comment]
@leongersen Have this issue been addressed?

**Comment by leongersen** [comment]
@afroty, it was, somewhere in 2013.

**Comment by afroty** [comment]
@leongersen Sorry for commenting on a very old issue. I noticed noUi-handle- (upper and lower) to max and min handles, but if you have more than two the ones in the middle seems to not have a specific class. Is there something I am missing as to how to style them individually.

**Comment by leongersen** [comment]
All handles have a `[data-handle]` attribute, so you can do something like `.noUi-handle[data-handle="4"]`.

**Comment by markgulisao** [comment]
HI is there anyway i could change the icon for the handle into a fa fa-calendar-plus-o icon for example?
or can i add fa fa-calendar-plus-o icon somewhere within the slider itself?
appreciate the help.

**Comment by leongersen** [comment]
@markgulisao Something like `document.querySelector('.noUi-handle[data-handle="4"]').classList += 'fa fa-calendar-plus-o';` should do.

**Comment by markgulisao** [comment]
is that for changing the handle icon or for adding an icon within the slider. im sorry im not that proficient with coding yet. i plan to put the icons as stop point for the handle and an event happens once the handle reach the icon.
