### ISSUE TITLE
Additional tooltips

### ISSUE THREAD

**Issue by Deilan** [leongersen/noUiSlider#791]
It is suggested to make an option to display additional tooltip. As a default it could display a difference between the current value and the previous value like that:

![image](https://cloud.githubusercontent.com/assets/4777512/26818846/00d09be2-4aa5-11e7-9946-e87d069ff35d.png)

**Comment by leongersen** [comment]
You can add additional tooltips to the handles yourself, then update them using the `update` event.

**Comment by Deilan** [comment]
@leongersen Thanks for pointing a direction! How can I do that? Or at least where do I start from?

**Comment by leongersen** [comment]
Select all `.noUi-handle` with e.g. `querySelectorAll`, `appendChild` a new handle element, then add an `update` event that changes its value, like so: `function ( values, handle ) { listOfHandles[handle].innerText = values[handle]; }`.

**Comment by Deilan** [comment]
@leongersen Thanks for the support! I achieved the desired result.
