### ISSUE TITLE
Bad behavior using ng-repeat and filters

### ISSUE THREAD

**Issue by Zeychiel** [leongersen/noUiSlider#792]
Hi,

Here is a copy of the issue i opened on the Yankovsky/nouislider-angular repo, as I use his angular wrapper ; but in my opinion the behavior would be the same without the wrapper and here would be the the best place to find an answer.

> I have troubles using the directive within a ng-repeat and using filters.
> Here is the plunkr 👍 
> http://plnkr.co/edit/t7avPB?p
> 
> I have 5 items containing the slider options (this is mandatory as options and values can be different from one item to another), the related values and events (this is not mandatory, but by design).
> The 5 items also contain a page number (1 or 2).
> 
> The items are displayed using ng-repeat, filtered by page number (by default, all of the are displayed, but when a page number is set within the input, filtering happens).
> By default, all items are displayed and moving the slider effectively changes the values of the related item (checkable in the 'data' section).
> When the filter is set to 1 page, only 3 items are displayed and moving the slider effectively changes the value of the related item.
> Then, changing the filter to 2, only 2 items are displayed and moving the slider does NOT affect the right item.
> 
> 
> It seems to me that the slider event triggered is based on the scope containing the slider, not the slider itself. Am I doing anything wrong ?! Any way to solve this ? Thanks a lot,

Thanks for your help,

**Comment by Zeychiel** [comment]
Hi,
I'm still struglging on this, does anyone has a hint on why this behavior occurs ?

**Comment by Zeychiel** [comment]
Hi,
Any one here ? @leongersen

**Comment by leongersen** [comment]
I'm not familiar with angular JS, and I'm currently abroad without a laptop or a proper internet connection. I'm afraid there's little I can do for you here.

**Comment by Zeychiel** [comment]
Ok, thanks for answering anyway.
I just solved it by removing the
`track by $index`
from the ng-repeat.

If someone gets by and can explain me why it worked, that would be awesome !
