### ISSUE TITLE
Find bug

### ISSUE THREAD

**Issue by gonardfreeman** [leongersen/noUiSlider#796]
Find only on stepslider.
Steps to repro:
1. setup sliders in range more than 2. ex 1,2,3,4,5,6,7,8 you need to setup in 1 and 4. then put them together on one place(ex. 2) and remember which slider was last. if follow your slider logic, you need to be able to move in direction opposite of last slider moves, but you cant.

**Comment by gonardfreeman** [comment]
After little code review Im found where problem is: 
`function setZindex ( ) {

		scope_HandleNumbers.forEach(function(handleNumber){
			// Handles before the slider middle are stacked later = higher,
			// Handles after the middle later is lower
			// [[7] [8] .......... | .......... [5] [4]
			var dir = (scope_Locations[handleNumber] > 50 ? -1 : 1);
			var zIndex = 3 + (scope_Handles.length + (dir * handleNumber));
			scope_Handles[handleNumber].childNodes[0].style.zIndex = zIndex;
		});
	}`
Problem is in calculating zIndex, for 2 elements we have an array of indices [0,1], and when we set el with index 2(2nd el with value of 1) and if we move 2nd handle to less than 50% of scope we can calc zIndex: zindex = 3 + (2 {length of array of handles} + (1 {because our handle is in 1st half of scope} * 1 {value in array of handles[0,1<--this value]}=6 and if we calc same for 1st handle we got zIndex = 5. 
To solve this I'll plan to rework formula that will consider which handle will moves to "collapse" last. And add to formula of zIndex some digit(ex +3)

**Comment by leongersen** [comment]
There is a lot going on in this issue, and I don't entirely understand the question. Could you provide a running example?

**Comment by leongersen** [comment]
Closing this for lack of input. Feel free to comment, I'll re-open.
