### ISSUE TITLE
Slider unresponsive on update (using set method)

### ISSUE THREAD

**Issue by tbyte80** [leongersen/noUiSlider#798]
I use a time based slider which gets constantly updated every 1-2 seconds from outside via "set" method. When the slider is dragged by the user I use events to temporary suspend updates on "start" event and reactivate updates on "end" event.

This is all working fine except when I try to move the slider handle while the slider is updated via "set". In that case the handle would move only a very limited range or not at all. I tried to disable the slider on "start" event and enable it back on "end" but behaviour is the same.

Is there any way of controlling this better?

**Comment by leongersen** [comment]
Try setting `animate: false` and remove transition from the stylesheet.

**Comment by tbyte80** [comment]
thanks, that helped!
