### ISSUE TITLE
Chrome handeling

### ISSUE THREAD

**Issue by MattiasWiberg** [leongersen/noUiSlider#800]
Everything don't work on chrome. I looks like the issue is that you get locked (focused) to a slide after using it and it stays active all the time after that. You try pulling in the sliders on the example page in google chrome you'll see for yourself what happens.

**Comment by eran-correlor** [comment]
Hi Mattias,I noticed the same issue and spent hours trying to resolve it, just try to pull ver 9.2.0 it looks like it behaves the way it should

**Comment by leongersen** [comment]
Merging with #805.
