### ISSUE TITLE
Error when using babel-polyfill and webpack2

### ISSUE THREAD

**Issue by perf2k2** [leongersen/noUiSlider#801]
Without polyfill in this [line](https://github.com/leongersen/noUiSlider/blob/master/src/js/range.js#L121) will be returned a right value `[object Array]`, but with babel-polyfill was returned `[object Array Iterator]`. Right now I am using temporary solution with `Object.prototype.toString = () => '[object Array]';` before initialize noUiSlider. 

It's a bug?
Sorry for English.

**Comment by leongersen** [comment]
I think we could be using `Array.isArray` anyway. I'll look into it.

**Comment by leongersen** [comment]
Fixed in noUiSlider 11. Thanks for reporting!
