### ISSUE TITLE
Accessibility: aria-valuetext is read twice on Safari / Voiceover.

### ISSUE THREAD

**Issue by akhramov** [leongersen/noUiSlider#802]
First of all, I would like to thank you for your incredible library. 

Unfortunately, there's an accessibility bug in Safari / Voiceover pair, described here: https://bugs.webkit.org/show_bug.cgi?id=174309.

So here's the info in regards to your library:
##### Steps to reproduce
1. Open https://jsfiddle.net/g6s3nrpL/1/ in Safari.
2. Turn on VoiceOver, navigate to slider
3. Press left or right to move the slider's handle

##### Expected result
aria-valuetext announced once.

##### Actual result
aria-valuetext announced twice.

##### Proposed solution
As a dirty workaround, we might use aria-live="assertive" on newly added accessible-hidden label instead of aria-valuetext. Or, should we wait for the next Safari / Voiceover release?

Thanks!

**Comment by leongersen** [comment]
Sorry for not responding sooner. This sounds like a mean bug. I think the aria attributes are implemented as per the spec for range sliders, so I'm hoping Safari will fix this. I'll give this a more detailed look.

**Comment by akhramov** [comment]
Hi, as of Safari Version 11.0.2 (13604.4.7.1.3), I can't reproduce the issue anymore.
Also I have upgraded OS to High Sierra, so VoiceOver might be updated as well.

Just FYI: my suggestion wasn't quite good, because it would certainly cause problems on other Screenreader / Browser pairs.

That being said, everything works just fine. I will try to find an older Safari, just to reproduce the issue.

**Comment by leongersen** [comment]
I'm glad the issue seems resolved by a fix on the vendor's end. If this remains an issue on other browser/OS combinations, feel free to comment. I'll re-open and we can investigate.
