### ISSUE TITLE
Slider renders only when noUiSlider.create() is called from within jQuery's ready() function

### ISSUE THREAD

**Issue by amadeann** [leongersen/noUiSlider#803]
I am struggling to understand this behavior. 

When I do this:

```
jQuery(document).ready(function ($) {
    ...
   var slider = document.getElementById('slider-id');
   noUiSlider.create(slider, {...
}
```

However, when I try:

```
var slider = document.getElementById('slider-id');

jQuery(document).ready(function ($) {
    ...
   noUiSlider.create(slider, {...
}
```

no slider is displayed. What's interesting, slider seems to be initialized on the element with id 'slider-id'. When I paste the create code in the console (Chrome Dev Tools) I get:

Uncaught Error: noUiSlider (10.0.0): Slider was already initialized.

But again, no slider is displayed. I see the same behavior in both Chrome and Firefox.

Everything boils down to moving `var slider = document.getElementById('slider-id');` in or out of the ready() function. Does anyone have any idea what may be causing this behavior?

**Comment by leongersen** [comment]
Are you running your code before the DOM is complete? The "#slider-id"
element may not exist yet.

**Comment by amadeann** [comment]
I don't think so. My js code is after all HTML/PHP in a single file. This may not be the issue with your library - maybe it's some quirk of jQuery variable scoping, which I don't understand. For some reason, it works only if I have both the element (#slider-id) assignment and noUiSlider.create() either within ready() or outside of it.

**Comment by VictorPietro** [comment]
Just want to thank you @amadeann , I was having this issue:

> nouislider.min.js:3 Uncaught Error: noUiSlider (10.0.0): create requires a single element, got: null


and your 

`jquery(document).ready(function($){} 
`
helped me soooo much, really thank you.
