### ISSUE TITLE
don't work option 'format'

### ISSUE THREAD

**Issue by SemenovN** [leongersen/noUiSlider#804]
error message:
wNumb is not defined

**Comment by mjpramos** [comment]
Hi, 
Check the Number formating section [here](https://refreshless.com/nouislider/slider-read-write/#section-formatting)
You need to download and include an aditional library: [wNumb](https://refreshless.com/wnumb/)

**Comment by training4all** [comment]
How to include wNumb in slider, when I used
format: wNumb({
                        decimals: 2
                    })
it says wNumb name not resolved

**Comment by leongersen** [comment]
It is a separate library you'll need to include.
