### ISSUE TITLE
How can i save slider value to localstorage and load them after page reload?

### ISSUE THREAD

**Issue by Wulfgorim** [leongersen/noUiSlider#806]
As the title says I don't really know how to save the localstorage and display it later I mean it saves the value in localstorage but when I am trying to load it after page reload it doesn't move the slider at all. Can anyone help me with that? This is what i am up with so far: https://codepen.io/Hatchling/pen/EXqeRN/

**Comment by AlexSwensen** [comment]
There are a number of solutions to do that, but none are part of this library. I would look into stackoverflow.

**Comment by leongersen** [comment]
Doing some housekeeping - closing this answered question.
