### ISSUE TITLE
Pip values for rtl direction (right to left) are not centered

### ISSUE THREAD

**Issue by Ceremony64** [leongersen/noUiSlider#807]
When setting the direction to rtl, the pip-values are no longer centered like in the usual left to right direction:
![capture](https://user-images.githubusercontent.com/5873369/28531781-1b11ab7c-7098-11e7-9ed2-953057a462a5.PNG)

See [this example](https://jsfiddle.net/nfw7f9zq/) or also currently in [the documentation](https://refreshless.com/nouislider/pips/#section-range)

**Comment by leongersen** [comment]
Something got botched in the CSS for the pips. I'll get it fixed in the next update.

**Comment by leongersen** [comment]
Addressed in #795
