### ISSUE TITLE
 Frequency of invoke addEventListener(...)

### ISSUE THREAD

**Issue by devtritus** [leongersen/noUiSlider#808]
I read code of this slider and saw function attachEvent() what contain invoke a addEventListener(...) ~1415 row of nouislider.js, this code is invoked all time. Is it normal what method adds listeners to element every time when mouse events emit? Sorry for my english.

**Comment by QuentinRoy** [comment]
This is indeed intended. For example, `mousemove` events are only meaningful for the slider between a `mousedown` on the slider and `mouseup`. The rest of the time, the event is not being subscribed to.
