### ISSUE TITLE
Multiple sliders updating simultaneously on mobile devices 

### ISSUE THREAD

**Issue by PieterJanVdb** [leongersen/noUiSlider#809]
I'm currently using the [ember-cli-nouislider](https://github.com/kennethkalmer/ember-cli-nouislider) plugin (which uses nouislider 9.2.0) to render three sliders on the page in this fashion:

`{{range-slider score=score start=value range=range step=step on-change="change" on-update="update"}}`

Using a mouse I can slide them all independently and it works perfectly fine.
However, on eg. a tablet, if I move the slider on one of the three and then proceed to move the slider on another, both sliders will move at the same time. If I then move the third slider, all three sliders will synchronise and move at the same time. I can even kind of slide my finger somewhere else on the page (not on any of the three sliders) and all three sliders will update.

Here's a video demonstrating the issue: https://streamable.com/bm2qt

The issue is fixed by removing the on-update action handler (handles the 'update' events), but then the values next to the slider are not updated.

I've done some digging and it seems as if the 'touchend' event (browser) is not being fired 90% of the time when lifting my finger of the screen (happens on both iOS and Android devices). As a result the 'change' and 'end' events of nouislider are not being fired either and I suppose this is where the problem lies?

Any help would be greatly appreciated!

**Comment by tempSt69** [comment]
So ? What did you do ? Please.
