### ISSUE TITLE
Better visibility on tooltips

### ISSUE THREAD

**Issue by SvetoslavStefanov** [leongersen/noUiSlider#810]
Hello,
I'm having a problem with tooltips. I have a slider of type 'range' and I have 2 tooltips displayed.
But when they are closer to each other the second one ( i.e. .noUi-handle-upper ) stands over the first one ( i.e.  .noUi-handle-lower ). 
Can you provide a fix by setting higher z-index on the last clicked element ?
My current fix is 
`#slider .noUi-handle:hover {
    z-index: 7 !important;
}`
 but I didn't like it, because it's not gonna work very well on mobile devices.
I think the best solution is to put z-index on the last clicked element, this way if the user wants to see the lower handle, it needs just to click on it.

**Comment by leongersen** [comment]
Handles are ordered (by z-index) so that they're all movable. I'm not sure if adding extended tooltip features to noUiSlider is the right move.

**Comment by leongersen** [comment]
As I see it, adding a more advanced tooltip-system is outside of the scope for noUiSlider, so I'm closing this issue.
