### ISSUE TITLE
Bug in Android 5.1 (Chrome)

### ISSUE THREAD

**Issue by Bonauze** [leongersen/noUiSlider#814]
Hello!
Found a bug in Android 5.1 (Chrome)
https://drive.google.com/open?id=0B73UnqAehtXbZDdKQmhaUEx2Slk

**Comment by leongersen** [comment]
I think you're likely triggering a tap that's moving the handle. It's hard to tell from the video, and I definitely agree it looks broken. What device is this?

**Comment by leongersen** [comment]
Actually, I think I'm looking at the same error described in #834 (merging)
