### ISSUE TITLE
Ability to drag both sliders left-right when on common value  

### ISSUE THREAD

**Issue by knalen** [leongersen/noUiSlider#815]
Currently, the slider that is in focus can be moved first if you bring both sliders to a value.

I would suggest to make it so that IF the users drags the slider to the right, switch focus from the left slider to the right and be able to move it, and vice-versa. Is this possible?
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/15885234/29455041-8084b562-8407-11e7-914d-bfcabf506066.gif)

**Comment by leongersen** [comment]
This is now a feature in noUiSlider 12.1.0. Thanks for contributing!

[Documentation on the `"unconstrained"` option](https://refreshless.com/nouislider/behaviour-option/#section-unconstrained).
