### ISSUE TITLE
noUiSlider.set

### ISSUE THREAD

**Issue by huyinxuan** [leongersen/noUiSlider#816]
I have a requirement
I want to dblclick on dom, then add a coordinate,
The initial value is [0,10,20]。 after dblclick i use set funciton , slider.noUiSlider.set([0, 5, 10, 35, 40, 60, 100, 80]); but   firefox error " scope_Handles[handleNumber] is undefined " ,  How do I implement this requirement  what API ？

**Comment by leongersen** [comment]
This has been open for a while, and I really don't understand the question, nor does it come with any code. Feel free to add info and I'll re-open.
