### ISSUE TITLE
Hide overflow with 100% width?

### ISSUE THREAD

**Issue by Zerebokep** [leongersen/noUiSlider#818]
More a question than an issue. My slider uses 100% width of the page. As soon as dragging the handle to the very right side a horizontal scrollbar is shown. Is there any way to disable this behavior? I've tried adding overflow: hidden, but it doesn't seem to have any effect.

**Comment by leongersen** [comment]
You can change this by adding padding to the slider element.

**Comment by Zerebokep** [comment]
Is there another way? I don't want to make the handle bigger.

**Comment by leongersen** [comment]
Merging with #842.
