### ISSUE TITLE
Use noUiSlider as video seekbar

### ISSUE THREAD

**Issue by apurvgandhwani** [leongersen/noUiSlider#819]
I am trying to use noUiSlider as seekbar for a video. I have a video player from which I can get current time of video every few fraction of seconds. Now I want to give this time to noUiSlider and see it behaving as seekbar. I know about "set()" method of noUiSlider. What would be the best way to see the seamless working noUiSlider seekbar?

**Comment by denism7** [comment]
Setup your range in milliseconds. Use it to set current position. Use custom formatting function to show it as hh:mm:ss inside of labels or pips.

**Comment by leongersen** [comment]
Doing some housekeeping - closing this answered question.
