### ISSUE TITLE
Number formatting with SkipSlider

### ISSUE THREAD

**Issue by thecosmic** [leongersen/noUiSlider#827]
Hi I want to add currency, decimal, thousand seperator for inputs. But when i try to add this code to my script noUiSlider crashes. 

`	format: wNumb({
		decimals: 3,
		thousand: '.',
		postfix: ' (US $)',
	})`

These are my codes: How can i achieve it?

`
var skipSlider = document.getElementById('dovizkuruslidertl');

noUiSlider.create(skipSlider, {
    connect: true, // Display a colored bar between the handles
    range: {
        'min': 10000,
        '1%': 100000,
        '2%': 200000,
        '3%': 300000,
        '4%': 400000,
        '5%': 500000,
        '10%': 1000000,
        '20%': 2000000,
        '30%': 3000000,
        '40%': 4000000,
        '50%': 5000000,
        '60%': 6000000,
        '70%': 7000000,
        '80%': 8000000,
        '90%': 9000000,
        'max': 10000000
    },

    snap: true,
    start: [100000, 4000000]

});

	var minButcetlInput = document.getElementById('minButcetl'),
		maxButcetlInput = document.getElementById('maxButcetl');

	// When the slider value changes, update the input and span
	skipSlider.noUiSlider.on('update', function( values, handle ) {
		if ( handle ) {
			maxButcetlInput.value = values[handle];
		} else {
			minButcetlInput.value = values[handle];
		}
	});

	minButcetlInput.addEventListener('change', function(){
		skipSlider.noUiSlider.set([null, this.value]);
	});

	maxButcetlInput.addEventListener('change', function(){
		skipSlider.noUiSlider.set([null, this.value]);
	});

`

**Comment by leongersen** [comment]
I can't really do anything with "it crashes". I'm assuming you may have forgotten to include `wNumb`, which is a separate project.
