### ISSUE TITLE
Allow handles to move past each other by setting "margin: null"

### ISSUE THREAD

**Issue by nicknack23** [leongersen/noUiSlider#828]
I need to be able to move handles past each other. I figured out an easy hack to make this work, just set `margin` to some large negative number. However, this could cause subtle bugs if the code base assumes that handles are always sorted. What do you think, is it safe to use this hack for now?

Anyway, as a feature request, I propose that setting `margin: null` would allow all sliders to move freely.

Also, the documentation says that there is no default value for `margin`, but since my hack works it seems the default is effectively zero.

**Comment by leongersen** [comment]
This is requested in #747 (merging)
