### ISSUE TITLE
Serious bug in Edge. Please investigate.

### ISSUE THREAD

**Issue by ullasmohan** [leongersen/noUiSlider#830]
Hi Guys,
Am facing a serious bug in Edge (tested in https://refreshless.com/nouislider/examples/ also). I used Windows 10 Dell Hybrid laptop and after **touch moving** the slider for sometimes(10-15 times) continuously then the slider behavior is changing. After that when we touch anywhere in the body, then the slider will move accordingly. I cant find the actual issue behind this. Please investigate.

**Comment by leongersen** [comment]
I think this isn't unique to Edge. This seems to be an error with the slider ignoring end events. Merging with #834
