### ISSUE TITLE
[pips] Unexpected 'range' behavior

### ISSUE THREAD

**Issue by xavierpena** [leongersen/noUiSlider#832]
[This image](https://i.imgur.com/RRtpQr2.png) shows the unexpected behavior.

This is the `range` object value:

	range:
	[
		12: 12
		24: 24
		36: 36
		48: 48
		60: 60
		72: 72
		max: 80
		min: 0
	]

And this is how it's created:

	var range = {};

	// `range` must contain 'min' and 'max':
	range['min'] = minIndex;
	range['max'] = maxIndex;

	// One intermediate pip every 12 hours:
	for(var index=minIndex+1; index<maxIndex-1; index++) {
		if(index % 12 === 0)
			range[index] = index;
	}

	indexSliderElement = document.getElementById(sliderDivId);        

	noUiSlider.create(indexSliderElement, {
		start: count,
		connect: [true, false],
		orientation: "horizontal",
		range: range,
		pips: {
			mode: 'steps',
			density: 1,
			format: {to: updatePips}
		},
		format: wNumb({
			decimals: 0
		})            
	});
	
    function updatePips( value, type ){
        return ('+' + value + 'h');
    }

**Comment by leongersen** [comment]
It took me a second too, but the slider and pips are doing exactly what you want it to do. In your generated range, you set the value at 72% of the slider width to 72 (`72: 72`). That leaves 100 - 72 = 28% of the slider width between 72 and 80. This is reflected in the slider and the pips.
