### ISSUE TITLE
Slider ignoring end events (Strange behaviour with trackjs)

### ISSUE THREAD

**Issue by georgest** [leongersen/noUiSlider#834]
The issue is that when I load TrackJs library to my React project, noUiSlider starts to behave differently. When I have two sliders on the page when I move the first, then the second, they start to move at the same time. A video is uploaded here: [https://we.tl/ksky7V5pFP](https://we.tl/ksky7V5pFP)
My code is:

```javascript
render() {
  return (
    <div style={{padding: 100}}>
      <div
        style={{ marginBottom: 20 }}
        ref={(item) => { this.slider1 = item; }}
      />
      <div
         style={{marginBottom: 20}}
         ref={(item) => { this.slider2 = item; }}
      />
    </div>
  );
}
```
And when component did mount
```javascript
componentDidMount() {
  noUiSlider.create(this.slider1, {
    start: 10,
    connect: [true, false],
    range: {
      min: 0,
      max: 100,
    },
    step: 10,
  });

  noUiSlider.create(this.slider2, {
    start: 75,
    connect: [true, false],
    range: {
      min: 0,
      max: 100,
    },
    step: 10,
  });
}
```

**Comment by ullasmohan** [comment]
Am also facing a strange behavior : https://github.com/leongersen/noUiSlider/issues/830
(Am facing a serious bug in Edge (tested in https://refreshless.com/nouislider/examples/ also). I used Windows 10 Dell Hybrid laptop and after touch moving the slider for sometimes(10-15 times) continuously then the slider behavior is changing. After that when we touch anywhere in the body, then the slider will move accordingly. I cant find the actual issue behind this.)

**Comment by ullasmohan** [comment]
@leongersen : Any updates? Eagerly waiting for a solution.

**Comment by leongersen** [comment]
I'm currently on a long term hiking trip in Guatemala with nothing but a phone, so I can't do a lot to look in to this. Could you try downgrading to noUiSlider 9.x?

**Comment by MathieuDR** [comment]
Hey, Is this the same issue as this? @ullasmohan 

![2017-09-28_15-48-37](https://user-images.githubusercontent.com/1561671/30970303-14e5ee24-a465-11e7-94b8-89fef9b9ac9f.gif)

I think it sounds the same and I've updated my version and posted to solution on another issue. I didn't think it was a general issue.

**Comment by leongersen** [comment]
@MathieuDR I think we could make this a little more robust by never rejecting any end event for the "tap is active" reason. Similarly, I think this issue could occur if the slider was disabled (for whatever reason) on the start event.

**Comment by leongersen** [comment]
We could add a `doNotReject` property to the `data` argument for `attachEvent`. `endEvent` and `outEvent` could activate this parameter.

**Comment by leongersen** [comment]
On a code re-read, there's another unjust reject: when there's multiple touches on the screen and the slider isn't in `multitouch` mode, the [touch may be rejected](https://github.com/leongersen/noUiSlider/blob/856f5ad531f01aa17584f9aeeb6e05adec4884fd/distribute/nouislider.js#L1482). That needs to be fixed as well. 

That too can be done with a `doNotReject` property. I'd just have to come up with a way to assign an end event to an individual slider when the `multitouch` option is active. @QuentinRoy, could you provide an insight there?

Some context: When the slider ignores a touch event as the result of `fixEvent` returning `false`, it misses an end event (such as `touchend`). This causes a handle to be stuck to any `touchmove`, with no way of unsticking the handle. To fix this, we'd need to make sure every end event is handled. For non-`multitouch` sliders, we could do this by changing [this line](https://github.com/leongersen/noUiSlider/blob/856f5ad531f01aa17584f9aeeb6e05adec4884fd/distribute/nouislider.js#L1391) to ` if ( !e && !data.doNotReject )`. However, in the case of `multitouch`, that would make every slider handle the `touchend` and every slider would stop dragging.

**Comment by leongersen** [comment]
I've just released noUiSlider 11 that fixes issues with ignored end events. Thanks for reporting!
