### ISSUE TITLE
Is there a way to turn on and off tooltips or change noUiSlider options after slider created?

### ISSUE THREAD

**Issue by rammohan201** [leongersen/noUiSlider#836]
is it possible to turn on and off tooltips? kind of dynamically updating slider options?
I do not want to show tooltip when slider values are not changed. want to show only when slider value is modified.

**Comment by leongersen** [comment]
Hide the tooltips in CSS. On the start event, add a class that shows them.
Remove the class on the end event.

**Comment by Josh979** [comment]
Ah, I was looking for this kind of functionality as well. Thank you for the workaround.

**Comment by leongersen** [comment]
Doing some housekeeping - closing this answered question.

**Comment by leongersen** [comment]
On second thought, this’d be a good example for the documentation.

**Comment by leongersen** [comment]
There's a [new example in the documentation](https://refreshless.com/nouislider/examples/#section-hiding-tooltips) that shows how to do this. Thanks for participating!

**Comment by ramparvataneni** [comment]
Can we make the tooltips active on hover, not only when we move the handle

**Comment by chandrantwins** [comment]
Hi Ramparvataneni are you able to achieve that behaviour.. i mean tooltips active on hover

**Comment by leongersen** [comment]
@ramparvataneni @chandrantwins 

You can use:

```
.noUi-tooltip {
    display: none;
}
.noUi-handle:hover .noUi-tooltip {
    display: block;
}
```

**Comment by chandrantwins** [comment]
thanks  for your quick reply @leongersen , but unfortunatly its not working

**Comment by chandrantwins** [comment]
I dont see inside handle this tooltip.. may be that is the issu
![image](https://user-images.githubusercontent.com/5931321/166891903-892a2248-4702-4f94-b97f-e647ace6f8d7.png)

**Comment by chandrantwins** [comment]
@leongersen do you have any idea why in my case tooltip is outside handle
![image](https://user-images.githubusercontent.com/5931321/166894113-dfa3b349-9348-4bbc-9c7b-9bdb8fef42db.png)

**Comment by leongersen** [comment]
What noUiSlider version are you using?

**Comment by chandrantwins** [comment]
this is the one i am using noUiSlider-15.6.0

**Comment by chandrantwins** [comment]
I am able to achieve it with this style

.noUi-tooltip{
 display:none
}

.noUi-active + .noUi-tooltip {
  display: block;
}

**Comment by chandrantwins** [comment]
@leongersen i found the issue 
when i use this merge script https://refreshless.com/nouislider/examples/#section-merging-tooltips
then i am getting that issue, tooltip is placed below, if i remove that script now your css is working
