### ISSUE TITLE
Default To value set wrong when max value set in floating point.

### ISSUE THREAD

**Issue by pranaysonisoft** [leongersen/noUiSlider#838]
i set a default start to value is 2000 but noUiSlider set 1980 .
i don't understand why default  value set wrong.

```

noUiSlider.create(marginSlider, {
  start:[30,2000],
  step:50,
  connect: false,
  range:{
    'min':30,
    'max':2000.1
  }
});
```

Problem Example 
https://jsfiddle.net/0rohoeLg/319/

**Comment by Januszpl** [comment]
I think it's because you set min as 30 and step 50.
30+(39*50) = 1980

**Comment by pranaysonisoft** [comment]
i don't understand what you say.
what is 39? 
and why max value is 1980.

**Comment by Januszpl** [comment]
Max value is 2000.1. You can move the handler to the right and you will get it ;)
You defined step: 50 and min and start as 30.
So when moving left handler you can set values as 30, 80... etc... and then (39th step) will be 1980 ;)

**Comment by pranaysonisoft** [comment]
My requirement is set default From value = 30  &  To value = 2000 .
How to set this from to value in noUiSlider ?

**Comment by leongersen** [comment]
@Januszpl has the right answer (thanks!). 2000 - 30 is just not cleanly divisible by 50.
