### ISSUE TITLE
Direction and UpdateOptions

### ISSUE THREAD

**Issue by aleincsharp** [leongersen/noUiSlider#839]
Hello,

i've created a Slider with ltr direction and now want to cange to rtl. It seems not do working with the updateOptions function.
Here my code:
` var config = {                         
                            direction: "rtl"
                        };

                        uiSlider[0].noUiSlider.updateOptions(config);`

Thanks.

**Comment by leongersen** [comment]
`direction` is not an updatable (as it would require a DOM change). You'll need to destroy and rebuild the slider. 

*todo*: throw error when trying to update an unsupported option.
