### ISSUE TITLE
Clicks on right edge of slider bar ignored when handles contained

### ISSUE THREAD

**Issue by pranksinatra** [leongersen/noUiSlider#842]
First of all, thanks for this super nifty and well-tested library!

In the documentation, on the [More page](https://refreshless.com/nouislider/more/), there's some sample CSS for containing the handles within the bounds of the slider bar. Here's a Pen of the result:
https://codepen.io/pranksinatra/pen/xPeWBp

As you'll notice, this technique reduces the size of noUi-base, so that the right edge of the bar cannot be clicked. 

I found a workaround using :before and :after pseudoelements on .noUi-base, which span the full width of the bar. However, when the right side is clicked, nothing happens, *even though noUiSlider handles the click event*. This is b/c `calcPointToPercentage()` and `getClosestHandle()` ignore clicked coordinates greater than 100% (beyond the width of .noUi-base). I was able to get things working by tweaking both functions in scope_helpers.js

```js
// Translate a coordinate in the document to a percentage on the slider
function calcPointToPercentage ( calcPoint ) {
    var location = calcPoint - offset(scope_Base, options.ort);
    var proposal = ( location * 100 ) / baseSize();

    // *** Give proposal upper bound ***
    if ( proposal > 100 ) proposal = 100;

    return options.dir ? 100 - proposal : proposal;
}

// Find handle closest to a certain percentage on the slider
function getClosestHandle ( proposal ) {

    var closest = 100;
    var handleNumber = false;

    scope_Handles.forEach(function(handle, index){

        // Disabled handles are ignored
        if ( handle.hasAttribute('disabled') ) {
            return;
        }

        var pos = Math.abs(scope_Locations[index] - proposal);

        // *** Accept upper-bounded pos ***
        if ( pos <= closest ) {
            handleNumber = index;
            closest = pos;
        }
    });

    return handleNumber;
}
```

I don't know what other side effects these tweaks could have, but would be happy to submit a PR if they're compatible.

**Comment by leongersen** [comment]
Sorry for not responding earlier. I'm expecting to be back to a setting I can do development in in mid-January, and I'll review your changes. My initial thought is that there'd not be any side effects to this, but I'll add some unit tests to the `tap` feature to confirm.

**Comment by leongersen** [comment]
I've updated the [documentation on styling](https://refreshless.com/nouislider/more/#section-styling). It had fallen out of date. There's a new example that shows how to 'pad' a slider while accepting click events. Thanks for reporting this!

**Comment by pranksinatra** [comment]
Thanks @leongersen. The updated CSS does work, but doesn't allow pseudoelements to be used to handle clicks above or below a skinny slider bar, by forcing them to be part of the padded slider.

I've updated the Pen with an example:
https://codepen.io/pranksinatra/pen/xPeWBp

Though this is probably not the most common styling choice (a skinny slider bar), it'd be great if it was possible w/out breaking accessibility. If you have other ideas for how to achieve these two features (skinny bar, contained handles), I'm all ears.

Thanks again!

**Comment by pranksinatra** [comment]
I was able to use :before and :after to add both features (contained handles -and- a larger click area on a skinny bar).
https://codepen.io/pranksinatra/pen/opPvRe

However, then we're back to square one: when the slider is all the way to the right or left, the opposite edge can't be clicked. I'm pretty sure this is due to the JS conditions I outlined in my first comment.

**Comment by leongersen** [comment]
I think there might be a way of working around it yet again (by setting a fixed height on `.noUi-base`?), but you're right and correcting the behaviour is a neater solution. I'd happily accept a pull request. Regarding unit testing, "slider_three_or_more_handles.js" should have all you need as an example.

**Comment by pranksinatra** [comment]
Great, I'll do some testing and submit a PR.

*A side note:*
As I was putting together these Pens and updating my app, I realized that using pseudoelements to implement the contained handles feature, while functional, introduces a good deal of CSS complexity. A couple examples:
- Adding a `border-radius` to the slider bar requires styling both pseudoelements, instead of just `.noUi-target`, or having `:before` span the full width of the bar.
- Similarly, using a `linear-gradient` background requires dividing it up into 3 parts -or- hiding `.noUi-connect` and having `:before` span the full width of the bar.

All this to say, perhaps a JS option would make more sense than a CSS one?

**Comment by pranksinatra** [comment]
By the way, the new test passed fine in the browser, but I was having some trouble w/ `npm test` (PhantomJS timeouts). Let me know if you notice anything that could be improved--I'm new to TDD.

Thanks again. Glad to see this moving forward!
