### ISSUE TITLE
not working with webpack

### ISSUE THREAD

**Issue by umarrg97** [leongersen/noUiSlider#843]
here is my code for the nouislider.

let noUiSlider = require('nouislider');
const search = document.querySelector('.search-wrapper');

if (search) {
    const field = document.getElementById('age');
    noUiSlider.create(field, {
        start: 40,
        connect: 'lower',
        range: {
            min: 0,
            max: 100
        }
    });
}

doesnt seem to be working.

**Comment by alex88** [comment]
@umarrg97 what you mean with "doesn't seems to be working"? Console errors? Is the html there but no css? Try to import nouislider css: `require('nouislider/distribute/nouislider.css';)`

**Comment by anselanza** [comment]
I really think the docs should just include a note that the CSS needs to be imported.

`import 'nouislider/distribute/nouislider.css';`
or 
`require('nouislider/distribute/nouislider.css')`

would be fine?

**Comment by leongersen** [comment]
@anselanza Yep, good point. Tracked in #843.

**Comment by MATEY15** [comment]
Webpack
@import '~nouislider/distribute/nouislider.css';
