### ISSUE TITLE
Vertical pips on left hand side

### ISSUE THREAD

**Issue by nickcotter** [leongersen/noUiSlider#844]
How would one put the pips on the left hand side of a vertical slider. Is there some particular css I should override?

**Comment by leongersen** [comment]
Assuming you mean horizontal as you're asking for left hand? For `.noUi-pips-horizontal`, remove `left: 0` and change it to `right: 100%`.

**Comment by nickcotter** [comment]
Actually I meant a vertical slider, which by default has the pips running down the right hand side. But thank you - .noUi-pips-vertical put me on the right track!

**Comment by leongersen** [comment]
Alright, glad it worked out!
