### ISSUE TITLE
use several colors for replacing connect green

### ISSUE THREAD

**Issue by pnizet** [leongersen/noUiSlider#845]
Is there a way to change the green color of the connect connection between two handles.
Typically I would like to do : 

- connect between first and second : green
- connect between second and third : yellow
- connect between third and fourth : red

thanks

**Comment by leongersen** [comment]
Sure! There is an example in the documentation:

https://refreshless.com/nouislider/examples/#section-colored-connect

**Comment by pnizet** [comment]
Many thanks,
I haven't saw this help...

Pierre
0625185648


-------- Message original --------
Objet : Re: [leongersen/noUiSlider] use several colors for replacing connect green (#845)
De : Leon Gersen <notifications@github.com>
À : leongersen/noUiSlider <noUiSlider@noreply.github.com>
Cc : niz <pierre@pierre-nizet.fr>,Author <author@noreply.github.com>

>Sure! There is an example in the documentation:
>
>https://refreshless.com/nouislider/examples/#section-colored-connect
>
>
>
