### ISSUE TITLE
Documentation revamp

### ISSUE THREAD

**Issue by leongersen** [leongersen/noUiSlider#848]
With the release of noUiSlider 11, I touched up on a lot of the documentation, but there's still pain points that need to be addressed. 

- [x] Remove any mention of `serialization`;
- [x] Split 'examples' page into PHP `include` statements and re-order them;
- [x] Update index. It's outdated; focusing on 'no dependencies' rather than features, and doesn't mention installation using e.g. npm at all;
- [x] Change comma-separated `var` statements into separate statements;
- [x] Remove 'new-version' page; It's about noUiSlider 8!
- [x] Some text is littered with `<code>` statements, not helping readability;
- [x] @webketje Mention in docs that `pips` can also be updated through `slider.updateOptions`.

**Comment by webketje** [comment]
* [ ] As per [scope_api.js #L194](https://github.com/leongersen/noUiSlider/src/js/scope_api.js#L194) , mention in docs that `pips` can also be updated through

**Comment by leongersen** [comment]
@webketje A reference is now avaible here: https://refreshless.com/nouislider/reference/

Thanks for the suggestion!
