### ISSUE TITLE
Retrieve values on click

### ISSUE THREAD

**Issue by tlebreton** [leongersen/noUiSlider#850]
Hi

First thanks for this awesome plugin :)

For my project i would like to be able to retrieve slider value on click. But not all the sliders values , only the connected value.

In my example i got two timevalue (01:00 -> 04:00) and (10:00 -> 16:45).

If i click on the first i want to get the value (01:00 -> 04:00) and if i click on the second i want to get (10:00  -> 16:45)

But for now i got all the value of the slider.

Is it possible to get what i want.

CodePen : https://codepen.io/anon/pen/dJpPpd

Thanks for the help

**Comment by leongersen** [comment]
I'm sorry, but I don't understand what you are asking?

**Comment by tlebreton** [comment]
Hi :)

All god i find another solution to do my think.

I add a click event on .noUi-connect and i can get the closest begin and end of my slider .

Thanks for the plugin and for the support and good luck in your future dev
