### ISSUE TITLE
Translations makes the page horizontal scrollable

### ISSUE THREAD

**Issue by MathieuDR** [leongersen/noUiSlider#852]
Because of the new noUiSlider using translations it now slides almost my whole page to the right, making it scroll-able horizontal-wise.

![Preview](https://i.imgur.com/qOWxCAQ.gif)

[JSFiddle](https://jsfiddle.net/MathieuDR/hfza0hh9/)

**Comment by dhardtke** [comment]
Yep, having the same issue.

**Comment by leongersen** [comment]
I'm seeing it too. `.noUi-origin` now has a width to work around [this](https://bugs.chromium.org/p/chromium/issues/detail?id=798223) Chrome bug. 

You can work around this issue by setting an `overflow: hidden` on a slider parent. I'll look for a fix.

**Comment by leongersen** [comment]
Fixed in noUiSlider 11.0.2. Thanks for reporting!
