### ISSUE TITLE
Create Doesn't Render

### ISSUE THREAD

**Issue by mikewalkerjr** [leongersen/noUiSlider#853]
I have installed both `nouislider` and `@types/nouislider` into my project using:

    npm install --save-dev nouislider
    npm install --save-dev @types/nouislider

I have a `<div>` at the top of my page for the `noUiSlider`

    <div class="noUiSlider" id="slider"></div>

Since I'm using `webpack` I also added the following to `plugins` within the `webpack.config.js` file:

```
new webpack.ProvidePlugin({
     noUiSlider: 'nouislider'
})
```

Within the `TypeScript` file, I use the import

    import * as noUiSlider from 'nouislider';

And within the `$(document).ready(function() {}` function, I create the `noUiSlider` with

```
var slider = document.getElementById('slider');

if (slider) {
    noUiSlider.create(slider, {
        start: [20, 80],
        connect: true,
        range: {
            'min': 0,
            'max': 100
        }
    });
} 
```

Nothing is displayed within the HTML, however when I inspect the element I get

```
<div id="slider" class="noUiSlider noUi-target noUi-ltr noUi-horizontal">
    <div class="noUi-base">
        <div class="noUi-connects">
            <div class="noUi-connect" style="transform: translate(20%, 0px) scale(0.6, 1);"></div>
        </div>
        <div class="noUi-origin" style="transform: translate(20%, 0px); z-index: 5;">
            <div class="noUi-handle noUi-handle-lower" data-handle="0" tabindex="0" role="slider" aria-orientation="horizontal" aria-valuemin="0.0" aria-valuemax="80.0" aria-valuenow="20.0" aria-valuetext="20.00"></div>
        </div>
        <div class="noUi-origin" style="transform: translate(80%, 0px); z-index: 4;">
            <div class="noUi-handle noUi-handle-upper" data-handle="1" tabindex="0" role="slider" aria-orientation="horizontal" aria-valuemin="20.0" aria-valuemax="100.0" aria-valuenow="80.0" aria-valuetext="80.00"></div>
        </div>
    </div>
</div>
```

What would be causing the element to not appear correctly?

**Comment by leongersen** [comment]
Is the CSS included?

**Comment by mikewalkerjr** [comment]
Ahh that was one error I was not seeing. I'm using the Visual Studio SPA template and had some issues with the CSS. Sorry I didn't see that earlier

**Comment by J0ssue** [comment]
hey i was just wondering where did you include the css for this issue?

**Comment by juandelacruz23** [comment]
To anyone looking into this issue:

I was using this library with a custom webpack configuration (in which I'm not really an export, so it wasn't obvious to me at first) and to make ir work I had to import the css and ensure that the styles and css loaders where included in my webpack.config.
