### ISSUE TITLE
Tooltip showing handles distance instead of current value

### ISSUE THREAD

**Issue by HectorLS** [leongersen/noUiSlider#857]
Hello, first of all thanks by this awesome library, just getting into 👏 

I was checking the [tooltip information ](https://refreshless.com/nouislider/slider-options/#section-tooltips)

But didn't get how to show custom info & elements.
```javascript
var options = {
      start: [0, 200],
      connect: true,
      orientation: 'vertical',
      direction: 'rtl',
      tooltips: [wNumb({ decimals: 0 }), wNumb({ decimals: 0 })],
      step: 10,
      margin: 20,
      limit: 200,
      range: {
        min: 0,
        max: 250
      }
    };
```

This is working sweet, but the tooltip are showing the current position value, and i'm trying to change them, to show both the distance between then.
`element.noUiSlider.get();  //=> [value0, value1]`
`value1 - value0`

There is an easy way to achieve that ?, and also a way to maybe include some html tags inside them.

Thanks in advance.

**Comment by leongersen** [comment]
Yeah! You can add a `edit` function to your `wNumb` formatter:

```Javascript
wNumb({
    decimals: 0
    edit: function( value ){
        var values = slider.noUiSlider.get();
        var difference = Number(values[1]) - Number(values[0]);
        return '<div class="more-tooltip-html">' + difference + '</div>';
    }
})

```

**Comment by HectorLS** [comment]
Good morning !
Thanks by your reply.

But at the time of set the options variable, the noUiSlider has yet not been created anything, and `element.noUiSlider` would be `undefined`, and cannot run the `.get()` method 🤔 
So if i'm not wrong i have to set the tooltip option after create runs  right ?

```javascript
noUiSlider.create(element, this.options);

    element.noUiSlider.options.tooltips = [
      wNumb({ decimals: 0, edit: (value) => {
        return getDistance(value);
      }}),
      wNumb({ decimals: 0, edit: (value) => {
        return getDistance(value);
      }})
    ];

    function getDistance(value) {
      var values = element.noUiSlider.get();
      var difference = Number(values[1]) - Number(values[0]);
      return `<div class='more-tooltip-html'>${difference}</div>`;
    }

```
because this is not being update 😕 
Checking the [tooltip](https://refreshless.com/nouislider/examples/#section-hiding-tooltips) section, but not getting the idea sorry


Thanks in advance

**Comment by HectorLS** [comment]
Hello, i have got to properly calc the height.

Problem is getDistance function is not running when i set the values
If i use `element.noUiSlider.set` then the function getDistance never been executed, 😕 
Just when i move the handlers.

Any idea how to fix this ? 🙏 

Thanks in advance

**Comment by leongersen** [comment]
Closing as this issue is stale (I missed the last follow-up, my bad!). Feel free to open if there are any remaining questions.

**Comment by nlourenco-tsd** [comment]
I have the same question, which wasn't answered unfortunately.

**Comment by leongersen** [comment]
@nlourenco-tsd What question do you have, exactly?
