### ISSUE TITLE
Two types of range? one for handles and another for the connecting bar

### ISSUE THREAD

**Issue by HectorLS** [leongersen/noUiSlider#858]
Hello,

What i'm trying to achieve is (sampleCase);

have a range of positions in case someone want to move the handles
```javascript
range: {
        min   : [0, 10],
        '40%' : [40, 2],
        '50%' : [50, 50],
        max   : 100
      }
```

But that if the user drag the connecting bar, then the slider would step by 5.
Right now this is not possible, because from 0 goes to 10, and ignore the `step: 5` value.

Is there a way to achieve this behaviour? like setForce the connecting bar in case of dragging.
But take in count the range only for the handles.

**Comment by leongersen** [comment]
This isn't a feature in noUiSlider. You could try to implement it using events and the set method.

**Comment by HectorLS** [comment]
Finally what i found easier and allow me more control was use 2 sliders
1 for the handlers
1 for drag only de connecting bar.

and put the handlers over the other. 
Each one with it's own options and after slider / change events if fire just set the position to his sibling.

**Comment by leongersen** [comment]
Closing for lack of interest other than from the original poster. A workaround seems available. Feel free to comment on this issue, it can be re-opened.
