### ISSUE TITLE
Problem with implementation on big commerce site

### ISSUE THREAD

**Issue by pearcemichal** [leongersen/noUiSlider#863]
I'm not sure if it being a big commerce site is the source of the issue or not, I'm mostly mentioning it for the sake of completeness. 

I've got it working to the point that I can see that the slider is being when I look at it with the inspector, but it is not visible on the site, with a height of zero. (although even if I force it to have a larger height, there is still nothing there)

Here is a screenshot of my setup, along with the html structure in the inspector. 

![screen shot 2018-02-09 at 2 44 35 pm](https://user-images.githubusercontent.com/29542619/36046877-6e7dd1fc-0da8-11e8-8308-4d81cde66397.png)

Any idea of things I could try to get this working?

**Comment by leongersen** [comment]
Looking at what you're showing me, my first guess is you didn't include the CSS file.

**Comment by pearcemichal** [comment]
I just figured it out, I had included the css file, however big commerce wants css files to be in the .scss format, which I was able to do just by changing the extension.
