### ISSUE TITLE
Feature Request: Encoder (for Pip display) should accept any function, not just wNumb objects

### ISSUE THREAD

**Issue by hillct** [leongersen/noUiSlider#864]
wNumb is quite limited, for example, when rendering time data in the form of hh:mm:ss which always fails, yielding 'false' rather than whatever string value is output. There are ham handed approaches of assembling a time string represented as a decimal hh.mm then passing mark: ':' to get the colon into the right place is silly, and yields unmaintainable code.

Alternately, proper time handling could be introduced into wNumb() but this seems redundant and still unnecessarily limiting.

That is to say, this is a ridiculous way to format time into mm:ss:
```
        format: wNumb({
          mark: ':',
          encoder: function(inputSeconds){
            var minutes=Math.floor(inputSeconds/60);
            var seconds=inputSeconds%60;
            var output=minutes+"."+seconds;
            console.log("Calculated Pip Value: "+output)
            return(parseFloat(output));
          }
        })
```

**Comment by leongersen** [comment]
noUiSlider does accept any object that has a `to` (numerical->formatted) and `from` (formatted->numerical) function.
