### ISSUE TITLE
nouiSlider inside another nouiSlider.

### ISSUE THREAD

**Issue by ergodaveh** [leongersen/noUiSlider#869]
I have a customize implementation of nouislider where a slider displays duration of time.  This slider also includes a new 'caption' element attached to specific 'connect' element.  The slider's built-in features work to display this 'caption' element and provide the impression of adjusting the timing by sliding the connect'd handles position along the  X axis...  looks cool enough.  Now, I want to provide a feature which will adjust this 'caption' element along a perceived Y axis.. (up and down a scale as seen as a backdrop)..   My attempt - I have tried attaching a vertical slider to the 'connect' element and believed listening to the new object would provide the update to some css on the 'caption' element.  ... but man it looks ugly.  The actions of the 'parent' slider have too much influence on this child.     Is there any way this could work..  I've seen the example demo for 'locking' two sliders together...  but this is kinda like isolation..

**Comment by leongersen** [comment]
If I understand the question correctly, you are inserting a second slider into a `connect` element. Those are css-transformed to fit between the handles, so you can't do that. Instead, use the fifth argument (`positions`) to the `update` event and use that value to place your slider relative to a parent element.

**Comment by ergodaveh** [comment]
Cool  Thanks for the suggestion
