### ISSUE TITLE
noUi-connect ie9 missing -ms-transform-origin

### ISSUE THREAD

**Issue by mdondorp** [leongersen/noUiSlider#870]
The slider on the demo-page is not displaying correctly on IE9
transform-origin is only supported in IE9 when using the prefix (https://developer.mozilla.org/en-US/docs/Web/CSS/transform-origin#Browser_compatibility) 

Seems to be fixed by using the correct prefix:
`.noUi-connect, .noUi-origin {-ms-transform-origin:0 0;}`

**Comment by leongersen** [comment]
You are right. Sorry for my slow response, I overlooked this issue.

**Comment by leongersen** [comment]
I just released noUiSlider 11.1.0 that fixes this. Thanks for reporting!
