### ISSUE TITLE
Sync Handles value when two adjacent connected handles fully overlap

### ISSUE THREAD

**Issue by ergodaveh** [leongersen/noUiSlider#872]
a feature or 'how the heck would this work'   

With a slider with Multiple connected handles   When the leading and trailing handles of two adjacent connected handles fully overlap..  then those two handles values sync on any further updates until they are released by some event ..

**Comment by leongersen** [comment]
You could rebuild the slider with one fewer handle, and set it to the positions of the first.

**Comment by ergodaveh** [comment]
Awesome suggestion.  Thanks   
I have tried such a method.   The drag event handles the components as before.  But, how could I adjust  'drag'n event  to allow 'drag'n the whole'  combined-connected object?

**Comment by leongersen** [comment]
Closing this issue as it went stale. Feel free to comment (with additional information), the issue can be re-opened.
