### ISSUE TITLE
Tooltip Not lined up to slider due to translate on noUI-origin

### ISSUE THREAD

**Issue by davidvanvelzen-weather** [leongersen/noUiSlider#873]
Tooltip is not lined up with slider, it is offset to the left due to large negative translate added to noUI-origin element.  Is this a known issue?  Is it planned to be fixed?  

In the past, the tooltip lined up correctly.

**Comment by bhulsman** [comment]
@davidvanvelzen-weather Having the same issue after an upgrade, how did you fix this?
