### ISSUE TITLE
Pips formatting doesn't support HTML entities

### ISSUE THREAD

**Issue by carlosescri** [leongersen/noUiSlider#875]
To reproduce the problem use a formatting function that adds a HTML entity to the value, for instance:

```javascript
function format(value) {
  return valuel.toFixed(2) + '&euro;';
}
```

I think the affected code is [here](https://github.com/leongersen/noUiSlider/blob/aa64a6d9/src/js/pips.js#L222). It uses `node.innerText` which doesn't parse the text.

For the moment I've added a call to a decoder to my formatting function, but it looks a bit weird having to do that.

I don't know if it's a conscious design decision. If so, you can close this and I will use my decoder.

Thanks!

**Comment by carlosescri** [comment]
![image](https://user-images.githubusercontent.com/482075/38321967-50c29d4e-3839-11e8-9925-296bfd3b34a1.png)

**Comment by leongersen** [comment]
I suppose it could support innerHTML there. For your case, if your documents are UTF-8, you can just use the euro symbol: €.

**Comment by carlosescri** [comment]
I think that using innerHTML is the easiest solution, given that, in this case, the slider is being used on third party pages with no control of the character encoding.

**Comment by leongersen** [comment]
I just released noUiSlider 12, which uses `innerHTML` to write pips values. Thanks for reporting!
