### ISSUE TITLE
Nouislider OOP

### ISSUE THREAD

**Issue by VladimirSchneider** [leongersen/noUiSlider#876]
How i can use nouislider through classes?
For example: 
let slider = new NoUiSlider(element, options)

**Comment by VladimirSchneider** [comment]
Need add nouislider to window

**Comment by leongersen** [comment]
I don't understand what you are asking.

**Comment by VladimirSchneider** [comment]
I'm importing nouislider `import "nouislider"` and can not use it.
Error `Uncaught ReferenceError: noUiSlider is not defined`

**Comment by VladimirSchneider** [comment]
Or so

![image](https://user-images.githubusercontent.com/3888518/38407615-695d40b8-39a4-11e8-9425-6e13ad597e73.png)

![image](https://user-images.githubusercontent.com/3888518/38407624-719e77a6-39a4-11e8-9d38-039c18133fd3.png)
