### ISSUE TITLE
start event for noUiSlider

### ISSUE THREAD

**Issue by rosariomartone** [leongersen/noUiSlider#877]
Hi,
I am trying to catch the start event for a noUISlider with no success.
I have tried this example:

<div id="slider" style="margin-left:20px;margin-right:20px"></div>
                                                    <script>
                                                        var vehiclePrice = document.getElementById('slider');

                                                        noUiSlider.create(vehiclePrice, {
                                                            start: 8000,
                                                            step: 100,
                                                            behaviour: 'hover-snap',
                                                            connect: [true, false],
                                                            range: {
                                                                'min': 1500,
                                                                'max': 60000
                                                            }
                                                        });

                                                        vehiclePrice.noUiSlider.on('start', function () {
                                                            var txtamount = parseInt($("#sliderValuePrice").val());

                                                            if (txtamount < 2500)
                                                                txtamount = 2500;
                                                            if (txtamount > 60000)
                                                                txtamount = 60000;

                                                            loanamount = txtamount;

                                                            vehiclePrice.noUiSlider.updateOptions({
                                                                start: txtamount,
                                                                step: 500,
                                                                connect: [true, false],
                                                                range: {
                                                                    'min': 1500,
                                                                    'max': 60000
                                                                }
                                                            });

                                                            calculate();
                                                            calculateECP();
                                                        });

                                                        vehiclePrice.noUiSlider.on('update', function (values, handle) {
                                                            $('#sliderValuePrice').val(values[handle]);

                                                            loanamount = $('#sliderValuePrice').val();
                                                            counter = loanamount;

                                                            calculate();
                                                            calculateECP();
                                                        });
                                                    </script>

I know that "start" event fires when the user is going to click and holding the mouse on the slider and in this moment I would like to override step property to something else (500 in the previous example).
Any help will be appreciated, thanks!

**Comment by leongersen** [comment]
Changed slider settings in the `start` event will not apply until the following interaction.
