### ISSUE TITLE
Broken in LTR mode

### ISSUE THREAD

**Issue by schlaegerz** [leongersen/noUiSlider#878]
The handles don't show up on the bar if I have the style have the direction reversed. 

Its easy for me to just set it right on the container div so not a huge issue, but probably should be looked at.

**Comment by leongersen** [comment]
LTR is the default. Can you give an example?

**Comment by schlaegerz** [comment]
Sorry I mistyped. I meant it only works in LTR for me. I'm having some super weird styling issue, with the handles being way off the edge. I will work on getting a smaller version of my repro to figure out exactly what is happening. I'm able to fix it by adding padding-left to the container

**Comment by leongersen** [comment]
Cleaning up issues. Feel free to comment/open a new issue with if this remains an issue.
