### ISSUE TITLE
Full-range padding

### ISSUE THREAD

**Issue by bazineta** [leongersen/noUiSlider#880]
In the commentary related to #865, there's some discussion as to the range test for padding.

I'm curious if there's a non-negotiable reason for the test being `>= 100`, rather than `> 100`.

A sample use case is that I have `n` sliders that together comprise a total allocation, and a budget that that total is against. As the sliders are actuated, one can then apply padding to limit the sliders to how much of the budget remains.

In that scenario, if for example a given slider is at 0 and the budget has been completely allocated by the other sliders, then you'd want to set the padding on that slider to the full range; there's no budget left, so the slider can't leave 0.

However, that seems not to be possible at present. Should it be? Modifying the test to be `> 100` seems to work, but doubtless I've not considered every scenario.

**Comment by leongersen** [comment]
This was fixed by @paulharfenmeister in noUiSlider 13.1.5. Thanks for contributing!
