### ISSUE TITLE
The mousedown event defined on noUi-connects cannot be triggered in IE11.

### ISSUE THREAD

**Issue by He0cool** [leongersen/noUiSlider#881]
Hi
The mousedown event defined on noUi-connects cannot be triggered in IE11.
For example,
$(".noUi-connects").on("mousedown",function() {
	alert(1);
    var time;
    clearTimeout(time);
    time = setTimeout(function() {
        setBposition_a();
        setBposition_b();
        setBposition_c();
        setBposition_d();

    }, 300);
});
The above code can't trigger, other events can, why?Please help me, thank you

**Comment by leongersen** [comment]
`.noUi-connects` holds the `.noUi-connect` elements that are on top of it.
