### ISSUE TITLE
Slider values goes automatically to the top and come back 

### ISSUE THREAD

**Issue by ullasmohan** [leongersen/noUiSlider#883]
Hi  @leongersen ,
Am facing a strange issue in latest version. 
In my application when page load , **first the slider values going top automatically and coming back to the actual position.** I dint know is anyone else have the same issue. 
How I can resolve this issue? My previous version was **10.1.0**

**Comment by leongersen** [comment]
Closing for lack of response. Feel free to comment or open another issue with additional information.
