### ISSUE TITLE
How can I get id of slider in the change function where I have multiple sliders?

### ISSUE THREAD

**Issue by robinaitken1356** [leongersen/noUiSlider#884]
I have multiple sliders.  I have set up change function which is called when slider is updated:
function ExecuteSliderChange(values, handle, unencoded, tap, positions ) { 
...
}
In this function I need to access information from the slider object so I can make call back to server to indicate changes.  How can I access the id of the slider that was changed?
Any help much appreciated!

**Comment by leongersen** [comment]
In your event function, `this` is the slider API. The slider element is available in `this.target`.
