### ISSUE TITLE
Please consider changing the license

### ISSUE THREAD

**Issue by michaelquinn32** [leongersen/noUiSlider#885]
Hi Leon!

WTFPL is not considered a proper open source license, and it is a blocker to individuals within organizations to use and support this project:

https://opensource.google.com/docs/thirdparty/licenses/#wtfpl-not-allowed

The fact that others can't use and work on your code because of WTFPL goes against the spirit of being as open as possible.

Please consider switching to another permissive license, like Apache 2.0

https://opensource.google.com/docs/thirdparty/licenses/#notice

For more info, see: https://opensource.google.com/docs/using/license/

Best wishes,
Michael

**Comment by leongersen** [comment]
I'll look into it.

**Comment by devssh** [comment]
Also Wtfpl is not really as explicit about you not being liable for damages for others using it.

**Comment by leongersen** [comment]
I just released noUiSlider 12.0.0. With this release, the license changes to MIT. Thanks for contributing!

**Comment by michaelquinn32** [comment]
Thank you Leon! This is a big help!
