### ISSUE TITLE
tap variable in event callback is undefined

### ISSUE THREAD

**Issue by rkrishnasanka** [leongersen/noUiSlider#890]
Below is the sample code I am using for controlling the zoom of my application using the UI slider. I have confirmed that the ` update ` event is firing but it seems that for some reason the tap variable is coming as undefined. I need to be able to read if the event is user-generated or not.

Below is the code snippet that showed me that the variable tap is undefinied:

```
        this.__zoomSlider.noUiSlider.on('update', function (values, handle, unencoded, tap, positions) {
            console.log('isTap', tap);
            console.log('handle', handle);
            if(tap){
                console.log('Zoom Value:', values[0]);
                //TODO - Map this directly to the zoom functions
                console.log(registryref);
                try{
                    registryref.viewManager.setZoom(values[0]);
                }catch (e) {
                    console.log("Could not set the zoom");
                }
            }
        });
```

**Comment by leongersen** [comment]
I have tried to reproduce this, but I can't find a case where tap would become `undefined`. If this is still an issue for you, feel free to comment or re-open. Are you on the latest noUiSlider release?
