### ISSUE TITLE
Add handles programmatically

### ISSUE THREAD

**Issue by KilianSillero** [leongersen/noUiSlider#892]
It is posible to add handles dinamically?
Something like:
    `slider.add(20);`
I looked in the documentation and didn't see something like this.
set() doesn't work because this "delete" the old values and I want to keep them.

Example:
[jsfiddle](http://jsfiddle.net/cop2hnb1/)

**Comment by leongersen** [comment]
To update a slider handle count, you should destroy and re-create it:

```JavaScript
sliderUp.noUiSlider.destroy();
options.start = [20,30,40];
noUiSlider.create(sliderUp, options);
```

Updated: http://jsfiddle.net/cop2hnb1/5/

**Comment by leongersen** [comment]
Yes, something like:

```JavaScript
var values = sliderUp.noUiSlider.get();
values.push(50); // Your new handle start value
values.sort();

sliderUp.noUiSlider.destroy();

options.start = values;
noUiSlider.create(sliderUp, options);
```

**Comment by KilianSillero** [comment]
Thanks for resolve my issue :D
