### ISSUE TITLE
Version 11.1.0 is incompatible with ng2-nouislider

### ISSUE THREAD

**Issue by itcag** [leongersen/noUiSlider#896]
Seems that your changes breaks compatibility with ng2-nouislider
see working [https://stackblitz.com/edit/angular-6zhtib]

Steps to reproduce this issue: 
Just update the dependency in the demo by entering nouislider in the dependency section. 
It will then update from 10.1.0 to 11.1.0.
After updating the slider stops working.

**Comment by itcag** [comment]
This is the correct link [(https://angular-6zhtib.stackblitz.io)]

**Comment by blinkcat** [comment]
Same issue here

ERROR Error: noUiSlider (11.1.0): 'start' is required.

**Comment by leongersen** [comment]
I'm afraid I can't really be of much help there, you'll have to take it up with the maintainers for ng2-nouislider.
