### ISSUE TITLE
Feature request: pass array of acceptable values rather than min, max and step

### ISSUE THREAD

**Issue by piever** [leongersen/noUiSlider#898]
Hello and thanks for this really nice library!

The current API allows to pass a series of points (specifying say the value at 10%, or 30%), but I imagine that internally the set of allowed values is represented as an `Array`. I was wondering whether it's possible to allow the user to pass directly this array. This is very useful for scientific applications when one often needs to have very good control over non-linear sliders (for example the values could be logarithmically spaced).

**Comment by leongersen** [comment]
You could achieve this effect by programmatically generating the `range` option, where you map your array of values according to your desired spacing (e.g. logarithmically). Either way, the slider will have to be told where a give value should be placed on the available space.

**Comment by piever** [comment]
That's a good point. What I had in mind is that if the user just passes in an array (rather than a dict) to range, then the library could assume that the values should be placed evenly on the slider. For example:

```js
range: [1, 10, 100, 1000, 10000]
```
would be a shorthand for
```js
range: {'min': 1, '25%': 10, '50%': 100, '75%': 1000, 'max': 10000}
```

Scientific libraries often create this "logspaces" simply as a list of values, for example:

```python
>>> import numpy as np
>>> np.logspace(-2, 2, 10)
array([  1.00000000e-02,   2.78255940e-02,   7.74263683e-02,
         2.15443469e-01,   5.99484250e-01,   1.66810054e+00,
         4.64158883e+00,   1.29154967e+01,   3.59381366e+01,
         1.00000000e+02])
```
or
```julia
julia> logspace(-2, 2, 10)
10-element Array{Float64,1}:
   0.01     
   0.0278256
   0.0774264
   0.215443 
   0.599484 
   1.6681   
   4.64159  
  12.9155   
  35.9381   
 100.0      
```

and in terms of usability it'd be nicer to not have to translate this into a dictionary of percentage : value pairs.

**Comment by leongersen** [comment]
Now that's a good idea! Maybe something like 

```
noUiSlider.create({
    range: noUiSlider.buildRange([1, 10, 100, 1000, 10000])
})
```

**Comment by piever** [comment]
If there's no ambiguity (meaning if passing an array to range right now would error), I think it's OK to allow passing an array and convert to range object automatically. I guess you can add a method `buildRange` that the user can use, butif the users sets `range` equals to some array you would call `buildRange` on it and then continue with your pipeline.

**Comment by leongersen** [comment]
Well, that would only allow for linear ranges as the default, and it wouldn't allow for additional parameters.

**Comment by piever** [comment]
My javascript is really not spectacular, so feel free to ignore this idea if it turns out to be nonsensical :)

What I was suggesting is that you could simply add a check when creating the slider to convert automatically if the user passed an array:

```js
function create(options) {
    Array.isArray(options.range) && (options.range = buildRange(options.range)); // or maybe a different way that doesn't modify the options object
    ...
}
```
if the user passes an object of type `range = {'min': 0, 'max': 10, '10%': 5}` that conversion simply wouldn't be executed and everything would continue as usual, so all current features are preserved.

As I mentioned, I don't have a lot of javascript experience, so maybe enforcing the manual conversion is more standard.

**Comment by leongersen** [comment]
I'm not planning to work on the change requested here, so I'm closing this issue. I'm open to further discussion or a pull request, but that'll have to be in a new issue.
