### ISSUE TITLE
Prototype.js and noUiSlider conflict

### ISSUE THREAD

**Issue by wwwwee0000** [leongersen/noUiSlider#899]
I hope to help me, the problem does not know how to solve it, tips

Uncaught TypeError: this.each is not a function

Function findAll(iterator,context){var results=[];this.each(function(value,index){if(iterator.call(context,value,index))

**Comment by leongersen** [comment]
Merging with #909

**Comment by manelaguayo** [comment]
I simply added:

TouchList.prototype.each = Array.prototype.each;
TouchList.prototype._each = Array.prototype._each;

to noUislider.min.js at beginning and seems to have fixed my issue(s).
