### ISSUE TITLE
Draggable don't work if slider is initialized on node before appended to DOM

### ISSUE THREAD

**Issue by QmarXX** [leongersen/noUiSlider#901]
I am creating plugin with noUiSlider and I have problem with initialization slider before append whole template to DOM. The slider is displayed, but handle is not draggable. The problem seems to be creating HTML document and getting nodes from it. When I append node to DOM before init slider everything is OK.

I created example: http://jsfiddle.net/keudyfrp/32/

Any ideas how to fix it to work with my code? I tried to add `.cloneNode(true)`, but without success.

**Comment by leongersen** [comment]
The slider events aren't transfered from the new HTMLDocument to the actual document. You could create an element outside the dom:

http://jsfiddle.net/keudyfrp/34/

**Comment by QmarXX** [comment]
I did not know that. Thank you for help.
