### ISSUE TITLE
Handle dragging not working on Mobile Safari

### ISSUE THREAD

**Issue by laurin1** [leongersen/noUiSlider#902]
noUiSlider Version: 11.1.0
iOS versions tested: 11.4.1 & 9.3.5

I am trying to upgrade from noUiSlider 6.2, which worked fine. Now, on iOS the handle does not drag. I can move the bar by touching the slider bar, but if I touch and hold and try to drag the handle, nothing happens.

Works fine on desktop browsers.

**Comment by leongersen** [comment]
I don't have an iPhone handy. Does the documentation work for you?

**Comment by laurin1** [comment]
I'm not sure what you are asking me. What about the documentation? I have reviewed it and handle dragging should always be active, correct?

I have tried manually changing the behavior setting to see of other values made a different, like tap-drag, but no matter what the setting, the handle does not allow dragging. Again, I can touch the slider bar and move the handle, but I can't drag it, as I can in a desktop browser or on iOS using an old noUiSlider version.

		var slider = document.getElementById('slider');

		noUiSlider.create(
			slider, {
				start: value,
				range:
					{
						'min': min,
						'max': max
					}
			});

		slider.noUiSlider.on(
			'change',
			callback)

**Comment by leongersen** [comment]
Sorry, I wasn't clear. Can you drag the sliders in the documentation?

**Comment by laurin1** [comment]
Oh yea, good idea! 

Darn, yes, I can drag them in the documentation. I wonder what the difference is - let me do something testing and strip out everything from my application that I can that might causes a conflict.

**Comment by laurin1** [comment]
FYI, I just tested my app using Blisk and this is not an iOS thing (or Blisk does a hell of an emulation job) because the iPhone pane does not drag, but the desktop pane does!

![image](https://user-images.githubusercontent.com/75857/43585654-470ac3a8-962b-11e8-9474-fa3e613dd320.png)

**Comment by laurin1** [comment]
I found the problem. We use PrototypeJS as our primary JS framework. I stripped the page down to nothing and if I inject the PrototypeJS library, drag stops working, then remove it and drag works. Again, this only occurs on mobile, but apparently there is some kind of a conflict.

**Comment by laurin1** [comment]
FYI, I tested the jQuery UI slider (on their web page) and it has the same problem, I can touch to move it, but cannot slide it. We are falling back to use a input range control, as we can't remove PrototypeJS from our application at this time.

**Comment by leongersen** [comment]
Merging into #909
