### ISSUE TITLE
Replace the handles by a simple bar

### ISSUE THREAD

**Issue by b-repo** [leongersen/noUiSlider#904]
Hello, 

I read in the documentation that we are allowed to modify the handle as much as we want using the class `.noUi-handle`. 
But, due to the 
```
html:not([dir=rtl]) .noUi-horizontal .noUi-handle {
    right: -17px;
    left: auto;
}
```
The position of the handle/cursor is shifted right... Can you tell me how can I solve this problem?

Thank you

**Comment by leongersen** [comment]
You can override that style, either with a more specific selector or using  `right: 0 !important`.

**Comment by b-repo** [comment]
Thank you ! That's exactly what I wanted ! 
Great library and great support !
