### ISSUE TITLE
Duplicate nouislider.css and name it: nouislider.scss

### ISSUE THREAD

**Issue by pimvdmolen** [leongersen/noUiSlider#905]
Hi there!

My compiler gives warnings when i import nouislider.css into my app.css because it won't be supported in the future. Instead i would like to import nouislider.scss.

I don't mind if it's a simple copy of the css file, as long as i can import a .scss file.
Can you please add it to the package?

Thank you!

**Comment by leongersen** [comment]
What compiler are you using?

**Comment by leongersen** [comment]
For reference, this is [this issue at node-sass](https://github.com/sass/node-sass/issues/2362).

**Comment by leongersen** [comment]
This is fixed in node-sass v4.11.0. If any issues remain, feel free to comment.
