### ISSUE TITLE
Alter markup for handle

### ISSUE THREAD

**Issue by cibgraphics** [leongersen/noUiSlider#910]
For advanced styling, I need additional markup for the handle, Perhaps some added divs inside .noUi-handle. How can this be done?

**Comment by leongersen** [comment]
You can use the [`tooltips` option](https://refreshless.com/nouislider/slider-options/#section-tooltips) to insert HTML into handles.

**Comment by leongersen** [comment]
Closing as answered. Feel free to comment if you need additional information.
