### ISSUE TITLE
Feature request: Margin support for non-linear slider

### ISSUE THREAD

**Issue by rajkumar-osm** [leongersen/noUiSlider#911]
Currently the library doesn't support margin value for a non-linear slider. Margin works only for linear slider.
It would be great if it is made available for non-linear slider also. 

May be could take a reference from https://github.com/leongersen/noUiSlider/issues/615

**Comment by leongersen** [comment]
It's not even all that tricky. The issue is mostly that the padding/margin/limit might not fit within one "sub-range" (I'll call them A, B, and C), and thus might not fit within the `step` values for those ranges.

To demonstrate:
A: 000% - 010%: 000 - 500, step 10
B: 010% - 090%: 500 - 900, step 50
C: 090% - 100%: 900 - 950, step 5

If my margin is 10, the handles can be correctly placed in range C, but when one handle is on range B and one is on range C, there is no "correct" way to determine where handles should end up.

Does that make sense?

**Comment by leongersen** [comment]
I figure this change would fit within the current design fine. You'll find the logic for determining the next/valid handle position in a function called `checkHandlePosition`.

However:

> I would assume margin and padding takes precedence over step

Currently, the exact opposite design decision was made. I think all options provided to the slider should be respected, so the slider shouldn't decide to ignore step to meet margin, or vice versa.

**Comment by patrickschaffrath** [comment]
It also would be a solution to take `padding` as minimum `padding` and prevent partial steps.
In my example above the handle would stay at value 850 and leave more `padding` than specified, since no full `step` to the right would be possible anymore.

**Comment by leongersen** [comment]
Yes, that would work too. If you're willing to give this a shot I'd be happy to give you some pointers, should you need any.

**Comment by patrickschaffrath** [comment]
I'm giving it a shot, thanks for offering help. I'll see how far I get on my own maybe till this weekend.

**Comment by Macro-Jackson** [comment]
@patrickschaffrath, I guess your try failed?
@leongersen, did you have any progress on this feature? 

IMHO it is a very vital feature that is missing.

**Comment by Macro-Jackson** [comment]
I'll give it a try myself. I'm no JS specialist....

@leongersen question:
As I can see the percentage calculation (fromPercentage) is now absolute over the whole range for the margin/padding/limits. How'd you like it as we need to calculate distance relative in it's range?

As we can keep it absolute but then we need a bit "complex calculation" in the fromPercentage and toPercentage functions. Or we need to do multiple relative calculations in each range relative to the positions of the handles.

**Comment by Macro-Jackson** [comment]
A bit harder then I thought but nevertheless made good progress. Modified testPadding, testLimit and testMargin already to be range depending. Tomorrow continuing....

**Comment by leongersen** [comment]
noUiSlider 14.5.0 allows margin on non-linear sliders. Many thanks to @Macro-Jackson for this implementation, and to everyone else for contributing!
