### ISSUE TITLE
Flipping range on drag

### ISSUE THREAD

**Issue by mkurte** [leongersen/noUiSlider#913]
Hi @leongersen!

First of all, many thanks for this great library. I am currently using your slider for filtering products and it works fine.

But I also have a idea / feature request: Imagine a range on a scale from 0 - 100 for example. The lower value is currently 50, the higher one is 80. If I want to change the range from 20 - 50, I have to drag both handles to achieve this status. It would be nice to just drag the upper range from 80 to 20, but it always stops at 50 because the upper handle cannot be smaller than the lower one.
Is this feature planned or is it maybe already possible?

Thanks again a lot!
Matthias

**Comment by leongersen** [comment]
Hi Matthias! Do you mean something similar to this request? #815

**Comment by matthiaskurte** [comment]
Absolutely, thats what I mean. So, do I get it right that this feature currently isn't planned?

**Comment by leongersen** [comment]
Yes, but mostly for lack of attention. I'd be open to a pull request, even if it is some initial exploration.

**Comment by brianhadaway** [comment]
I'm looking to implement the same feature. The code in question is in the checkHandlePosition fn in lines 1829 - 1837: 

`            if (scope_Handles.length > 1 && options.limit) {
                if (lookBackward && handleNumber > 0) {
                    to = Math.min(to, reference[handleNumber - 1] + options.limit);
                }

                if (lookForward && handleNumber < scope_Handles.length - 1) {
                    to = Math.max(to, reference[handleNumber + 1] - options.limit);
                }
            }`

I don't have time for a PR right now but I produced the desired behavior by commenting out the above lines. [https://codepen.io/brianhadaway/pen/JmXKdx](https://codepen.io/brianhadaway/pen/JmXKdx)

**Comment by leongersen** [comment]
That'd be a good approach.

- [ ] Add option to `behaviour` setting
- [ ] Add condition [here](https://github.com/leongersen/noUiSlider/blob/master/src/nouislider.js#L1829) and [here](https://github.com/leongersen/noUiSlider/blob/master/src/nouislider.js#L1842)
- [ ] Add documentation

**Comment by leongersen** [comment]
This is now a feature in noUiSlider 12.1.0. Thanks for contributing!

[Documentation on the `"unconstrained"` option](https://refreshless.com/nouislider/behaviour-option/#section-unconstrained).
