### ISSUE TITLE
Optionally replace pip value with an icon

### ISSUE THREAD

**Issue by strayguevara** [leongersen/noUiSlider#916]
It would be cool if this had native support, but this is how we've replaced the pip values with a circle.

.noUi-value-large {
    text-indent:-9999px;
    background-color: green;
    width: 1rem;
    height: 1rem;
    border-radius: 1rem;
}

**Comment by leongersen** [comment]
As of noUiSlider, you can have the `format` in pips return html, and thus place arbitrary content in any pip.

**Comment by leongersen** [comment]
Closing as answered. Feel free to comment.
