### ISSUE TITLE
Support slider range numbers with decimals

### ISSUE THREAD

**Issue by cdalexndr** [leongersen/noUiSlider#919]
It would be nice to support float ranges instead of only integers. (ex: 0.01 -> 10)
Current workaround: offset data to integer range, and after user input, unoffset to real value

**Comment by leongersen** [comment]
Float ranges are completely supported. You'll just need to set the `format` option to retrieve them as numbers.

**Comment by cdalexndr** [comment]
Indeed, the problem was in my code.
