### ISSUE TITLE
Segmenting with a styles the Slider Bar 

### ISSUE THREAD

**Issue by ethanae** [leongersen/noUiSlider#922]
Hi,

I have a need to segment the actual slider bar at each step. Is this currently supported or could you advise on the best way to get this done? I have one handler, see below example of what I'd like to get done. As you can see I have 3 steps, where a white marker shows the point of each step.

![screen shot 2018-10-09 at 15 32 17](https://user-images.githubusercontent.com/19476308/46672831-baabdd00-cbd8-11e8-916e-cf155927eb71.png)

**Comment by leongersen** [comment]
You could use the [pips feature in "steps" mode](https://refreshless.com/nouislider/pips/#section-steps), and slide the pips on top of the slider using CSS.

**Comment by ethanae** [comment]
Cool, thanks for that the pointer.

What I ended up doing was to overlay pip-styled div elements along the slider bar.
