### ISSUE TITLE
All Contributors

### ISSUE THREAD

**Issue by MatheusRV** [leongersen/noUiSlider#926]
All Contributors is a fair and effective way to recognize all contributors who have helped and assisted noUiSlider. All Contributors is transparent, democratic and easily understood.

Reference:
https://github.com/kentcdodds/all-contributors

CLI:
https://github.com/jfmengels/all-contributors-cli

**Comment by leongersen** [comment]
Thanks for the suggestion. Contributors are available [here](https://github.com/leongersen/noUiSlider/graphs/contributors).

**Comment by MatheusRV** [comment]
This are contributors who mad commit, all contributors show all type of contribution
