### ISSUE TITLE
Handle flickers in Safari when using set() after dragging

### ISSUE THREAD

**Issue by roger6106** [leongersen/noUiSlider#927]
My goal is to have a smooth slider that only has a couple of steps. I am accomplishing this by:
1. Setting a handler for the `end` event.
2. In that handler, round the value to the desired value and calling `slider.set()`.

When doing this on Safari, the handle disappears until the animation is done.

I am using Safari 12.0.1 on macOS Mojave 10.14.1. This also occurs in Safari Technology Preview Release 68. I do not have a iOS device, so I am not sure if the issue occurs there as well.

I have attached an example of this issue.
[example.zip](https://github.com/leongersen/noUiSlider/files/2557897/example.zip)

**Comment by roger6106** [comment]
What I'm doing seems to be similar to what is requested in this issue: https://github.com/leongersen/noUiSlider/issues/627

**Comment by VlkaFenryka** [comment]
That Problem is easy to replicate with the examples in the official documentation.
Tested via browserstack and native devices on MacOS Mojave, iOS 11 with Safari 12
https://refreshless.com/nouislider/examples/#section-dates
DESKTOP: https://drive.google.com/file/d/1tycsXW3jUjqeC1erQZMzkFmO6I0fXXQ9/view
MOBILE: https://drive.google.com/file/d/1uiYTAoUjd1QpdOj8OUgwXmfq66JYuyCJ/view

**Comment by leongersen** [comment]
Thanks for the demonstration. Does this happen if you set `animate` to `false`?

**Comment by VlkaFenryka** [comment]
> Thanks for the demonstration. Does this happen if you set `animate` to `false`?
https://drive.google.com/file/d/1NrkzuzPYEHdCpFSxP74-1FeVJOOlfxza/view

The option is functioning, but does not solve the issue with the flickering (there never was a flickering on that example).
The mentioned problem is mostly at the last 2/3 of a range and not on all sliders
https://refreshless.com/nouislider/examples/#section-huge-numbers
https://drive.google.com/file/d/1FCfvDG3Qc1TCy6eCTJDPr8eQX9OsijFb/view

**Comment by leongersen** [comment]
I've now reproduced this issue in BrowserStack myself.

**Comment by leongersen** [comment]
Things that are _not_ the issue (from experimenting):
- The handle css transform changing
- The z-index changing

**Comment by leongersen** [comment]
Setting the following on resolves the issue for me in BrowserStack:

```CSS
.noUi-target, .noUi-target * {
    -webkit-transform-style: preserve-3d;
    -webkit-backface-visibility: hidden;
}
```

@VlkaFenryka, if you can confirm this I'll ship this as a new release.

**Comment by VlkaFenryka** [comment]
@leongersen 
**Confirmation** 
https://github.com/leongersen/noUiSlider/issues/927#issuecomment-472016113 solves the Problem,

**Comment by leongersen** [comment]
I've tested this more extensively, and adding these rules cause major slowdowns in Edge. I'll see what I can do about that.

**Comment by leongersen** [comment]
Setting the properties more carefully, and adding `transform-style: flat;` solved the slowdown in Edge. With the fixes in place I could no longer reproduce this issue, so I've release noUiSlider 13.1.2. Many thanks for contributing, @roger6106 and @VlkaFenryka!
