### ISSUE TITLE
'end' event not firing when updating the slider programatically

### ISSUE THREAD

**Issue by brian1037** [leongersen/noUiSlider#930]
Hi,

When updating the value of a slider handle programatically, the 'end' event does not fire.

Example: https://jsfiddle.net/93em1vud/2/ (drag the slider handle first to see the alert(), then click the text)

I see that this method has a second argument, a boolean for firing the 'set' event. I've tried this, and while it does function as intended, I can't use it for my purposes. In my specific use case, certain variables are not accessible to me during 'set' but are during 'end'.

So, as far as I can tell, I cannot trigger the 'end' event programatically which seems like a bug to me. If I am mistaken then I apologize in advance :)

**Comment by leongersen** [comment]
The set event should work for the case you describe, unless I'm missing some important details about your situation. `end` is fired immediately after `set`, so could you elaborate on:

>  "[...] are not accessible to me during 'set' but are during 'end'."

One thing in your example is that you are passing a one-value array to a two-handle slider, firing `set` for both handles. If you set the other value to `null`,  you'll get one set event:

https://jsfiddle.net/leongersen/93em1vud/3/

**Comment by brian1037** [comment]
Thanks for the reply.

I left out some details about my particular implementation of noUiSlider because they weren't relevant to the issue. Basically I am using custom tooltips that I inject on the 'slide' event, and they avoid each other while sliding around by measuring the distance between them.

The reason that I needed 'end' rather than 'set' is because 'set' fires before the animations. I modified the original example to demonstrate this here:

https://jsfiddle.net/93em1vud/8/

I am not sure if 'set' _should_ fire before or after animations when used programatically, but regardless, I can't find a way to reliably calculate the distance between handles (or, my custom tooltips) after all animations have finished.

So that's why I went looking for 'end', and when I found it wasn't being fired, submitted this bug.

At this point I am not sure if you consider any of this a bug, but I think that having a sort of 'afterAnimations' event would be useful and perhaps this is more of a feature request.

**Comment by leongersen** [comment]
That all makes sense! The animations are CSS transitions that take a fixed 300 ms. To get something like `afterAnimations`:

```
s.on('set', function() {
    setTimeout(function(){
        // Will happen after animations are done.
    }, 300);
});

```

**Comment by leongersen** [comment]
Also, for the offset calculations you are doing: the fifth argument, `positions`, to the event callback contains the relative positions for the slider handles (after animations). If you use these instead of the pixel-value `offset`, you'll get a nice performance increase and it'll keep your slider responsive.

**Comment by brian1037** [comment]
Thanks again for the reply.

Unfortunately I can't use the `positions` variable because of the nature of my custom tooltips. That variable is useful for the handles themselves, but the tooltips on this particular project can contain strings with a varying length of characters so the tooltips can collide long before the handles get close. And they'll collide at different points depending on the font size... I truly need to calculate the tooltip positions on the screen.

It seems like my best option is the 300ms timer, which I'll use.

I just thought of another potential solutions - for the programmatic .set() event to also trigger the 'slide' event. It would work just as well as it already works with the mouse.

Anyway, I'll go with the 300ms delay but I'll also keep an eye on noUiSlider in case you decide to implement any of those ideas ;)

Thanks for your help and thanks for making this wonderful library.

**Comment by leongersen** [comment]
Closing this as resolved. Feel free to comment!
