### ISSUE TITLE
syntax error in distribute/nouislider.css

### ISSUE THREAD

**Issue by Ibadichan** [leongersen/noUiSlider#931]
I found a syntax error in nouislider.css.
What says CSS Validation Service:
![2018-11-29 14 13 03](https://user-images.githubusercontent.com/26125121/49224140-eed59a00-f3e0-11e8-9940-d0ad72b530f7.png)
the line with error:
![2018-11-29 14 14 27](https://user-images.githubusercontent.com/26125121/49224237-2d6b5480-f3e1-11e8-9e73-c7425f1ff434.png)

**Comment by leongersen** [comment]
Jep, that's wrong. Thanks for reporting.

**Comment by leongersen** [comment]
This is fixed in noUiSlider 13.0.0. Thanks for reporting!
