### ISSUE TITLE
Feature Request/Query: can we add or remove handle from slider  on button click?

### ISSUE THREAD

**Issue by neerajshrimali** [leongersen/noUiSlider#934]
Hi @leongersen   
I am developing schedule planner functionality with help of noUISlider. 
I have a question  - How can we add or removed handle in slider by a button click. 
can we add addHandle(), removeHandle() method like setHandle() method.

I have one example which exactly matching my requirement.
http://embed.plnkr.co/XJyMrxVgFixCKkUnwUTA/preview

**Comment by leongersen** [comment]
Adding/removing handles is currently not a feature in noUiSlider. You'll have to call `destroy()` and create a new slider (although this is low overhead).

**Comment by leongersen** [comment]
Merging with #789.
