### ISSUE TITLE
Question: Pips Value below 1

### ISSUE THREAD

**Issue by LuckyLuzz** [leongersen/noUiSlider#935]
Hey, great lib! I was plaing around the last couple days, but I coulden't get a pip slider running with values under "1". 

If value is 0.5 it shows 1.

Please have a look at the jsfiddle: [http://jsfiddle.net/LuckyLuzz/1Lx5qtr9/]( http://jsfiddle.net/LuckyLuzz/1Lx5qtr9/)

**Comment by leongersen** [comment]
You are seeing the default format (rounding to one decimal). You can set the `format` option (within `pips`) to get all decimals:

http://jsfiddle.net/leongersen/8462a0og/1/

**Comment by LuckyLuzz** [comment]
awesome! :)  I guess I just found a bug, try imput 0.3 as value, it shows like 0.3000000000000

http://jsfiddle.net/LuckyLuzz/1Lx5qtr9/75/

**Comment by leongersen** [comment]
Well, since `0.3` is stored as a floating point number, it has arbitrary precision. Using `String` to print it yields more decimals than you want. You can use `.toFixed` (or another formatting option):

http://jsfiddle.net/leongersen/8462a0og/4/

**Comment by LuckyLuzz** [comment]
thank you very much :)
