### ISSUE TITLE
Feature/ Query : how can we bind/insert any template/text inside noUi-connects class element.

### ISSUE THREAD

**Issue by neerajshrimali** [leongersen/noUiSlider#936]
Hi @leongersen 
I have one question/doubt pls help!

How can we display handels value in noUi-connects element like in image, the vaue will change when user move these handles.
![image](https://user-images.githubusercontent.com/3906335/49853501-5510e280-fe0d-11e8-8b9d-a1bf6c8dd69b.png)

**Comment by leongersen** [comment]
You can add an element to the slider after you create it, then set it's value in the `update` event.

**Comment by leongersen** [comment]
Closing this, as I assume the original question was answered.
