### ISSUE TITLE
Dragging range can change disabled handle

### ISSUE THREAD

**Issue by ryankfrench** [leongersen/noUiSlider#938]
I noticed that your documentation section on disabling the slider and handles does not address the case of two handles that are connected with the behavior set to drag.  If any or both of the handles are set to disabled, the user can still change their values by dragging the range. I am not sure if this was intended.

I was hoping I could listen for the start event and somehow ignore or handle the event if the user tries to move that handle by dragging the range but I can't seem to figure out how to ignore an event or stop subsequent events from being fired. Any ideas?

**Comment by leongersen** [comment]
This is definitely a bug, thanks for reporting!

I think I'll have some spare time this month to work on this project, I'll pick this bug up as well.

**Comment by leongersen** [comment]
This is fixed in noUiSlider 13.0.0. Thanks again for reporting!
