### ISSUE TITLE
Cumulative set event for all handles?

### ISSUE THREAD

**Issue by AAverin** [leongersen/noUiSlider#940]
I have 4 handles and I do a programmatic set for them.
set event ends up being fired 4 times, one for each handle.
Is it possible somehow to get and event when everything is set?

**Comment by leongersen** [comment]
You can check if the handle index (the second argument to the set event) matches the number of handles - 1.

**Comment by AAverin** [comment]
@leongersen I have a heavy script that needs to run each time values on the slider change. In the beginning I set values on the slider programmatically. At this moment I get 4 events, one for each slider.
After that user would drag the slider and I will be getting only one event because only one event changes. 
Another case is when range can be dragged together, it will also give multiple events. 
Woukd be great to have a cumulative change event for cases when either all handles are set programmatically or when range is dragged - that way I can trigger my script once for every change. 

With what you suggest, I can't really tell the difference between cases if multiple identical events and single unique event

**Comment by leongersen** [comment]
If you can give me some example code I can give some pointers.

**Comment by leongersen** [comment]
I'm closing this as there's been no follow-up. Feel free to comment if any questions remain, I'll re-open.
