### ISSUE TITLE
updateOptions: set option to default/delete option

### ISSUE THREAD

**Issue by jukkahuuskonen** [leongersen/noUiSlider#944]
Hi,

Is there a way to set one of the slider options to default value or delete user defined value (=making the slider use the default value)?

For example, if I set the **margin**, **limit**, **padding** or **step** to **20**, when creating the slider and then I want to remove the option(s) later, how can I do that? 
Default value for them is 'none' but that cannot be set manually. Setting those options to 0, seems to work, but I'd rather have that option removed from options-object.

Also removing pips seems to be impossible. You can update them, but I can't remove them.

Do I need to destroy slider and recreate it if I want to remove one of user defined values? That is the only way I've found so far.

**Comment by leongersen** [comment]
You can use `null` for values you'd like to unset in `updateOptions` (`slider.noUiSlider.updateOptions`). Pips can be removed using `removePips` (`slider.noUiSlider.removePips`).

**Comment by leongersen** [comment]
I've updated the [documentation on updating](https://refreshless.com/nouislider/more/#section-update). It now has more examples, including unsetting values. Thanks for contributing!
