### ISSUE TITLE
Feature request: add possibility to update padding without recreating slider

### ISSUE THREAD

**Issue by Soulafein** [leongersen/noUiSlider#945]
Currently the library doesn't support updating padding value without recreating slider. It would be great if padding update will be available without such workarounds.

**Comment by leongersen** [comment]
Padding can actually be updated using the `updateOptions` method, but I'm noticing now that `padding` is missing from the documentation. I'll fix that.

**Comment by leongersen** [comment]
I've fixed this omission in the documentation. Thanks for contributing!
