### ISSUE TITLE
Color left and right side of the slider

### ISSUE THREAD

**Issue by madmark81** [leongersen/noUiSlider#947]
related to issue: #445

Is there a way to color both the left and the right side of a slider bar at the same time? 
or upper and lower part relative to the slider for a vertical one? I would like the bar to stand out more from my white background, while also making the other half of the bar yet another color. 

thanks

**Comment by leongersen** [comment]
Could you add a quick mockup of what you're looking to achieve? Super simple (like in paint) is fine.

**Comment by madmark81** [comment]
give me a minute, will do

**Comment by madmark81** [comment]
![image](https://user-images.githubusercontent.com/29946999/52562768-d978e500-2dff-11e9-957b-b401ca617988.png)

This is what my slider currently looks like, minus the dark blue part, which is what I'm trying to achieve. 
(should fill like the bottom but paint is sloppy)

p.s., also not quite sure why the box around the slider value has such an odd shape. It happened when I added this line to my css: 
                                                 `          .noUi-vertical .noUi-tooltip {-webkit-transform: translate(0,-50%);transform: translate(0,-50%);top: 50%;left: 200%;}`

**Comment by leongersen** [comment]
Looking at that, something like the following should do:

```CSS
.noUi-target {
    background: blue;
    box-shadow: none;
}
```

**Comment by madmark81** [comment]
Doesn't seem to do anything other than flashing the whole div around the slider blue on load in R shiny

**Comment by leongersen** [comment]
Is there any other CSS overriding your additions?

**Comment by madmark81** [comment]
In the test app there is no other css other than this: 
  tags$head(tags$style(HTML('
                                #Histoslider .noUi-connect { background: red;}
                         #Histoslider .noUi-target, .noUi-target  {background: blue;box-shadow: none;}'))),


I see this, for 0.2 seconds or so, super fast 
![image](https://user-images.githubusercontent.com/29946999/52564316-278fe780-2e04-11e9-8263-3bffbfcf3fef.png)

I can't find the background: blue anywhere in de DevTool console. It shows this: 
![image](https://user-images.githubusercontent.com/29946999/52564377-527a3b80-2e04-11e9-99ce-c6abc4cce4c8.png)

**Comment by madmark81** [comment]
afterwards it looks like this: 
![image](https://user-images.githubusercontent.com/29946999/52564475-9d944e80-2e04-11e9-9a59-2697270499e7.png)

**Comment by leongersen** [comment]
You have `#Histoslider .noUi-target`, that should be `#Histoslider.noUi-target` (it is the same element).

**Comment by madmark81** [comment]
Got it!

**Comment by leongersen** [comment]
Closing this, since I think the question was answered. Feel free to comment!
