### ISSUE TITLE
Fixed custom steps and custom styling

### ISSUE THREAD

**Issue by fmigliorato** [leongersen/noUiSlider#949]
I need to build a range-slider like this image below. Is it possible to have fixed custom steps (from one point to another, NOT in between)

Also, is it possible to style the noUiSLider like the image?

![custom range slider](https://i.imgur.com/IRb7oWQ.png)

Thank You

**Comment by leongersen** [comment]
Yes! You can use [the `snap` option](https://refreshless.com/nouislider/slider-values/#section-snap). Regarding the styling, you can use [the `tooltips` option](https://refreshless.com/nouislider/slider-options/#section-tooltips) to get the value in the handle.

**Comment by fmigliorato** [comment]
@leongersen Thank You so much for the quick reply! Really appreciated. May I close the issue and reopen if I need further assistance?

**Comment by leongersen** [comment]
Absolutely, glad I could help :)
