### ISSUE TITLE
Wrong URL to full list of class names

### ISSUE THREAD

**Issue by dbingel** [leongersen/noUiSlider#950]
In the [documentation](https://github.com/leongersen/noUiSlider/blob/master/documentation/more/classes.js#L12), `/documentation/more/classes.js` contains a URL to the full list of class names. This URL does not exist. The link should be `https://github.com/leongersen/noUiSlider/blob/master/src/nouislider.js#L880`.

Solved in https://github.com/leongersen/noUiSlider/pull/951.

**Comment by leongersen** [comment]
Thanks for fixing this! I've updated the documentation.
