### ISSUE TITLE
One segment per value

### ISSUE THREAD

**Issue by montalvomiguelo** [leongersen/noUiSlider#952]
Hey,

I need to build a range with one segment per value, is this currently supported?

![screen shot 2019-02-28 at 08 12 06](https://user-images.githubusercontent.com/5134470/53572502-fec05f80-3b30-11e9-9ad1-e45e27a7bc85.png)

Thanks

**Comment by leongersen** [comment]
Yes! You can use the [`snap`](https://refreshless.com/nouislider/slider-values/#section-snap) option to have the slider jump between steps. Alternatively, if all your segments are of size 1, you can set `step` to `1`. The lines on the slider can be done in CSS.

**Comment by leongersen** [comment]
I'm closing this as answered. Feel free to comment if any questions remain, I'll re-open.
