### ISSUE TITLE
Disabled doesn't disable arrow keys?

### ISSUE THREAD

**Issue by mluhring** [leongersen/noUiSlider#953]
Just wondering if I missed something, but disabling the slider does not disable tabbing in and using the arrow keys.  Tabbing in is not a huge issue, but disabling the ability to use the arrow keys is crucial.

**Comment by mluhring** [comment]
Just noticed the KeyboardSupport option.  I'll give that a try.

**Comment by leongersen** [comment]
I missed this as you closed it, but a disabled slider should definitely ignore the arrow keys.

**Comment by mluhring** [comment]
I just used the SuppotKeyboard option.  I was able to get the functions I needed with that and disabled.  Thanks for reopening and incorporating both when disabled is true.  I like the control!

**Comment by leongersen** [comment]
I've fixed this issue in noUiSlider 13.1.2. Thanks for reporting!
