### ISSUE TITLE
Minor website copy issue

### ISSUE THREAD

**Issue by AdamJaggard** [leongersen/noUiSlider#954]
You have a very small copy issue on your events grid in the hidden yes/no text that I'm guessing is there for accessibility reasons. Just a stray Yes where it should say No, see screenshot.

I'm hoping this qualifies for the highest tier of bug bounty rewards! :)

<img width="796" alt="screenshot 2019-03-07 at 11 17 37" src="https://user-images.githubusercontent.com/9952680/53954412-16b65700-40ce-11e9-8f45-8c6930b879d5.png">

**Comment by leongersen** [comment]
Fixed! Thanks @AdamJaggard. I guess I'd better get to work putting a bug bounty program together, can't have things like this around 😄
