### ISSUE TITLE
Lock with different steps

### ISSUE THREAD

**Issue by knittycatkitty** [leongersen/noUiSlider#955]
Hi is it possible to lock two sliders with different step intervals?

I am using it as a selector for a package quantity while the other slider is used for the dollar amount the package will cost.

the other slider is hidden and outputting the value to a html5 input box.

so far what i have seen, i can't get them to step at different intervals, always the same

**Comment by leongersen** [comment]
I'm not sure what you are asking. Can you add an example with what you're trying to do?

**Comment by knittycatkitty** [comment]
> I'm not sure what you are asking. Can you add an example with what you're trying to do?

Hi sorry I just saw this response

I am trying to make different step intervals for two sliders that are locked to each other

A slider to select the hashrate and a slider that reflects the price which is hidden and passes value over to the USD box as shown below

![image](https://user-images.githubusercontent.com/42597963/54888275-4ad19c00-4e72-11e9-971f-8cd89aa4c2fe.png)

**Comment by knittycatkitty** [comment]
Each 1 TH/s should be $50 but as can be seen here, they are not proportional :/  Any idea how to fix this?

![image](https://user-images.githubusercontent.com/42597963/54888295-7b193a80-4e72-11e9-9e5e-0153f9bbced9.png)

![image](https://user-images.githubusercontent.com/42597963/54888296-7d7b9480-4e72-11e9-9b4c-680101353725.png)

![image](https://user-images.githubusercontent.com/42597963/54888297-7f455800-4e72-11e9-9e89-f387f9fbd93b.png)

**Comment by knittycatkitty** [comment]
`
    var selector = document.getElementById('exampleFormControlSelect1').value

    if(selector === 'Bitcoin BTC'){
        document.getElementById('exampleFormControlSelect1').setAttribute('class', 'form-control allocation-box btc-allocation')
        document.getElementById('exampleFormControlSelect2').innerHTML = 'SHA-256 Hashrate'

        var lockedState = true;
        var lockedValues = [0, 0];
        
        var slider1 = document.getElementById('slider1');
        var slider2 = document.getElementById('slider2');
        
        var slider1Value = document.getElementById('input-slider-value');
        slider1Value.setAttribute('class', 'range-slider-value')
        var slider2Value = document.getElementById('usdprice');
        

        function crossUpdate(value, slider) {

        
            // Select whether to increase or decrease
            // the other slider value.
            var a = slider1 === slider ? 0 : 1;
        
            // Invert a
            var b = a ? 0 : 1;
        
            // Offset the slider value.
            value -= lockedValues[b] - lockedValues[a];
        
            // Set the value
            slider.noUiSlider.set(value);
        }

        noUiSlider.create(slider1, {
            start: 0,
        
            // Disable animation on value-setting,
            // so the sliders respond immediately.
            animate: false,
            range: {
                'min': 0,
                'max': 250
            }
        });
        
        noUiSlider.create(slider2, {
            start: 0,
            animate: false,
            connect: true,
            range: {
                'min': [0,50],
                'max': 12500
            }
            
        });
        
        
        slider1.noUiSlider.on('update', function (values, handle) {
            slider1Value.innerHTML = values[handle] + ' TH/s';
        });
        
        slider2.noUiSlider.on('update', function (values, handle) {
            slider2Value.value = '$' + values[handle];
        });

        function setLockedValues() {
            lockedValues = [
                Number(slider1.noUiSlider.get()),
                Number(slider2.noUiSlider.get())
            ];
        }
        
        slider1.noUiSlider.on('change', setLockedValues);
        slider2.noUiSlider.on('change', setLockedValues);
        
        slider1.noUiSlider.on('slide', function (values, handle) {
            crossUpdate(values[handle], slider2);
        });
        
        slider2.noUiSlider.on('slide', function (values, handle) {
            crossUpdate(values[handle], slider1);
        });

    }`

**Comment by leongersen** [comment]
Sorry, but I still don't understand what, specifically, you are asking. If you could abstract the question away from the specific problem you are trying to solve, that might help.

**Comment by knittycatkitty** [comment]
No problem

I'm using the lock feature on noUISlider with two sliders right now so they increase at the same increments as one another if I move one of the sliders up or down.

I was wondering if it was possible where they can have two independent increments 

Say for example
Slider 1 has a value that can go from 1 to 10
Slider 2 has a value that can go from 1 to 100

**Currently** 
Move _Slider 1_ to value '7' (increments by 1)
_Slider 2_ moves to value '7' (increments by 1)
There is no option to change increment per each slider as far as I can tell for two locked sliders, they seem to only follow the first slider's increment settings. No independent increments

**Ideal** 
Move _Slider 1_ to value '7' (increments by 1)
_Slider 2_ moves to value '70' (increments by 10)

Wondering if I'm missing something or it is not a feature yet on noUISlider

I hope this gets my message across and what I'm trying to accomplish

Regards,
knitty

**Comment by leongersen** [comment]
You could do that in the `crossUpdate` function. Something like the following should do:

```JavaScript
value -= (lockedValues[b] - lockedValues[a]) * [0.1, 10][a]; // multiply or divide by 10
```

**Comment by leongersen** [comment]
Closing this as I assume the question was resolved. Feel free to comment.
