### ISSUE TITLE
Slider does not seem to work with low values

### ISSUE THREAD

**Issue by martinRenou** [leongersen/noUiSlider#956]
I want to create a slider with a min value of `-0.0000013931280717964222` and a max value of `0.0000013929894809231831`, the slider is correctly created, but when printing the value on change event it only shows `0.00`

```javascript
var min = -0.0000013931280717964222;
var max = 0.0000013929894809231831;

slider = noUiSlider.create(el, {
    start: [min, max],
    connect: true,
    range: {
        'min': min,
        'max': max
    }
});

slider.on('update', function (values, handle) {
    var value = values[handle];
    console.log(value) // Prints `0.00`
});
```

**Comment by leongersen** [comment]
Formatting to [two decimals is the default](https://refreshless.com/nouislider/slider-read-write/#section-formatting). You can change this using the `format` option.

**Comment by martinRenou** [comment]
I'm not entirely sure it's a formatting issue. I tried this option and it prints `NaN`:
```javascript
    format: {
        to: function (value) {
            console.log(value); // This prints NaN
            return parseFloat(value);
        }
    }
```

**Comment by leongersen** [comment]
You should provide both `to` and `from`. `to` should return the formatted value (as a string), not the float.

Your original example with formatting:

```JavaScript
slider = noUiSlider.create(slider, {
    start: [min, max],
    connect: true,
    format: {
        to: String,
        from: Number
    },
    range: {
        'min': min,
        'max': max
    }
});
```

**Comment by martinRenou** [comment]
Thanks, actually the slider from JqueryUI does not work with very small values, that's why I had the wrong idea in mind at first.
We'll definitely move to use noUiSlider :)

**Comment by leongersen** [comment]
Glad I could help :smile:
