### ISSUE TITLE
Pips numbers are wrong if you use values 0 to 10

### ISSUE THREAD

**Issue by Chatzimina** [leongersen/noUiSlider#958]
Hello. If you have minimum 0 and maximum 1 , the values under the slider are wrong compared to the slider and the tooltip. Specifically in number 3 and 8 (something like the division is wrong?). If I add 0 to 12 for example it is working correctly.

Here is a picture
![13-3-2019 3-59-57 μμ](https://user-images.githubusercontent.com/5290778/54284753-30add900-45a9-11e9-8793-89e8ee1b542e.png)

Thank you

**Comment by leongersen** [comment]
Could you add your code?

**Comment by Chatzimina** [comment]
I use it through surveyjs so my json is:
      {
            type: "nouislider",
            name: "range",
            title: "Please range",
            rangeMin: 0,
            rangeMax: 10
        },
and in my html page I add this:

    <script src="https://unpkg.com/nouislider@9.2.0/distribute/nouislider.js"></script>
    <link href="https://unpkg.com/nouislider@9.2.0/distribute/nouislider.min.css" rel="stylesheet"/>

Then I dried to change it by adding this javascript:

    var slider = document.getElementsByClassName('noUi-target ')[0];
    slider.noUiSlider.updateOptions({
    range: {
        'min': 0,
        'max':10
    },
     pips: {
            mode: 'values',
            values: [0, 1, 2, 3, 4, 5,6,7,8,9,10],
            density: 100
        },
     start: 5,
     step : 1
    });

but only range is changing. 

I also used this with no change:

     var pips = document.getElementsByClassName('noUi-pips')[0];
     noUiSlider.create(pips, {

     start: 0,
     pips: {
        mode: 'positions',
        values: [0, 25, 50, 75, 100],
        density: 4
       }
    });

I used values in positions 25 and 75 because is the correct positions that the number 3 and 8 are as I saw from the browser:

    <div class="noUi-marker noUi-marker-horizontal noUi-marker-normal" style="left: 0.00000%"></div>
    <div class="noUi-marker noUi-marker-horizontal noUi-marker-normal" style="left: 5.00000%"></div>
    <div class="noUi-marker noUi-marker-horizontal noUi-marker-normal" style="left: 10.00000%"></div>
    <div class="noUi-marker noUi-marker-horizontal noUi-marker-normal" style="left: 15.00000%"></div>
    <div class="noUi-marker noUi-marker-horizontal noUi-marker-normal" style="left: 20.00000%"></div>
    <div class="noUi-marker noUi-marker-horizontal noUi-marker-large" style="left: 25.00000%"></div>
    <div class="noUi-value noUi-value-horizontal noUi-value-large" style="left: 25.00000%">3</div>
    <div class="noUi-marker noUi-marker-horizontal noUi-marker-normal" style="left: 30.00000%"></div>
    <div class="noUi-marker noUi-marker-horizontal noUi-marker-normal" style="left: 35.00000%"></div>
    <div class="noUi-marker noUi-marker-horizontal noUi-marker-normal" style="left: 40.00000%"></div>
    <div class="noUi-marker noUi-marker-horizontal noUi-marker-normal" style="left: 45.00000%"></div>
    <div class="noUi-marker noUi-marker-horizontal noUi-marker-large" style="left: 50.00000%"></div>
    <div class="noUi-value noUi-value-horizontal noUi-value-large" style="left: 50.00000%">5</div>
    <div class="noUi-marker noUi-marker-horizontal noUi-marker-normal" style="left: 55.00000%"></div>
    <div class="noUi-marker noUi-marker-horizontal noUi-marker-normal" style="left: 60.00000%"></div>
    <div class="noUi-marker noUi-marker-horizontal noUi-marker-normal" style="left: 65.00000%"></div>
    <div class="noUi-marker noUi-marker-horizontal noUi-marker-normal" style="left: 70.00000%"></div>
    <div class="noUi-marker noUi-marker-horizontal noUi-marker-large" style="left: 75.00000%"></div>
    <div class="noUi-value noUi-value-horizontal noUi-value-large" style="left: 75.00000%">8</div>        
    <div class="noUi-marker noUi-marker-horizontal noUi-marker-normal" style="left: 80.00000%"></div>
    <div class="noUi-marker noUi-marker-horizontal noUi-marker-normal" style="left: 85.00000%"></div>
    <div class="noUi-marker noUi-marker-horizontal noUi-marker-normal" style="left: 90.00000%"></div>
    <div class="noUi-marker noUi-marker-horizontal noUi-marker-normal" style="left: 95.00000%"></div>
    <div class="noUi-marker noUi-marker-horizontal noUi-marker-normal" style="left: 100.00000%"></div>

thanks

**Comment by leongersen** [comment]
Your pips configuration isn't what you want:

```
 pips: {
        mode: 'values',
        values: [0, 1, 2, 3, 4, 5,6,7,8,9,10],
        density: 100 // This is way too dense
    },
```

Try this:

```
    pips: {
        mode: 'values',
        values: [3, 5, 8]
    }
```

Also, the `updateOptions` you are doing is adding steps, which I don't think is what you are trying to do. The second item in the array is the step value.

```
updateOptions({
range: {
    'min': [     0 ], // step not set
    '10%': [ 1 , 1 ], // step = 1
    '20%': [ 2 , 2 ], // step = 2
    // etc
```

For what you are trying to do, you don't need `updateOptions` at all.

**Comment by Chatzimina** [comment]
So I added  only 

        pips: {
        mode: 'values',
        values: [3, 5, 8]
    }

But values are still wrong. I think there is something wrong regardless my code. If you go to this link
https://surveyjs.io/Examples/Library/?id=custom-widget-nouislider&platform=jQuery&theme=default.
 and press "Edit plunker" button  

and add in  json in index.js 
    "rangeMin": 0,
     "rangeMax":10

you will see that the values are still wrong. 
Also I cannot add all the numbers in the pip bar like 1,2,3,4,5,6,7,8,9,10 and not only 3,5,8

thank you

**Comment by leongersen** [comment]
The version of noUiSlider on that page is 9.2.0

**Comment by Chatzimina** [comment]
Ok so I fixed it by destroying the slider the surveyjs was creating and create a new one with the code you provided me. Like this: 

    var slider = document.getElementsByClassName('noUi-target ');
    slider.noUiSlider.destroy();
    noUiSlider.create(slider,{
    range: {
        'min': [ 0],
        'max': [ 10]

    },
     connect: "lower",
     tooltips: [true],
     step: 1,
     start: 3,
     pips: {
        mode: 'range',
        format: {

        to: function(a){
        return pipFormats[a];
        }},
         mode: 'values',
    values: [0,1,2,3,4, 5,6,7, 8,9,10]},
     step:1
    });
     }

**Comment by leongersen** [comment]
Alright! Glad you worked it out 😄
