### ISSUE TITLE
I need different ranges for minimum and maximum range

### ISSUE THREAD

**Issue by gajerajimesh** [leongersen/noUiSlider#959]
We have used slider for one of my client and they need different ranges for minimum and maximum knobs like mentioned below,

Left knob of the slider can be set to any of the low values : 2, 6, 9, 12, 15, 18, 21, 25, 30, 35, 40, 45, 50, 55, 65+
Right knob of the slider can be set to any of the high values: 5, 8, 11, 14, 17, 20, 24, 29, 34, 39, 44, 49, 54, 64, 65+

Could you please suggest me, How we can implement that?

**Comment by leongersen** [comment]
Right now, the slider doesn't support different ranges for handles. You have two options:
- Use two sliders
- Use a linear slider, and use the `format` option to map the slider values to your expected output.

**Comment by leongersen** [comment]
Closing this as answered. Feel free to comment if you have further questions.
