### ISSUE TITLE
Not operable by keyboard using VoiceOver

### ISSUE THREAD

**Issue by jurajk** [leongersen/noUiSlider#963]
When using VoiceOver, i'm not able to operate the slider using arrow keys. 

This might be caused by VoiceOver focusing a different element - upon focusing a handle, VO announces "You are currently on a slider. To start interacting with the slider press VOkey + Down Arrow.". 

Pressing arrowkeys now results in VO continuing focusing next elements in order. Stepping inside the slider disables the arrow keys, and with each press VO announces current value.

**Comment by leongersen** [comment]
I'd be happy to help improve the situation here. What do you mean by "stepping inside the slider"?

**Comment by jurajk** [comment]
@leongersen whoa, you're fast! :)

my bad, it should be "when i press VOkey + Down Arrow to start interacting with the slider", just like VO announces

**Comment by leongersen** [comment]
Could you try two things for me?
- Try a slider with the [`keyboardSupport`](https://refreshless.com/nouislider/slider-options/#section-keyboard-support) option set to `false`
- Try [this W3 aria example ](https://www.w3.org/TR/wai-aria-practices-1.1/examples/slider/slider-1.html) to see if it behaves as you expect

**Comment by jurajk** [comment]
- setting `keyboardSupport` results in the handle not being focusable by tabbing, but focusable by VO using arrowkeys. however, this does not impact VO interaction - still no interaction using arrow keys
- the example behaves the same as noUiSlider, so I would consider this either a voiceover or w3 example bug.

**Comment by leongersen** [comment]
I've been looking around, and the only reference I could find is here:

https://labs.levelaccess.com/index.php/ARIA_Slider_-_Horizontal

I couldn't find any open issue in an Apple related issue tracker, but maybe there is one?

**Comment by jurajk** [comment]
it seems this is a widespread issue - http://pauljadam.com/demos/multithumb-slider.html

just thinking out loud: create an actual native rangeslider, hide it visually, make noUiSlider purely presentational and bind all keyboard interactions form the native one to noUi.

**Comment by leongersen** [comment]
I've sought contact with Apple using [their accessibility contact information](https://www.apple.com/lae/accessibility/), referring to this page and the issues linked above. I'll update here if/when I receive a response.

**Comment by jurajk** [comment]
thanks 💯 times

**Comment by leongersen** [comment]
Apple replied, and send me to the [Webkit bug tracker](https://bugs.webkit.org/buglist.cgi?list_id=625399&query_format=advanced&bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&component=Accessibility&product=WebKit). I went though the 454 accessibility bugs, and found the following report:

https://bugs.webkit.org/show_bug.cgi?id=174898

Could you perhaps add your findings there? I'll do the same once I've been able to test this on a Mac (I don't own one).

There's one other relevant issue:

https://bugs.webkit.org/show_bug.cgi?id=174309

**Comment by jurajk** [comment]
this is no longer an issue in safari 14.1

**Comment by leongersen** [comment]
Glad to hear that. Thanks for reporting back!
