### ISSUE TITLE
Non linear slider incorrect step when using keyboard

### ISSUE THREAD

**Issue by ssi-john-quirol** [leongersen/noUiSlider#964]
In the demo below, step jumps from 0.1 to 0.2 after the value of 5 when using keyboard.

Dragging the handle seems to work just fine.

[https://jsfiddle.net/c6ud0kmx/](https://jsfiddle.net/c6ud0kmx/)

**Comment by leongersen** [comment]
That's because the `step` option [only applies to the first part of `range`](https://refreshless.com/nouislider/slider-values/#section-non-linear-step). You can set the step values for every part of the range, like so:

```JavaScript
'min': [1, 0.1],
'25%': [5, 0.1],
'50%': [7, 0.1],
'75%': [9, 0.1],
'max': [10, 0.1] 
```

Updated demo:
https://jsfiddle.net/leongersen/3x7rgybL/

**Comment by leongersen** [comment]
Some notes for me:
- [ ] Add note about non-linear sliders on the [`step` option page](https://refreshless.com/nouislider/slider-options/#section-step);
- [ ] Add note about the `step` option on the [`range` documentation](https://refreshless.com/nouislider/slider-values/#section-non-linear-step);

**Comment by ssi-john-quirol** [comment]
It worked! Thank you for your help!
