### ISSUE TITLE
Clicking to right of handle doesn't move it when it's at the same point as another

### ISSUE THREAD

**Issue by missmatsuko** [leongersen/noUiSlider#965]
Example Fiddle:
https://jsfiddle.net/ynhx50pv/

When the handles are at the same value, clicking to the right of a handle won't move it.
Clicking to the left does move the left handle.
If there's a gap between the two handles, clicking on the right of a handle does move it.

**Comment by leongersen** [comment]
Looking at it, the logic selects the left-most handle as the "closest" to the click, whereas the right-most one is just as close.

**Comment by leongersen** [comment]
This is fixed as of noUiSlider 14.0.0. Thanks for reporting!
