### ISSUE TITLE
Pips value rounding up when start range has decimal point

### ISSUE THREAD

**Issue by davidtregoning** [leongersen/noUiSlider#967]
I have setup my slider as follows:
```
noUiSlider.create(updateSlider, {
    start: 2.5,
    range: {
        'min': 2.5,
        'max': 10
    },   
    pips: {
            mode: 'range'
        }
});
```
However the start range for the pips display is showing as **3** as opposed to **2.5**
This can be seen when inspecting the slider:
`<div class="noUi-value noUi-value-horizontal noUi-value-large" data-value="2.5" style="left: 0%;">3</div>`

Is this an issue with the code or (more than likely) my configuration of the code?
Many thanks

**Comment by leongersen** [comment]
You can use the `format` option within `pips`:

```
pips: {
	mode: 'steps',
	density: 3,
	format: wNumb({
		decimals: 3
	})
}
```

`wNumb` is optional, you can use [any of the formatting options](https://refreshless.com/nouislider/slider-read-write/#section-formatting).

**Comment by davidtregoning** [comment]
Thank you @leongersen
