### ISSUE TITLE
Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by Hussainzz** [leongersen/noUiSlider#968]
the slider is created perfectly the problem is with the event. it says "Cannot read property 'on' of undefined"

my code 
	var slider = $('#slider');
	noUiSlider.create(slider[0], {
		start: [20000, 40000],
		range: { min: 10000, max: 60000 },
		step: 100,
		connect: true,
		tooltips:[true,true]
	});

	var settlementMin = document.getElementById('min-settlement'),
    settlementMax = document.getElementById('max-settlement');

	slider.noUiSlider.on('update', function (values, handle) {
		if (handle) {
			settlementMin.innerHTML = values[handle];
		} else {
			settlementMax.innerHTML = values[handle];
		}
	});

**Comment by Hussainzz** [comment]
sorry my bad i fixed it with the example on site

**Comment by leongersen** [comment]
Glad you figured it out :)
