### ISSUE TITLE
Slider Skipping / Duplicating Values

### ISSUE THREAD

**Issue by AlecWeekes** [leongersen/noUiSlider#969]
I've found that our current slider is having some odd behaviour. We've found that is seems to have duplicate numbers, and to also skip another.

We're using a range from 18 - 100 as a an Age Picker. When you get to 52, it holds the value 52 twice, while console logging the value it intends to have shows 53. When we get to 55 however, we entirely skip it, going from 54 straight to 56.

You can see this happening here in this gif: ![NoUISlider](https://user-images.githubusercontent.com/22915163/55719540-61d9c780-59f6-11e9-99bb-2ad83f9522ad.gif)

This is our set up;
```
            return {
                start: [18, 100],
                step: 1,
                connect: true,
                range: {
                    min: [18],
                    max: [100]
                }
            };
```

We've seen this occuring in all the modern browsers, and we've completely stripped off all CSS in the event some padding or margin was forcing some awkward shift.

Would love to get to the bottom of this.

**Comment by AlecWeekes** [comment]
Hey @leongersen 

Thanks for getting back to me. I should've stated sorry, that I did try this, but when doing so, I was able to find (on our slider) 53 & 54, but when selecting them it slipped back to the previous number, as shown in this gif:

![NoUISlider-2](https://user-images.githubusercontent.com/22915163/55732919-c1df6680-5a14-11e9-8b64-59ef599872cd.gif)

When I console log the numbers it's actually using, it's correct. Selecting what _should_ be 55 shows 55 in the console, but the UI is showing otherwise.

**Comment by leongersen** [comment]
Are you using the `tooltips` option, or are you implementing them yourself?

**Comment by AlecWeekes** [comment]
Implementing them ourselves, however having now put the console logs back in, I am getting the following results;

Selecting 51: ["18", "51"]
Selecting 52: ["18", "52"]
Selecting 53: ["18", "52.99999999999999"] (2) [18, 52.99999999999999] **

The same is occuring on 54 -> 55, we're getting a long decimal point value. The UI is looking to move to 53, and switches back to 52. I guess this is because of the rounding?

**Comment by leongersen** [comment]
Can you show me some more code? Are you changing the slider value pragmatically?

**Comment by AlecWeekes** [comment]
Hey, real sorry for the long delay.

I didn't get an email to say there was a response. Weird!

We've created a Vue Component (Slider), that we're using for this. We're handling the update via `this.$el.noUiSlider.on('update',` with a Mixin that handles all of the actual logic. We pass all the javascript via that mixin to the component, and then the component watches for any changes.

**Mixin Method:**
```
        methodName() {
            return {
                start: this.dob || [18, 100],
                step: 1,
                connect: true,
                range: {
                    min: 18,
                    max: 100
                }
            };
        },
```

**Vue Component Call**

```
<slider :options="methodName"></slider>
```

The Vue Component is a tad too big to post.

**Comment by leongersen** [comment]
Sorry, but that doesn't really give me any additional information to help you.

**Comment by leongersen** [comment]
I'm closing this issue for lack of feedback. Feel free to comment if you still have questions.
