### ISSUE TITLE
ES6 import

### ISSUE THREAD

**Issue by acespace90** [leongersen/noUiSlider#971]
Hi, I've installed noUiSlider with ES6 imports as suggested with
```
// main.js
import 'nouislider';
```

and this is my HTML

```
<html>

<body>

  <div id="slider"></div>

  <script src="js/bundle.js"></script>

  <script>
    var slider = document.getElementById('slider');

    noUiSlider.create(slider, {
      start: [20, 80],
      connect: true,
      range: {
        'min': 0,
        'max': 100
      }
    });
  </script>

</body>

</html>
```

But it doesn't work and in the console I have the following message error:
`Uncaught ReferenceError: noUiSlider is not defined`.

If I insert 
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/13.1.4/nouislider.min.js"></script>
```
 instead of `<script src="js/bundle.js"></script>` it works.

Can someone help me? Thanks.

**Comment by leongersen** [comment]
Does your `js/bundle.js` export `noUiSlider` back to `window`?

**Comment by acespace90** [comment]
@leongersen ehmmm what? 😅

**Comment by leongersen** [comment]
Tracked here: https://stackoverflow.com/questions/55745018/nouislider-es6-import/5576110

**Comment by acespace90** [comment]
Hi, what about wNumb?

I imported as an ES6 Module

```
import wNumb from 'wnumb';
```

But when I use it into slider options, the console prints `wNumb is not defined`.

Can you help me with the integration with a code example? Thanks.
