### ISSUE TITLE
[Q] Highlight selected Scale/Pip / Show tooltips only on change

### ISSUE THREAD

**Issue by oiBio** [leongersen/noUiSlider#972]
Hi, 

Is it possible to highlight the scale/pips of the selected range?
I was also wondering if it is possible to show the tooltips while using the keys to change the values, not only when using the handles.

This is my slider so far
https://jsfiddle.net/bnwfqz6d/

ps: 
Thank you very much for this awesome slider!

**Comment by leongersen** [comment]
> if it is possible to show the tooltips while using the keys to change the values

Yes! You can use:

```CSS
.noUi-handle:focus .noUi-tooltip,
.noUi-active .noUi-tooltip {
  display: block;
}
```

> Is it possible to highlight the scale/pips of the selected range?

Yes, using the `update` event:

```
slider.noUiSlider.on('update', function(values, handle, unEncodedValues) {
       for (var i = 0; i < pips.length; i++) {
         var value = Number(pips[i].getAttribute('data-value'));
         // Or set a class, etc.
         pips[i].setAttribute('data-in-range', (value > unEncodedValues[0] && value < unEncodedValues[1]) ? '1' : '0');
       }
});
```

Updated fiddle (kinda rough):

https://jsfiddle.net/leongersen/v3kwLct8/11/

**Comment by oiBio** [comment]
Awesome! Thank you very much ;-)
