### ISSUE TITLE
Step not incrementing correctly

### ISSUE THREAD

**Issue by Vimiso** [leongersen/noUiSlider#975]
Take the given code:

```
noUiSlider.create(elems.slider, {
    start: [5000000],
    step: 10000,
    range: {
        'min': [0],
        'max': [10000000]
    }
});

elems.slider.noUiSlider.on('update', function(values, handle) {
    console.log(values[handle]);
});
````

When moving the slider, the steps increments correctly. But when I change the `max` to `100000000` (larger than in the example) it steps very inconsistently. Basically not with the `step` value I have set.

What is going on here?

**Comment by Vimiso** [comment]
I'm not by my codebase right now but:

Say the min is `20000` and max `100000000` and the step `100000`, it adds the `20000` on when stepping? Makes sense because `20000` is smaller than `100000`. But I need everything from above `100000` to step normally like; `100000`, `200000`, `300000`... and so on, all the way to the max.

**Comment by leongersen** [comment]
You can do that with [multiple ranges with different step values](https://refreshless.com/nouislider/slider-values/#section-non-linear-step).
