### ISSUE TITLE
Styling selected range (connect: true doesn't work)

### ISSUE THREAD

**Issue by lorraineS** [leongersen/noUiSlider#977]
In many examples, there is a color in a bar, to the left of the slider, and white color to the right of it. How can I do it?

I've set the `connect` option :

```
noUiSlider.create(sliderKm, {
    connect: true,
    start: [5],
    range: {
      'min': 1,
      'max': 51
    },
  });
```

Demo available here :
[https://codepen.io/lorraineS/pen/wbWQaJ](url)

Thank you.

**Comment by leongersen** [comment]
You'll want `connect: [true, false, true]`.

**Comment by lorraineS** [comment]
> You'll want `connect: [true, false, true]`.

This property returns me an error : `Uncaught Error: noUiSlider (13.1.5): 'connect' option doesn't match handle count.`

**Comment by leongersen** [comment]
Sorry, thought you had two handles. `connect: [true, false]`.
