### ISSUE TITLE
Is there any way to put custom values in tooltips ?

### ISSUE THREAD

**Issue by skiiiks** [leongersen/noUiSlider#978]
Hi:
Any way to create a slider from 1, 12 (in values) but from "January" to "December" in tooltips ?

**Comment by leongersen** [comment]
Yes, you can [pass a formatter to the `tooltips`](https://refreshless.com/nouislider/slider-read-write/#section-formatting) option.

**Comment by skiiiks** [comment]
Please, any example? I REALLY have tried hardly ... but I can't figure out how to do it

**Comment by leongersen** [comment]
`tooltips: [{ from: Number, to: function(value) { /* value to date */ } ]`

**Comment by leongersen** [comment]
I've add some additional documentation on number formatting in noUiSlider:

https://refreshless.com/nouislider/number-formatting/
