### ISSUE TITLE
Using Different Images as slider handler

### ISSUE THREAD

**Issue by frmostafa** [leongersen/noUiSlider#979]
hi .
in [https://github.com/leongersen/noUiSlider/issues/172](url) you say how to change the handlers background .
but i wanna change the backgrouund Separate and use them for Separate job.
can you help me? sorry for my bad english typing

**Comment by leongersen** [comment]
Do you want a different image for each slider handle?

If so:

```
.noUi-handle[data-handle="0"] {
  background-image: url('/path/to/your/image-1.png');
}
.noUi-handle[data-handle="1"] {
  background-image: url('/path/to/your/image-2.png');
}
```

**Comment by frmostafa** [comment]
thank's for your Great answer .
yes i wanna this. 
but another Question . it is  a little Confusing
i wanna use multiple slider
any slider have Settings . my mean is slider one handlers have Separate shape and slider two have Separate.
like image that upladed and more sliders in one page 
sorry for Confusing Question.
![Screen Shot 2019-05-16 at 2 03 19 PM](https://user-images.githubusercontent.com/44520902/57843558-be918480-77e3-11e9-9172-32c993d66b25.png)

**Comment by leongersen** [comment]
Sorry, I don't know what you are asking.

**Comment by frumbert** [comment]
I'd also like to be able to easily use different shapes for each handle position. In the screenshot above I'd consider the handle to be the red and green things. Imagine the slider being a timeline control and the handles being various types of event markers on that timeline.

**Comment by leongersen** [comment]
@frumbert Could you open a new issue with what you're trying to do? If you could add a code example, that'd be helpful.

**Comment by leongersen** [comment]
I'm closing this issue as there hasn't been any activity in a while. Feel free to comment if you have any questions remaining.
