### ISSUE TITLE
Keyboard support. Adjustable 10% increments

### ISSUE THREAD

**Issue by jonny64bit** [leongersen/noUiSlider#981]
I was wondering if it would be possible to make it so the 10% default if no step value was present for keyboard users configurable?

The use case for this is for mouse and touch users be able to do any value in say a slider set for 1-100. Keyboard users i could do with a finer control than 10% but don't want them to have to deal with a step of 1.

**Comment by leongersen** [comment]
That should be a minor change, here:

https://github.com/leongersen/noUiSlider/blob/master/src/nouislider.js#L1823

**Comment by leongersen** [comment]
I missed this issue at the time, but this feature was added in noUiSlider 14.6.0.

You can not set the [`keyboardDefaultStep` option](https://refreshless.com/nouislider/slider-options/#section-keyboard-support) to configure the slider stepping when there is no `step` option set.
