### ISSUE TITLE
Keyboard support does not seem to work on IE and Safari browsers

### ISSUE THREAD

**Issue by ssi-john-quirol** [leongersen/noUiSlider#982]
Keyboard functionality (moving of slider through arrow keys) does not seem to work on IE (tested on 9, 10 and 11) and Safari (tested on 12 and 11.1) browsers.

The issue can be replicated here: https://refreshless.com/nouislider/

**Comment by leongersen** [comment]
IE (and I think Safari) do not give the handles focus when clicking them. Press `<tab>` in the document to focus a handle. This is a choice made in the user agent.
