### ISSUE TITLE
Slider not draggable

### ISSUE THREAD

**Issue by RobinOehler** [leongersen/noUiSlider#983]
Hello world,

i included nouislider.min.css & nouislider.min.js and the slider shows up, but i cant drag the handles. Is there something i don't see?

I use this code to init the slider:

```
<div id="slider">
</div>
```

```
<script>
var slider = document.getElementById('slider');

noUiSlider.create(slider, {
    start: [20, 80],
    connect: true,
    tooltips: true,
    range: {
        'min': 0,
        'max': 100
    }
});
</script>
```

**Comment by leongersen** [comment]
Since that's pretty much the minimal slider initialization code, there's not enough information here to help you.

**Comment by RobinOehler** [comment]
But it should work with that, shouldn't it ? I don't have any Error in my console, but i can't drag the handles. I used an other range slider "framework" by now and i have the exact same problem. There has to be something wrong, but i don't get any error. Everything looks fine codewise.

**Comment by leongersen** [comment]
- Is your slider hidden behind some other element?
- Is there some touch even listener on the whole page?

**Comment by RobinOehler** [comment]
THIS! -> Is there some touch even listener on the whole page?
I think not. At least i did not code any! What should i listen for?

**Comment by leongersen** [comment]
Well, nothing. You might inadvertently be blocking events. Try using the slider in a minimal example, then keep adding your own code until it stops working.

**Comment by RobinOehler** [comment]
That exactly what I did :sob: ...I'll update you, when i found the issue.

**Comment by RobinOehler** [comment]
Does it help to say that I use Laravel?

**Comment by RobinOehler** [comment]
It works when I put the Slider outside of my "col-3" Div....... hm.

**Comment by RobinOehler** [comment]
It works now. For some reason the id="app" in a div above killed the slider. I have no clue why. This ID was not even in my .css at this point. Thanks for your help & code :)
