### ISSUE TITLE
Feature request: Conditional tooltip

### ISSUE THREAD

**Issue by seanhak** [leongersen/noUiSlider#985]
I would like to format the tooltip differently based on value, for example:
0: "None", 1-4999: {value}, 5000:"All"

Current solution proposed is to listen in on the update event, and manipulate the dom. #859 

Ideally it would be nice if we could have conditional methods like this:
`tooltips: [ function(value){ return value; } ]`

```
tooltips: [ function(value){ 
if(value===0) { return "None"; }
else if(value===5000) { return "Max"; }
else{ return value; }
}]
```

**Comment by leongersen** [comment]
You can do this by providing a formatter:

```
tooltips: [{ to: /* your function */, from: Number  }]
```

**Comment by leongersen** [comment]
I've add some additional documentation on number formatting in noUiSlider:

https://refreshless.com/nouislider/number-formatting/
