### ISSUE TITLE
Vertical slider page height

### ISSUE THREAD

**Issue by mkounkel** [leongersen/noUiSlider#987]
Im' using a vertical slider. For whatever reason, the lowest slider (no matter how many or how few handles) seems to adjust the size of the page (e.g., if the slider is 500 px, it forces the page height to be ~1000 px, filling it with white space. On the other hand, when it is drawn to the very top, the page is the normal size.

**Comment by leongersen** [comment]
Do you have an example somewhere I can have a look at?

**Comment by mkounkel** [comment]
Here: http://mkounkel.com/mw3d/test.html

**Comment by leongersen** [comment]
I'm seeing this issue too, I'll look into it.

**Comment by mkounkel** [comment]
That made it worse, I think? The bottom handle disappeared miles below the slider adding 10 times the white space, the top handle disappears the second I move it...

**Comment by leongersen** [comment]
Did you update the CSS too?

**Comment by mkounkel** [comment]
Ah, I didn't! Looks great now, thanks!

**Comment by leongersen** [comment]
Ah, good. Thanks for reporting this issue, btw :)

**Comment by xiaogengxu** [comment]
> Ah, I didn't! Looks great now, thanks!

Could you please tell how you fixed the problem in detail? I have the same problem but I'm very new to less files. Thank you!

**Comment by leongersen** [comment]
@xiaogengxu You'll want to make sure you have the same noUiSlider version for both the JS and CSS file. Both have a comment (`/*! nouislider - 14.6.2 - 9/16/2020 */`) on top.

**Comment by xiaogengxu** [comment]
@leongersen Thanks a lot for the prompt reply. I'm a newbie to css and less. Now in <head> I use nouislider.min.css, nouislider.min.js, and wNumb.min.js. The vertical sliders are fine, just the space between the last slider and Next button is very big. Where can I get the new versions of the css and js files? Thank you!

**Comment by xiaogengxu** [comment]
@leongersen I think I asked a stupid question. I've found them. Thanks!!

**Comment by xiaogengxu** [comment]
@leongersen I'm sorry to bother again. I used the most recent css and js files but the big space after the vertical slider maintains. May I ask if I need to change anything in style?
