### ISSUE TITLE
Feature Request: Selectable spaces

### ISSUE THREAD

**Issue by asdf23** [leongersen/noUiSlider#991]
I'd like to be able to select the spaces between the sliders. 
It might help to have a use case.. imagine the sliders are marking shifts between a tv show and commercial. I want to be able to select a space between the sliders (then in unrelated code assign a name/color to the space)

**Comment by leongersen** [comment]
I don't really know what you mean by "spaces". It sounds like you're looking at an implementation, not a feature per se. What api changes would you expect for this feature?

**Comment by asdf23** [comment]
By spaces I mean the area between the sliders.  If there are two sliders there are 3 spaces. I want to be able to click theses spaces to select them (instead of moving the sliders) also I want to be able to color these differently.

**Comment by leongersen** [comment]
This issue isn't really clear enough for me to do anything with, so I'm closing it for now. Feel free to comment, or consider asking a [StackOverflow](https://stackoverflow.com/questions/tagged/nouislider) question if you have a more general implementation issue.
