### ISSUE TITLE
Feature request: Specify step size when using keyboard to change slider handle

### ISSUE THREAD

**Issue by bjarnef** [leongersen/noUiSlider#992]
Great to see the build in keyboard support added in noUiSlider version 13.0.0.
However when the slider has a very small step size (e.g. 0.001) it might not be ideal to use the default step size when using keyboard arrows.

In that scenario it would be great to have an property (or function) to override the step size, when using keyboard arrows.
For example you might have a slider with `min="0"`, `max="2"` and `step="0.001"`, but when using keyboard arrows it would be okay to change the handle with a step size of `0.01` or `0.1`.

![2019-06-12_12-10-47](https://user-images.githubusercontent.com/2919859/59343738-ce31b980-8d0c-11e9-8fdd-b7c71357a36d.gif)

**Comment by leongersen** [comment]
This seems like a good addition. How would you suggest the API should look?

**Comment by bjarnef** [comment]
@leongersen not sure if the best option if the have this as a separate property or via a function? Maybe it would be easier in a function to calculate the keyboard step size. I also imagine that something like `ctrl+arrow` or `shift+arrow` could be used to fine tune change of the handle.

For example:
`arrow left/right`: move the handle a specific step size (if set specific for keyboard), default the general step size.
`arrow left/right+ctrl/shift`: move the handle the general step size

**Comment by leongersen** [comment]
Right now, the second value in the `range` argument specifies the step value for that sub-range. That could be changed to it accepts either a number or a `function()`. The function could receive the current value and the `KeyboardEvent`, so any custom logic could be implemented. How does that sound?

**Comment by bjarnef** [comment]
It sounds great. Could you give a few examples of how you imagine the api would look like when using it with a single or multiple handles?

**Comment by leongersen** [comment]
Something like this?

```
// with keyboardEvent = null if the step isn't a keyboard interaction
function decideStep(handleNumber, value, keyboardEvent) {
    return value / (keyboardEvent && keyboardEvent.ctrlKey ? 10 : 5)
}

noUiSlider.create(slider, {
    start: 20,
    range: {
        'min': [0, decideStep],
        '50%': [60, 5], // fixed step from here
        'max': 100
    },
   // or, for simple linear ranges:
   step: decideStep
});

```

**Comment by bjarnef** [comment]
Yes, that might work well.

In Umbraco CMS is now used as slider when cropping an image, which just use the `step` property.
https://github.com/umbraco/Umbraco-CMS/blob/9b62269bdeb697ec1a5d371565aa270eeca16531/src/Umbraco.Web.UI.Client/src/common/directives/components/imaging/umbimagecrop.directive.js#L44

Actually I haven't tried defining a specific step in the range, so not sure what the best option is, but it seems ideal from your code snippet.

In the `decideStep` function I guess it is also possible to check on the specific keyboard keys, e.g. left arrow step with a size of 5 and right key step with a size of 10 (not meaning that it is user friendly or should be used).

**Comment by bjarnef** [comment]
@leongersen did you had any time to look further at this?
The code example you shown seems to be the way to handle this.

**Comment by leongersen** [comment]
noUiSlider 15.3.0 adds a `keyboardMultiplier` option (#1151), which could be set to 10 or 100 to multiply the step of 0.001 in the example to 0.01 or 0.1. I considered the callback feature as described earlier, but I think this simpler solution should be enough in the majority of use cases.

**Comment by bjarnef** [comment]
@leongersen is it possible fine tune the step movement using `keyboardMultiplier` and e.g. `ctrl` key, while left/right key by default move 100, but you then want to adjust to value to 95?

**Comment by leongersen** [comment]
Not with `keyboardMultiplier` as it currently is, no.

**Comment by bjarnef** [comment]
Okay. Just from an accessibility point of view and you only had keyboard available. It could probably use step size e.g. when holding `ctrl` key otherwise use step size * keyboardMultiplier.
