### ISSUE TITLE
"change" event is not fired when using the keyboard

### ISSUE THREAD

**Issue by steliyan** [leongersen/noUiSlider#994]
The `change` event is not fired when navigating with the keyboard keys.
It can easily be observed in the [locking sliders together example](https://refreshless.com/nouislider/examples/#section-lock).

Steps to reproduce:
1. Click on the "Lock" button.
2. Click on the first slider (no movement is necessary).
3. Press the `left`/`right` arrow on the keyboard.

Expected: Both sliders are moved to the left/right.
Actual: Only the first (focused) slider is moved.

Greetings, Steliyan.

**Comment by leongersen** [comment]
After reviewing the events table, that's an oversight on my end. It would make sense for the change event to fire on keyboard control.

**Comment by leongersen** [comment]
noUiSlider 14.0.0 resolves this issue. Thanks for reporting! Here's the updated events table:

https://refreshless.com/nouislider/events-callbacks/
