### ISSUE TITLE
Blurry text on tooltip in Google chrome

### ISSUE THREAD

**Issue by gauravsarwal** [leongersen/noUiSlider#995]
We are using the version 75.0.37 of this plugin and the text of some of values in tooltip is blurred,  however it works fine in Firefox and edge, I am attaching the 2 screenshots in one of it its coming fine and on other its blurred. 
![image](https://user-images.githubusercontent.com/2039902/59507199-f9acd380-8ec7-11e9-9116-22233afef46c.png)
![image](https://user-images.githubusercontent.com/2039902/59507209-016c7800-8ec8-11e9-9dea-7e1a6920730b.png)

Any help/suggestion will be highly appreciated.

**Comment by leongersen** [comment]
Do you have this code somewhere accessible for me so I can have a look?

**Comment by gauravsarwal** [comment]
> Do you have this code somewhere accessible for me so I can have a look?

Yes, Please go to link:  https://jsfiddle.net/yxbu6epm/1/ and open it on google chrome, only last tooltip which is on scale 5 is coming sharp and clear and all other are blurred or broken, We are using latest version of chrome which is : Version 75.0.3770.100 (Official Build) (64-bit).

**Comment by leongersen** [comment]
The slider handles are placed and moved using CSS transforms. You can use [any of these techniques](https://stackoverflow.com/a/16878602/775265) to change how the fonts in your tooltips are rendered.

**Comment by leongersen** [comment]
Closing this as answered. By the way, I'm not seeing this issue on Chrome OS Version 75.0.3770.102 (Official Build) (64-bit), so it may be platform rendering specific.

**Comment by gauravsarwal** [comment]
> Closing this as answered. By the way, I'm not seeing this issue on Chrome OS Version 75.0.3770.102 (Official Build) (64-bit), so it may be platform rendering specific.
Thanks leongersen, we were able to fix it by trying one of the techniques which you shared on stackoverflow link.
