### ISSUE TITLE
Can we get the event variable and call stopPropagation on it?

### ISSUE THREAD

**Issue by BennyHinrichs** [leongersen/noUiSlider#996]
I'd like to do my own event on `tap` and override the native `tap` in the process. The docs say the variables available to us are `values, handle, unencoded, tap, positions`. Is it possible to get an `event` variable in there? I mean, I guess I could try to tap into `touchstart` on the browser level, but then I wouldn't have any of the variables mentioned above.

Edit: It looks like on tap the new position has already been calculated when the `start` event fires, so I guess that would make it hard to do `stopPropagation`. Is there some other way I could go about doing this?

Edit 2: This is what I've been able to get in place for the time being:

```javascript
let sliderVals;
sliderEl.noUiSlider.on('slide', (values, handle, unencoded, tap, positions) => {
  tap && sliderEl.noUiSlider.setHandle(handle, sliderVals[handle], true);
})
sliderEl.noUiSlider.on('update', (values, handle, unencoded, tap, positions) => {
  !tap && (sliderVals = values);
})
```

**Comment by leongersen** [comment]
As noUiSlider abstracts the event systems between different browsers, I don't think exposing the underlying events would be a good API choice. I you want to stop events propagating to the document, you can listen to the event on the slider element and stop propagation from there.

**Comment by bpmartin20** [comment]
Pardon my ignornance ... decades of IT experience but I'm pretty green at JavaScript. I have the same problem. I understand your answer in general, but I'm unclear on what the slider element name is, given that I have a single slider with two values on it. I want to stop propagation on both handles, and really anything involving the slider. Below are excerpts of my code. So what's the name of my slider element?

HTML:

```
<link href="/my_mh/css/nouislider.min.css" rel="stylesheet" TYPE="text/css">
<form name="thermoslider">
                <input type="hidden" id="sliderinput" name="sliderinput">
                        <div id="slider"></div> <!-- Insert the slider here -->
</form>

```
JavaScript:```
```

<script>
       var slider = document.getElementById('slider');
       noUiSlider.create(slider, {
            connect:        true,
            start:          [70, 80],
            tooltips:      true,
            range:      {
                  'min': 60,
                  'max': 90
            }
        });
</script>
<script>
       var sliderStartLow;
       var sliderStartHigh;
       slider.noUiSlider.on('start', function (values, handle, unencoded) {
                sliderStartLow = values[0];
                sliderStartHigh = values[1];
        });
        slider.noUiSlider.on('set', function (values, handle, unencoded) {
              if (values[0] === sliderStartLow ) {
                   <!-- do something -->
                   return false;
             }
             else {
                    <!-- do something else -->
                    return false;
              }
              });
</script>
```
I've tried "handle.stopPropagation()", "slider.noUiSlider.stopPropagation()", and some other guesses. Can you put me on the right track?

Other than dealing with newbie ignorance, I have to say I'm loving noUiSlider! Thanks for the great work.

**Comment by leongersen** [comment]
@bpmartin20 Glad you're liking noUiSlider!

You can do something like:

```JavaScript
slider.addEventListener('...the event of your choice...', function(event) { 
    event.stopPropagation();
});
```
