### ISSUE TITLE
2 sliding range limiters and 1 slider on on<<<<<<<<<<<<<<<<<<e row?

### ISSUE THREAD

**Issue by delinde** [leongersen/noUiSlider#997]
Can I have 3 sliders on 1 range-row,
two of them as (slidable) range limiters,
and one for selecting the chosen value?
And those two limiters have a different shape?

**Comment by delinde** [comment]
Should be:
2 sliding range limiters and 1 slider on one row?

**Comment by leongersen** [comment]
I don't really know what you are asking here, sorry. If you have a specific implementation question, might I direct you to [stackOverflow](https://stackoverflow.com/questions/tagged/nouislider).

**Comment by leongersen** [comment]
Closing this for lack of feedback.
