### ISSUE TITLE
Connect position not accurate after updating to version 14.0.0

### ISSUE THREAD

**Issue by suhailkc** [leongersen/noUiSlider#998]
Position of connect not working properly.
In version 13.1.5 it's working properly, I have the issue after updating to version 14.0.0

How can I fix it?

Screenshot:
[view screenshot](https://ibb.co/vkBScF0)

**Comment by suhailkc** [comment]
In version 13.1.5 it's working properly, I have the issue after updating to version 14.0.0

**Comment by leongersen** [comment]
Do you have an example with running code I can look at? Also, did you update the CSS when updating to the new version?

**Comment by suhailkc** [comment]
Screenshot from the official example.
[Screenshot from the official site](https://ibb.co/Tr4Js93)

**Comment by leongersen** [comment]
Looks like the fixed bug that allowed this change in Chrome wasn't fixed in Safari. I'll look into it.

**Comment by leongersen** [comment]
I changed the scaling factor to 10 (instead of 1 in 14.0.0 and 100 in 13.1.5). That should work around this issue in Safari.
