### ISSUE TITLE
Step not working if range is negative

### ISSUE THREAD

**Issue by rfazi** [leongersen/noUiSlider#999]
Hi,
this is the code:
```javascript
noUiSlider.create(startSlider, {
		range: {
			'min': [-5],
			'50%': [0],
			'max': [5]
		},
		start: 0,
		step: 0.5,
		orientation: 'vertical',
		pips: {
			mode: 'range',
			density: 5,
			stepped: true
		}
	});
```

When we drag using the mouse, the step "0.5" work when the value is <=0.
But if the value is >0 then the "0.5" will not work.
If we use the keyboard instead of the mouse drag then the step "0.5" works perfectly from -5 to +5.

Any help?

**Comment by leongersen** [comment]
The `step` option does not apply to apply ranges, it is merely a shorthand for linear sliders. You'll need to specify steps for all ranges:

```
range: {
	'min': [-5, 0.5],
	'50%': [0, 0.5],
	'max': [5]
},
```

If you remove the `'50%': [0]`, it will also work, as that is already the center of the slider.

**Comment by rfazi** [comment]
Thanks for the fast reply! Now is working.
